{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-config-yaml",
    "version": "1.21.1-mc1201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-yaml-1.21.1-mc1201-mc1.20.jar",
          "url": "magicutils-config-yaml-1.21.1-mc1201-mc1.20.jar",
          "size": 1726,
          "sha512": "a7357bf33469ef5284fd34f6c4679168ba3a15528c110998dbee1f2602cb14b2ff3c8afcae47de5309380e159d86274fae1c87be8b0fe102875b5c965dce8e59",
          "sha256": "4b9cfd79827a9f2c6c102bd37c39978c0040bc8b12053c8963dc5707048ced33",
          "sha1": "38b249aa37dc233024ef0d2ceefd5f6a7ec40bdb",
          "md5": "96a76bd18a42b42a0f321553006f6043"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-yaml-1.21.1-mc1201-mc1.20.jar",
          "url": "magicutils-config-yaml-1.21.1-mc1201-mc1.20.jar",
          "size": 1726,
          "sha512": "a7357bf33469ef5284fd34f6c4679168ba3a15528c110998dbee1f2602cb14b2ff3c8afcae47de5309380e159d86274fae1c87be8b0fe102875b5c965dce8e59",
          "sha256": "4b9cfd79827a9f2c6c102bd37c39978c0040bc8b12053c8963dc5707048ced33",
          "sha1": "38b249aa37dc233024ef0d2ceefd5f6a7ec40bdb",
          "md5": "96a76bd18a42b42a0f321553006f6043"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.21.1-mc1201-sources.jar",
          "url": "magicutils-config-yaml-1.21.1-mc1201-sources.jar",
          "size": 1615,
          "sha512": "7dd035aa467194e1f75f05e02b1afd2a2c881d14c30a7d577196ca3a326633df2cd9700da0936c91f30e1e9cb7cdedb5e3b373fab0a5b3ee0552940a8037fcbb",
          "sha256": "134bc160155c0948959d106b1fb7d7cb2b2e759d22e70303a8297ba77a13697e",
          "sha1": "3d4491714d06e6a1d91b497be8c6bfe0ef63c648",
          "md5": "f03bc030224c866efafb871d3584d804"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.21.1-mc1201-javadoc.jar",
          "url": "magicutils-config-yaml-1.21.1-mc1201-javadoc.jar",
          "size": 79829,
          "sha512": "3208d3da7e74685c6096e09e712e5237b6ba8fb90f6dbc617a3980d180117c4c67451063951088967c42725d4c0302a6e336d0f2f9025e83bd636d8fe0f0db6e",
          "sha256": "f9d7d6a4266c5a35205403520effb435a5faad8bfbbfc9e69067fa0704788c0c",
          "sha1": "2c3152e29a487f55a8b4fc52376cb3cd221dea94",
          "md5": "4b5fcb28304f9a95744061e3d4ce66a2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.21.1-mc1201-all.jar",
          "url": "magicutils-config-yaml-1.21.1-mc1201-all.jar",
          "size": 3349369,
          "sha512": "311558a1b4d1c0aa548d462f2d9d187be6bc49e6404f1d3d5b7ec6ed777f2ae8fd7452a34be144b6384f3ba2d935b7b1f93a7649d3cffc90ea86e4a960cce2ef",
          "sha256": "b1a6b53e6be68bdb63e0cd6145419dd3f6bea00739d0f90a1cf01038fad3ceea",
          "sha1": "d7af9b30d1402b1e1808ad66fe7d00d61e882f62",
          "md5": "4c0f732cc89e916bb766ad3591371cf4"
        }
      ]
    }
  ]
}
