{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-http-client",
    "version": "1.14.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.14.5"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.14.5-mc1.21.jar",
          "url": "magicutils-http-client-1.14.5-mc1.21.jar",
          "size": 56617,
          "sha512": "09bc1bde919e4fda8f6c168ef98c1f0e02ca522d9b5bf33c9bce4a68ca3b9ecb1b874efcf2c62822d46b28acb286b35c4873a19cf391ee835f214b622f5fc659",
          "sha256": "1dc5d645190a791d7b790b906de0154280b2412e35ff2a867e533969d7d8762a",
          "sha1": "0fd45cf9fc8496713e2f80562a9b0f4aec7a88b0",
          "md5": "33a5198d9d28ce0ddf5e3d5fe51f7893"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.14.5"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.14.5-mc1.21.jar",
          "url": "magicutils-http-client-1.14.5-mc1.21.jar",
          "size": 56617,
          "sha512": "09bc1bde919e4fda8f6c168ef98c1f0e02ca522d9b5bf33c9bce4a68ca3b9ecb1b874efcf2c62822d46b28acb286b35c4873a19cf391ee835f214b622f5fc659",
          "sha256": "1dc5d645190a791d7b790b906de0154280b2412e35ff2a867e533969d7d8762a",
          "sha1": "0fd45cf9fc8496713e2f80562a9b0f4aec7a88b0",
          "md5": "33a5198d9d28ce0ddf5e3d5fe51f7893"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.14.5-sources.jar",
          "url": "magicutils-http-client-1.14.5-sources.jar",
          "size": 20828,
          "sha512": "0592c15958ee8060d8cc40f8a3fb91cfb7e7225c37fd4df5dce4bebf8b298175987529bb353d73c8e0e395a5a78b7ac8134d9a700317c68a1c8f1ac4fa6fdd9e",
          "sha256": "a047a1bfc5aacbbfb4742069ff1b8609623a6c1e3a63fe03e431a6ecd6661f82",
          "sha1": "c02180acd21e930582c4e58ef05048e4bcaccbdb",
          "md5": "08a71f85e7ea867926357543a8860bc2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.14.5-javadoc.jar",
          "url": "magicutils-http-client-1.14.5-javadoc.jar",
          "size": 149275,
          "sha512": "bca911dafa0c0c80a2f83319b69038ca57cf7c7210e5df8ed3f4d57cdc5bc13023d628b39938c84616c88ae501e7c2546b53e9634a942a7cef3029b635723167",
          "sha256": "da0f58f62e56624dbd6488a76f2dd40cfc844fa895a4812fe28b3f24e013132c",
          "sha1": "95cf3b97b69fccb92749be96fc603e660c21edbf",
          "md5": "d926762e19246b98772819ffa216787c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.14.5-all.jar",
          "url": "magicutils-http-client-1.14.5-all.jar",
          "size": 3467604,
          "sha512": "75269eb72a7da73acc3ed8fcdc3d0f576d9a3fb81e78ad1f0cf6bfa3e0f78b3f647ddba34c6e3cf4a50809baa7b9b721c24f4bdc70108585639d23b7eac3f130",
          "sha256": "a21adebba5923a0bb2a51d51b52d5f29aedbc28b740093dbf203db877e75a74e",
          "sha1": "72484613a5bfaadaf914db2b8fc3352f9aa98632",
          "md5": "2c38eaf80a336599cf263d39d13ae0c2"
        }
      ]
    }
  ]
}
