{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-config",
    "version": "1.21.3-mc2611",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-1.21.3-mc2611-mc26.1.jar",
          "url": "magicutils-config-1.21.3-mc2611-mc26.1.jar",
          "size": 78359,
          "sha512": "b1813fa821409ac9b3c76db738084d4eb04a986b2a70274a579f95bf6f75aa5941c91c0b5364253d771ef27c8f451175224d80e82c13bf882f1b0c5250f39fb0",
          "sha256": "d205ad7c0b1bfe2902622cc25e9428d980fa1c75a5fe4f80163e1095ff863502",
          "sha1": "ba1e07974cbd218cc273f824035a5aad02a96f08",
          "md5": "b457d2f17a17f9f1df105c161a8fb9b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-1.21.3-mc2611-mc26.1.jar",
          "url": "magicutils-config-1.21.3-mc2611-mc26.1.jar",
          "size": 78359,
          "sha512": "b1813fa821409ac9b3c76db738084d4eb04a986b2a70274a579f95bf6f75aa5941c91c0b5364253d771ef27c8f451175224d80e82c13bf882f1b0c5250f39fb0",
          "sha256": "d205ad7c0b1bfe2902622cc25e9428d980fa1c75a5fe4f80163e1095ff863502",
          "sha1": "ba1e07974cbd218cc273f824035a5aad02a96f08",
          "md5": "b457d2f17a17f9f1df105c161a8fb9b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.21.3-mc2611-sources.jar",
          "url": "magicutils-config-1.21.3-mc2611-sources.jar",
          "size": 37256,
          "sha512": "63dc0ef787b091790945cf85f94b22f955b01911bfb32a287d6425be58571b609b403207559b04982e46f07c52bf92dd865465419b09e5f47877d414bf226b4e",
          "sha256": "65049a214719af417f1e2b25839f9c8b07aa682b31a60436f08a58770ef0b6df",
          "sha1": "6b5544ab5393238ff5c49bdcf4b100e9be7262b0",
          "md5": "225e154a78687284fd724e8ddc37c9e4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.21.3-mc2611-javadoc.jar",
          "url": "magicutils-config-1.21.3-mc2611-javadoc.jar",
          "size": 4220355,
          "sha512": "2c68f4aec87e0dd9cc7fb413cd1e87989e5109c8851a73e2c57a84ba25916a95467f1b6d076fcf38329b37675b8d9064563f6e2bd86b8ac6d764bb10d0152dae",
          "sha256": "48f0b1292dd0788440a7789df63e5e4acfe358684c09496ce71480d5a23bf498",
          "sha1": "12594d19195ba35615e4ca31a71d0cdcf22367b4",
          "md5": "c58dfaa395fa250dd4f67da158bf4c5b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.21.3-mc2611-all.jar",
          "url": "magicutils-config-1.21.3-mc2611-all.jar",
          "size": 2962966,
          "sha512": "3564a8196705e9c298977e5a453d132f6cdbecfc2d4ffb435b4419f43570e0bf68b2cd4be9ed202753b592f65657a30bf0676536b52f297c775961d91f48a01e",
          "sha256": "3c82228df8980501e1f74ea6bab645d44904d818268d0d95cc59265c225def06",
          "sha1": "35fd5defa5728e8b631ee3dfd9da1467b4151977",
          "md5": "664065eb425d1441fa022bd35964ceeb"
        }
      ]
    }
  ]
}
