{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-config-yaml",
    "version": "1.19.0-mc1201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.19.0-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-yaml-1.19.0-mc1201-mc1.20.jar",
          "url": "magicutils-config-yaml-1.19.0-mc1201-mc1.20.jar",
          "size": 1726,
          "sha512": "4d90b190b2993570ae37273d114cdeb37bc64e8e72d76bda07ef2560822710e7dc871fccc9d790dbaed09ba643a1f552d91014d4e507739004db7e852fcdb37d",
          "sha256": "f270766f16ab7fb9d02ef25d2cb571baac351dffe6f7e39a7ed91167fb6d1c6f",
          "sha1": "995cb49d54c0e544186a81a031ffe958ae83db15",
          "md5": "d66e6b5a8547db956c26eb013a3aeb36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.19.0-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-yaml-1.19.0-mc1201-mc1.20.jar",
          "url": "magicutils-config-yaml-1.19.0-mc1201-mc1.20.jar",
          "size": 1726,
          "sha512": "4d90b190b2993570ae37273d114cdeb37bc64e8e72d76bda07ef2560822710e7dc871fccc9d790dbaed09ba643a1f552d91014d4e507739004db7e852fcdb37d",
          "sha256": "f270766f16ab7fb9d02ef25d2cb571baac351dffe6f7e39a7ed91167fb6d1c6f",
          "sha1": "995cb49d54c0e544186a81a031ffe958ae83db15",
          "md5": "d66e6b5a8547db956c26eb013a3aeb36"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.19.0-mc1201-sources.jar",
          "url": "magicutils-config-yaml-1.19.0-mc1201-sources.jar",
          "size": 1615,
          "sha512": "7dd035aa467194e1f75f05e02b1afd2a2c881d14c30a7d577196ca3a326633df2cd9700da0936c91f30e1e9cb7cdedb5e3b373fab0a5b3ee0552940a8037fcbb",
          "sha256": "134bc160155c0948959d106b1fb7d7cb2b2e759d22e70303a8297ba77a13697e",
          "sha1": "3d4491714d06e6a1d91b497be8c6bfe0ef63c648",
          "md5": "f03bc030224c866efafb871d3584d804"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.19.0-mc1201-javadoc.jar",
          "url": "magicutils-config-yaml-1.19.0-mc1201-javadoc.jar",
          "size": 79836,
          "sha512": "2c0722a91c8cd49643c494ce9f73e54e0a7a7964e91fea0caeb7a9db685cb99c14bb7b76a76dc26246e3f3effaa1f8796e9ad3503ebd10ca6ca77e621a3c2935",
          "sha256": "2e08d13b2cb3ad3b5bd89198ddbac7b19440572e5de8591fcc23e98335825e05",
          "sha1": "48c13e34927ca25d11ac7aac19340ce007c26fae",
          "md5": "099d7721b3145c54d795d03dee35f5bb"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.19.0-mc1201-all.jar",
          "url": "magicutils-config-yaml-1.19.0-mc1201-all.jar",
          "size": 3340739,
          "sha512": "7d4ad31401391aadaf11e13cc6f4f8cadb961b8cfbc31c8ff3add252c132cac3ce2006fc8878dab4d4d905ef79538321ae610444acd7bbde64bb6a219be5ab9c",
          "sha256": "24cf8c435865dea4c438bb4a2f705b8f8cf5bde1e58565e8f25cf65da97bc49b",
          "sha1": "07ed02c530f54d11258605a66492f4d49899476b",
          "md5": "7ad353cfda41cd8d0cec1e06b333d569"
        }
      ]
    }
  ]
}
