{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-diagnostics",
    "version": "1.21.5-mc1201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.5-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-diagnostics-1.21.5-mc1201-mc1.20.jar",
          "url": "magicutils-diagnostics-1.21.5-mc1201-mc1.20.jar",
          "size": 60878,
          "sha512": "b4463b19d85ab11305f5938c6308bbe8433f9370c990e5b9c1f367a6fc94ef8fd81b8584e7cc28a8be05f7385573152b9f373a0ecf0cc14d012daedc51bebb08",
          "sha256": "0dc6f2f058e12871698aac27b5c8980ecf7d5093a9074e953b3fafc64bcf97e0",
          "sha1": "42f5d9ccde7c1fe6f1a382aa935a845fc95c3591",
          "md5": "238371cecd97c31c671bc8c0eb138e86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.5-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-diagnostics-1.21.5-mc1201-mc1.20.jar",
          "url": "magicutils-diagnostics-1.21.5-mc1201-mc1.20.jar",
          "size": 60878,
          "sha512": "b4463b19d85ab11305f5938c6308bbe8433f9370c990e5b9c1f367a6fc94ef8fd81b8584e7cc28a8be05f7385573152b9f373a0ecf0cc14d012daedc51bebb08",
          "sha256": "0dc6f2f058e12871698aac27b5c8980ecf7d5093a9074e953b3fafc64bcf97e0",
          "sha1": "42f5d9ccde7c1fe6f1a382aa935a845fc95c3591",
          "md5": "238371cecd97c31c671bc8c0eb138e86"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-diagnostics-1.21.5-mc1201-sources.jar",
          "url": "magicutils-diagnostics-1.21.5-mc1201-sources.jar",
          "size": 25570,
          "sha512": "bf1bf971429d2dde57dfd3d93f1fb15a3a68fe5170ba37ebaf51de9cd9e82946f72525e34a4759030a9718ab12b6fefc598f2e2ff2acdd8d46ceb0ea455dd72a",
          "sha256": "7eb04daf0a6018fe354e44ad851e3a124106faf431fd17c5d6634e154676ab80",
          "sha1": "bd353cf97eb2f2a6e4ecdbd129cacacfac9944e0",
          "md5": "80d76ce16f395f6bc5ba377f237d9cb2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-diagnostics-1.21.5-mc1201-javadoc.jar",
          "url": "magicutils-diagnostics-1.21.5-mc1201-javadoc.jar",
          "size": 135859,
          "sha512": "ad3a0e1e88cc409397aade696fe470bc0af24326649ba5702939c08e1783281c9c2742396dc3f8df0b7531b39907e5426c3487136213da1a22161cc394ff9908",
          "sha256": "6aa40dc045021f124e71d25a527c3fd0d5ce4a40e5fea0af6f4bf3cabad3c8de",
          "sha1": "3ba927695dc554ab73c084ed348fd5c2cc70a70f",
          "md5": "80c06ed6a524b7fea2da0c02e149a2e2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-diagnostics-1.21.5-mc1201-all.jar",
          "url": "magicutils-diagnostics-1.21.5-mc1201-all.jar",
          "size": 3506203,
          "sha512": "bd70219000cb66768b9481ad787f1def8a83e38d35788863c5bec6fe4dcd47b38122cf70e4f7cbf6fa6cbe0c5e9b7cca34ab59c2493d5ec40c314cc6645d6ad6",
          "sha256": "163d720671b50c20dbf53fa2d60cfcc9ec799dabedd6e32f4095f13d1b08b0ca",
          "sha1": "0f9bfcc41f7010b15543a57ffed24358bff274cd",
          "md5": "dbbb256b7645101d30d60746a0a48bc2"
        }
      ]
    }
  ]
}
