{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-http-client",
    "version": "1.21.1-mc1201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.21.1-mc1201-mc1.20.jar",
          "url": "magicutils-http-client-1.21.1-mc1201-mc1.20.jar",
          "size": 58198,
          "sha512": "ae8b86c80d40484ad1224bf792d2e16c12330d4cb3e73ff4778ed0478b52589a3eb711189261d94980b1a56bbef2dc68e350046275b04065ff31191ea2926b46",
          "sha256": "6652253d30705ff3d686d45f1b82b915c4ae271bea80740d03951a929157e278",
          "sha1": "9f1d67ead1dbf8b3f435176fdc283db41299603e",
          "md5": "5a967544f3e25a44a6a8d5350f81152b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.21.1-mc1201-mc1.20.jar",
          "url": "magicutils-http-client-1.21.1-mc1201-mc1.20.jar",
          "size": 58198,
          "sha512": "ae8b86c80d40484ad1224bf792d2e16c12330d4cb3e73ff4778ed0478b52589a3eb711189261d94980b1a56bbef2dc68e350046275b04065ff31191ea2926b46",
          "sha256": "6652253d30705ff3d686d45f1b82b915c4ae271bea80740d03951a929157e278",
          "sha1": "9f1d67ead1dbf8b3f435176fdc283db41299603e",
          "md5": "5a967544f3e25a44a6a8d5350f81152b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.21.1-mc1201-sources.jar",
          "url": "magicutils-http-client-1.21.1-mc1201-sources.jar",
          "size": 21590,
          "sha512": "94fde141f0c6aa3a602f194001bb5d9ad3c924882c6f3e07209ba8b8cc11f72c6e9457102864565d6585a3ddad4ffecc68bd63ba15345c5e4fb7133cebc699c0",
          "sha256": "d56fd445eccd8f18d0dc1cbd0a4e52ef38ea3ae752784fd7b9775bf86f362081",
          "sha1": "c75bc9748d407dc223ef8b26d8a203437fa98cf9",
          "md5": "fbf841914dd9cb02b159c954a7176056"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.21.1-mc1201-javadoc.jar",
          "url": "magicutils-http-client-1.21.1-mc1201-javadoc.jar",
          "size": 137265,
          "sha512": "cd25ec16785e5340fa3f8d2af2d43d280a3ec326d93fa0476e83b03025562b5f94bc8ae35973d2129fe322714e2d565a97d453583f54cf9039500b641af5a642",
          "sha256": "eaf25a63902b7a80992fd32fac0f6126cd3cd5fcca9dab27449a56e10bb13152",
          "sha1": "d403a6ce805ef297f561c122facbd5a3e2533ce0",
          "md5": "1044927bf09f878ab06235f09e346f91"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.21.1-mc1201-all.jar",
          "url": "magicutils-http-client-1.21.1-mc1201-all.jar",
          "size": 3500003,
          "sha512": "5a2c47f7bc94b3d0de063e2b4577142cbdeabdcb0652363f46f1fc7ac29346c5d0fc297b51763b38efce77ea2d1125367705a9c866e8cc4df9a2e16b6a067282",
          "sha256": "d100aee5842ef7afc721e960f257942ede1cc6642d5b7d58b2932a3e08bac75d",
          "sha1": "7827adeb0c95eb7631d20037a86914bb6def006d",
          "md5": "772f92230a983d05b586c29b5826c11b"
        }
      ]
    }
  ]
}
