{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bukkit",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.12.0-mc1.21.jar",
          "url": "magicutils-bukkit-1.12.0-mc1.21.jar",
          "size": 111973,
          "sha512": "da97eb6b31f08ed3438acd18b6777bac40b33fc950a1a0f1c00abf20c8e22dd079fe5bc9da2b5a36191fdd8aca1d7d59cde00c482e60ae25718b86bfe1bc1f1d",
          "sha256": "edbb8f7d3afc03eb930c0d9b57c79a215e8bcd96083dde4cbd92a56c63d1f419",
          "sha1": "1b3693a62f6a5bbbbe28d140f0242d983bb00ac7",
          "md5": "d52a0d7f8bc786ee2e475dabedc760ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.12.0-mc1.21.jar",
          "url": "magicutils-bukkit-1.12.0-mc1.21.jar",
          "size": 111973,
          "sha512": "da97eb6b31f08ed3438acd18b6777bac40b33fc950a1a0f1c00abf20c8e22dd079fe5bc9da2b5a36191fdd8aca1d7d59cde00c482e60ae25718b86bfe1bc1f1d",
          "sha256": "edbb8f7d3afc03eb930c0d9b57c79a215e8bcd96083dde4cbd92a56c63d1f419",
          "sha1": "1b3693a62f6a5bbbbe28d140f0242d983bb00ac7",
          "md5": "d52a0d7f8bc786ee2e475dabedc760ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.12.0-sources.jar",
          "url": "magicutils-bukkit-1.12.0-sources.jar",
          "size": 50361,
          "sha512": "ae9d2c73bf2b54dcf70f783746f9d36fda2924680db3717ef4cafd6e94ca6be6115bfbd3be61b7915d1cfe378d3b2720559298a0b653c004b5d3ef70854010df",
          "sha256": "b5a2896e40ed1c97c74710e07177d0ec95e80396a6e56d035fc9dcadc3dc6db7",
          "sha1": "53c6cc6a7c3f029dfcaa9858c06315f9208005c4",
          "md5": "d89ef7e9e1093a08263a4ab848338bb7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.12.0-javadoc.jar",
          "url": "magicutils-bukkit-1.12.0-javadoc.jar",
          "size": 257974,
          "sha512": "55055b77a454f69756e42506f8442c4f762c7177f1e31bde03d5081787b8eaed215098fe1b0009cafe6ce6993a8ea339849df4140b986cb916904946ee3a3b48",
          "sha256": "d23332351882139b8e8dd5f094631ddf04cd414ab84a19275ba8d47ba6d562bb",
          "sha1": "556aece1ea088b1dc58e3228eba1420b253d521a",
          "md5": "28f83b8963323380657e39c26ded3e0d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.12.0-all.jar",
          "url": "magicutils-bukkit-1.12.0-all.jar",
          "size": 3469094,
          "sha512": "b1101076446dd7bc3c9afdbfec3a9002c1192c4445188d817a10c058c6113bbff590c6cc6ad8091814b938db157872cc1bef595e9db77bedcf44130abb9a1940",
          "sha256": "ef4a121b28477f8c5042bff0542ee324480c57987930c1fedb19aa5106f16291",
          "sha1": "e46d089fc0896fd7d01f2a7156d16d8a788763a6",
          "md5": "4a6a9f0f4e4e7ef376f6f98309713196"
        }
      ]
    }
  ]
}
