{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-logger",
    "version": "1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.21.1-mc1.21.jar",
          "url": "magicutils-logger-1.21.1-mc1.21.jar",
          "size": 77263,
          "sha512": "6a0e1f14c2555f68d7b3b75da87253d8241eec594f2ae615deca4ff17f6a066da995d526fe51174ad84bcf9e44c8e4d4a53fb55dcc444eb45062b04d9d6539bb",
          "sha256": "54a23a82eacfa45e32eb7fd2a8a44c3cf30f9a87dc27b2bdd643f9da6bd73d0e",
          "sha1": "ccbbf16ecdfd390c21ef3f9ffe80ab40c0f0f001",
          "md5": "22fe472a319f4dd24655b664641896b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.21.1-mc1.21.jar",
          "url": "magicutils-logger-1.21.1-mc1.21.jar",
          "size": 77263,
          "sha512": "6a0e1f14c2555f68d7b3b75da87253d8241eec594f2ae615deca4ff17f6a066da995d526fe51174ad84bcf9e44c8e4d4a53fb55dcc444eb45062b04d9d6539bb",
          "sha256": "54a23a82eacfa45e32eb7fd2a8a44c3cf30f9a87dc27b2bdd643f9da6bd73d0e",
          "sha1": "ccbbf16ecdfd390c21ef3f9ffe80ab40c0f0f001",
          "md5": "22fe472a319f4dd24655b664641896b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.21.1-sources.jar",
          "url": "magicutils-logger-1.21.1-sources.jar",
          "size": 35251,
          "sha512": "fb897db17baadb42f711f76483f1384132753ea660dc056b714d16313bebdc466a4554ece221851150d28112b5963057af6982cdf57b7269518e842a5110dea2",
          "sha256": "5b3032ca147e41cebb07b060147495acf50d7865e8dc6de2791aaa15a9ec9bbc",
          "sha1": "3e3c73b102e2b0892885c3ede99623beeff994db",
          "md5": "7a802ef6011516fc85e3dd9b3543c493"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.21.1-javadoc.jar",
          "url": "magicutils-logger-1.21.1-javadoc.jar",
          "size": 203356,
          "sha512": "57ff23e29c16c26a3560e8446ea51aae4ef1b9c3cd5468da844efcef76ffe82cc7689c253ec7f3296c0fa6b040b6a5348832fb96db03d2b7446566f102cfdffa",
          "sha256": "fdb6d0d8c1697969b9de3af1dfa8934966a55c4773a738e8e9c65432fc3cd1a8",
          "sha1": "eb7e6679351c6f0266e7fcda48d21862b30d6928",
          "md5": "0427317ebf19232e0dca729c11d906df"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.21.1-all.jar",
          "url": "magicutils-logger-1.21.1-all.jar",
          "size": 3240046,
          "sha512": "4031d4347a9c4ac9d3e58542a5e2b3c7e3ec2ac6f7d9c9ea1e24ef15bfa26187cd9d789e52872d7caf9649684bb1d42601d3a4f08c0ee1894932f6fdbbfd5dc7",
          "sha256": "f136c816f5a24a389eb2f2ed139eb0320fb35b8e0f1f351ac8347f5bd4ba0c20",
          "sha1": "886ccafe367c657e1fdee315c8e81774188d7b33",
          "md5": "2170ed617532bb2bab0f317771dcd5db"
        }
      ]
    }
  ]
}
