{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-http-client",
    "version": "1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.21.5-mc1.21.jar",
          "url": "magicutils-http-client-1.21.5-mc1.21.jar",
          "size": 57929,
          "sha512": "79ae16d335f231a5d7cd6ba2b921d420cbd73d9f629f6bcfe51f1a31e87c3c12dbbaa308960a923be7d726f364cfeee75d452d1537233dcfdb9c880abf43b010",
          "sha256": "ea6a6fb08af8d7dfee30dfc5355c8b895924d8b076dae40fd1fb968afd4329ac",
          "sha1": "4629c63ab5135fe779f0e1d1ff888c132d3422fc",
          "md5": "ef57b036ff0aaeecf56d2c25b75349d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.21.5-mc1.21.jar",
          "url": "magicutils-http-client-1.21.5-mc1.21.jar",
          "size": 57929,
          "sha512": "79ae16d335f231a5d7cd6ba2b921d420cbd73d9f629f6bcfe51f1a31e87c3c12dbbaa308960a923be7d726f364cfeee75d452d1537233dcfdb9c880abf43b010",
          "sha256": "ea6a6fb08af8d7dfee30dfc5355c8b895924d8b076dae40fd1fb968afd4329ac",
          "sha1": "4629c63ab5135fe779f0e1d1ff888c132d3422fc",
          "md5": "ef57b036ff0aaeecf56d2c25b75349d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.21.5-sources.jar",
          "url": "magicutils-http-client-1.21.5-sources.jar",
          "size": 21507,
          "sha512": "fb389b9f1f736dd8405ad9f2e68a89dc3dd5625355e16553c62e1a8a12cacea19b39e97180aa3637d4edf5f1764795df5b87075506fb48dd4792cd05e9742eed",
          "sha256": "fa759d674e2ad66b23b8b35143483e0d80d5ed1029c165509da8f70e8efa22f4",
          "sha1": "52d6404d731984780975828e0a538a965721821f",
          "md5": "2b11a3e17892708ccb61ad8fd41c3331"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.21.5-javadoc.jar",
          "url": "magicutils-http-client-1.21.5-javadoc.jar",
          "size": 149265,
          "sha512": "e26dd01cfedf6e24d7661e6f44ee2859785fd5dbdf7ea2dc09c998a01c676112dea956211ed93c7ab9de101b6c7f0e5fa0fd3e4bea921d0286aa69a179c91a84",
          "sha256": "45a61ca392cccc9bfb780d240d1f610a4b41fb478ca2e56e4d3eab3bb034194d",
          "sha1": "d07644604fdc1ecf1d36e470bcaad304466ee2ae",
          "md5": "cb94310659ab09499480fb0516c4ca6d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.21.5-all.jar",
          "url": "magicutils-http-client-1.21.5-all.jar",
          "size": 3503076,
          "sha512": "cacfaadf1e678fe9af2966b6242531315ac74a33ea572e3e83e7d1ac77846a9b40e09576d44be02bafc87c2a0d62f05106143355e55d8d89691e2bb0d7a40038",
          "sha256": "29624de98db532154c4d641a895abb64efaa07f523ba247de3e80e66db88fbd8",
          "sha1": "3452542d4da3c3397042a0f903a31fe2a997ca49",
          "md5": "f782153d7d1c5571f719f9872f9c55d9"
        }
      ]
    }
  ]
}
