{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands-neoforge",
    "version": "1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands-brigadier",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-neoforge",
          "version": {
            "requires": "1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.21.1-mc1.21.jar",
          "url": "magicutils-commands-neoforge-1.21.1-mc1.21.jar",
          "size": 49424,
          "sha512": "4bb5792de8aebc331ed8da83d70ec9c396771e6660e7e642ecc45cb0bd33d11ac87b98a81579f9c84ab2a6d309cadf2eb661573ff80d0ac49ed99eaf81e19643",
          "sha256": "cdc717d884bf922fac5ea95320299de8b16cd224ab0534cbb96204ef67ec5bf6",
          "sha1": "7be815d81c01b1c8e5c750a72a4d5270b293b6fa",
          "md5": "f83f6dc66c0cd206c118d2c2e0daf7a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands-brigadier",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-neoforge",
          "version": {
            "requires": "1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.21.1-mc1.21.jar",
          "url": "magicutils-commands-neoforge-1.21.1-mc1.21.jar",
          "size": 49424,
          "sha512": "4bb5792de8aebc331ed8da83d70ec9c396771e6660e7e642ecc45cb0bd33d11ac87b98a81579f9c84ab2a6d309cadf2eb661573ff80d0ac49ed99eaf81e19643",
          "sha256": "cdc717d884bf922fac5ea95320299de8b16cd224ab0534cbb96204ef67ec5bf6",
          "sha1": "7be815d81c01b1c8e5c750a72a4d5270b293b6fa",
          "md5": "f83f6dc66c0cd206c118d2c2e0daf7a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.21.1-sources.jar",
          "url": "magicutils-commands-neoforge-1.21.1-sources.jar",
          "size": 16673,
          "sha512": "31b54cec2fef5e6713cb717adbd662157b417eedd75415b51297d49d3cec4b41c91fbca9f590e860795e78a2f33b242e4a4581de9db017e90763c310c98af440",
          "sha256": "8bc80b11b0068d7975d1aa805f34f8336fa745f9fc3349d8c73073fb34f2595d",
          "sha1": "7917a1e3beb41420315bfcb7f5ed403e97c39852",
          "md5": "4533120bbf8aa170b4781cb493b7b3cd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.21.1-javadoc.jar",
          "url": "magicutils-commands-neoforge-1.21.1-javadoc.jar",
          "size": 152268,
          "sha512": "f9227e85120e1a46c639256260683a13ee0b38329d680ba9a8152a5ef52ab71f578fa49580d1dc8e0f29dc6443a001a4f3e383207e3ca10810ba910066d5e30e",
          "sha256": "5fd71b64eadba6cf2561a53e20011b9a5c7c9b541398cb9d72317845745e6b99",
          "sha1": "717758a8ff7e38fac141f9ffd4f44d1ed693bd69",
          "md5": "ef1fb6f847b1bb08cca75679919954f7"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.21.1-all.jar",
          "url": "magicutils-commands-neoforge-1.21.1-all.jar",
          "size": 40522262,
          "sha512": "e533d9700aa536fd0a662cee5eaa5c9d9f68b2aecae8c774019b1e926a50ff52703d78cb7a3cf96a6419c55a610c32ba8714ce5d77f59734af1e1f34d32f6ad3",
          "sha256": "0aafd4011abb5a65e4330f8bec50d5b66382761e7ec9a6402315d953fbd2f055",
          "sha1": "8d2e73911dfeb0be56de8267faee022093e75404",
          "md5": "63a1ac0e0b2a181f605020e3d9f55c20"
        }
      ]
    }
  ]
}
