{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-logger",
    "version": "1.21.3-mc1201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.3-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.21.3-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.21.3-mc1201"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.21.3-mc1201-mc1.20.jar",
          "url": "magicutils-logger-1.21.3-mc1201-mc1.20.jar",
          "size": 77291,
          "sha512": "a7fd28d083833c257257f81425d451b9d196ee7668bf617a36f573f71a43f463e308a73db62dc5dc3ff89df8533dbc63f444feae6ea6f59b46279b7a47148ebc",
          "sha256": "13a676a86c92ea0c004a8f909c64a69076b6973757f25f58ba0c77ff7b5fbab3",
          "sha1": "89b5b10b53f30bb186859030b54b2d198d7eeca2",
          "md5": "e9a420b6f5d1a97779e2d03b1ef5cb9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.3-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.21.3-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.21.3-mc1201"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.21.3-mc1201-mc1.20.jar",
          "url": "magicutils-logger-1.21.3-mc1201-mc1.20.jar",
          "size": 77291,
          "sha512": "a7fd28d083833c257257f81425d451b9d196ee7668bf617a36f573f71a43f463e308a73db62dc5dc3ff89df8533dbc63f444feae6ea6f59b46279b7a47148ebc",
          "sha256": "13a676a86c92ea0c004a8f909c64a69076b6973757f25f58ba0c77ff7b5fbab3",
          "sha1": "89b5b10b53f30bb186859030b54b2d198d7eeca2",
          "md5": "e9a420b6f5d1a97779e2d03b1ef5cb9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.21.3-mc1201-sources.jar",
          "url": "magicutils-logger-1.21.3-mc1201-sources.jar",
          "size": 35251,
          "sha512": "fb897db17baadb42f711f76483f1384132753ea660dc056b714d16313bebdc466a4554ece221851150d28112b5963057af6982cdf57b7269518e842a5110dea2",
          "sha256": "5b3032ca147e41cebb07b060147495acf50d7865e8dc6de2791aaa15a9ec9bbc",
          "sha1": "3e3c73b102e2b0892885c3ede99623beeff994db",
          "md5": "7a802ef6011516fc85e3dd9b3543c493"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.21.3-mc1201-javadoc.jar",
          "url": "magicutils-logger-1.21.3-mc1201-javadoc.jar",
          "size": 190747,
          "sha512": "0ad983de9dd3398a50015ce738c822e86860838f35be22223fbef9090d559ca9da617a82a01d96907f1228ea3a0f095e26e77c1e2c654ef246462fd5bc8988fe",
          "sha256": "121061e74018545ec1dba78572494fa35f0deaef9acbbf76b7963b8576a180d6",
          "sha1": "9e790503c2ae350dd3ae99658b6dc7a2f67e43d6",
          "md5": "dafde779eec4c6b3adc4c414111bb2a8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.21.3-mc1201-all.jar",
          "url": "magicutils-logger-1.21.3-mc1201-all.jar",
          "size": 3240373,
          "sha512": "463e2cbcaf2dc49d47cb356d4759cae503949c4a495efdb7156d55c96c777af29104931b2f2da193742c65cf0bf21d5004e8bda6c71f7fe5516cd27f45e83f5e",
          "sha256": "08ec82260581038573235a979b1e5f162a4feeeb63cdf62b1ae0686af1ec6dad",
          "sha1": "81a934198a563f3b0042e8708818617bdab98cfc",
          "md5": "1daae2bd0594db5f7078b2ee27853fdd"
        }
      ]
    }
  ]
}
