{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-http-client",
    "version": "1.14.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.14.3-mc1.21.jar",
          "url": "magicutils-http-client-1.14.3-mc1.21.jar",
          "size": 56617,
          "sha512": "09bc1bde919e4fda8f6c168ef98c1f0e02ca522d9b5bf33c9bce4a68ca3b9ecb1b874efcf2c62822d46b28acb286b35c4873a19cf391ee835f214b622f5fc659",
          "sha256": "1dc5d645190a791d7b790b906de0154280b2412e35ff2a867e533969d7d8762a",
          "sha1": "0fd45cf9fc8496713e2f80562a9b0f4aec7a88b0",
          "md5": "33a5198d9d28ce0ddf5e3d5fe51f7893"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.14.3-mc1.21.jar",
          "url": "magicutils-http-client-1.14.3-mc1.21.jar",
          "size": 56617,
          "sha512": "09bc1bde919e4fda8f6c168ef98c1f0e02ca522d9b5bf33c9bce4a68ca3b9ecb1b874efcf2c62822d46b28acb286b35c4873a19cf391ee835f214b622f5fc659",
          "sha256": "1dc5d645190a791d7b790b906de0154280b2412e35ff2a867e533969d7d8762a",
          "sha1": "0fd45cf9fc8496713e2f80562a9b0f4aec7a88b0",
          "md5": "33a5198d9d28ce0ddf5e3d5fe51f7893"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.14.3-sources.jar",
          "url": "magicutils-http-client-1.14.3-sources.jar",
          "size": 20828,
          "sha512": "0592c15958ee8060d8cc40f8a3fb91cfb7e7225c37fd4df5dce4bebf8b298175987529bb353d73c8e0e395a5a78b7ac8134d9a700317c68a1c8f1ac4fa6fdd9e",
          "sha256": "a047a1bfc5aacbbfb4742069ff1b8609623a6c1e3a63fe03e431a6ecd6661f82",
          "sha1": "c02180acd21e930582c4e58ef05048e4bcaccbdb",
          "md5": "08a71f85e7ea867926357543a8860bc2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.14.3-javadoc.jar",
          "url": "magicutils-http-client-1.14.3-javadoc.jar",
          "size": 149264,
          "sha512": "eeb14b523d955a221c624deb4b509af3d1e9d1fe7eaac3782b3ac83df7c6a7abba2b29626a448625019195d5bfa7b0a7ce424a3c6ebd3edf4d4ebe05fe077202",
          "sha256": "d49ea32f9e1c420987302cfd89447aa31f201b435fd094c3fccf4f8b23c4aa95",
          "sha1": "979558894887524b5942b7dfbd5434584ee36c4b",
          "md5": "98befead5076890e39b9eef0eabf82b7"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.14.3-all.jar",
          "url": "magicutils-http-client-1.14.3-all.jar",
          "size": 3466092,
          "sha512": "37cee7b177b6a6f193a93168672b81fae5d475736378f01eff2621b17f2ac55b17e2d68d87c59bc7ae507d955a41cf277110c41f30a59ff78dad3903de5d29c8",
          "sha256": "816a7f2563e9238557f1134a706064d2c58817432ec44aea9b52d723c296442f",
          "sha1": "2e2c5313b314fee4dd17ec5fcf012c0531053548",
          "md5": "3b7c9755fab7e296d44946db81cff7a3"
        }
      ]
    }
  ]
}
