{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-neoforge",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.13.0-mc1.21.jar",
          "url": "magicutils-neoforge-1.13.0-mc1.21.jar",
          "size": 14657,
          "sha512": "90370a0e5f8c60342d8db38fab04e52a179d623b83f24d81284899c6b586ad76ccd28af7d997c530625fece6841ad52cee90b1172c51f439ac9f3d4fb238dbf2",
          "sha256": "adca55258d6aa90380984d0c429ebfecc5bf7bace7fc4444784e31c3d33363fa",
          "sha1": "df08fbadd3343b7f52bda5d4aa1fb0f85e4ec58b",
          "md5": "50b429d8a42021ff774bd9857a23c2bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.13.0-mc1.21.jar",
          "url": "magicutils-neoforge-1.13.0-mc1.21.jar",
          "size": 14657,
          "sha512": "90370a0e5f8c60342d8db38fab04e52a179d623b83f24d81284899c6b586ad76ccd28af7d997c530625fece6841ad52cee90b1172c51f439ac9f3d4fb238dbf2",
          "sha256": "adca55258d6aa90380984d0c429ebfecc5bf7bace7fc4444784e31c3d33363fa",
          "sha1": "df08fbadd3343b7f52bda5d4aa1fb0f85e4ec58b",
          "md5": "50b429d8a42021ff774bd9857a23c2bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.13.0-sources.jar",
          "url": "magicutils-neoforge-1.13.0-sources.jar",
          "size": 8247,
          "sha512": "184ba0fe6dfafafe701e5bc77b283e6fbd9f220c68bdf2c58637ded5c8804968cca371c0f1af366fbc6712c3c600d8e9710e42c35a3b290da170d959f4773304",
          "sha256": "23f283d33e0113687ef05e2fba9713115daaffd00fb6fb671a2d3cdf43aaa3d7",
          "sha1": "1003943f1510f59e5ca4acb08a60f7f796b4248b",
          "md5": "fcb2110501a1262d5d033f0ded246695"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.13.0-javadoc.jar",
          "url": "magicutils-neoforge-1.13.0-javadoc.jar",
          "size": 114902,
          "sha512": "d933f953d0947e6372ccdbb1a9e959b778fadd145dac7c69288c5991d173584ae993d724b4062ef2214de07c7610852e7527028b1a79c309d02fad8a33af61b4",
          "sha256": "e416c928b111c5e1c8145cda3e15eba03b7cace43477f397226d4b5a4f959a4f",
          "sha1": "c7254e472a5d02a2f1d93503e08b1c55c6e837cc",
          "md5": "055d9c00374f822afddff6bc8e2fd3af"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.13.0-all.jar",
          "url": "magicutils-neoforge-1.13.0-all.jar",
          "size": 40303235,
          "sha512": "19508b4d6c642612e6d604216fb5397996109154f39047697ab3048d88fa3fde954e47acd7662d2033c62ff0646d5657a10f7e1d3fed5624c9334d75659d8222",
          "sha256": "266bd5304b5e315091171fe8ee276279699662a187737eccf93c721c0fd40e7c",
          "sha1": "c0f4afb91b3b74e6c75e511b210285cb65dfba76",
          "md5": "3a896fb56c3421f861f2114650047ced"
        }
      ]
    }
  ]
}
