package dev.ua.theroer.magicutils.logger;

import dev.ua.theroer.magicutils.Logger;
import org.bukkit.entity.Player;

import java.util.Collection;

/**
 * Generated logger methods for convenient static access.
 * This class is normally generated by annotation processor, but provided here
 * as example.
 * 
 */
public final class LoggerGen {
    /**
     * Private constructor to prevent instantiation.
     */
    private LoggerGen() {
    }

    /**
     * Sends an info message.
     * 
     * @param msg the message to send
     */
    public static void info(Object msg) {
        Logger.send(LogLevel.INFO, msg, null, null, Logger.getDefaultTarget(), false);
    }

    /**
     * Sends an info message with a format string.
     * 
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void info(String fmt, Object... args) {
        Logger.send(LogLevel.INFO, String.format(fmt, args), null, null, Logger.getDefaultTarget(), false);
    }

    /**
     * Sends an info message to the console.
     * 
     * @param msg the message to send
     */
    public static void infoConsole(Object msg) {
        Logger.send(LogLevel.INFO, msg, null, null, LogTarget.CONSOLE, false);
    }

    /**
     * Sends an info message to the console with a format string.
     * 
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void infoConsole(String fmt, Object... args) {
        Logger.send(LogLevel.INFO, String.format(fmt, args), null, null, LogTarget.CONSOLE, false);
    }

    /**
     * Sends an info message to all players.
     * 
     * @param msg the message to send
     */
    public static void infoAll(Object msg) {
        Logger.send(LogLevel.INFO, msg, null, null, LogTarget.BOTH, true);
    }

    /**
     * Sends an info message to all players with a format string.
     * 
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void infoAll(String fmt, Object... args) {
        Logger.send(LogLevel.INFO, String.format(fmt, args), null, null, LogTarget.BOTH, true);
    }

    /**
     * Sends an info message to a specific player.
     * 
     * @param p   the player to send the message to
     * @param msg the message to send
     */
    public static void info(Player p, Object msg) {
        Logger.send(LogLevel.INFO, msg, p, null, LogTarget.CHAT, false);
    }

    /**
     * Sends an info message to a specific player with a format string.
     * 
     * @param p    the player to send the message to
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void info(Player p, String fmt, Object... args) {
        Logger.send(LogLevel.INFO, String.format(fmt, args), p, null, LogTarget.CHAT, false);
    }

    /**
     * Sends an info message to a collection of players.
     * 
     * 
     * @param players the collection of players to send the message to
     * @param msg     the message to send
     */
    public static void info(Collection<? extends Player> players, Object msg) {
        Logger.send(LogLevel.INFO, msg, null, players, LogTarget.CHAT, false);
    }

    /**
     * Sends an info message to a collection of players with a format string.
     * 
     * 
     * @param players the collection of players to send the message to
     * @param fmt     the format string
     * @param args    the arguments for the format string
     */
    public static void info(Collection<? extends Player> players, String fmt, Object... args) {
        Logger.send(LogLevel.INFO, String.format(fmt, args), null, players, LogTarget.CHAT, false);
    }

    /**
     * Sends a warning message.
     * 
     * @param msg the message to send
     */
    public static void warn(Object msg) {
        Logger.send(LogLevel.WARN, msg, null, null, Logger.getDefaultTarget(), false);
    }

    /**
     * Sends a warning message with a format string.
     * 
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void warn(String fmt, Object... args) {
        Logger.send(LogLevel.WARN, String.format(fmt, args), null, null, Logger.getDefaultTarget(), false);
    }

    /**
     * Sends a warning message to the console.
     * 
     * @param msg the message to send
     */
    public static void warnConsole(Object msg) {
        Logger.send(LogLevel.WARN, msg, null, null, LogTarget.CONSOLE, false);
    }

    /**
     * Sends a warning message to the console with a format string.
     * 
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void warnConsole(String fmt, Object... args) {
        Logger.send(LogLevel.WARN, String.format(fmt, args), null, null, LogTarget.CONSOLE, false);
    }

    /**
     * Sends a warning message to all players.
     * 
     * @param msg the message to send
     */
    public static void warnAll(Object msg) {
        Logger.send(LogLevel.WARN, msg, null, null, LogTarget.BOTH, true);
    }

    /**
     * Sends a warning message to all players with a format string.
     * 
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void warnAll(String fmt, Object... args) {
        Logger.send(LogLevel.WARN, String.format(fmt, args), null, null, LogTarget.BOTH, true);
    }

    /**
     * Sends a warning message to a specific player.
     * 
     * @param p   the player to send the message to
     * @param msg the message to send
     */
    public static void warn(Player p, Object msg) {
        Logger.send(LogLevel.WARN, msg, p, null, LogTarget.CHAT, false);
    }

    /**
     * Sends a warning message to a specific player with a format string.
     * 
     * @param p    the player to send the message to
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void warn(Player p, String fmt, Object... args) {
        Logger.send(LogLevel.WARN, String.format(fmt, args), p, null, LogTarget.CHAT, false);
    }

    /**
     * Sends a warning message to a collection of players.
     * 
     * 
     * @param players the collection of players to send the message to
     * @param msg     the message to send
     */
    public static void warn(Collection<? extends Player> players, Object msg) {
        Logger.send(LogLevel.WARN, msg, null, players, LogTarget.CHAT, false);
    }

    /**
     * Sends a warning message to a collection of players with a format string.
     * 
     * 
     * @param players the collection of players to send the message to
     * @param fmt     the format string
     * @param args    the arguments for the format string
     */
    public static void warn(Collection<? extends Player> players, String fmt, Object... args) {
        Logger.send(LogLevel.WARN, String.format(fmt, args), null, players, LogTarget.CHAT, false);
    }

    /**
     * Sends an error message.
     * 
     * @param msg the message to send
     */
    public static void error(Object msg) {
        Logger.send(LogLevel.ERROR, msg, null, null, Logger.getDefaultTarget(), false);
    }

    /**
     * Sends an error message with a format string.
     * 
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void error(String fmt, Object... args) {
        Logger.send(LogLevel.ERROR, String.format(fmt, args), null, null, Logger.getDefaultTarget(), false);
    }

    /**
     * Sends an error message to the console.
     * 
     * @param msg the message to send
     */
    public static void errorConsole(Object msg) {
        Logger.send(LogLevel.ERROR, msg, null, null, LogTarget.CONSOLE, false);
    }

    /**
     * Sends an error message to the console with a format string.
     * 
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void errorConsole(String fmt, Object... args) {
        Logger.send(LogLevel.ERROR, String.format(fmt, args), null, null, LogTarget.CONSOLE, false);
    }

    /**
     * Sends an error message to all players.
     * 
     * @param msg the message to send
     */
    public static void errorAll(Object msg) {
        Logger.send(LogLevel.ERROR, msg, null, null, LogTarget.BOTH, true);
    }

    /**
     * Sends an error message to all players with a format string.
     * 
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void errorAll(String fmt, Object... args) {
        Logger.send(LogLevel.ERROR, String.format(fmt, args), null, null, LogTarget.BOTH, true);
    }

    /**
     * Sends an error message to a specific player.
     * 
     * @param p   the player to send the message to
     * @param msg the message to send
     */
    public static void error(Player p, Object msg) {
        Logger.send(LogLevel.ERROR, msg, p, null, LogTarget.CHAT, false);
    }

    /**
     * Sends an error message to a specific player with a format string.
     * 
     * @param p    the player to send the message to
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void error(Player p, String fmt, Object... args) {
        Logger.send(LogLevel.ERROR, String.format(fmt, args), p, null, LogTarget.CHAT, false);
    }

    /**
     * Sends an error message to a collection of players.
     * 
     * 
     * @param players the collection of players to send the message to
     * @param msg     the message to send
     */
    public static void error(Collection<? extends Player> players, Object msg) {
        Logger.send(LogLevel.ERROR, msg, null, players, LogTarget.CHAT, false);
    }

    /**
     * Sends an error message to a collection of players with a format string.
     * 
     * @param players the collection of players to send the message to
     * @param fmt     the format string
     * @param args    the arguments for the format string
     */
    public static void error(Collection<? extends Player> players, String fmt, Object... args) {
        Logger.send(LogLevel.ERROR, String.format(fmt, args), null, players, LogTarget.CHAT, false);
    }

    /**
     * Sends a debug message.
     * 
     * @param msg the message to send
     */
    public static void debug(Object msg) {
        Logger.send(LogLevel.DEBUG, msg, null, null, Logger.getDefaultTarget(), false);
    }

    /**
     * Sends a debug message with a format string.
     * 
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void debug(String fmt, Object... args) {
        Logger.send(LogLevel.DEBUG, String.format(fmt, args), null, null, Logger.getDefaultTarget(), false);
    }

    /**
     * Sends a debug message to the console.
     * 
     * @param msg the message to send
     */
    public static void debugConsole(Object msg) {
        Logger.send(LogLevel.DEBUG, msg, null, null, LogTarget.CONSOLE, false);
    }

    /**
     * Sends a debug message to the console with a format string.
     * 
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void debugConsole(String fmt, Object... args) {
        Logger.send(LogLevel.DEBUG, String.format(fmt, args), null, null, LogTarget.CONSOLE, false);
    }

    /**
     * Sends a debug message to all players.
     * 
     * @param msg the message to send
     */
    public static void debugAll(Object msg) {
        Logger.send(LogLevel.DEBUG, msg, null, null, LogTarget.BOTH, true);
    }

    /**
     * Sends a debug message to all players with a format string.
     * 
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void debugAll(String fmt, Object... args) {
        Logger.send(LogLevel.DEBUG, String.format(fmt, args), null, null, LogTarget.BOTH, true);
    }

    /**
     * Sends a debug message to a specific player.
     * 
     * @param p   the player to send the message to
     * @param msg the message to send
     */
    public static void debug(Player p, Object msg) {
        Logger.send(LogLevel.DEBUG, msg, p, null, LogTarget.CHAT, false);
    }

    /**
     * Sends a debug message to a specific player with a format string.
     * 
     * @param p    the player to send the message to
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void debug(Player p, String fmt, Object... args) {
        Logger.send(LogLevel.DEBUG, String.format(fmt, args), p, null, LogTarget.CHAT, false);
    }

    /**
     * Sends a debug message to a collection of players.
     * 
     * @param players the collection of players to send the message to
     * @param msg     the message to send
     */
    public static void debug(Collection<? extends Player> players, Object msg) {
        Logger.send(LogLevel.DEBUG, msg, null, players, LogTarget.CHAT, false);
    }

    /**
     * Sends a debug message to a collection of players with a format string.
     * 
     * @param players the collection of players to send the message to
     * @param fmt     the format string
     * @param args    the arguments for the format string
     */
    public static void debug(Collection<? extends Player> players, String fmt, Object... args) {
        Logger.send(LogLevel.DEBUG, String.format(fmt, args), null, players, LogTarget.CHAT, false);
    }

    /**
     * Sends a success message.
     * 
     * @param msg the message to send
     */
    public static void success(Object msg) {
        Logger.send(LogLevel.SUCCESS, msg, null, null, Logger.getDefaultTarget(), false);
    }

    /**
     * Sends a success message with a format string.
     * 
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void success(String fmt, Object... args) {
        Logger.send(LogLevel.SUCCESS, String.format(fmt, args), null, null, Logger.getDefaultTarget(), false);
    }

    /**
     * Sends a success message to the console.
     * 
     * @param msg the message to send
     */
    public static void successConsole(Object msg) {
        Logger.send(LogLevel.SUCCESS, msg, null, null, LogTarget.CONSOLE, false);
    }

    /**
     * Sends a success message to the console with a format string.
     * 
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void successConsole(String fmt, Object... args) {
        Logger.send(LogLevel.SUCCESS, String.format(fmt, args), null, null, LogTarget.CONSOLE, false);
    }

    /**
     * Sends a success message to all players.
     * 
     * @param msg the message to send
     */
    public static void successAll(Object msg) {
        Logger.send(LogLevel.SUCCESS, msg, null, null, LogTarget.BOTH, true);
    }

    /**
     * Sends a success message to all players with a format string.
     * 
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void successAll(String fmt, Object... args) {
        Logger.send(LogLevel.SUCCESS, String.format(fmt, args), null, null, LogTarget.BOTH, true);
    }

    /**
     * Sends a success message to a specific player.
     * 
     * @param p   the player to send the message to
     * @param msg the message to send
     */
    public static void success(Player p, Object msg) {
        Logger.send(LogLevel.SUCCESS, msg, p, null, LogTarget.CHAT, false);
    }

    /**
     * Sends a success message to a specific player with a format string.
     * 
     * @param p    the player to send the message to
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void success(Player p, String fmt, Object... args) {
        Logger.send(LogLevel.SUCCESS, String.format(fmt, args), p, null, LogTarget.CHAT, false);
    }

    /**
     * Sends a success message to a collection of players.
     * 
     * @param players the collection of players to send the message to
     * @param msg     the message to send
     */
    public static void success(Collection<? extends Player> players, Object msg) {
        Logger.send(LogLevel.SUCCESS, msg, null, players, LogTarget.CHAT, false);
    }

    /**
     * Sends a success message to a collection of players with a format string.
     * 
     * @param players the collection of players to send the message to
     * @param fmt     the format string
     * @param args    the arguments for the format string
     */
    public static void success(Collection<? extends Player> players, String fmt, Object... args) {
        Logger.send(LogLevel.SUCCESS, String.format(fmt, args), null, players, LogTarget.CHAT, false);
    }

    /**
     * Sends a broadcast message.
     * 
     * @param message the message to send
     */
    public static void broadcast(Object message) {
        Logger.send(LogLevel.INFO, message, null, null, LogTarget.BOTH, true);
    }
}
