package dev.ua.theroer.magicutils.logger;

import dev.ua.theroer.magicutils.Logger;
import org.bukkit.entity.Player;

import java.util.Collection;

/**
 * Logger instance with custom prefix.
 * All log methods are generated by annotation processor.
 */
@LogMethods(staticMethods = false, audienceType = "org.bukkit.entity.Player")
public class PrefixedLogger extends PrefixedLoggerMethods implements PrefixedLoggerAdapter<Player, LogBuilder> {
    private final Logger logger;
    private final PrefixedLoggerCore core;

    public PrefixedLogger(Logger logger, PrefixedLoggerCore core) {
        this.logger = logger;
        this.core = core;
    }

    @Override
    public PrefixedLoggerCore getCore() {
        return core;
    }

    @Override
    public LoggerAdapter<Player, ?> getLoggerAdapter() {
        return logger;
    }

    @Override
    public LogBuilder buildLogBuilder(LogLevel level) {
        return new PrefixedLogBuilder(level);
    }

    @Override
    public void send(LogLevel level, Object message) {
        PrefixedLoggerAdapter.super.send(level, message);
    }

    @Override
    public void send(LogLevel level, Object message, Player player) {
        PrefixedLoggerAdapter.super.send(level, message, player);
    }

    @Override
    public void send(LogLevel level, Object message, Player player, boolean all) {
        PrefixedLoggerAdapter.super.send(level, message, player, all);
    }

    @Override
    public void sendToConsole(LogLevel level, Object message) {
        PrefixedLoggerAdapter.super.sendToConsole(level, message);
    }

    @Override
    public void sendToPlayers(LogLevel level, Object message, Collection<? extends Player> players) {
        PrefixedLoggerAdapter.super.sendToPlayers(level, message, players);
    }

    private class PrefixedLogBuilder extends LogBuilder {
        PrefixedLogBuilder(LogLevel level) {
            super(logger, level);
        }

        @Override
        public void send(Object message, Object... placeholders) {
            if (!core.isEnabled()) {
                return;
            }
            super.send(core.formatMessage(message), placeholders);
        }
    }
}
