package dev.ua.theroer.magicutils.logger;

import dev.ua.theroer.magicutils.Logger;
import dev.ua.theroer.magicutils.platform.Audience;
import org.bukkit.entity.Player;

import java.util.Collection;

/**
 * Logger instance with custom prefix.
 * All log methods are generated by annotation processor.
 */
@LogMethods(staticMethods = false, audienceType = "org.bukkit.entity.Player")
public class PrefixedLogger extends PrefixedLoggerMethods {
    private final Logger logger;
    private final PrefixedLoggerCore core;

    public PrefixedLogger(Logger logger, PrefixedLoggerCore core) {
        this.logger = logger;
        this.core = core;
    }

    public String getName() {
        return core.getName();
    }

    public String getPrefix() {
        return core.getPrefix();
    }

    public boolean isEnabled() {
        return core.isEnabled();
    }

    public void setEnabled(boolean enabled) {
        core.setEnabled(enabled);
    }

    public void send(LogLevel level, Object message) {
        core.send(level, message, null, null, logger.getDefaultTarget(), false);
    }

    public void send(LogLevel level, Object message, Player player) {
        core.send(level, message, logger.wrapAudience(player), null, LogTarget.CHAT, false);
    }

    public void send(LogLevel level, Object message, Player player, boolean all) {
        core.send(level, message, logger.wrapAudience(player), null, logger.getDefaultTarget(), all);
    }

    public void sendToConsole(LogLevel level, Object message) {
        core.send(level, message, null, null, LogTarget.CONSOLE, false);
    }

    public void sendToPlayers(LogLevel level, Object message, Collection<? extends Player> players) {
        core.send(level, message, null, wrapPlayers(players), LogTarget.CHAT, false);
    }

    public LogBuilder log() {
        return new PrefixedLogBuilder(LogLevel.INFO);
    }

    public LogBuilder noPrefix() {
        return new PrefixedLogBuilder(LogLevel.INFO).noPrefix();
    }

    public LogBuilder info() {
        return new PrefixedLogBuilder(LogLevel.INFO);
    }

    public LogBuilder warn() {
        return new PrefixedLogBuilder(LogLevel.WARN);
    }

    public LogBuilder error() {
        return new PrefixedLogBuilder(LogLevel.ERROR);
    }

    public LogBuilder debug() {
        return new PrefixedLogBuilder(LogLevel.DEBUG);
    }

    public LogBuilder success() {
        return new PrefixedLogBuilder(LogLevel.SUCCESS);
    }

    private Collection<? extends Audience> wrapPlayers(Collection<? extends Player> players) {
        if (players == null || players.isEmpty()) {
            return null;
        }
        return players.stream()
                .filter(player -> player != null)
                .map(logger::wrapAudience)
                .toList();
    }

    private class PrefixedLogBuilder extends LogBuilder {
        PrefixedLogBuilder(LogLevel level) {
            super(logger, level);
        }

        @Override
        public void send(Object message, Object... placeholders) {
            if (!core.isEnabled()) {
                return;
            }
            super.send(core.formatMessage(message), placeholders);
        }
    }
}
