package dev.ua.theroer.magicutils.logger;

import dev.ua.theroer.magicutils.Logger;
import dev.ua.theroer.magicutils.Logger.LogLevel;
import lombok.Getter;
import lombok.Setter;

import org.bukkit.entity.Player;

import java.util.Collection;

/**
 * Logger instance with custom prefix.
 * All log methods are generated by annotation processor.
 */
@Getter @Setter
@LogMethods(staticMethods = false)
public class PrefixedLogger {
    private final String name;
    private final String prefix;
    private boolean enabled;

    /**
     * Creates a new PrefixedLogger with the specified name and prefix.
     * 
     * @param name   the name identifier for this logger
     * @param prefix the prefix to prepend to all messages
     */
    public PrefixedLogger(String name, String prefix) {
        this.name = name;
        this.prefix = prefix;
        this.enabled = true;
    }

    /**
     * Formats a message by adding the prefix.
     * 
     * @param message the original message
     * @return the formatted message with prefix
     */
    private String formatMessage(String message) {
        return prefix + " " + message;
    }

    // Universal send methods
    /**
     * Sends a message with the specified log level to console.
     * 
     * @param level   the log level (INFO, WARN, ERROR, DEBUG, SUCCESS)
     * @param message the message to send (any Object)
     */
    public void send(LogLevel level, Object message) {
        if (!enabled)
            return;
        if (message instanceof String) {
            Logger.send(level, formatMessage((String) message), null, null, Logger.getDefaultTarget(), false);
        } else {
            Logger.send(level, message, null, null, Logger.getDefaultTarget(), false);
        }
    }

    /**
     * Sends a message with the specified log level to a specific player.
     * 
     * @param level   the log level (INFO, WARN, ERROR, DEBUG, SUCCESS)
     * @param message the message to send (any Object)
     * @param player  the target player to send the message to
     */
    public void send(LogLevel level, Object message, Player player) {
        if (!enabled)
            return;
        if (message instanceof String) {
            Logger.send(level, formatMessage((String) message), player, null, LogTarget.CHAT, false);
        } else {
            Logger.send(level, message, player, null, LogTarget.CHAT, false);
        }
    }

    /**
     * Sends a message with the specified log level with full control over delivery.
     * 
     * @param level   the log level (INFO, WARN, ERROR, DEBUG, SUCCESS)
     * @param message the message to send (any Object)
     * @param player  the target player (can be null for console-only)
     * @param all     if true, sends to all online players; if false, sends to
     *                specified player or console
     */
    public void send(LogLevel level, Object message, Player player, boolean all) {
        if (!enabled)
            return;
        if (message instanceof String) {
            Logger.send(level, formatMessage((String) message), player, null, Logger.getDefaultTarget(), all);
        } else {
            Logger.send(level, message, player, null, Logger.getDefaultTarget(), all);
        }
    }

    /**
     * Sends a message to console only.
     * 
     * @param level   the log level
     * @param message the message to send
     */
    public void sendToConsole(LogLevel level, Object message) {
        if (!enabled)
            return;
        if (message instanceof String) {
            Logger.send(level, formatMessage((String) message), null, null, LogTarget.CONSOLE, false);
        } else {
            Logger.send(level, message, null, null, LogTarget.CONSOLE, false);
        }
    }

    /**
     * Sends a message to a collection of players.
     * 
     * @param level   the log level
     * @param message the message to send
     * @param players the collection of players
     */
    public void sendToPlayers(LogLevel level, Object message, Collection<? extends Player> players) {
        if (!enabled)
            return;
        if (message instanceof String) {
            Logger.send(level, formatMessage((String) message), null, players, LogTarget.CHAT, false);
        } else {
            Logger.send(level, message, null, players, LogTarget.CHAT, false);
        }
    }

    // Fluent API
    /**
     * Creates a fluent log builder for info level.
     * 
     * @return LogBuilder for info level logging
     */
    public LogBuilder log() {
        return new PrefixedLogBuilder(LogLevel.INFO);
    }

    /**
     * Creates a fluent log builder for info level.
     * 
     * @return LogBuilder for info level logging
     */
    public LogBuilder info() {
        return new PrefixedLogBuilder(LogLevel.INFO);
    }

    /**
     * Creates a fluent log builder for warn level.
     * 
     * @return LogBuilder for warn level logging
     */
    public LogBuilder warn() {
        return new PrefixedLogBuilder(LogLevel.WARN);
    }

    /**
     * Creates a fluent log builder for error level.
     * 
     * @return LogBuilder for error level logging
     */
    public LogBuilder error() {
        return new PrefixedLogBuilder(LogLevel.ERROR);
    }

    /**
     * Creates a fluent log builder for debug level.
     * 
     * @return LogBuilder for debug level logging
     */
    public LogBuilder debug() {
        return new PrefixedLogBuilder(LogLevel.DEBUG);
    }

    /**
     * Creates a fluent log builder for success level.
     * 
     * @return LogBuilder for success level logging
     */
    public LogBuilder success() {
        return new PrefixedLogBuilder(LogLevel.SUCCESS);
    }

    /**
     * Custom LogBuilder that applies prefix to messages.
     */
    private class PrefixedLogBuilder extends LogBuilder {
        public PrefixedLogBuilder(LogLevel level) {
            super(level);
        }

        @Override
        public void send(Object message, Object... placeholders) {
            if (!enabled)
                return;
            if (message instanceof String) {
                super.send(formatMessage((String) message), placeholders);
            } else {
                super.send(message, placeholders);
            }
        }
    }
}
