{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bukkit",
    "version": "1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.21.5-mc1.21.jar",
          "url": "magicutils-bukkit-1.21.5-mc1.21.jar",
          "size": 137441,
          "sha512": "6b0f4bdff3b761cd4d213f3b69a30d330866554ad52abbd3241f04fdbe73ab74eebc493da22df7496a9bb6d92969b7c0a0951054a5caaf855bb8cf38f3a34c8c",
          "sha256": "4434a193a62a58c9beac0f67aafbcadeadc6ffd380528fc385399aafaaab941c",
          "sha1": "235f9a0c696f64e08dd1c98a3220d94510d7a471",
          "md5": "15aa1c6ba737465cc86173005adce2ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.21.5-mc1.21.jar",
          "url": "magicutils-bukkit-1.21.5-mc1.21.jar",
          "size": 137441,
          "sha512": "6b0f4bdff3b761cd4d213f3b69a30d330866554ad52abbd3241f04fdbe73ab74eebc493da22df7496a9bb6d92969b7c0a0951054a5caaf855bb8cf38f3a34c8c",
          "sha256": "4434a193a62a58c9beac0f67aafbcadeadc6ffd380528fc385399aafaaab941c",
          "sha1": "235f9a0c696f64e08dd1c98a3220d94510d7a471",
          "md5": "15aa1c6ba737465cc86173005adce2ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.5-sources.jar",
          "url": "magicutils-bukkit-1.21.5-sources.jar",
          "size": 59830,
          "sha512": "53e94fae59db7a9ebf65137b8ab321bcb4fae0282d6e06f1e2715580cbf1c5cb80b6b845d63771353f9485b432e9d4b2358fb07a1a1957d0a985a436d983699b",
          "sha256": "31accedcce4e0028bd11fc4b8fe9cc11c181b83840e5bec49937a7324e04cfc3",
          "sha1": "4ff8c65cc052f02986d54ce44a2591b8e1d80845",
          "md5": "ae938ea6f30d022ce01b5d70d389df39"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.5-javadoc.jar",
          "url": "magicutils-bukkit-1.21.5-javadoc.jar",
          "size": 286609,
          "sha512": "12f669266ae808cc28ad988260c13814be601e71956d8f7a7cdb25b8f618416fcded85eccb6ea07d76ce68750379dd402a96bce374dd1eef02ec79b19bfd3ccd",
          "sha256": "72c8d6210aa3c2cf0c393861208d20de3d3817fd783efbe8daf283e498490743",
          "sha1": "8d2cd9ddc0c5fd2651831abea3dfa6dff28df2c3",
          "md5": "e1ef9c105a33e8b17fa208c264d77054"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.5-all.jar",
          "url": "magicutils-bukkit-1.21.5-all.jar",
          "size": 3642806,
          "sha512": "35bb4fed2ce5c7ef6c1cb59a2c3fea6b628b8266ee78035d58cb8d228f1187bf30b878dea75aeca391a4fc430c4d2dda83795dbad9f2c92297f861ab6530c5e5",
          "sha256": "a0f2dc24b373859a3569bc27af2b9a6b9e3135863aee68e85a919146800a55cc",
          "sha1": "4bd93f3e5899f1daf12c85d151702af911d6710e",
          "md5": "bc3420a3b3a7d3bdd6547f0f0babeda5"
        }
      ]
    }
  ]
}
