{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-neoforge",
    "version": "1.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.16.1-mc1.21.jar",
          "url": "magicutils-neoforge-1.16.1-mc1.21.jar",
          "size": 14657,
          "sha512": "90370a0e5f8c60342d8db38fab04e52a179d623b83f24d81284899c6b586ad76ccd28af7d997c530625fece6841ad52cee90b1172c51f439ac9f3d4fb238dbf2",
          "sha256": "adca55258d6aa90380984d0c429ebfecc5bf7bace7fc4444784e31c3d33363fa",
          "sha1": "df08fbadd3343b7f52bda5d4aa1fb0f85e4ec58b",
          "md5": "50b429d8a42021ff774bd9857a23c2bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.16.1-mc1.21.jar",
          "url": "magicutils-neoforge-1.16.1-mc1.21.jar",
          "size": 14657,
          "sha512": "90370a0e5f8c60342d8db38fab04e52a179d623b83f24d81284899c6b586ad76ccd28af7d997c530625fece6841ad52cee90b1172c51f439ac9f3d4fb238dbf2",
          "sha256": "adca55258d6aa90380984d0c429ebfecc5bf7bace7fc4444784e31c3d33363fa",
          "sha1": "df08fbadd3343b7f52bda5d4aa1fb0f85e4ec58b",
          "md5": "50b429d8a42021ff774bd9857a23c2bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.16.1-sources.jar",
          "url": "magicutils-neoforge-1.16.1-sources.jar",
          "size": 8247,
          "sha512": "184ba0fe6dfafafe701e5bc77b283e6fbd9f220c68bdf2c58637ded5c8804968cca371c0f1af366fbc6712c3c600d8e9710e42c35a3b290da170d959f4773304",
          "sha256": "23f283d33e0113687ef05e2fba9713115daaffd00fb6fb671a2d3cdf43aaa3d7",
          "sha1": "1003943f1510f59e5ca4acb08a60f7f796b4248b",
          "md5": "fcb2110501a1262d5d033f0ded246695"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.16.1-javadoc.jar",
          "url": "magicutils-neoforge-1.16.1-javadoc.jar",
          "size": 114912,
          "sha512": "8a2e9dc74263f3c8fadb7270a487408609b7f31f873f55db366ad7d65965a2df1d6fddee4fe599e142318ee1565fd8d7a58979996452d3ddbeba9e86982a147e",
          "sha256": "83c0470f3db5ce66c8ab6538a76b605e19191072317f5b27d0de85e70ae37e33",
          "sha1": "dd3787b1d2d920b0e5b86d4040588dad835b59f4",
          "md5": "3046018fa9e265d83ea2edc573c65514"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.16.1-all.jar",
          "url": "magicutils-neoforge-1.16.1-all.jar",
          "size": 40352025,
          "sha512": "c0530c5d83504764cc6c922d620eabdde58d5237264822d1a469d11c267390462e73b19296968e91ca46458b1a401af347079ecdf5cc000f88cb465440effd04",
          "sha256": "8b244784d6cc6d358a8a4efa4c12c962730200c1f66c30c7472e3c3a95ac763e",
          "sha1": "a8849045019e69ea6bececf4ec43991cc2b3842a",
          "md5": "a0994a1c4ef02ce39cbd2bd4bebe045c"
        }
      ]
    }
  ]
}
