{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-lang",
    "version": "1.21.4-mc2611",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.4-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.21.4-mc2611-mc26.1.jar",
          "url": "magicutils-lang-1.21.4-mc2611-mc26.1.jar",
          "size": 51896,
          "sha512": "70d6f45192698a6d9b7166a2a6e81585f4396b89863635cec5453119b7a31137a9e2eb1e2ae662525870f9daa97f53044a363c571bd8189eae580b753bfdda3e",
          "sha256": "17b7cb4c3702316f97889026cfd884aaab674ad88439ceba8fa8985e44dd4b57",
          "sha1": "9b704a561a3e4811a1b7a96596a4249e6decd4e7",
          "md5": "e6b48aaa777572386690a56cb5dfd39d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.4-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.21.4-mc2611-mc26.1.jar",
          "url": "magicutils-lang-1.21.4-mc2611-mc26.1.jar",
          "size": 51896,
          "sha512": "70d6f45192698a6d9b7166a2a6e81585f4396b89863635cec5453119b7a31137a9e2eb1e2ae662525870f9daa97f53044a363c571bd8189eae580b753bfdda3e",
          "sha256": "17b7cb4c3702316f97889026cfd884aaab674ad88439ceba8fa8985e44dd4b57",
          "sha1": "9b704a561a3e4811a1b7a96596a4249e6decd4e7",
          "md5": "e6b48aaa777572386690a56cb5dfd39d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.21.4-mc2611-sources.jar",
          "url": "magicutils-lang-1.21.4-mc2611-sources.jar",
          "size": 31450,
          "sha512": "a34c0b43bdd6a6f20f2cf9522a5565a280ca57866cca6337715f6ecd7bfb1e379f01f3739b3b2278a7635a1103357e0b0cfc3fc7cd352957ba5caf8a215aaf2d",
          "sha256": "64ed562273ae171839ee732e268f23e740f3df2be2ce55f5b9e904aadee233de",
          "sha1": "efdc4adc4a48166c249dd6bac8abd6d0f2a99088",
          "md5": "5d2385ce895fe432310a5e91b07fc26a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.21.4-mc2611-javadoc.jar",
          "url": "magicutils-lang-1.21.4-mc2611-javadoc.jar",
          "size": 4211676,
          "sha512": "fa82ac1351bfd64824ed3ea6095575fe5cda0eef62cc2ff66da7de7f41afbfee4fe36db1d813cb70407f98b88fcac63bc6fc6221c1cfccc49a3910469d890965",
          "sha256": "b8ec34fc891cb7fda9063152556a46d6d6c4557d55524fac700e194bc64b19d0",
          "sha1": "6a4e0205f1b7747d02df21c016b13bd500809873",
          "md5": "9d36278d8e493de00972803f0eabd6c4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.21.4-mc2611-all.jar",
          "url": "magicutils-lang-1.21.4-mc2611-all.jar",
          "size": 3202005,
          "sha512": "65e59685249efd341a2de77a7b8c3e2eb47c7ab0028b306f9411c5fd074b3a2b6e708a3508efc6424efc0e898c587c8707981dac61404d0898173d93482b0075",
          "sha256": "997567d57b2ad86efb714286aebc6019dfb1651f00d87cc5d4322565cb623c39",
          "sha1": "589d82e259aa845bf2d6a1f9c2f3c2fe11e77a0f",
          "md5": "8ac7841abcee6bd0ce12bfd93ddf1f89"
        }
      ]
    }
  ]
}
