{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-core",
    "version": "1.14.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.14.5"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.14.5-mc1.21.jar",
          "url": "magicutils-core-1.14.5-mc1.21.jar",
          "size": 21073,
          "sha512": "808e2aa8a2d8826203345e9a292f7d06d57f3087e22ceed2e15768dedde1f488385ebbc25139d8f7eb4612dcd31cf8d2bc7455b714dc7ea706326873330c9966",
          "sha256": "e172b0e6c223cecfb55f43ae1931c8dfe1e68cb9a177da3b53ad7509ec32503b",
          "sha1": "b39f222759a1ad18cf4541e8c8f9d1b43b1b679a",
          "md5": "8a72fe7e233fffa8cbbc832ab2689c54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.14.5"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.14.5-mc1.21.jar",
          "url": "magicutils-core-1.14.5-mc1.21.jar",
          "size": 21073,
          "sha512": "808e2aa8a2d8826203345e9a292f7d06d57f3087e22ceed2e15768dedde1f488385ebbc25139d8f7eb4612dcd31cf8d2bc7455b714dc7ea706326873330c9966",
          "sha256": "e172b0e6c223cecfb55f43ae1931c8dfe1e68cb9a177da3b53ad7509ec32503b",
          "sha1": "b39f222759a1ad18cf4541e8c8f9d1b43b1b679a",
          "md5": "8a72fe7e233fffa8cbbc832ab2689c54"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.14.5-sources.jar",
          "url": "magicutils-core-1.14.5-sources.jar",
          "size": 9454,
          "sha512": "2bfdc337b18f931a1ef6d82bf08df4c1cf27d2b6b6703a7d7c12c8d9d2b15387876b73d06876b6460c8addb495580d5eebc910099013c6f24fa02caab29fa3ec",
          "sha256": "c9b2e6842dce04bf0391e2af4264d7d57e5ea985870093fd24d3be3710e75bad",
          "sha1": "8b17c7a2c6b430bc25a04638fb36894c3f45e873",
          "md5": "fb8036fbcc4202637eabec9101e6e7c1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.14.5-javadoc.jar",
          "url": "magicutils-core-1.14.5-javadoc.jar",
          "size": 120831,
          "sha512": "b00dea3a63a1ef84a8438da7e6005e5c8991066f085399ce475b6e5522936a6a3032cfbddea0575918ec9b247569a45d533ff58f3fe6ec7f9e8b88c96c855f81",
          "sha256": "34689fa6be1fb2831ae0db80d4954fea8d568e89614c1c329c0730b2f40456e3",
          "sha1": "f32621f58d5911744019ca328a348b0ba92ceadb",
          "md5": "937110488d03cd85ca34450822081684"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.14.5-all.jar",
          "url": "magicutils-core-1.14.5-all.jar",
          "size": 3411360,
          "sha512": "f99e9d7e164e652f6cef90bc8d9ee70654f430d9d12b141ee96a69048f9ea63a22af5d0956903149aff8cee7b38b4e1b12722d859ee5a52a87e3df03f512e382",
          "sha256": "7a41d83e734e44c247d9242d9ef48a216c725bcfa4cc8ccdf1d0852c8ef25fd5",
          "sha1": "64be70fc974eb463a8ca8ef49d4b709a250344e7",
          "md5": "828dfd83077254b90582e8c39dee505b"
        }
      ]
    }
  ]
}
