{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-api",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-api-1.10.0.jar",
          "url": "magicutils-api-1.10.0.jar",
          "size": 3365,
          "sha512": "ec90a106e2ed34313c179d4bbda1a6da67787b69160299368f22c5cda1a9be432fc2f3cf50caa750e8e973d112b79daae3b40d534070450070b08e1ec455cc88",
          "sha256": "8462ec3dc9992f10fbf90533e519b1709d924755f7e5e672daa40ae408122232",
          "sha1": "5af32920dc1596f36425ccfa2c7496062e717e38",
          "md5": "16c86f8cbe3a6aa81a2efe15efc60350"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-api-1.10.0.jar",
          "url": "magicutils-api-1.10.0.jar",
          "size": 3365,
          "sha512": "ec90a106e2ed34313c179d4bbda1a6da67787b69160299368f22c5cda1a9be432fc2f3cf50caa750e8e973d112b79daae3b40d534070450070b08e1ec455cc88",
          "sha256": "8462ec3dc9992f10fbf90533e519b1709d924755f7e5e672daa40ae408122232",
          "sha1": "5af32920dc1596f36425ccfa2c7496062e717e38",
          "md5": "16c86f8cbe3a6aa81a2efe15efc60350"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-api-1.10.0-all.jar",
          "url": "magicutils-api-1.10.0-all.jar",
          "size": 492720,
          "sha512": "c7e4792a744f0a287315242f50082086e4bff6c342de93c10f5e72cb026d1dcd8b2c5eca3dabed18383d628f9bf3fcf31969a4eac2c59941e67a278e6f8f494d",
          "sha256": "c024bdfeb79e2057e293c5a2c499707f2ddddcdd53971c319f54c1a2b40c3b77",
          "sha1": "ba2a38f82fe19cf9c2d20b2bec54f96e8be94256",
          "md5": "c328cc11fa18860c8afe49ff2779e806"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-api-1.10.0-sources.jar",
          "url": "magicutils-api-1.10.0-sources.jar",
          "size": 3630,
          "sha512": "9c879f125fdada25415f37384d282f7eb82b42f980aae5c00ee54073b84b87f719886bb5a0069d9cc78e392d44517f89d66b246f49a39958d57580684bc3a157",
          "sha256": "f51dbdcb4bba0a94ecbc44058ffa77c79370349d81850f3b5cc4296f57f5f0e2",
          "sha1": "d1261309b9d79c1970bdeb61b6d9573adc6bc21f",
          "md5": "98d8e101c381c6ac77bb389b158397d4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-api-1.10.0-javadoc.jar",
          "url": "magicutils-api-1.10.0-javadoc.jar",
          "size": 104821,
          "sha512": "ae9416c899c9f7a522fee16ab4d8b5ce876fd5d906ab935ee44b4dae7eb90039ffa8210e516f5bf5b2be7d3ab53afccf9f6544d56d851beeea38415f676d6437",
          "sha256": "e5799f16ca89090693f1f02beb7ca20e704a8ed29b2924d77eb891cfadc69490",
          "sha1": "7b256508a860ce0af14ff1788cc824106f0d481b",
          "md5": "76a02f2cbc43a038c726af1c9de4cdf2"
        }
      ]
    }
  ]
}
