{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-api",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-api-1.10.0.jar",
          "url": "magicutils-api-1.10.0.jar",
          "size": 3365,
          "sha512": "d1f09c77790e219d0f4a0fb41cb8f9b4d8c0a4f122668d1564ee0cf7ea7124c20300e6d43b7016433927348ff40086f1fb9381bce9b04f01f63ce4a1043539c1",
          "sha256": "9ed340c9e1c8fab8a05cbd7ef45344d1a30a3b9a709de234ff8553f3c2531bf0",
          "sha1": "0aa1c3e88333bac09dfb4785e03dd0a48984468c",
          "md5": "ec5d2e0de7b70c85ff7ace934ae80b2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-api-1.10.0.jar",
          "url": "magicutils-api-1.10.0.jar",
          "size": 3365,
          "sha512": "d1f09c77790e219d0f4a0fb41cb8f9b4d8c0a4f122668d1564ee0cf7ea7124c20300e6d43b7016433927348ff40086f1fb9381bce9b04f01f63ce4a1043539c1",
          "sha256": "9ed340c9e1c8fab8a05cbd7ef45344d1a30a3b9a709de234ff8553f3c2531bf0",
          "sha1": "0aa1c3e88333bac09dfb4785e03dd0a48984468c",
          "md5": "ec5d2e0de7b70c85ff7ace934ae80b2b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-api-1.10.0-all.jar",
          "url": "magicutils-api-1.10.0-all.jar",
          "size": 492720,
          "sha512": "c7e4792a744f0a287315242f50082086e4bff6c342de93c10f5e72cb026d1dcd8b2c5eca3dabed18383d628f9bf3fcf31969a4eac2c59941e67a278e6f8f494d",
          "sha256": "c024bdfeb79e2057e293c5a2c499707f2ddddcdd53971c319f54c1a2b40c3b77",
          "sha1": "ba2a38f82fe19cf9c2d20b2bec54f96e8be94256",
          "md5": "c328cc11fa18860c8afe49ff2779e806"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-api-1.10.0-sources.jar",
          "url": "magicutils-api-1.10.0-sources.jar",
          "size": 3630,
          "sha512": "e55afffdebe4b8f8060d32a6163900963fe3dc7ad1d8a4a84f22a07fdb9404782780ebaf81213be38f4a5259e47ceda81bdfe9670ccd833ee7840f45d0a129c4",
          "sha256": "0a58a1f561172fac9bcdd9852b1a61091b9b258f2dba82d014d7350c9ad812c9",
          "sha1": "a71bf2cc6899ab8c4fdce9f671f8c3d8fdbc4d2a",
          "md5": "621e55ce113a193d63d6ce90c190914b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-api-1.10.0-javadoc.jar",
          "url": "magicutils-api-1.10.0-javadoc.jar",
          "size": 104821,
          "sha512": "36f40fbb8063e51c8abe28d792f159f6e1107fb7301e1bb9e178601673b6748e0489367ecb4c431fc76e5e088041c9d15139aa10ecb57d13a3e341e04c1b0346",
          "sha256": "22318131704a825ef4e0218370e8f8ecfbbe124b1ed3ba7442d426d9fbbeae64",
          "sha1": "7c84f4c5caf3bcf797d3b00d5da602e612026cfd",
          "md5": "021f5ccde8e6ce7782e6fbbbf82beafb"
        }
      ]
    }
  ]
}
