{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-api",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-api-1.10.0.jar",
          "url": "magicutils-api-1.10.0.jar",
          "size": 3365,
          "sha512": "a8b95b0a5d46e8f9d181bc740ef8839a07f44f261c8a6d4845b076bc860c77a73555da38ddf0c267c48619324d6826e7f24f3c4793f622f5fcface3916e6c610",
          "sha256": "e6a52e39a45c8f4a6f570637ed57b3a717ab76b26a6c67f32dc32acccc588bc5",
          "sha1": "af2bb82467b32dc8f500fe5eefdec56d8694cd9c",
          "md5": "6dce659c226bad1c877b3c146d87fee1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-api-1.10.0.jar",
          "url": "magicutils-api-1.10.0.jar",
          "size": 3365,
          "sha512": "a8b95b0a5d46e8f9d181bc740ef8839a07f44f261c8a6d4845b076bc860c77a73555da38ddf0c267c48619324d6826e7f24f3c4793f622f5fcface3916e6c610",
          "sha256": "e6a52e39a45c8f4a6f570637ed57b3a717ab76b26a6c67f32dc32acccc588bc5",
          "sha1": "af2bb82467b32dc8f500fe5eefdec56d8694cd9c",
          "md5": "6dce659c226bad1c877b3c146d87fee1"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-api-1.10.0-all.jar",
          "url": "magicutils-api-1.10.0-all.jar",
          "size": 492720,
          "sha512": "c7e4792a744f0a287315242f50082086e4bff6c342de93c10f5e72cb026d1dcd8b2c5eca3dabed18383d628f9bf3fcf31969a4eac2c59941e67a278e6f8f494d",
          "sha256": "c024bdfeb79e2057e293c5a2c499707f2ddddcdd53971c319f54c1a2b40c3b77",
          "sha1": "ba2a38f82fe19cf9c2d20b2bec54f96e8be94256",
          "md5": "c328cc11fa18860c8afe49ff2779e806"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-api-1.10.0-sources.jar",
          "url": "magicutils-api-1.10.0-sources.jar",
          "size": 3630,
          "sha512": "5ccccf21f9635751483f61d6736490972a796ac14fb6566b1d42c8277646677b8dff35e853442ec177e7db7edeb96996148df025069fa0b5c96ae4d35e6b40e4",
          "sha256": "6269acdc317f3176f19c82588eaa97345298587d0713c8d68b5de7124320211e",
          "sha1": "bd066969692cfad9e845e831ace6ef973d3f85f2",
          "md5": "a2d009d3a37c79790025bd98659bcf44"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-api-1.10.0-javadoc.jar",
          "url": "magicutils-api-1.10.0-javadoc.jar",
          "size": 104821,
          "sha512": "3a3bc691d65877c2a774f07b7cea5eb04c36dc765c145ae202579492546988e624836057e5d3728878517d90d4d350518feac77833fd043f2ab7f32c233975c2",
          "sha256": "35c73bd68e12bfe87d6ffe04eb6a086209c29eab60d55528db85e53d24eaab36",
          "sha1": "17553973ba9e57d267f17c1280043f3545ad2994",
          "md5": "a2213150b3e4b954d4221c30772ffd3f"
        }
      ]
    }
  ]
}
