{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-config",
    "version": "1.21.3-mc1201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.21.3-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-1.21.3-mc1201-mc1.20.jar",
          "url": "magicutils-config-1.21.3-mc1201-mc1.20.jar",
          "size": 78372,
          "sha512": "e84df783cd7413375ccf114c6452c6c9b008a37715443428597c87733779d1c98c2eb7f7b954abee51799b67e0053036e1f4ac2a2d77794749d0425c926f0de0",
          "sha256": "dd14f1ff7726269bfc307d725f258edf813fb252044e1979170935f54c15f8be",
          "sha1": "3f6a6ac3acd4ba5793af7d42250360a5fa7b2186",
          "md5": "8948f029303a5769dad2bf5c08c95a59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.21.3-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-1.21.3-mc1201-mc1.20.jar",
          "url": "magicutils-config-1.21.3-mc1201-mc1.20.jar",
          "size": 78372,
          "sha512": "e84df783cd7413375ccf114c6452c6c9b008a37715443428597c87733779d1c98c2eb7f7b954abee51799b67e0053036e1f4ac2a2d77794749d0425c926f0de0",
          "sha256": "dd14f1ff7726269bfc307d725f258edf813fb252044e1979170935f54c15f8be",
          "sha1": "3f6a6ac3acd4ba5793af7d42250360a5fa7b2186",
          "md5": "8948f029303a5769dad2bf5c08c95a59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.21.3-mc1201-sources.jar",
          "url": "magicutils-config-1.21.3-mc1201-sources.jar",
          "size": 37256,
          "sha512": "63dc0ef787b091790945cf85f94b22f955b01911bfb32a287d6425be58571b609b403207559b04982e46f07c52bf92dd865465419b09e5f47877d414bf226b4e",
          "sha256": "65049a214719af417f1e2b25839f9c8b07aa682b31a60436f08a58770ef0b6df",
          "sha1": "6b5544ab5393238ff5c49bdcf4b100e9be7262b0",
          "md5": "225e154a78687284fd724e8ddc37c9e4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.21.3-mc1201-javadoc.jar",
          "url": "magicutils-config-1.21.3-mc1201-javadoc.jar",
          "size": 148661,
          "sha512": "583d5997f3c3e673f7cbc042dd9e12e73317451e48c9a12a7802e82a33d8e6a8b050a238dcf2c4751c187748514d5d9215dd3607bb9149b31da0df5a2b190fb1",
          "sha256": "ac0cf8583f3212499f3512ef8914168e18715e3b65e9c606d1103a143bee3381",
          "sha1": "419685d04cb5e9ca6e6ef7ef366f4cd57ff5143b",
          "md5": "2a6bb20cb2051fecfad9fa415d584853"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.21.3-mc1201-all.jar",
          "url": "magicutils-config-1.21.3-mc1201-all.jar",
          "size": 2963006,
          "sha512": "3b001c069efc84eba53d40be821fa08e7c5139b512ab0047c62e0d207ae3c48700bf2036b40d6c119a44267907170e6710c308d43814cf8f3af8b3e0d8d22015",
          "sha256": "827cfc54558fc21d05968d93ed9259640832083cf8ab70589317eaa094e238c6",
          "sha1": "2b90dd86744eb5d72879a4589dbc1a34b5c5d286",
          "md5": "ab3f8ca4bfb79bd2d4c77010e720dccb"
        }
      ]
    }
  ]
}
