{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bukkit",
    "version": "1.14.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.14.3-mc1.21.jar",
          "url": "magicutils-bukkit-1.14.3-mc1.21.jar",
          "size": 121710,
          "sha512": "4c5b88c574324913111e0ffd625ba779a2c820c65d5f9e159ea00ac820c8d2c8a0d19912211035936cf66976bddd67881a1ce1d2445498a9bfb7b1b43da81e98",
          "sha256": "e9dd530e6537e7d4294e03d9e9416d9d679ab8dcaf2e5d4f2b7a87909f8d19bf",
          "sha1": "92a95ad2d780d6f9a441832b87a1a424fec01135",
          "md5": "f20f0441839df0e1ae8e0f7086bef637"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.14.3-mc1.21.jar",
          "url": "magicutils-bukkit-1.14.3-mc1.21.jar",
          "size": 121710,
          "sha512": "4c5b88c574324913111e0ffd625ba779a2c820c65d5f9e159ea00ac820c8d2c8a0d19912211035936cf66976bddd67881a1ce1d2445498a9bfb7b1b43da81e98",
          "sha256": "e9dd530e6537e7d4294e03d9e9416d9d679ab8dcaf2e5d4f2b7a87909f8d19bf",
          "sha1": "92a95ad2d780d6f9a441832b87a1a424fec01135",
          "md5": "f20f0441839df0e1ae8e0f7086bef637"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.14.3-sources.jar",
          "url": "magicutils-bukkit-1.14.3-sources.jar",
          "size": 52639,
          "sha512": "2c2e2add96b2837638814a99e4301223a8b426bbc85c5b716106c787331bc59f90c5f5b4102e780ffbe5860d247ef3026a152bbeb4dfd4a42dbcaba5f5e75d11",
          "sha256": "114fde0153b8a21d0b82b4c27134b3c770a2044f06c85bcd88936ee58cf17cf2",
          "sha1": "cf83851c01ba49e4c777dd38839f4019a5539bd4",
          "md5": "460977a3272ae67c86e9694151fbc35b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.14.3-javadoc.jar",
          "url": "magicutils-bukkit-1.14.3-javadoc.jar",
          "size": 266307,
          "sha512": "698ca06a72e7b9030a5856e73303e76d0031d3b9f5e922c45734769ff8d7b89df1fb184982d637f0e670bd65b5ae5b820fc35a3a4020495d478af07c98a9aec6",
          "sha256": "da2dde2f3b38b906ba4ddc78aec241321cd8956c00926e1defc05d4d318166dc",
          "sha1": "ceebcae6ba56c2be3c9b6b5dc653ee82ff8885fb",
          "md5": "6264639ffe1def5020b0900feb72a751"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.14.3-all.jar",
          "url": "magicutils-bukkit-1.14.3-all.jar",
          "size": 3530655,
          "sha512": "cf1a285eb2d73010965b614b3cd43f2ec03a40e0c812c76c9feaffebd9337800522ee2512dca5cf59b4edd061af12e46f14b22874ed3976778debde23810d3f1",
          "sha256": "696a2c3bd7a9d8691d161980e1a13b7075b11d783e6036132f44454765fb7000",
          "sha1": "2c9b7c732434af1edf46f1701016709b08ea2f16",
          "md5": "f75bcfa00592c2ef234c537d8c0bd18a"
        }
      ]
    }
  ]
}
