{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bungee",
    "version": "1.19.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.19.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.19.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bungee-1.19.1-mc1.21.jar",
          "url": "magicutils-bungee-1.19.1-mc1.21.jar",
          "size": 41287,
          "sha512": "4023547b574de8614e1823eddf4ebd65a18fbb73366300b2dfcd7e1216bacaacc511b14a5d901c40c4c6170ac52a75360933ffa5884cc883afddf80d27a8aa20",
          "sha256": "6a7f07c298598405079c0494865fd03bd0c98c3b5ceb3d8c038976c9d315bb66",
          "sha1": "f43ebaa706cee4dd602dd0e0449dadae95425d80",
          "md5": "381df1ea3321a087ba9ccd515b7e409f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.19.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.19.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bungee-1.19.1-mc1.21.jar",
          "url": "magicutils-bungee-1.19.1-mc1.21.jar",
          "size": 41287,
          "sha512": "4023547b574de8614e1823eddf4ebd65a18fbb73366300b2dfcd7e1216bacaacc511b14a5d901c40c4c6170ac52a75360933ffa5884cc883afddf80d27a8aa20",
          "sha256": "6a7f07c298598405079c0494865fd03bd0c98c3b5ceb3d8c038976c9d315bb66",
          "sha1": "f43ebaa706cee4dd602dd0e0449dadae95425d80",
          "md5": "381df1ea3321a087ba9ccd515b7e409f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bungee-1.19.1-sources.jar",
          "url": "magicutils-bungee-1.19.1-sources.jar",
          "size": 16377,
          "sha512": "d815234b9fa5df88f61d793a285dff2709146dae1accaff68464082ba7bc87e48d6f39278e6f934421227dd7b2b01fc6c72f70f16917ddf505e4e85bc2a77c3c",
          "sha256": "45354e4af86fba39a49a18e0dfbcf3136404119f7d85db8b44fab05c7f10c644",
          "sha1": "483d153b7c4343443d2cf2eda3a7ee78471c915b",
          "md5": "90b39b58111f77ba3342a3839eff9d74"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bungee-1.19.1-javadoc.jar",
          "url": "magicutils-bungee-1.19.1-javadoc.jar",
          "size": 133228,
          "sha512": "2538fac95d0c9f3fda5e0c2f9648ebc203b249e8fe649471f96a42cc85f3865e92fc5e54ca1868de74271cc99529d4b2233a9eb8c1fb61a70557a68c7cb4aba1",
          "sha256": "55eccc28a79fbd6b24b5d574594b1217a7756ecee0c8b0a9338e553f0f180766",
          "sha1": "aab224f84260d57fc7b4f759620738969f28a9ef",
          "md5": "7381e788795996e7d01476d6b6dbe7ba"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bungee-1.19.1-all.jar",
          "url": "magicutils-bungee-1.19.1-all.jar",
          "size": 3551536,
          "sha512": "c46e45aea98da798cebcb298bc515d68f6d3ec49023fe807f5bc26797f73f9fa34b88bc3225b744e03473f9730481a22102e3a2a6869a8854dc624c2670e128d",
          "sha256": "131edc496dad4901549217a3c0a9e979d847ec2c76306b58d12188b53e2db670",
          "sha1": "da89cedd4278e343d9bc1f90078a809990363c9d",
          "md5": "9b7469718f986f40042258d438009611"
        }
      ]
    }
  ]
}
