import dev.ua.theroer.magicutils.build.publish.*

plugins {
    id("base")
    id("magicutils.matrix-root")
    id("magicutils.target")
}

val baseVersion = (project.properties["version"] as String?) ?: "0.0.0"
// Fabric-style version per target: <base>+<minecraft> (e.g. 1.22.0+26.2). Every
// target is its own Maven version, so its module metadata (Java level,
// transitive deps) never collides with another target's. The consumer plugins
// mirror this suffix from their resolved target, so downstream builds keep
// declaring the bare base version.
val resolvedContext = gradle.extensions.extraProperties.get("magicutilsMatrixResolved")
    as dev.ua.theroer.magicutils.build.matrix.MagicUtilsMatrixResolvedContext
// Use the library Minecraft (the published coordinate's branch), not the runtime
// one — they differ when a target overrides library_minecraft, and consumers
// resolve against the library branch (publishedVersion mirrors this).
val targetMinecraft = resolvedContext.target.libraryMinecraft
val targetVersion = "$baseVersion+$targetMinecraft"

val publishingSpec = gradle.extensions.extraProperties.get("magicutilsPublishingSpec")
    as MagicUtilsPublishingSpec

allprojects {
    group = publishingSpec.group
    version = targetVersion
}

val reflectionPatterns = listOf(
    "Class.forName(",
    ".getMethod(",
    ".getDeclaredMethod(",
    ".getField(",
    ".getDeclaredField(",
)

val reflectionAllowlistFile = rootProject.file("gradle/reflection-allowlist.txt")

val collectReflectionOccurrences: () -> List<String> = {
    val projectRoot = rootProject.rootDir.toPath()
    val occurrences = mutableListOf<String>()
    fileTree(projectRoot.toFile()) {
        include("**/src/main/java/**/*.java")
        exclude("**/build/**")
        exclude("**/.gradle/**")
        exclude("**/.venv/**")
        exclude("**/out/**")
    }.forEach { source ->
        val relative = projectRoot.relativize(source.toPath()).toString().replace('\\', '/')
        source.readLines(Charsets.UTF_8).forEachIndexed { index, line ->
            reflectionPatterns.forEach { marker ->
                if (line.contains(marker)) {
                    occurrences.add("$relative:${index + 1}:$marker")
                }
            }
        }
    }
    occurrences.sorted().distinct()
}

tasks.register("refreshReflectionAllowlist") {
    group = "verification"
    description = "Rebuilds gradle/reflection-allowlist.txt from current source tree."

    doLast {
        val occurrences = collectReflectionOccurrences()
        reflectionAllowlistFile.parentFile.mkdirs()
        reflectionAllowlistFile.writeText(
            "# Auto-generated by ./gradlew refreshReflectionAllowlist\n" +
                "# Each line format: <relative-path>:<line>:<marker>\n" +
                "# Do not edit manually unless you are intentionally curating this list.\n\n" +
                occurrences.joinToString("\n") + "\n",
            Charsets.UTF_8,
        )
        logger.lifecycle("Reflection allowlist refreshed: ${occurrences.size} entries -> $reflectionAllowlistFile")
    }
}

tasks.register("verifyReflectionBoundaries") {
    group = "verification"
    description = "Fails when new raw reflection markers appear outside the recorded allowlist."

    doLast {
        if (!reflectionAllowlistFile.exists()) {
            throw GradleException(
                "Missing $reflectionAllowlistFile. Run ./gradlew refreshReflectionAllowlist first."
            )
        }

        val allowlist = reflectionAllowlistFile.readLines(Charsets.UTF_8)
            .map { it.trim() }
            .filter { it.isNotEmpty() && !it.startsWith("#") }
            .toSet()
        val current = collectReflectionOccurrences().toSet()

        val newlyAdded = (current - allowlist).sorted()
        val stale = (allowlist - current).sorted()

        if (stale.isNotEmpty()) {
            logger.warn("Reflection allowlist contains stale entries (consider refresh):\n - ${stale.joinToString("\n - ")}")
        }

        if (newlyAdded.isNotEmpty()) {
            val details = "\n - " + newlyAdded.joinToString("\n - ")
            throw GradleException(
                "New raw reflection markers detected.$details\n" +
                    "Review them and run ./gradlew refreshReflectionAllowlist if accepted."
            )
        }
    }
}

tasks.matching { it.name == "check" }.configureEach {
    dependsOn(tasks.named("verifyReflectionBoundaries"))
}
