import dev.ua.theroer.magicutils.build.publish.*

plugins {
    id("base")
    id("magicutils.matrix-root")
    id("magicutils.target")
}

val baseVersion = (project.properties["version"] as String?) ?: "0.0.0"
// Coordinate version is module-aware (see magicUtilsPublishedModuleVersion):
//  - bundles (`*-bundle`) keep `<base>+java<N>` — their shaded dependency set
//    genuinely differs per Java level / Minecraft branch;
//  - plain library modules publish the BARE `<base>` — they are byte-identical
//    across Java levels (the per-level diffs are javac codegen artifacts), so a
//    single coordinate replaces the former three near-duplicate `+java17/21/25`
//    copies. A resumed release with -Pskip_existing HEADs each POM, so the second
//    and third Java-level representatives skip the already-uploaded bare module.
// The consumer plugins mirror this exact rule from their resolved target's Java
// level (see publishedVersion), so downstream builds keep declaring the bare base
// version and always resolve a coordinate that exists.
val resolvedContext = gradle.extensions.extraProperties.get("magicutilsMatrixResolved")
    as dev.ua.theroer.magicutils.build.matrix.MagicUtilsMatrixResolvedContext
val javaLevel = resolvedContext.target.java

val namingSpec = gradle.extensions.extraProperties
    .let { if (it.has("magicutilsModuleNaming")) it.get("magicutilsModuleNaming") else null }
        as? dev.ua.theroer.magicutils.build.module.MagicUtilsModuleNamingSpec
    ?: dev.ua.theroer.magicutils.build.module.MagicUtilsModuleNamingSpec()

val publishingSpec = gradle.extensions.extraProperties.get("magicutilsPublishingSpec")
    as MagicUtilsPublishingSpec

allprojects {
    group = publishingSpec.group
    // Keyed on the project's published artifact id so `-bundle` projects keep the
    // Java suffix and library modules go bare. The root project has no artifact id
    // of its own; its version is unused for publication but set for consistency.
    val artifactId = namingSpec.moduleName(name)
    version = dev.ua.theroer.magicutils.build.target.magicUtilsPublishedModuleVersion(
        artifactId, baseVersion, javaLevel,
    )
}

val reflectionPatterns = listOf(
    "Class.forName(",
    ".getMethod(",
    ".getDeclaredMethod(",
    ".getField(",
    ".getDeclaredField(",
)

val reflectionAllowlistFile = rootProject.file("gradle/reflection-allowlist.txt")

val collectReflectionOccurrences: () -> List<String> = {
    val projectRoot = rootProject.rootDir.toPath()
    val occurrences = mutableListOf<String>()
    fileTree(projectRoot.toFile()) {
        include("**/src/main/java/**/*.java")
        exclude("**/build/**")
        exclude("**/.gradle/**")
        exclude("**/.venv/**")
        exclude("**/out/**")
    }.forEach { source ->
        val relative = projectRoot.relativize(source.toPath()).toString().replace('\\', '/')
        source.readLines(Charsets.UTF_8).forEachIndexed { index, line ->
            reflectionPatterns.forEach { marker ->
                if (line.contains(marker)) {
                    occurrences.add("$relative:${index + 1}:$marker")
                }
            }
        }
    }
    occurrences.sorted().distinct()
}

tasks.register("refreshReflectionAllowlist") {
    group = "verification"
    description = "Rebuilds gradle/reflection-allowlist.txt from current source tree."

    doLast {
        val occurrences = collectReflectionOccurrences()
        reflectionAllowlistFile.parentFile.mkdirs()
        reflectionAllowlistFile.writeText(
            "# Auto-generated by ./gradlew refreshReflectionAllowlist\n" +
                "# Each line format: <relative-path>:<line>:<marker>\n" +
                "# Do not edit manually unless you are intentionally curating this list.\n\n" +
                occurrences.joinToString("\n") + "\n",
            Charsets.UTF_8,
        )
        logger.lifecycle("Reflection allowlist refreshed: ${occurrences.size} entries -> $reflectionAllowlistFile")
    }
}

tasks.register("verifyReflectionBoundaries") {
    group = "verification"
    description = "Fails when new raw reflection markers appear outside the recorded allowlist."

    doLast {
        if (!reflectionAllowlistFile.exists()) {
            throw GradleException(
                "Missing $reflectionAllowlistFile. Run ./gradlew refreshReflectionAllowlist first."
            )
        }

        val allowlist = reflectionAllowlistFile.readLines(Charsets.UTF_8)
            .map { it.trim() }
            .filter { it.isNotEmpty() && !it.startsWith("#") }
            .toSet()
        val current = collectReflectionOccurrences().toSet()

        val newlyAdded = (current - allowlist).sorted()
        val stale = (allowlist - current).sorted()

        if (stale.isNotEmpty()) {
            logger.warn("Reflection allowlist contains stale entries (consider refresh):\n - ${stale.joinToString("\n - ")}")
        }

        if (newlyAdded.isNotEmpty()) {
            val details = "\n - " + newlyAdded.joinToString("\n - ")
            throw GradleException(
                "New raw reflection markers detected.$details\n" +
                    "Review them and run ./gradlew refreshReflectionAllowlist if accepted."
            )
        }
    }
}

tasks.matching { it.name == "check" }.configureEach {
    dependsOn(tasks.named("verifyReflectionBoundaries"))
}
