{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-1.10.0.jar",
          "url": "magicutils-commands-1.10.0.jar",
          "size": 137583,
          "sha512": "8349449d12b11025cd93c1f17dd51d2e9050f6f13dbc13dc4b320fd33eb2f2cc221207ee4338bd9d0510b33e8d6a07447f69a93297460123512b26143c8fb07b",
          "sha256": "9bf2c9fbc9eb98dc304489d4f78183610df479de318e33402fe2acb51e1c4c29",
          "sha1": "955ce322c1f2a8c548bf0f625c6ca7fc0f87f44c",
          "md5": "7346bb750f20d7ffeaa0c2fdc41dc7db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-1.10.0.jar",
          "url": "magicutils-commands-1.10.0.jar",
          "size": 137583,
          "sha512": "8349449d12b11025cd93c1f17dd51d2e9050f6f13dbc13dc4b320fd33eb2f2cc221207ee4338bd9d0510b33e8d6a07447f69a93297460123512b26143c8fb07b",
          "sha256": "9bf2c9fbc9eb98dc304489d4f78183610df479de318e33402fe2acb51e1c4c29",
          "sha1": "955ce322c1f2a8c548bf0f625c6ca7fc0f87f44c",
          "md5": "7346bb750f20d7ffeaa0c2fdc41dc7db"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.10.0-all.jar",
          "url": "magicutils-commands-1.10.0-all.jar",
          "size": 3317906,
          "sha512": "ba70d151ddb78beaff73e1e1de962cac5763c7aa697eb74bafae8c1a9e91dbf1d5e4eacd301d6e96d55266dccdb2381ac74bf3ff57cc9d13805ed98749f4f3aa",
          "sha256": "05adc218f3553195d13c42133800ddc257e7db8c21a9125bcf9b9d24fcc04e59",
          "sha1": "e23db07eb814f86aba8acf3d470d036fcd23e11b",
          "md5": "7875487745324f8c58681dd4ed5bd9fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.10.0-sources.jar",
          "url": "magicutils-commands-1.10.0-sources.jar",
          "size": 61718,
          "sha512": "a8b6682b04da7198d6eac2b5f78dae53457637c95abd602ac87a4faffa5c171969aa8274253fd1beea3201214a9dcbe7d022581ddbb94fadc32ab2afcb7a2572",
          "sha256": "af2ded167a6fae47f93d46a9f7e4ce4c25fa6a635520a524eb3543b99b0110f0",
          "sha1": "cee2cc74f9d0fd879d45e2a8c0c7dc8c5c942b08",
          "md5": "39021c604114e9473693da6a86d5503d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.10.0-javadoc.jar",
          "url": "magicutils-commands-1.10.0-javadoc.jar",
          "size": 259112,
          "sha512": "522d6adcffa5e5d89ae41ea1c7f070a2a39ac7800ffe71240555bc5240010b64c64387fa07038740d1d444a44fe1f27a61eb9973de3e22a3d0d5687de79568c0",
          "sha256": "d120b9ad678d394e4035c1bfb40bbfad170c9ba503cec33012b700cd4bf45906",
          "sha1": "d945d1908d2614f7c751d3081fe7470776ccd9d0",
          "md5": "30e9fc9b9b6c9b403941a7d10f11b41b"
        }
      ]
    }
  ]
}
