{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-1.10.0.jar",
          "url": "magicutils-commands-1.10.0.jar",
          "size": 137583,
          "sha512": "dabbb85e12aca10099170945792df6dcc5c6611bbf466965749d4ba36d56a53a8fb1f9e58c22306c60c0cb245c7042c43ea2fbc8a9cc85c76c42507987521c7d",
          "sha256": "db912172032a162dc23f82465438bcd5c82f00919817f40eb3d820bf970fe0a9",
          "sha1": "27f6a611318b7b736876bf3931f74432103ab95d",
          "md5": "adba6d997c9141f6f16458a1151557f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-1.10.0.jar",
          "url": "magicutils-commands-1.10.0.jar",
          "size": 137583,
          "sha512": "dabbb85e12aca10099170945792df6dcc5c6611bbf466965749d4ba36d56a53a8fb1f9e58c22306c60c0cb245c7042c43ea2fbc8a9cc85c76c42507987521c7d",
          "sha256": "db912172032a162dc23f82465438bcd5c82f00919817f40eb3d820bf970fe0a9",
          "sha1": "27f6a611318b7b736876bf3931f74432103ab95d",
          "md5": "adba6d997c9141f6f16458a1151557f0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.10.0-all.jar",
          "url": "magicutils-commands-1.10.0-all.jar",
          "size": 3317906,
          "sha512": "ba70d151ddb78beaff73e1e1de962cac5763c7aa697eb74bafae8c1a9e91dbf1d5e4eacd301d6e96d55266dccdb2381ac74bf3ff57cc9d13805ed98749f4f3aa",
          "sha256": "05adc218f3553195d13c42133800ddc257e7db8c21a9125bcf9b9d24fcc04e59",
          "sha1": "e23db07eb814f86aba8acf3d470d036fcd23e11b",
          "md5": "7875487745324f8c58681dd4ed5bd9fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.10.0-sources.jar",
          "url": "magicutils-commands-1.10.0-sources.jar",
          "size": 61718,
          "sha512": "546db7cf09b54e394853d5988fedb4afd26d174d1855d45440854b28d150c61eccb78f13902abfcf595761933e157216fc947d70cd3d01482463141f6cb486eb",
          "sha256": "64a9434731df3588a616e705ab60c296a7a4362232a9db03ecdaa5b5210d5e07",
          "sha1": "89157ba39de5a19daac8e66149790c77956aa14e",
          "md5": "2dcab69fe1d4a546e75aa034dcb0c570"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.10.0-javadoc.jar",
          "url": "magicutils-commands-1.10.0-javadoc.jar",
          "size": 259112,
          "sha512": "afd156369faae4c36a929e640eaaeeeebe771198d1ce867cb9a8a77baa5d70e9dcc7a53e56861cd81409b366a138ce198274475422b47b689bcb84dc8a9a38c8",
          "sha256": "71fffc94f2ae9bd16c81664b3cd5858dcb9d901f353f51c671955b60327c4dba",
          "sha1": "cae8af90f5230d5423faf5bc586eb563ba49c277",
          "md5": "0138083a72fcacf3b0c66ee0a9cf2ce8"
        }
      ]
    }
  ]
}
