{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-1.10.0.jar",
          "url": "magicutils-commands-1.10.0.jar",
          "size": 137583,
          "sha512": "3100fe75046df4a9b15be005a70d75ebddf78906562cd28d5c3ca8c86babdeb7d742972e18a8ccdc9b72150275331773f2ac026c0c36011ec6baabf2a53644da",
          "sha256": "41c566511e5fedbd6f40e0a6b4d27ca68d2e42e5f2f8911a6a103479703ce5a7",
          "sha1": "09a77d323b57bbb2337e15d8e7b4dbc3ea39d40a",
          "md5": "52d193ea997040cb480e6373e58db53c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-1.10.0.jar",
          "url": "magicutils-commands-1.10.0.jar",
          "size": 137583,
          "sha512": "3100fe75046df4a9b15be005a70d75ebddf78906562cd28d5c3ca8c86babdeb7d742972e18a8ccdc9b72150275331773f2ac026c0c36011ec6baabf2a53644da",
          "sha256": "41c566511e5fedbd6f40e0a6b4d27ca68d2e42e5f2f8911a6a103479703ce5a7",
          "sha1": "09a77d323b57bbb2337e15d8e7b4dbc3ea39d40a",
          "md5": "52d193ea997040cb480e6373e58db53c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.10.0-all.jar",
          "url": "magicutils-commands-1.10.0-all.jar",
          "size": 3317906,
          "sha512": "9f3dca74ff5324552127b0f085e69b54836fc98b937fddd0ded01a11059c7f3c65d92bf4e7d3e8fe9ab16ad6f085f03f737263008a74454d9a46f60a9cad9437",
          "sha256": "bb5f6f9cb3e0c13ec3b2360f2598d70e84447f94725e77578eb57568140245f9",
          "sha1": "f6cac04d30a38bb6d779fba3e6d59e297237b5af",
          "md5": "8290d4d85e9f63ec98049415135a4458"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.10.0-sources.jar",
          "url": "magicutils-commands-1.10.0-sources.jar",
          "size": 61718,
          "sha512": "81d54f265540f219df8a8b6aa43d3a7465b2a3bbd079acbe1a9f3f7176bcf8b0a3ff60caf9308b365418268c7d31932821919b21aaf9bcf4cf0618cc6a376618",
          "sha256": "87a459e9abdd3ef42c9aa378cccf8f9325ddb220cd1b93bdaf879c9ee729be7d",
          "sha1": "3952370a6754214aa2337d88148aef34f2c75e69",
          "md5": "813c43ad98742b68d111225d51ff3ca6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.10.0-javadoc.jar",
          "url": "magicutils-commands-1.10.0-javadoc.jar",
          "size": 259112,
          "sha512": "409727600ae262ffdc3d7aa8c099758bea422fd96487315b50a48243af19398e1e3b5ce8e5026c019aedd2f4bd3030cb3ffb6dee0821889183dd62bbaa3cdbbd",
          "sha256": "61d61c6f61df5e05a5757cf4d0645db8c98257412b49c855a05e70c9c32565c4",
          "sha1": "77cbd36ccf5a78d4fabdb27e3683e1c4544bec21",
          "md5": "895f200fe015621e2c48e0e153089280"
        }
      ]
    }
  ]
}
