{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands-brigadier",
    "version": "1.21.3-mc1201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.21.3-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.3-mc1201-mc1.20.jar",
          "url": "magicutils-commands-brigadier-1.21.3-mc1201-mc1.20.jar",
          "size": 22466,
          "sha512": "14fc27c123ed8000d3368b304bfe8956070b5e72d00087d75138ffdafccd9c709a32ad05804a8798fc2b6d85a7a527892930528075b1d6c29ffa48e12f35af6b",
          "sha256": "45d13fc110e21059014e2f7b0e06e8b179bc08e9975d1c29466d381cbe8a33da",
          "sha1": "e99d0dda729aa11fcbd4286e67aeb7428cba9c5a",
          "md5": "31e8b4de5680e42d0ae24dd2d62c1f15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.21.3-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.3-mc1201-mc1.20.jar",
          "url": "magicutils-commands-brigadier-1.21.3-mc1201-mc1.20.jar",
          "size": 22466,
          "sha512": "14fc27c123ed8000d3368b304bfe8956070b5e72d00087d75138ffdafccd9c709a32ad05804a8798fc2b6d85a7a527892930528075b1d6c29ffa48e12f35af6b",
          "sha256": "45d13fc110e21059014e2f7b0e06e8b179bc08e9975d1c29466d381cbe8a33da",
          "sha1": "e99d0dda729aa11fcbd4286e67aeb7428cba9c5a",
          "md5": "31e8b4de5680e42d0ae24dd2d62c1f15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.3-mc1201-sources.jar",
          "url": "magicutils-commands-brigadier-1.21.3-mc1201-sources.jar",
          "size": 8154,
          "sha512": "25f9dd6bed138735d89c5c631f16d9706c5aeaef73fd2f6be4b6c34d10bfe7c7915b5099946b5ef3f97c4000678c1fc3f691fd5c14e40c3fa1bcfb5414eb0a92",
          "sha256": "88be7c5f9e2f69a9aebcab3f464f144eca700f8317649f6fbf8a8686ae449ee6",
          "sha1": "0c17dbc0cb33d0b3a7d067480b123cead0c45f03",
          "md5": "57137a65b952bdc8d20269aed9abf9a0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.3-mc1201-javadoc.jar",
          "url": "magicutils-commands-brigadier-1.21.3-mc1201-javadoc.jar",
          "size": 96663,
          "sha512": "3d919e6c9ca8b4a4842b0a06975b8ddd33d99e805dfff6327c912a3a529b9df8017cb46aabb470ca65da6472ea5a1f9debaba620c503719e556da7da44b31f1c",
          "sha256": "99a835a6370508bb4bd9aee69c1f1a235b712cf616121035dc4b183bfec47be2",
          "sha1": "09f9a1e2685c425f5c46754b2e066645c1450506",
          "md5": "dcc47614797e9b1cc02b2e3bfb0854cd"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.3-mc1201-all.jar",
          "url": "magicutils-commands-brigadier-1.21.3-mc1201-all.jar",
          "size": 3442865,
          "sha512": "ef95b1d58fd98bc1723e635b4eeab55e47a7142f9d1b5bc37f56a817f1ff9621f3a170f10f25157c679ec3b2ea6f3f7f4343559dfda6a0663871c0b136cfb877",
          "sha256": "a4b4240c56c10f61f0b25f0a9b902e7b59200393ca8521eb30d21c91c297b18f",
          "sha1": "a49867cff9c835ddb8d12640605fadf8d374cb96",
          "md5": "c01d326b72df4c7a170667aef02310e6"
        }
      ]
    }
  ]
}
