{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-lang",
    "version": "1.21.3-mc1201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.3-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.21.3-mc1201-mc1.20.jar",
          "url": "magicutils-lang-1.21.3-mc1201-mc1.20.jar",
          "size": 51926,
          "sha512": "8eaa1fbaed42a4d53075740bbde39490af511f9d5a60a870b433622acdc0b44c417b8684967f4e4c0d4dc98c7457424f144dc7ee57f48d5f314643c9af035494",
          "sha256": "17147ade5850b5c08f53840e8427d3f0f969ce72b412c3da3749910e8cede7e9",
          "sha1": "b9f9cb07d0750f047d04958cc163f3a9c5ecb5a0",
          "md5": "3a7857c85a2a588045cc42827b0f41d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.3-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.21.3-mc1201-mc1.20.jar",
          "url": "magicutils-lang-1.21.3-mc1201-mc1.20.jar",
          "size": 51926,
          "sha512": "8eaa1fbaed42a4d53075740bbde39490af511f9d5a60a870b433622acdc0b44c417b8684967f4e4c0d4dc98c7457424f144dc7ee57f48d5f314643c9af035494",
          "sha256": "17147ade5850b5c08f53840e8427d3f0f969ce72b412c3da3749910e8cede7e9",
          "sha1": "b9f9cb07d0750f047d04958cc163f3a9c5ecb5a0",
          "md5": "3a7857c85a2a588045cc42827b0f41d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.21.3-mc1201-sources.jar",
          "url": "magicutils-lang-1.21.3-mc1201-sources.jar",
          "size": 31450,
          "sha512": "a34c0b43bdd6a6f20f2cf9522a5565a280ca57866cca6337715f6ecd7bfb1e379f01f3739b3b2278a7635a1103357e0b0cfc3fc7cd352957ba5caf8a215aaf2d",
          "sha256": "64ed562273ae171839ee732e268f23e740f3df2be2ce55f5b9e904aadee233de",
          "sha1": "efdc4adc4a48166c249dd6bac8abd6d0f2a99088",
          "md5": "5d2385ce895fe432310a5e91b07fc26a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.21.3-mc1201-javadoc.jar",
          "url": "magicutils-lang-1.21.3-mc1201-javadoc.jar",
          "size": 140903,
          "sha512": "fdd74cac341d343529d435b7d9231d42092e11b62f80f42f9833c300bd8cfbc431ad9c0bd4bf7d80af512e9dbfc1619c7d014d3c80246af221a44c4d32997434",
          "sha256": "aaea25c58f6b85c107474b21270e4293cc355001ba2749e53e079057e58e50e7",
          "sha1": "a86ebf3449606b367596a5b86f21ed0c58db2e66",
          "md5": "c14aa546fa5271daa08cb64c46f99f1f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.21.3-mc1201-all.jar",
          "url": "magicutils-lang-1.21.3-mc1201-all.jar",
          "size": 3201828,
          "sha512": "1e63511d970fa76a2b7541940265708e1e74a0b7ad660630f571c2e3a2f33e94e6409b56400aae2d657b11e9453dc7aacf796fa09be5ff7e6c3ac3c743938663",
          "sha256": "6f644af7f8eec5f4fec2c36274f6a768d6997f70fc56f541aef89d4e54c8868c",
          "sha1": "ea88e0ccaeb8058edbf377653cd9cef155f884b6",
          "md5": "414ef926da41482e1f491c269feb0c92"
        }
      ]
    }
  ]
}
