{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-core",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.10.0.jar",
          "url": "magicutils-core-1.10.0.jar",
          "size": 1219,
          "sha512": "09df652c077fc3ff0db7ea4e45fd844255bb8a91a81e87fb0b618c55bf2c212267884e2d11bbd07e4f0d9ca611ccc496d6ff988dd3a6e10242dc74caece2a55c",
          "sha256": "ec5004ec6b85deb0bafe0273f3a801d0bca0f5f83eccef63c031c804420ce693",
          "sha1": "7c2eb72618327ec50098b25b8844b4690827b106",
          "md5": "f62abd5fdc7476ceead15dabff4930da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.10.0.jar",
          "url": "magicutils-core-1.10.0.jar",
          "size": 1219,
          "sha512": "09df652c077fc3ff0db7ea4e45fd844255bb8a91a81e87fb0b618c55bf2c212267884e2d11bbd07e4f0d9ca611ccc496d6ff988dd3a6e10242dc74caece2a55c",
          "sha256": "ec5004ec6b85deb0bafe0273f3a801d0bca0f5f83eccef63c031c804420ce693",
          "sha1": "7c2eb72618327ec50098b25b8844b4690827b106",
          "md5": "f62abd5fdc7476ceead15dabff4930da"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.10.0-all.jar",
          "url": "magicutils-core-1.10.0-all.jar",
          "size": 3326159,
          "sha512": "ea2d92778669c509221b4ddbcd1cb0c1876f435155b9de0868ba324440ae5b55c6eefbad50d3fd5e51cb724229d88177886eb15872bd5e11f708d0d0c711ddaa",
          "sha256": "e2fefcb6cf7357b26968ee97114c99e7b5264c42006d97420c5b828955ee6872",
          "sha1": "0f9b97665d731ac016278a0ebd5511f592e584c0",
          "md5": "ac11675c34aaa0d61b2064fdb20ecdf9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.10.0-sources.jar",
          "url": "magicutils-core-1.10.0-sources.jar",
          "size": 1086,
          "sha512": "6b4a148cb3907c4a17eeecc379d7cb92a8e04f820f550020539e3e00e979868e3b7470f82b31fa1844a3764f97b4aafe2f9c16e4274e6a505fa8122ab8dd8364",
          "sha256": "39f258a4ca0db1fa415d6fc3421b0b01a5951fc84960c406a6c1654c7c4a12be",
          "sha1": "37801f4d9594cd8e0c2fad309c564e8aa6915ae7",
          "md5": "fc58eddc5a9771d6f26678de207da38f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.10.0-javadoc.jar",
          "url": "magicutils-core-1.10.0-javadoc.jar",
          "size": 91527,
          "sha512": "5d7e87dec019393be65dfcb95aaee67da187380218c04013b0988455256a9c48ac55dd0fd043016d876b4712903927a701cfb00ada3c10e1fcedfc2399f41150",
          "sha256": "312ebe90142502f85a7ed98f4365c5eaea948873a20118869d3a7956cbbd05fb",
          "sha1": "ca2dac90fc3919b49226818d7aab1a2ee80b42ba",
          "md5": "92811309999c3e8e821cba3adfa6f432"
        }
      ]
    }
  ]
}
