{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-core",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.10.0.jar",
          "url": "magicutils-core-1.10.0.jar",
          "size": 1219,
          "sha512": "6695b6f6032c58ff2b310cd9c80ea729bcd1c5fb6e6d0d7459fbbab01fa07004fe812ab72d64d96530b322ee5c4801ade608ea21ff62aeb1470d2be033feedf6",
          "sha256": "d195d8d8f26793b4728a6198891e86f7f3c273e6e69ba9208485f9c77c39283d",
          "sha1": "72df64f1c23f3bb6d88491e3bde74b4610dfc8c6",
          "md5": "637a713e7369c236d05a2d6f044ee048"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.10.0.jar",
          "url": "magicutils-core-1.10.0.jar",
          "size": 1219,
          "sha512": "6695b6f6032c58ff2b310cd9c80ea729bcd1c5fb6e6d0d7459fbbab01fa07004fe812ab72d64d96530b322ee5c4801ade608ea21ff62aeb1470d2be033feedf6",
          "sha256": "d195d8d8f26793b4728a6198891e86f7f3c273e6e69ba9208485f9c77c39283d",
          "sha1": "72df64f1c23f3bb6d88491e3bde74b4610dfc8c6",
          "md5": "637a713e7369c236d05a2d6f044ee048"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.10.0-all.jar",
          "url": "magicutils-core-1.10.0-all.jar",
          "size": 3326159,
          "sha512": "ea2d92778669c509221b4ddbcd1cb0c1876f435155b9de0868ba324440ae5b55c6eefbad50d3fd5e51cb724229d88177886eb15872bd5e11f708d0d0c711ddaa",
          "sha256": "e2fefcb6cf7357b26968ee97114c99e7b5264c42006d97420c5b828955ee6872",
          "sha1": "0f9b97665d731ac016278a0ebd5511f592e584c0",
          "md5": "ac11675c34aaa0d61b2064fdb20ecdf9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.10.0-sources.jar",
          "url": "magicutils-core-1.10.0-sources.jar",
          "size": 1086,
          "sha512": "52b904a0f908d19167a7a844a9185f382dee6eeb659d5a081f48743f2c5fdcbd14e065b48f8c3cd0c06d9052294199d49281f2e0cf11d40e3b38bef4dd9e2189",
          "sha256": "09095b85e6cda0377129bc3a915f67cc2b3d22ca84e963b1902627c2e6787e2f",
          "sha1": "0c2775ea0ff043af7de37581063c125bc7076b2a",
          "md5": "2482450868b6483a857ff2f6d52b18d2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.10.0-javadoc.jar",
          "url": "magicutils-core-1.10.0-javadoc.jar",
          "size": 91527,
          "sha512": "5ceaccb2a0dfe0375cf025f5060e268c71e74373246be07e94fac32410b122726778b82118e64d63ca3f37d67f7b95ee6a53a3c71319be5113466e7d3f656d3f",
          "sha256": "2dc744228a935a7ff658b080ba43acf6e7d8618f0d2f3712f1df043cf088d94c",
          "sha1": "03bf8f9b086223f55b0aa2b98dd38655195169dc",
          "md5": "667cc3c38ff82cdfe1058a512e2635e6"
        }
      ]
    }
  ]
}
