{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-core",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.10.0.jar",
          "url": "magicutils-core-1.10.0.jar",
          "size": 1219,
          "sha512": "068c6dfe15bb975c227a966b0187923f94ee0832ffc125814d1a138349f67edb4402347346b3209571d02a7b5930ec53397dcddadc27b549edf9f0753ea6fefd",
          "sha256": "14317d884ad65454b8e934990c89f4356a647860d7d446e081ce157675621665",
          "sha1": "25dca5bf21819b43f458a1100263ad27181d4a10",
          "md5": "1ac65bdf35e51cf22781de436be07d44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.10.0.jar",
          "url": "magicutils-core-1.10.0.jar",
          "size": 1219,
          "sha512": "068c6dfe15bb975c227a966b0187923f94ee0832ffc125814d1a138349f67edb4402347346b3209571d02a7b5930ec53397dcddadc27b549edf9f0753ea6fefd",
          "sha256": "14317d884ad65454b8e934990c89f4356a647860d7d446e081ce157675621665",
          "sha1": "25dca5bf21819b43f458a1100263ad27181d4a10",
          "md5": "1ac65bdf35e51cf22781de436be07d44"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.10.0-all.jar",
          "url": "magicutils-core-1.10.0-all.jar",
          "size": 3326159,
          "sha512": "ea2d92778669c509221b4ddbcd1cb0c1876f435155b9de0868ba324440ae5b55c6eefbad50d3fd5e51cb724229d88177886eb15872bd5e11f708d0d0c711ddaa",
          "sha256": "e2fefcb6cf7357b26968ee97114c99e7b5264c42006d97420c5b828955ee6872",
          "sha1": "0f9b97665d731ac016278a0ebd5511f592e584c0",
          "md5": "ac11675c34aaa0d61b2064fdb20ecdf9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.10.0-sources.jar",
          "url": "magicutils-core-1.10.0-sources.jar",
          "size": 1086,
          "sha512": "0ef74522a2514a69a80cb982dc1db483a33027339f3b5f349b82968710333d23eea8b9253be44953cfd341fab55623ddea7915bd03c3bfc27bab9f3dbc480550",
          "sha256": "ab2e516b12fa475157b964f35275a81543c906774c2e7c1f175cc3e34cef800b",
          "sha1": "28600f4e9849422729f1ca47da18bc4d2fe4a4ce",
          "md5": "e26843630efebbe9e6b5a91ef21f8786"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.10.0-javadoc.jar",
          "url": "magicutils-core-1.10.0-javadoc.jar",
          "size": 91527,
          "sha512": "eeec2f53b43fceb726c351836436990d2e659997f5dae4def17948266733486f0a57f8d0f4780dacee39dd7323e38393dcac9c2d5096765f821ceaa6899987d9",
          "sha256": "835c8faec320bfe5b41324526c6b8a51d94375b23952eeebb08a2729709515c5",
          "sha1": "7624d6c622802d77fdc1ad2431bac9d88dcc85ee",
          "md5": "62f60cb091c33fa730148bb613055d53"
        }
      ]
    }
  ]
}
