{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-http-client",
    "version": "1.19.0-mc1201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.19.0-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.19.0-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.19.0-mc1201-mc1.20.jar",
          "url": "magicutils-http-client-1.19.0-mc1201-mc1.20.jar",
          "size": 58198,
          "sha512": "ae8b86c80d40484ad1224bf792d2e16c12330d4cb3e73ff4778ed0478b52589a3eb711189261d94980b1a56bbef2dc68e350046275b04065ff31191ea2926b46",
          "sha256": "6652253d30705ff3d686d45f1b82b915c4ae271bea80740d03951a929157e278",
          "sha1": "9f1d67ead1dbf8b3f435176fdc283db41299603e",
          "md5": "5a967544f3e25a44a6a8d5350f81152b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.19.0-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.19.0-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.19.0-mc1201-mc1.20.jar",
          "url": "magicutils-http-client-1.19.0-mc1201-mc1.20.jar",
          "size": 58198,
          "sha512": "ae8b86c80d40484ad1224bf792d2e16c12330d4cb3e73ff4778ed0478b52589a3eb711189261d94980b1a56bbef2dc68e350046275b04065ff31191ea2926b46",
          "sha256": "6652253d30705ff3d686d45f1b82b915c4ae271bea80740d03951a929157e278",
          "sha1": "9f1d67ead1dbf8b3f435176fdc283db41299603e",
          "md5": "5a967544f3e25a44a6a8d5350f81152b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.19.0-mc1201-sources.jar",
          "url": "magicutils-http-client-1.19.0-mc1201-sources.jar",
          "size": 21590,
          "sha512": "94fde141f0c6aa3a602f194001bb5d9ad3c924882c6f3e07209ba8b8cc11f72c6e9457102864565d6585a3ddad4ffecc68bd63ba15345c5e4fb7133cebc699c0",
          "sha256": "d56fd445eccd8f18d0dc1cbd0a4e52ef38ea3ae752784fd7b9775bf86f362081",
          "sha1": "c75bc9748d407dc223ef8b26d8a203437fa98cf9",
          "md5": "fbf841914dd9cb02b159c954a7176056"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.19.0-mc1201-javadoc.jar",
          "url": "magicutils-http-client-1.19.0-mc1201-javadoc.jar",
          "size": 137277,
          "sha512": "7da297a173830f40bb4813cb198ac83f9ead6de3b85efb42fd1e2c4d3eba72cd09e9212f5fc54bd883dd6bb7b83f04330ceae9c3c3d957304729c6c6a89335ea",
          "sha256": "13b56d88c0a3f1dec36fbb898bd4bc4017464445c1d4f26d64b30a964bd10840",
          "sha1": "973e7f2ee8a6ceed260427f836d027e3c62d0eb3",
          "md5": "3bb46f189efec3b23bd3087fb902264c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.19.0-mc1201-all.jar",
          "url": "magicutils-http-client-1.19.0-mc1201-all.jar",
          "size": 3479146,
          "sha512": "b98927e664472d97d6279cf56af07196446ee1e06350c7d38ec2af4c4da83baa8d1f1392a65be5cebfadf14feb8a77fe59696d31a5db265c1b61f1dfa7660bc7",
          "sha256": "0d2d371ec663a0d49dfa625dea742bdd41eb9f73d180d17c650c5c97b5c44820",
          "sha1": "eb2365de08b6dc7e5e878ba0d25b5a2a5a72c2ff",
          "md5": "6992755bf460e39862e4c0d5c3554ccf"
        }
      ]
    }
  ]
}
