{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-velocity",
    "version": "1.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-velocity-1.16.1-mc1.21.jar",
          "url": "magicutils-velocity-1.16.1-mc1.21.jar",
          "size": 38274,
          "sha512": "34037e452fbf71a93c5cc1729ffdcd72121ab9d46705fd21f0340f42eb721caa8fe5283fc311971be0883f6ff7aa740fbfa2db4ff7715503b9408ba73688e3e1",
          "sha256": "04e90c82f5acc508691abbe790a68af527d4086454d1d5eae0ffcf05c01c6ae6",
          "sha1": "e993f9e837bd4cf9441ebc40c00e7318fbc201bc",
          "md5": "49b59798789cffd7e00a541f53b5a3b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-velocity-1.16.1-mc1.21.jar",
          "url": "magicutils-velocity-1.16.1-mc1.21.jar",
          "size": 38274,
          "sha512": "34037e452fbf71a93c5cc1729ffdcd72121ab9d46705fd21f0340f42eb721caa8fe5283fc311971be0883f6ff7aa740fbfa2db4ff7715503b9408ba73688e3e1",
          "sha256": "04e90c82f5acc508691abbe790a68af527d4086454d1d5eae0ffcf05c01c6ae6",
          "sha1": "e993f9e837bd4cf9441ebc40c00e7318fbc201bc",
          "md5": "49b59798789cffd7e00a541f53b5a3b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.16.1-sources.jar",
          "url": "magicutils-velocity-1.16.1-sources.jar",
          "size": 14617,
          "sha512": "77f0d02b0244c5aec67695cd7df5cfb6fdd1182b5b3495c538df78053f6fd78a62cfac6a037ce8eb3161662ae1ca6857eb73cc05fafede15711e4a989e1b6ae0",
          "sha256": "9737347738110514ff593d07cd7ca7f83bf564f9fc32a4a1672dd5defd86d857",
          "sha1": "5edfd4b307937bbb69996e05b30fa30778248dbc",
          "md5": "19cab55fe5d558a730b8a947424a1285"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.16.1-javadoc.jar",
          "url": "magicutils-velocity-1.16.1-javadoc.jar",
          "size": 128597,
          "sha512": "a72f6f5c10c3b74a9217a0a4c9de9647e2a0f09e4f703137d1fab00e0a6a5679e2f808a305284c89420bdbef2df76352a77f7dce21477ca6f4c14ed5ed70db89",
          "sha256": "6401b99d4e88e098bfc83b09537755f0cff1646369b9e833253c463a58b3c0bd",
          "sha1": "1cc933ebb50848219c5cec76091b5301f9c550eb",
          "md5": "2bbde75f686600370348ae304283f55e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.16.1-all.jar",
          "url": "magicutils-velocity-1.16.1-all.jar",
          "size": 3449371,
          "sha512": "fbba68dbfe561c1e2dbaf5c4df958a1b94384ad42e628819a0875d1311050f56029b2551347854342fe8d8f7d003c4c18c7e13a463fa732687066bddd6f40256",
          "sha256": "e3d93ceda1adc55a39a9f1da1f43491cbea38f00dea7c6a418c4728642678979",
          "sha1": "2c245ad99aa3a144fa9a3bde47282777221c190f",
          "md5": "bd2fb08b738fa087d8b2f93e38dbc4b5"
        }
      ]
    }
  ]
}
