{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-core",
    "version": "1.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.16.1-mc1.21.jar",
          "url": "magicutils-core-1.16.1-mc1.21.jar",
          "size": 21073,
          "sha512": "808e2aa8a2d8826203345e9a292f7d06d57f3087e22ceed2e15768dedde1f488385ebbc25139d8f7eb4612dcd31cf8d2bc7455b714dc7ea706326873330c9966",
          "sha256": "e172b0e6c223cecfb55f43ae1931c8dfe1e68cb9a177da3b53ad7509ec32503b",
          "sha1": "b39f222759a1ad18cf4541e8c8f9d1b43b1b679a",
          "md5": "8a72fe7e233fffa8cbbc832ab2689c54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.16.1-mc1.21.jar",
          "url": "magicutils-core-1.16.1-mc1.21.jar",
          "size": 21073,
          "sha512": "808e2aa8a2d8826203345e9a292f7d06d57f3087e22ceed2e15768dedde1f488385ebbc25139d8f7eb4612dcd31cf8d2bc7455b714dc7ea706326873330c9966",
          "sha256": "e172b0e6c223cecfb55f43ae1931c8dfe1e68cb9a177da3b53ad7509ec32503b",
          "sha1": "b39f222759a1ad18cf4541e8c8f9d1b43b1b679a",
          "md5": "8a72fe7e233fffa8cbbc832ab2689c54"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.16.1-sources.jar",
          "url": "magicutils-core-1.16.1-sources.jar",
          "size": 9454,
          "sha512": "2bfdc337b18f931a1ef6d82bf08df4c1cf27d2b6b6703a7d7c12c8d9d2b15387876b73d06876b6460c8addb495580d5eebc910099013c6f24fa02caab29fa3ec",
          "sha256": "c9b2e6842dce04bf0391e2af4264d7d57e5ea985870093fd24d3be3710e75bad",
          "sha1": "8b17c7a2c6b430bc25a04638fb36894c3f45e873",
          "md5": "fb8036fbcc4202637eabec9101e6e7c1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.16.1-javadoc.jar",
          "url": "magicutils-core-1.16.1-javadoc.jar",
          "size": 120823,
          "sha512": "05c53d38f54da6fb252bf0518ac9f860c4e2750e2b10a32ecb72495abd4409fa4ecb9d2a4ded9550612297d11fe4fc89089bad911171487cd51a6271199d50bd",
          "sha256": "9c2760f088369469e675e8223472346d5da672c029d294457837b6c1d9afabdc",
          "sha1": "a9747f45e70801352204cbfc2afa5822198cc100",
          "md5": "bda11f2ae7d27476c04052176d4ac928"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.16.1-all.jar",
          "url": "magicutils-core-1.16.1-all.jar",
          "size": 3411916,
          "sha512": "c83460af542263c53d94c9a7f802c31c6291dcf872a4b2b2e917180b2f99b2de5968093ea3b54c5ff90fb00ea072f84a9cad9ae696cd84507d360de59ebc5164",
          "sha256": "99746b273d7a55dbec35953cfb62a1e8d794025f9341c4200eb0defb94428a3e",
          "sha1": "9fce06e5085f59a052b81edf2e610854a20f51b7",
          "md5": "a7583a44e30621191bb3d80bd01319b2"
        }
      ]
    }
  ]
}
