{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-diagnostics",
    "version": "1.21.1-mc2611",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.1-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-diagnostics-1.21.1-mc2611-mc26.1.jar",
          "url": "magicutils-diagnostics-1.21.1-mc2611-mc26.1.jar",
          "size": 60917,
          "sha512": "a3af237914045b5f44716b4576183c0003ea21193bdffa1c3123f58242534e81d61bc3326b408ca4327821d82f7a4a0fde532ff4d61529b99e416c8427650a12",
          "sha256": "767e4cd84bf0a7adef968883b121269fd043d3975ce10ae0c45bb88a23272b9c",
          "sha1": "40c29c84636063c8f269c1917c75661a8d0a10dd",
          "md5": "85a6d1fa5207ee8dc9e80136e5dc8961"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.1-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-diagnostics-1.21.1-mc2611-mc26.1.jar",
          "url": "magicutils-diagnostics-1.21.1-mc2611-mc26.1.jar",
          "size": 60917,
          "sha512": "a3af237914045b5f44716b4576183c0003ea21193bdffa1c3123f58242534e81d61bc3326b408ca4327821d82f7a4a0fde532ff4d61529b99e416c8427650a12",
          "sha256": "767e4cd84bf0a7adef968883b121269fd043d3975ce10ae0c45bb88a23272b9c",
          "sha1": "40c29c84636063c8f269c1917c75661a8d0a10dd",
          "md5": "85a6d1fa5207ee8dc9e80136e5dc8961"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-diagnostics-1.21.1-mc2611-sources.jar",
          "url": "magicutils-diagnostics-1.21.1-mc2611-sources.jar",
          "size": 25570,
          "sha512": "bf1bf971429d2dde57dfd3d93f1fb15a3a68fe5170ba37ebaf51de9cd9e82946f72525e34a4759030a9718ab12b6fefc598f2e2ff2acdd8d46ceb0ea455dd72a",
          "sha256": "7eb04daf0a6018fe354e44ad851e3a124106faf431fd17c5d6634e154676ab80",
          "sha1": "bd353cf97eb2f2a6e4ecdbd129cacacfac9944e0",
          "md5": "80d76ce16f395f6bc5ba377f237d9cb2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-diagnostics-1.21.1-mc2611-javadoc.jar",
          "url": "magicutils-diagnostics-1.21.1-mc2611-javadoc.jar",
          "size": 4205577,
          "sha512": "d6f836ced472f36d6ecffcc20b7c2afc92e791ad5919e9d4746ecd87bad1718bbeaf7148ee53b55d0c7ce0f55d625c99ad29ca3f557d1098936eb1fa058a1b42",
          "sha256": "43d34c2b58876e731a88d18a6a8c57ea29910c1aa312b883c270f43c5dd89159",
          "sha1": "89e2b4dbc6243630c8f3baf639c780f4c57729b4",
          "md5": "c197add6f8d25627d0d593cde2d65dd4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-diagnostics-1.21.1-mc2611-all.jar",
          "url": "magicutils-diagnostics-1.21.1-mc2611-all.jar",
          "size": 3502941,
          "sha512": "388c36686db43e8b1499aa3f5753e63e17aab8053042163b22fd0445e01055e7f20ed74df877302cd57d97f94f050b8b279968ef176a9db1da2711f6b1b8be40",
          "sha256": "58d3721ff4c6c0b58d155a1d68722654ca9cc9783261e22258172ebd6c77f1fd",
          "sha1": "cc601bba837395f3892953cd933f8c49f4a5e0a8",
          "md5": "ff77c38ae2d4e0054ea23209493c5e5d"
        }
      ]
    }
  ]
}
