{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-lang",
    "version": "1.14.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.14.4"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.14.4-mc1.21.jar",
          "url": "magicutils-lang-1.14.4-mc1.21.jar",
          "size": 41391,
          "sha512": "0432a2025cd1bf0eff1b8e39b1414d8e57034d5c4c30cf3286ce9c1c52c7e55125ca26eb33a53e3f975f65c52d9cf1a4893f901954bae059872eedee22172b15",
          "sha256": "1db86f776053935098472c6431c589780636a23ae46910e5159c1f775e854640",
          "sha1": "a184fb65c0867b220ade24f7941dd5609a379742",
          "md5": "6b901bdf9a2e3541aa8af72c7d8fdec5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.14.4"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.14.4-mc1.21.jar",
          "url": "magicutils-lang-1.14.4-mc1.21.jar",
          "size": 41391,
          "sha512": "0432a2025cd1bf0eff1b8e39b1414d8e57034d5c4c30cf3286ce9c1c52c7e55125ca26eb33a53e3f975f65c52d9cf1a4893f901954bae059872eedee22172b15",
          "sha256": "1db86f776053935098472c6431c589780636a23ae46910e5159c1f775e854640",
          "sha1": "a184fb65c0867b220ade24f7941dd5609a379742",
          "md5": "6b901bdf9a2e3541aa8af72c7d8fdec5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.14.4-sources.jar",
          "url": "magicutils-lang-1.14.4-sources.jar",
          "size": 23151,
          "sha512": "5b7fe3885850962867ba1b25b13a856d5831bbc4367d97971a99ea7254ffef9c2e6cec14fd54fc174b7604a8935cdbe5fcca61774966a39b17abaae4d18fd498",
          "sha256": "038cd0d76c55663c6ac5fb5ee0b32997e6e9a088a1173c86567ffb6bf8439fb6",
          "sha1": "7c56cd8901d8fe87389072b2b6b88149622b8db0",
          "md5": "35c27066e68e728f701346f77a592062"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.14.4-javadoc.jar",
          "url": "magicutils-lang-1.14.4-javadoc.jar",
          "size": 141905,
          "sha512": "02c0dc8bf6551e3afc2081ff4154f0b4ce4a0b937ca1d811122c67768a10ab3ec19c23f1f0ba22ffbfabe11056e217057c74998dbf7ea53a203d267e870b7c48",
          "sha256": "7a723dd5106163943fb18e6b7714ffcb91a3f0a9aeaf42392735b1512c47369f",
          "sha1": "2de82367eff87bba291b6464a5f1a875ee7e0cbb",
          "md5": "79e3d106e582dc92ecec125b7eb70082"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.14.4-all.jar",
          "url": "magicutils-lang-1.14.4-all.jar",
          "size": 3178459,
          "sha512": "0d912c97d669b3d08666adebfa37e06a17c4d8ede6463f58bb5e92c23a7c270f35043447be0437fbe5054bb488c832061ca633dd044279bba172e9b36b4b22f7",
          "sha256": "47dea3b04cac805db0a8d61c941b95a3babca5c7c69ccbe67cafcc855997bdff",
          "sha1": "2a3b4f6ee8a8bbd837ef97647d998d3f339a30ce",
          "md5": "7047cb447e247479c3e38802d1bf4093"
        }
      ]
    }
  ]
}
