{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands-brigadier",
    "version": "1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.4-mc1.21.jar",
          "url": "magicutils-commands-brigadier-1.21.4-mc1.21.jar",
          "size": 22463,
          "sha512": "12bfc6ff3838d9a4a464a9588d81540235fd545070411192d7cd23b73d9066e643b1a4acf3edc015b7b6d728fbb1c4cd4fe062f2163006dde54a9181dd78487f",
          "sha256": "0c4814a02c6bbe07b3129d36948deb3fa3151b7b72bf1e4b25f79c80a0a1f94b",
          "sha1": "7ddd8658fdfe7c9ab1dc9ec60cc08e27a535a156",
          "md5": "dc259a2601d6ec1627b3309de8cbbe84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.4-mc1.21.jar",
          "url": "magicutils-commands-brigadier-1.21.4-mc1.21.jar",
          "size": 22463,
          "sha512": "12bfc6ff3838d9a4a464a9588d81540235fd545070411192d7cd23b73d9066e643b1a4acf3edc015b7b6d728fbb1c4cd4fe062f2163006dde54a9181dd78487f",
          "sha256": "0c4814a02c6bbe07b3129d36948deb3fa3151b7b72bf1e4b25f79c80a0a1f94b",
          "sha1": "7ddd8658fdfe7c9ab1dc9ec60cc08e27a535a156",
          "md5": "dc259a2601d6ec1627b3309de8cbbe84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.4-sources.jar",
          "url": "magicutils-commands-brigadier-1.21.4-sources.jar",
          "size": 8154,
          "sha512": "25f9dd6bed138735d89c5c631f16d9706c5aeaef73fd2f6be4b6c34d10bfe7c7915b5099946b5ef3f97c4000678c1fc3f691fd5c14e40c3fa1bcfb5414eb0a92",
          "sha256": "88be7c5f9e2f69a9aebcab3f464f144eca700f8317649f6fbf8a8686ae449ee6",
          "sha1": "0c17dbc0cb33d0b3a7d067480b123cead0c45f03",
          "md5": "57137a65b952bdc8d20269aed9abf9a0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.4-javadoc.jar",
          "url": "magicutils-commands-brigadier-1.21.4-javadoc.jar",
          "size": 107845,
          "sha512": "7bd9aa3d0c0ffd4f06321a27a777ae72a8e1a6fa7c5f74220e7bd412a5373f5d8309b8aef3336254ad0f52c1163e3f07e100c213c95787e8c6dc805179c7966f",
          "sha256": "0d48411fe78cf66d7b48a22db2a1aebf2df845e1c8c8ab9a3ae9309c462b0f13",
          "sha1": "48093d3a83107b4e1b18b5b65047a57161eae08f",
          "md5": "f3ce3fa2969fd8f0c740b11b75777e37"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.4-all.jar",
          "url": "magicutils-commands-brigadier-1.21.4-all.jar",
          "size": 3443041,
          "sha512": "5ad8e5522540ee97dd4c5d7f7f54af7fceeb67eed80d7c7578d711ed3ab38554ab20b913a25db71a935e172431505d6fc9262a2023fd19b463e9c4e1bcd5f942",
          "sha256": "1e4b868cfdb2db9e15cf45c6dc5d74ea4bc33387f7bcb352c6978bb1e31de430",
          "sha1": "06c88916286f00917f35d7ba9b7f69b45cff4830",
          "md5": "65825c1155bfeb8bc57b15bdc795c506"
        }
      ]
    }
  ]
}
