{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands-brigadier",
    "version": "1.14.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.14.2-mc1.21.jar",
          "url": "magicutils-commands-brigadier-1.14.2-mc1.21.jar",
          "size": 22275,
          "sha512": "637779b72b225c8b850a2d1ad3f9d1417ca3bc79551b0248bb3328baee5796b4c864298d33c81fc213d639682c92122e74e92485ef1636c329b669c70b807b23",
          "sha256": "9482ae47a37d2fdf6c378f3435037483a07d24d7e13cd9ebea25aac57b841504",
          "sha1": "7fd0e7cf4349cefe3b3a82240916e0927c9f898a",
          "md5": "743056a9418e9c107beb96842acaaa46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.14.2-mc1.21.jar",
          "url": "magicutils-commands-brigadier-1.14.2-mc1.21.jar",
          "size": 22275,
          "sha512": "637779b72b225c8b850a2d1ad3f9d1417ca3bc79551b0248bb3328baee5796b4c864298d33c81fc213d639682c92122e74e92485ef1636c329b669c70b807b23",
          "sha256": "9482ae47a37d2fdf6c378f3435037483a07d24d7e13cd9ebea25aac57b841504",
          "sha1": "7fd0e7cf4349cefe3b3a82240916e0927c9f898a",
          "md5": "743056a9418e9c107beb96842acaaa46"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.14.2-sources.jar",
          "url": "magicutils-commands-brigadier-1.14.2-sources.jar",
          "size": 7877,
          "sha512": "917b949d668ac2cb4e335d0b61c61fd687420971fc2e457c08e64f497b199a23d9530fa501d5af0d2869f2ae6475b69314a1228010feb399de2b86e096a2f360",
          "sha256": "ecdb49e6dedcd89c7edebdf549658b53b5fa0b9375c5df23b70732d402606e9a",
          "sha1": "2e8d27ab8769d326169d31c1368d6793c92ed273",
          "md5": "191bbea570ded279de44b591055abcfb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.14.2-javadoc.jar",
          "url": "magicutils-commands-brigadier-1.14.2-javadoc.jar",
          "size": 107314,
          "sha512": "b9df4e0382afdc812edb76541499c360cda80ba4163f54c3fb761c39f2f80520c79f64e258ca20007af87b843580e290f2104435b08e19ce789bced3d7715b33",
          "sha256": "6f67a63e7d04c1faf58255b1ee1c18753a0b576709691743d370f16930e60267",
          "sha1": "53a77f65d85f5a9066001c7c04501dfa13fde83e",
          "md5": "2814c6c990a6094d28fe675535c842e3"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.14.2-all.jar",
          "url": "magicutils-commands-brigadier-1.14.2-all.jar",
          "size": 3410816,
          "sha512": "5929f4c44cd12c96dd124f5d955f81f5678b592eae127fb4224bf8bb2c5112e253c696f54765fa9be527672eef0cd8b1fdcb2b0fceb9a14b02d9315592c4a079",
          "sha256": "50173cd63ea83ffa6a4f974334eafc31ed65a3737cfd92a3f51bdd03ff162a87",
          "sha1": "ed917ea8fa1e00d2827ced2fb28b1eaf5e96a60d",
          "md5": "04fc2c9d4bde7619e07a671f3c9d696d"
        }
      ]
    }
  ]
}
