{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bungee",
    "version": "1.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bungee-1.17.0-mc1.21.jar",
          "url": "magicutils-bungee-1.17.0-mc1.21.jar",
          "size": 40483,
          "sha512": "e99d4215ed0f427e6a0b0becfa362ab5490745b388b15067d6e98ffbb65d041948cef83592f83d7e24868da7d31281801f1cbd523580cd9e3e5aeabc27ca68d8",
          "sha256": "a16ed394c3b1f1d7a7122faa784cf11ee2dabec996e952f9da0860c82abb68ef",
          "sha1": "1b2fa2cd98a230188d88b50b9b398a0bf57e7f46",
          "md5": "705adbc575be46646024609b6b89718f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bungee-1.17.0-mc1.21.jar",
          "url": "magicutils-bungee-1.17.0-mc1.21.jar",
          "size": 40483,
          "sha512": "e99d4215ed0f427e6a0b0becfa362ab5490745b388b15067d6e98ffbb65d041948cef83592f83d7e24868da7d31281801f1cbd523580cd9e3e5aeabc27ca68d8",
          "sha256": "a16ed394c3b1f1d7a7122faa784cf11ee2dabec996e952f9da0860c82abb68ef",
          "sha1": "1b2fa2cd98a230188d88b50b9b398a0bf57e7f46",
          "md5": "705adbc575be46646024609b6b89718f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bungee-1.17.0-sources.jar",
          "url": "magicutils-bungee-1.17.0-sources.jar",
          "size": 16031,
          "sha512": "edac1ea114921b3cb380e6cc18f9ed48123600903310445a393c1170d3e9f7d12230b22d2762a8b04fe37d6e7d2add5460e258e6b9c25906647dc2e41d7795f6",
          "sha256": "f2b8e44c18da7bdd797bc6cacdb8a7cc805f3f062b3bef508f88d2fbc1fc9635",
          "sha1": "116123f608b3cf991055064351c1944fce5a7838",
          "md5": "6387ce27bf5fe8391fb10fb16cb59d62"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bungee-1.17.0-javadoc.jar",
          "url": "magicutils-bungee-1.17.0-javadoc.jar",
          "size": 132632,
          "sha512": "35f7c01534f3e5b3cf630a912345baefa847329871be742862dbe4771c1ac02c69ab6094a885f5306021313862d605fe4ad0a4e5fc7e16807bb35971f84bb1b7",
          "sha256": "88ab6445d5c00baff391c10951213219015e237dca20e0210582940540f3afdf",
          "sha1": "55afcb40851906ca1005f6fb44467b362e9c528a",
          "md5": "fe247bbd93b7e782c2186d31aa8b6fe7"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bungee-1.17.0-all.jar",
          "url": "magicutils-bungee-1.17.0-all.jar",
          "size": 3481518,
          "sha512": "bbf1f9b0b3b676d1377e479c309290d82aaf1a592891fdca298b65188201d5f63d57d1b8310b08f1abbc9681bf93b4546503d31e548207cc714303bf738c3b3d",
          "sha256": "82ae378649691bafed1f689a39adde15804fd5d8e95c55a6301355cd35e43daa",
          "sha1": "a2aee4c845ef003ebd0de38dfb478530b913d830",
          "md5": "3aa4e0779fcf3b59677ead7c2d1a0905"
        }
      ]
    }
  ]
}
