{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-core",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.12.1-mc1.21.jar",
          "url": "magicutils-core-1.12.1-mc1.21.jar",
          "size": 4377,
          "sha512": "ac8b363ced147ce78d4ab095ea9538dad2699617cb71baa7f5052340a119d553c1ca12453ee12b6108fecaf61db78b25da69dc0bb971d4b7e1722dfd4d01b0ff",
          "sha256": "8410475e18a1db3f60fd984eb6f1dd9062bfbccde91828798fa390808576ec94",
          "sha1": "c2d29aafbf277f6c4b9e28ecbc116c565b0ae422",
          "md5": "4c439dbf49fdab3af8be5440b1a29e72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.12.1-mc1.21.jar",
          "url": "magicutils-core-1.12.1-mc1.21.jar",
          "size": 4377,
          "sha512": "ac8b363ced147ce78d4ab095ea9538dad2699617cb71baa7f5052340a119d553c1ca12453ee12b6108fecaf61db78b25da69dc0bb971d4b7e1722dfd4d01b0ff",
          "sha256": "8410475e18a1db3f60fd984eb6f1dd9062bfbccde91828798fa390808576ec94",
          "sha1": "c2d29aafbf277f6c4b9e28ecbc116c565b0ae422",
          "md5": "4c439dbf49fdab3af8be5440b1a29e72"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.12.1-sources.jar",
          "url": "magicutils-core-1.12.1-sources.jar",
          "size": 2524,
          "sha512": "04bb83ad430534e0b4bc94aa4c89464de5c2ffcc27f05d7927a647676f0c397887be618996f41d68f8bfbef90843a38c576af27e4e0bfe52bf96299394e073cf",
          "sha256": "8308ded3b6fe989c3e35c011d75bc59ae94cfc14a41c22c40a9a689f47d5c365",
          "sha1": "37d2a7c7dcce03f132b0fb357ceff0e32d7d4c25",
          "md5": "ac00672cc734cd708213b54a43217574"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.12.1-javadoc.jar",
          "url": "magicutils-core-1.12.1-javadoc.jar",
          "size": 100041,
          "sha512": "457508125f4928cee21de6b36b394a325cfcb511dcf60ff076253c725213320010de82a1240db7dcb81b7fd453af53e5f2a47e8d7b993ee9abdbc479d5d0e74b",
          "sha256": "7963783f01c830f9f8d4d382b418ef2a3567e3d0dc3d59a777628193140abb14",
          "sha1": "d027df1e3920a9b8634a08fc80e67f3524579f29",
          "md5": "9b22ea2aaddb9394330902601cbe75e4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.12.1-all.jar",
          "url": "magicutils-core-1.12.1-all.jar",
          "size": 3359854,
          "sha512": "00a21533d355a12b5dd4e35c64ae94bab84f4d3009e9ab7d6976fffb29eb80377555f395a050c85d4bd473a4ba9ddcf49d8bec50be08ff2a2ffdc6755e1158ef",
          "sha256": "2ef0f832278ffc86853f90999a29f946c9503d585e1d77cec9f5b8e612d9ab67",
          "sha1": "5c979d1c650aaaee2f7f1f2774185829ef0f991f",
          "md5": "0c4a80e3c6ae6b62015af84a7c3fb7ff"
        }
      ]
    }
  ]
}
