{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-processor",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magicutils-processor-1.10.0.jar",
          "url": "magicutils-processor-1.10.0.jar",
          "size": 9101,
          "sha512": "fcf5397a1eaca49c2b6f3dab84db51fb1b1cdeabb13f1531d2c39144c462aa3627de425388e129a4adbe685c95b8cf57ba607c9d6c761f7782dddc927eb42b0f",
          "sha256": "560fab020f57fe30a8a11706da174c6225a495fbebbf26fc018678ad5dbb3e73",
          "sha1": "990dbd39e842a9c803589e7876a894421e001a1d",
          "md5": "a104cdeaf667c3683608c63cef9e8f33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-processor-1.10.0.jar",
          "url": "magicutils-processor-1.10.0.jar",
          "size": 9101,
          "sha512": "fcf5397a1eaca49c2b6f3dab84db51fb1b1cdeabb13f1531d2c39144c462aa3627de425388e129a4adbe685c95b8cf57ba607c9d6c761f7782dddc927eb42b0f",
          "sha256": "560fab020f57fe30a8a11706da174c6225a495fbebbf26fc018678ad5dbb3e73",
          "sha1": "990dbd39e842a9c803589e7876a894421e001a1d",
          "md5": "a104cdeaf667c3683608c63cef9e8f33"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-processor-1.10.0-sources.jar",
          "url": "magicutils-processor-1.10.0-sources.jar",
          "size": 5019,
          "sha512": "15642f570d4cf08005979485d46950ae36c80168291e5bf81b89b9075ac2be04e96618f2518f0700c2a7b0054b6ca33c8c8a157e2f82c2d2daddbc6d893eef1e",
          "sha256": "9031377876a907e44eb81aecad0daf87f4f5b04fd6b1ed385199aaf1be56b90c",
          "sha1": "95322ee6300b0a5eedb72fbec0d688bb3398777d",
          "md5": "8f5269c23335fc793864c8d013565fa5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-processor-1.10.0-javadoc.jar",
          "url": "magicutils-processor-1.10.0-javadoc.jar",
          "size": 85266,
          "sha512": "63c3e1a695ba036ba0980680df035afb0f3e3e1f7f386dc4bd813beb216fb02f7b0a270cffc62f952a3da30cb6e41e8ab14872f7d8e0afdd3f3f04e17f132061",
          "sha256": "8eea6815eb2e8f1178212ff4b4b846152c88b10b91badf32b45651825d26359a",
          "sha1": "f4a4812db0e1da50f33fac5d9957805c850bcbb0",
          "md5": "0d26ecc566213116a37fc56beeb0da70"
        }
      ]
    }
  ]
}
