{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-processor",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magicutils-processor-1.10.0.jar",
          "url": "magicutils-processor-1.10.0.jar",
          "size": 9101,
          "sha512": "93873a7ba08d82f903689f5e94726d001d479521d1a08fd9ef48244f0650e27b387b6745011db277201a4af29aedc93b730a7013d4b950ab121792a01de4baf2",
          "sha256": "66944d332d1ee87b59a43386e23a96062c51ee8560e26160b4d5b236a8a32a65",
          "sha1": "a5efdffd71b10ac55d107f61075f522273c1e9f5",
          "md5": "646fba988fc08dc6a955b53fd66ffeb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-processor-1.10.0.jar",
          "url": "magicutils-processor-1.10.0.jar",
          "size": 9101,
          "sha512": "93873a7ba08d82f903689f5e94726d001d479521d1a08fd9ef48244f0650e27b387b6745011db277201a4af29aedc93b730a7013d4b950ab121792a01de4baf2",
          "sha256": "66944d332d1ee87b59a43386e23a96062c51ee8560e26160b4d5b236a8a32a65",
          "sha1": "a5efdffd71b10ac55d107f61075f522273c1e9f5",
          "md5": "646fba988fc08dc6a955b53fd66ffeb2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-processor-1.10.0-sources.jar",
          "url": "magicutils-processor-1.10.0-sources.jar",
          "size": 5019,
          "sha512": "f9c3620c07c23ea290fad764efb2095ce78a248a39a061086c652547dfee95f5f449e35238a20d8c21362eb5f897de3ee47413d6c2f045feab18d1b53fbf4067",
          "sha256": "ca5bacc039df1b01bfcf84fe58f8e79f994b0529be06cf4381f16358faf41000",
          "sha1": "d2e5c36e30d5a76b2c58d2b6ba874515ad4efce3",
          "md5": "67f25c1c24b79b766dbbc3d9b6d44d23"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-processor-1.10.0-javadoc.jar",
          "url": "magicutils-processor-1.10.0-javadoc.jar",
          "size": 85266,
          "sha512": "c26f5a229f33cabe589b5f8877829cd629a7f89b6b3d984bb5c45533444fae46bcb3ef35cd9b62b363c0ca5f17192680a7746b1f43f78deddd34ab91af10e50d",
          "sha256": "2b921ad9352bd5fe141e8f4c566ae91a9a7e378ebb750124e965f3af005c0c1e",
          "sha1": "92795dc12c0082e5a55d551e6f8abca00c77f062",
          "md5": "46c7fdf87cec97f8234911bf4f65684d"
        }
      ]
    }
  ]
}
