{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-velocity",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-velocity-1.10.0-mc1.21.jar",
          "url": "magicutils-velocity-1.10.0-mc1.21.jar",
          "size": 9987,
          "sha512": "76c72fc7bf908eaadd35832c20d5fafe44be3c8724aa30063630576a77cafcb295476f19e3cb55b109d5b39c5f1f65d72155c0303a9a0d3a2d7e1600c41f6fd4",
          "sha256": "85a487e0124d3be520eb3d267e99152bcc6bd42e85361b5a67ef93a0431f7fbe",
          "sha1": "fbb01d1139c8e3fd2a4bf900a99a8c66259f9cbb",
          "md5": "3a8ffde815902270c137718d2a6f2c49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-velocity-1.10.0-mc1.21.jar",
          "url": "magicutils-velocity-1.10.0-mc1.21.jar",
          "size": 9987,
          "sha512": "76c72fc7bf908eaadd35832c20d5fafe44be3c8724aa30063630576a77cafcb295476f19e3cb55b109d5b39c5f1f65d72155c0303a9a0d3a2d7e1600c41f6fd4",
          "sha256": "85a487e0124d3be520eb3d267e99152bcc6bd42e85361b5a67ef93a0431f7fbe",
          "sha1": "fbb01d1139c8e3fd2a4bf900a99a8c66259f9cbb",
          "md5": "3a8ffde815902270c137718d2a6f2c49"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.10.0-sources.jar",
          "url": "magicutils-velocity-1.10.0-sources.jar",
          "size": 5207,
          "sha512": "04195437342bc5e0991794bc8dd5af28f6311b20fdc173980eed644cb8c7023911c772ba98d74a816835e7b260c05f82004089d9b12451fcd45a7bd601fc4748",
          "sha256": "d91a7f0e4e2e441ea00a1072606f2ab13fe99e556c4b916a3ed2bcd5108db23f",
          "sha1": "facc6a1a8ee8d458ca7e59a745bb7fbcc04b578c",
          "md5": "d13f68065154e29e2ea88e19ff22999e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.10.0-javadoc.jar",
          "url": "magicutils-velocity-1.10.0-javadoc.jar",
          "size": 97404,
          "sha512": "89069eb37f0b6a9bf11c3473788b7f3d1dd09f4d36cf0eaeac931fb7971c2a0b440854fc54581f4b86ba7f52ed68e51de8af21085c0b9dcf891f122b9c7f4146",
          "sha256": "78f561e17c471d8a3b76b11e308580e8290ae46af34aa3806049eadae81d8f5a",
          "sha1": "7f0b44e25ccd3a1c1989d49c93861f7682d1ff5c",
          "md5": "c121bea50ac808c8ca271232e27eb3b0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.10.0-all.jar",
          "url": "magicutils-velocity-1.10.0-all.jar",
          "size": 3349044,
          "sha512": "8239efc0e473e5cca926a31ada291c4450e39a62f0b96369524a3bc8e9f08c0098a3968e291282dc60d94017d6976b4ec395bf0ad002746ace773152795fd704",
          "sha256": "13f35c902b8677c9fd4a84a593814924c191a61965f1ebe4f39f833b589e7822",
          "sha1": "96a74538e816406cfd13ede7bf279fbde4e0b91b",
          "md5": "c8d764d5616f277e4cdb434dc4f130ea"
        }
      ]
    }
  ]
}
