{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-velocity",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-velocity-1.10.0.jar",
          "url": "magicutils-velocity-1.10.0.jar",
          "size": 9054,
          "sha512": "240caeaa9d047312d978ca3969dbce6651fcf7ba17ac33bff64253a3da5e9dbb64c470fefc3ce0dd2ac538b6b39fd489c6eb99187fa7f9c1955e97c4b9cb0c49",
          "sha256": "d3a46461cf040b14e6db6a8890fc989ccbaacd0ff29624546c270aca0d6a7572",
          "sha1": "c90657d48f7df89108ad7290c8e34081a832ab97",
          "md5": "75a036ab85dc2121fc041e7dfe522230"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-velocity-1.10.0.jar",
          "url": "magicutils-velocity-1.10.0.jar",
          "size": 9054,
          "sha512": "240caeaa9d047312d978ca3969dbce6651fcf7ba17ac33bff64253a3da5e9dbb64c470fefc3ce0dd2ac538b6b39fd489c6eb99187fa7f9c1955e97c4b9cb0c49",
          "sha256": "d3a46461cf040b14e6db6a8890fc989ccbaacd0ff29624546c270aca0d6a7572",
          "sha1": "c90657d48f7df89108ad7290c8e34081a832ab97",
          "md5": "75a036ab85dc2121fc041e7dfe522230"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.10.0-all.jar",
          "url": "magicutils-velocity-1.10.0-all.jar",
          "size": 3334506,
          "sha512": "a5cd1c4db297936b177c29f4f5bee89fb3723016ce1f996c9ddd4368c317aa0f1a3163e6de80dc3a0560f50dbec655717a42391cf8d8562ec77a79f925adbd89",
          "sha256": "c4790448b2d83a7383a4ef534811916e13e41b17c30cf37b17347ff4f8345e31",
          "sha1": "2c1f4fca5af2a0f1575b1678c3cddad58944e8cd",
          "md5": "79338b774ba53641ca645835f8747821"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.10.0-sources.jar",
          "url": "magicutils-velocity-1.10.0-sources.jar",
          "size": 4643,
          "sha512": "33dbf8d0138f441d10740e09f253634ea3e200ccf664e0192bbce20e58acb7c7b191a12f6d97375f53fb1bb4d34aaedeb124bd1e7d05615e8d62a8a379ac06b0",
          "sha256": "d3ad0f892036519931a17981703fbb0134ea02a019c349f3c0a0581e78c48586",
          "sha1": "f2e63a1ec36fd38b54a6d21d768e3a68b1ec0c97",
          "md5": "cbc1a4edaa3b753fe76f9ec4e237f563"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.10.0-javadoc.jar",
          "url": "magicutils-velocity-1.10.0-javadoc.jar",
          "size": 96745,
          "sha512": "2234efc5e1e5d1f7a8faf72d6d5ecfa65a59a7142641c2b4c66bb694b12ce0ec34d0c87fd289560ce50ede4b771b1bd8060bca8ac1a67d6c93f1a23eae1d3915",
          "sha256": "1c7adbf579b2ea2f4659bae97a8c55165d5493c9a5b9451b29b184f7a1980b59",
          "sha1": "b33b738063bb5c8397fbe3d6a3a0d3487f388e17",
          "md5": "0f2bc79079297aa12b3e5af63e08e0d7"
        }
      ]
    }
  ]
}
