{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands-brigadier",
    "version": "1.21.3-mc2611",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.3-mc2611-mc26.1.jar",
          "url": "magicutils-commands-brigadier-1.21.3-mc2611-mc26.1.jar",
          "size": 22495,
          "sha512": "c843d09ae8f18792edcc71d80a31d92e849a108d990338f5d6a990e038cfc901f0e93f6cc7142ddbda6ee56ac3a368cf8dcfd80f637a4893b6201fdc7feef3c6",
          "sha256": "8eb0e32acaf2d27b498dd6ce9fc49f68df2ca59f491e7f2b534eca57746f268d",
          "sha1": "dc72494fde19642cc36b256a07930e201cf52691",
          "md5": "cd53f537dc0bb250a37f61bf085966c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.3-mc2611-mc26.1.jar",
          "url": "magicutils-commands-brigadier-1.21.3-mc2611-mc26.1.jar",
          "size": 22495,
          "sha512": "c843d09ae8f18792edcc71d80a31d92e849a108d990338f5d6a990e038cfc901f0e93f6cc7142ddbda6ee56ac3a368cf8dcfd80f637a4893b6201fdc7feef3c6",
          "sha256": "8eb0e32acaf2d27b498dd6ce9fc49f68df2ca59f491e7f2b534eca57746f268d",
          "sha1": "dc72494fde19642cc36b256a07930e201cf52691",
          "md5": "cd53f537dc0bb250a37f61bf085966c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.3-mc2611-sources.jar",
          "url": "magicutils-commands-brigadier-1.21.3-mc2611-sources.jar",
          "size": 8154,
          "sha512": "25f9dd6bed138735d89c5c631f16d9706c5aeaef73fd2f6be4b6c34d10bfe7c7915b5099946b5ef3f97c4000678c1fc3f691fd5c14e40c3fa1bcfb5414eb0a92",
          "sha256": "88be7c5f9e2f69a9aebcab3f464f144eca700f8317649f6fbf8a8686ae449ee6",
          "sha1": "0c17dbc0cb33d0b3a7d067480b123cead0c45f03",
          "md5": "57137a65b952bdc8d20269aed9abf9a0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.3-mc2611-javadoc.jar",
          "url": "magicutils-commands-brigadier-1.21.3-mc2611-javadoc.jar",
          "size": 4163457,
          "sha512": "ed5b832db8b60fbe5eef1b63ee59480567423f57ddfc75d969071b4f1296b27157b41bf3d184b8876d6be3ffc05031c71af85479b8943e8c3b842bd2cfae9971",
          "sha256": "5b1b98633dda2f750f04b65c5845e7754f11bb54f17db9bb063fc7683a674b54",
          "sha1": "38821e4b86c9aa9738d9ea156aea96820f0b6ed8",
          "md5": "e28caf75711f7fb4a6ae50c7d8b375ec"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.3-mc2611-all.jar",
          "url": "magicutils-commands-brigadier-1.21.3-mc2611-all.jar",
          "size": 3443208,
          "sha512": "70bb10e31430f27b60841983e3f5b2006f73736c996124d25919439ea7c532c99e6697174b061eb09e5ec38309ecd1328d74ffd81f5c338cf822e5b3d2d6b5ba",
          "sha256": "431d42d387610aa5b648dc10f3bbfd66a5813d820169443a2c0b1cc861254248",
          "sha1": "5a6fa7dc3e1c8d177e32ca02176ce416fd104a58",
          "md5": "f81a0ca621c6ff9db08dba397afd0e3f"
        }
      ]
    }
  ]
}
