{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bukkit",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.11.0-mc1.21.jar",
          "url": "magicutils-bukkit-1.11.0-mc1.21.jar",
          "size": 111777,
          "sha512": "8b060cbfa1427938d88a14426689779b4eaaf203fc27f87e7cc0b328cadcf7f8191f5f4bb18da74ec496847c413899cb716763f089c83ac617f3ffafda37a4fc",
          "sha256": "710212fd485a849ea24861925a3c573e3cdbeabf461a93449aea5e20aafff8d4",
          "sha1": "63ed1686c475ae4c478cd2a276a90f2b342d0960",
          "md5": "1554cd90e4b2b248110063302f04bfb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.11.0-mc1.21.jar",
          "url": "magicutils-bukkit-1.11.0-mc1.21.jar",
          "size": 111777,
          "sha512": "8b060cbfa1427938d88a14426689779b4eaaf203fc27f87e7cc0b328cadcf7f8191f5f4bb18da74ec496847c413899cb716763f089c83ac617f3ffafda37a4fc",
          "sha256": "710212fd485a849ea24861925a3c573e3cdbeabf461a93449aea5e20aafff8d4",
          "sha1": "63ed1686c475ae4c478cd2a276a90f2b342d0960",
          "md5": "1554cd90e4b2b248110063302f04bfb4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.11.0-sources.jar",
          "url": "magicutils-bukkit-1.11.0-sources.jar",
          "size": 50241,
          "sha512": "1e9bc7b85c7da97c27efbf70ea9769fc7f8493188e65c6e6042b9de45abe40052796df136831c59a9b1ed777e32976dcf3f0010a4359fa47a014549d9665b9af",
          "sha256": "98a7f8a865d75d8f4b982b3a5929392c3ce2fc1a8e23164ca4a9f7df19ce5d96",
          "sha1": "8321610482d965720bb0f7a013a86ef0be455bc3",
          "md5": "6be864ac0ad2279e442fd942f30b4b80"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.11.0-javadoc.jar",
          "url": "magicutils-bukkit-1.11.0-javadoc.jar",
          "size": 257734,
          "sha512": "9209bac180129c1b38cd6456067afada38d82847fc21d43115bc11db42ca408089ce3cb5ca333f25625f5b1b3076454a986516fbab15584af42fdede231e62c0",
          "sha256": "7867dc80e364c33503b0647b5fa10afe8b9e8858ab411b2d8c36c5d38514dfa6",
          "sha1": "16a61836ca6b6ac362ffdfd905b849c84a23fb1c",
          "md5": "1d31f0de41fb844ed6618259c593228b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.11.0-all.jar",
          "url": "magicutils-bukkit-1.11.0-all.jar",
          "size": 3465533,
          "sha512": "95795c53fdba95f2010dd521724ee9e0541b16ef3a0d45aba8363479b1f699615750372bc4700797c647c24525aa9a01aeb3c66011ed4cb726c7e7956684e4aa",
          "sha256": "d5d07ba8bf672d0d7d00b01d76ff1ce78840d86e09acfcff4b644056184207f8",
          "sha1": "e8b1bc09aa424f5dd0867842a6c4ce786651021e",
          "md5": "5662fea156e2db69105faeb8358c6280"
        }
      ]
    }
  ]
}
