{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bukkit",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.11.0-mc1.21.jar",
          "url": "magicutils-bukkit-1.11.0-mc1.21.jar",
          "size": 111776,
          "sha512": "2c015ea3551088c3e08feccb68851ad337a2b8a1a874e5e2b3312dab5050714603362cacbe0c93522af9513955fc7d0c01f405f3abbaa261786255620c4dd40c",
          "sha256": "3643e6c3b69649831a10462ee073c6622fb42f17bd0f8713199bc4de20a768a8",
          "sha1": "fb3c5b38bbb49f3e8e3c1f9a2ebe232dbbe22ce9",
          "md5": "bb3548433374e998f008839d8ca2afc9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.11.0-mc1.21.jar",
          "url": "magicutils-bukkit-1.11.0-mc1.21.jar",
          "size": 111776,
          "sha512": "2c015ea3551088c3e08feccb68851ad337a2b8a1a874e5e2b3312dab5050714603362cacbe0c93522af9513955fc7d0c01f405f3abbaa261786255620c4dd40c",
          "sha256": "3643e6c3b69649831a10462ee073c6622fb42f17bd0f8713199bc4de20a768a8",
          "sha1": "fb3c5b38bbb49f3e8e3c1f9a2ebe232dbbe22ce9",
          "md5": "bb3548433374e998f008839d8ca2afc9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.11.0-sources.jar",
          "url": "magicutils-bukkit-1.11.0-sources.jar",
          "size": 50241,
          "sha512": "1e9bc7b85c7da97c27efbf70ea9769fc7f8493188e65c6e6042b9de45abe40052796df136831c59a9b1ed777e32976dcf3f0010a4359fa47a014549d9665b9af",
          "sha256": "98a7f8a865d75d8f4b982b3a5929392c3ce2fc1a8e23164ca4a9f7df19ce5d96",
          "sha1": "8321610482d965720bb0f7a013a86ef0be455bc3",
          "md5": "6be864ac0ad2279e442fd942f30b4b80"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.11.0-javadoc.jar",
          "url": "magicutils-bukkit-1.11.0-javadoc.jar",
          "size": 257734,
          "sha512": "9209bac180129c1b38cd6456067afada38d82847fc21d43115bc11db42ca408089ce3cb5ca333f25625f5b1b3076454a986516fbab15584af42fdede231e62c0",
          "sha256": "7867dc80e364c33503b0647b5fa10afe8b9e8858ab411b2d8c36c5d38514dfa6",
          "sha1": "16a61836ca6b6ac362ffdfd905b849c84a23fb1c",
          "md5": "1d31f0de41fb844ed6618259c593228b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.11.0-all.jar",
          "url": "magicutils-bukkit-1.11.0-all.jar",
          "size": 3465531,
          "sha512": "42c4989151bccb0e00a7b27dd6b62a959421246688f6c8d933787a96331f3834f422a6b49efe0f838355ba01904791c1e9f447ba3c7ceeee6ff8635ee17f4242",
          "sha256": "93167b8a9aad01c8b976c5e92a448bfdc3e4699ce946093a202d4e7d61af24da",
          "sha1": "58a3b830c7fe457f46dbdd102bf589c069df1124",
          "md5": "e1c6bfb9b5743dba8c571a98e8d17aaa"
        }
      ]
    }
  ]
}
