{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bukkit",
    "version": "1.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.13.1-mc1.21.jar",
          "url": "magicutils-bukkit-1.13.1-mc1.21.jar",
          "size": 121224,
          "sha512": "beacd788aca8fffead3210c0d0a90f09a6e5359ab45d93358fe76606eac551621767592e5d59f02e19da91fa2c45a67ada3b7e193e51719e84e0c475601c13ee",
          "sha256": "03a5b62ed0eb25cf37b72c69bf72655a967d6d7ecd4d0d5ba6944e0b30fc01f3",
          "sha1": "59493f1d9d28cd77be734d1709dc410df5bf7eab",
          "md5": "8a7481a092dae9b60f5a920f1efc5eb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.13.1-mc1.21.jar",
          "url": "magicutils-bukkit-1.13.1-mc1.21.jar",
          "size": 121224,
          "sha512": "beacd788aca8fffead3210c0d0a90f09a6e5359ab45d93358fe76606eac551621767592e5d59f02e19da91fa2c45a67ada3b7e193e51719e84e0c475601c13ee",
          "sha256": "03a5b62ed0eb25cf37b72c69bf72655a967d6d7ecd4d0d5ba6944e0b30fc01f3",
          "sha1": "59493f1d9d28cd77be734d1709dc410df5bf7eab",
          "md5": "8a7481a092dae9b60f5a920f1efc5eb2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.13.1-sources.jar",
          "url": "magicutils-bukkit-1.13.1-sources.jar",
          "size": 52423,
          "sha512": "8ab2f2246b046c0e7c09aa08aaa4c2865a1cf65fdb25fb9ced1a61c3271761a3094a2c424cfc84461d1c68f1143fd55c0a0e58774dd081c781a000cacbb81372",
          "sha256": "6a1a5f3950897a3671fa7a7cff269925e45c7de3861179386cefafbcf79f83ec",
          "sha1": "7f0f24ac666ddb9927a82421f51872eb0a20a8fb",
          "md5": "0f9c8780418dfbd8acf41c16fbdf31e0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.13.1-javadoc.jar",
          "url": "magicutils-bukkit-1.13.1-javadoc.jar",
          "size": 266068,
          "sha512": "94a908df83b1e4b461603ab1acf237e5a57febeed4379979af86f18020d69816df4f7a185aa705ea3c63fe00710b602ba27e2563a54adaaf1bbaafe88cd2d7dd",
          "sha256": "3d2da340b13293c3f9a014a7002131115035f350c57acf1e5b00e7a831b0e3c2",
          "sha1": "acf5c201f6a2169ed8ef24869809d720ab808034",
          "md5": "b4c59998f3b4600eb716c96c5906a42d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.13.1-all.jar",
          "url": "magicutils-bukkit-1.13.1-all.jar",
          "size": 3522597,
          "sha512": "55362c302ec975599681c8b1f3332babe508fb9059d2ee03970989e8ddcc0fafb7905b7ac38855cc76b723f630a4e2b98b13f4b3d60d2673b7cec2612322382f",
          "sha256": "90c02b781eb11b9ea83402ce0d3cdca53752dd9d79bc718deb4fba3f0b9439bc",
          "sha1": "e491ad8bb79c2f1b02c317d8477f1740ba758cd5",
          "md5": "2dcd6b82672db5b2922353534d436591"
        }
      ]
    }
  ]
}
