{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bukkit",
    "version": "1.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.13.1-mc1.21.jar",
          "url": "magicutils-bukkit-1.13.1-mc1.21.jar",
          "size": 121231,
          "sha512": "1428b00c66de18bba4415984d493629cc2a8d13a124b5438115f465adee85f44fb333c63912027b62c24b4dc4352fa56bfd7c10cf110c3220c0cd272e562045f",
          "sha256": "ce2ab4b58f6a65bc35ad3e68a88293fc78d64b65a847a79467fb575396d2ccfa",
          "sha1": "a27f7a1204ea24667b72ef8011ec61cfb63f1d7a",
          "md5": "cfd4cc7918970f1eaf5a4029475637b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.13.1-mc1.21.jar",
          "url": "magicutils-bukkit-1.13.1-mc1.21.jar",
          "size": 121231,
          "sha512": "1428b00c66de18bba4415984d493629cc2a8d13a124b5438115f465adee85f44fb333c63912027b62c24b4dc4352fa56bfd7c10cf110c3220c0cd272e562045f",
          "sha256": "ce2ab4b58f6a65bc35ad3e68a88293fc78d64b65a847a79467fb575396d2ccfa",
          "sha1": "a27f7a1204ea24667b72ef8011ec61cfb63f1d7a",
          "md5": "cfd4cc7918970f1eaf5a4029475637b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.13.1-sources.jar",
          "url": "magicutils-bukkit-1.13.1-sources.jar",
          "size": 52423,
          "sha512": "8ab2f2246b046c0e7c09aa08aaa4c2865a1cf65fdb25fb9ced1a61c3271761a3094a2c424cfc84461d1c68f1143fd55c0a0e58774dd081c781a000cacbb81372",
          "sha256": "6a1a5f3950897a3671fa7a7cff269925e45c7de3861179386cefafbcf79f83ec",
          "sha1": "7f0f24ac666ddb9927a82421f51872eb0a20a8fb",
          "md5": "0f9c8780418dfbd8acf41c16fbdf31e0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.13.1-javadoc.jar",
          "url": "magicutils-bukkit-1.13.1-javadoc.jar",
          "size": 266089,
          "sha512": "b8968fe61ef93989ea46428c8da9e7dbc0cf6e7288957fbe0bffe05bd98ffb00352606edb215f660f86a911178acdb2dd6b506b898e4422fa933d431c87a24eb",
          "sha256": "66fd633da58828da91f58a28b74f155e3e052f7a007558e3da7446c50b80b800",
          "sha1": "21742a42380301320839742053c0165ee796fd74",
          "md5": "a058d39eb4d90bfe99157f8acfde249a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.13.1-all.jar",
          "url": "magicutils-bukkit-1.13.1-all.jar",
          "size": 3526068,
          "sha512": "9a74b144d3102a3e34e91bfde1b299470baf75b5226800d63ce6fd9e7e1f10a0b1a1720e89d70e5bd0ab7f9940160df6796f67f02ed52cf3fdf6059c691f5029",
          "sha256": "60248392a01f88a16c592cb0fced1619f8dc4e913b690809d125c7ede1cddf47",
          "sha1": "c92cc55363a107264455d06aa4a13572858f12a2",
          "md5": "f7f6943e6f47e449410a67bc0cb4673c"
        }
      ]
    }
  ]
}
