{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-http-client",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.12.0-mc1.21.jar",
          "url": "magicutils-http-client-1.12.0-mc1.21.jar",
          "size": 45021,
          "sha512": "9f2b5822a1745c59e9b417b3943f43423c41509469eec9b15b267e1b66149d1adbae55a41341678785607ca65c2105d4431b848f44c51425c1277ae71abe43c0",
          "sha256": "ef18a1973fb1686f1b0f514906cd0e7f4528513b183a796e8eccb5e6a9fa3bdb",
          "sha1": "2dcb7c3e8a3df7ab2b06bf04efa999a9c132edf9",
          "md5": "6da95e1a5691efc8c9210f6da8ab3825"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.12.0-mc1.21.jar",
          "url": "magicutils-http-client-1.12.0-mc1.21.jar",
          "size": 45021,
          "sha512": "9f2b5822a1745c59e9b417b3943f43423c41509469eec9b15b267e1b66149d1adbae55a41341678785607ca65c2105d4431b848f44c51425c1277ae71abe43c0",
          "sha256": "ef18a1973fb1686f1b0f514906cd0e7f4528513b183a796e8eccb5e6a9fa3bdb",
          "sha1": "2dcb7c3e8a3df7ab2b06bf04efa999a9c132edf9",
          "md5": "6da95e1a5691efc8c9210f6da8ab3825"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.12.0-sources.jar",
          "url": "magicutils-http-client-1.12.0-sources.jar",
          "size": 15923,
          "sha512": "f94308c9a11823ed642b23c58eabf6f2b3fd412df717a8f1b0524beb6b7e38e0af2386b04a087059b395573621600b5ecd90c3f6f34242f08794584f91dd3268",
          "sha256": "6c0091e5e03df301b370e3c0c32e6c627c0f264f7e291d79226602807f022ab9",
          "sha1": "09b39d895fd5d57c736c8350ccc1b183958fb57d",
          "md5": "d72ecaf7a924a29ca1e503d97e08c1f2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.12.0-javadoc.jar",
          "url": "magicutils-http-client-1.12.0-javadoc.jar",
          "size": 132323,
          "sha512": "663b8b7fe391f1806b16f2b2c25bf93229d8fca927e231a89f2b661c6532ff7b2c0afa2968c1f3a94accd4688cc4d95baec928e086c91d897a63eddc1c2d7923",
          "sha256": "0683aad19c7f09f8d3dc95d0a30042f9a1565ed3418843192d12aeb3eb32b921",
          "sha1": "add9acc3264ffcede0d3efe3b4dcaac8e0769cbc",
          "md5": "8dd8dc42f441c80141a140bcd87ec517"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.12.0-all.jar",
          "url": "magicutils-http-client-1.12.0-all.jar",
          "size": 2916093,
          "sha512": "87ba514a04a2590efefa55ddcf7076558f90c4c49d32e20e1b401fed49c6ca05bb0ec7fdc4d514eb5625dd544d93fb41642a1fb84b86a637566bb4bb1b93d62a",
          "sha256": "c828f78e2909820a3f5f6550845503c56e1b758181574626734edc3b438532e3",
          "sha1": "0a4e131b75cf48ea0c37f7f285e9cc0b2129e2d9",
          "md5": "2681e39c40c75e1604b068f75e4fdc21"
        }
      ]
    }
  ]
}
