{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-placeholders",
    "version": "1.19.1-mc2611",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.19.1-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-placeholders-1.19.1-mc2611-mc26.1.jar",
          "url": "magicutils-placeholders-1.19.1-mc2611-mc26.1.jar",
          "size": 17877,
          "sha512": "e7e273d4ba092c41aa699c99a69601cd2017751a2967b57696263ade91d7916d0acf1fc18f2d7b7cbd9a40b3e63c9ccfd941c6db21e3da30a1db191d6b324bca",
          "sha256": "399d8f62460c69a2cfd076405406fa9ccbafdcd4a499bb722f74ae1e964d93b7",
          "sha1": "fbf34fd6ea28639e3f40e5a6e4282cf04d277c2c",
          "md5": "25cd2012eda5f2f805b86235f56b8d8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.19.1-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-placeholders-1.19.1-mc2611-mc26.1.jar",
          "url": "magicutils-placeholders-1.19.1-mc2611-mc26.1.jar",
          "size": 17877,
          "sha512": "e7e273d4ba092c41aa699c99a69601cd2017751a2967b57696263ade91d7916d0acf1fc18f2d7b7cbd9a40b3e63c9ccfd941c6db21e3da30a1db191d6b324bca",
          "sha256": "399d8f62460c69a2cfd076405406fa9ccbafdcd4a499bb722f74ae1e964d93b7",
          "sha1": "fbf34fd6ea28639e3f40e5a6e4282cf04d277c2c",
          "md5": "25cd2012eda5f2f805b86235f56b8d8c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-placeholders-1.19.1-mc2611-sources.jar",
          "url": "magicutils-placeholders-1.19.1-mc2611-sources.jar",
          "size": 7370,
          "sha512": "6ca047e63ff109127ca4d04c8cb3eb30fae2e48ff422ba9b8346479427ffe29d2c1514b4a3227ec09b2978acf81bf72a72305580fb9ee22c02ad9bace12b183a",
          "sha256": "3b8210282b46b06732a9febb7c21c84a6c2da06bc48218455d25a24eb20cd272",
          "sha1": "f94ae8c1bf477eb39ee3f978c683b420249545dc",
          "md5": "c24c7817acb07ecc60c3bbd58f314cc1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-placeholders-1.19.1-mc2611-javadoc.jar",
          "url": "magicutils-placeholders-1.19.1-mc2611-javadoc.jar",
          "size": 4178859,
          "sha512": "0c4bda54118572948009ead37a081d4311984a91b9880104bb1587d8c93ff49d9f35a97136b204f417fb38f8298e203b3efa200e200758216f928184fcfeb3e7",
          "sha256": "27d68fa543ae1d8e7b3fd06a6bc46af0bab25e7f875a4e6574302d21791cea50",
          "sha1": "e15ddd03298c4e9206ed9362662bfe5a7eeefed4",
          "md5": "d8c3a1b641ab26103eccd916fcc65d62"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-placeholders-1.19.1-mc2611-all.jar",
          "url": "magicutils-placeholders-1.19.1-mc2611-all.jar",
          "size": 526194,
          "sha512": "cc4e5fba15c289d1f8014c7bed658e99167230a1f2df35ba0b9631a043060f5d60dcdb6d22ea55d55760fb4e80808848415512eb47d2492320608d7ee25f4bd7",
          "sha256": "fc22402579ef1c579261896d1e68a3ea8b40c935e2368edff468742acdee9cdd",
          "sha1": "86525bb8d667478016ca52067abddea425dd53ab",
          "md5": "95bac265b3791c4c5edd9eedc1712616"
        }
      ]
    }
  ]
}
