{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bukkit",
    "version": "1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.21.1-mc1.21.jar",
          "url": "magicutils-bukkit-1.21.1-mc1.21.jar",
          "size": 137437,
          "sha512": "8094b177afd7f23d715719c45692217a11128ab7d7ba1c3f233332a9879772060a38d5bf026051f3f05d5a14efc3e06df283a9dd04591297b81d59b24c1765b8",
          "sha256": "8e2a8a77ccb42660f9b9a4f9ac4ac264db9f57e6485577ea1e4f2abe0ba3b6da",
          "sha1": "33aa0a379d624e1e19cc9893f140ccd7dbe885bc",
          "md5": "f7f72d305af73b5d17cdc2d0e5d25cd1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.21.1-mc1.21.jar",
          "url": "magicutils-bukkit-1.21.1-mc1.21.jar",
          "size": 137437,
          "sha512": "8094b177afd7f23d715719c45692217a11128ab7d7ba1c3f233332a9879772060a38d5bf026051f3f05d5a14efc3e06df283a9dd04591297b81d59b24c1765b8",
          "sha256": "8e2a8a77ccb42660f9b9a4f9ac4ac264db9f57e6485577ea1e4f2abe0ba3b6da",
          "sha1": "33aa0a379d624e1e19cc9893f140ccd7dbe885bc",
          "md5": "f7f72d305af73b5d17cdc2d0e5d25cd1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.1-sources.jar",
          "url": "magicutils-bukkit-1.21.1-sources.jar",
          "size": 59830,
          "sha512": "53e94fae59db7a9ebf65137b8ab321bcb4fae0282d6e06f1e2715580cbf1c5cb80b6b845d63771353f9485b432e9d4b2358fb07a1a1957d0a985a436d983699b",
          "sha256": "31accedcce4e0028bd11fc4b8fe9cc11c181b83840e5bec49937a7324e04cfc3",
          "sha1": "4ff8c65cc052f02986d54ce44a2591b8e1d80845",
          "md5": "ae938ea6f30d022ce01b5d70d389df39"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.1-javadoc.jar",
          "url": "magicutils-bukkit-1.21.1-javadoc.jar",
          "size": 286561,
          "sha512": "0499515bb9c19d38c2d0e66158f8074973b95c2e0e7ee811949b72cba96a06a3f0ecae47e01826ab2654757063e306bc8be8c4213412fd8a9ae62b9b612f57e1",
          "sha256": "29d28b6b692d62581cac0005207cc76e02e54e107919be1edd9d44d04212e86c",
          "sha1": "1320c8b7b0370422f17d226fcf8db172d5d627b9",
          "md5": "19789c34e2113f77203557fbd04e9e39"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.1-all.jar",
          "url": "magicutils-bukkit-1.21.1-all.jar",
          "size": 3639419,
          "sha512": "dd88ac00ecc216246f973f3ab0f5ace995aecc30dcad9ea436da41dffd26c46ae5806e0ee172ffbacf2e663abcf77be9789a27d0a738a6e5e7e1f9438e7b53c8",
          "sha256": "86d8f611b270ff855c93a9fb3403365a169850df68765d8528605c26b345e970",
          "sha1": "823fd511249753510757e1d72c21e7c3b363e37e",
          "md5": "10aeb229fd83f10a86a4a892546f260c"
        }
      ]
    }
  ]
}
