{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-velocity",
    "version": "1.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-velocity-1.13.1-mc1.21.jar",
          "url": "magicutils-velocity-1.13.1-mc1.21.jar",
          "size": 37790,
          "sha512": "fb67e23de2e029a3b1857c3583c045cdf53dd501283678da5b2e0d38a6d1025dd2a944a29944f55420046c3afab6addf8596e85dd381bd05c86119ee8e60ce06",
          "sha256": "77fcd84e7caf91eae1c2fd2812772804b94dcce2da6298724c006707a23840e0",
          "sha1": "7ec96645308d185606fea9a60d7c4675a8f7debb",
          "md5": "6a9f01c4b2d1d68fac2d241c6fa0e038"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-velocity-1.13.1-mc1.21.jar",
          "url": "magicutils-velocity-1.13.1-mc1.21.jar",
          "size": 37790,
          "sha512": "fb67e23de2e029a3b1857c3583c045cdf53dd501283678da5b2e0d38a6d1025dd2a944a29944f55420046c3afab6addf8596e85dd381bd05c86119ee8e60ce06",
          "sha256": "77fcd84e7caf91eae1c2fd2812772804b94dcce2da6298724c006707a23840e0",
          "sha1": "7ec96645308d185606fea9a60d7c4675a8f7debb",
          "md5": "6a9f01c4b2d1d68fac2d241c6fa0e038"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.13.1-sources.jar",
          "url": "magicutils-velocity-1.13.1-sources.jar",
          "size": 14472,
          "sha512": "2c6e73d3c64772955ed93d62fae444e3963a952259b23d3bd4d04cc67594718b1521b8ad349653c6061a63ebc9e3f27b79a9757c3a3f339492e6cc01903ae2b2",
          "sha256": "78b9c23df836a9a30ee9dd3990ac44fd159b8d3108496a2ff529746ad2b5e119",
          "sha1": "140937875c79a420cc3ef9e26f4a88395f90c6f0",
          "md5": "0eae995590fde4b68119536a42336d6c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.13.1-javadoc.jar",
          "url": "magicutils-velocity-1.13.1-javadoc.jar",
          "size": 128589,
          "sha512": "024d0c7c3323cbddef04f0ef7ef91ef2aeedddac66ad3e7addf826b38f7cb4ce162cb29ce82e51546406a47e406338cc1a341a9bc479d54e8ef8583bc4a62e31",
          "sha256": "799754aff7908a525dbc2e112395f614181eea4c4a041aae5521e9b6c2b63658",
          "sha1": "b9606c352204d283efde6b4c8cf43dca87e589b5",
          "md5": "2463533f523ae3eecae743cc20432fdb"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.13.1-all.jar",
          "url": "magicutils-velocity-1.13.1-all.jar",
          "size": 3439247,
          "sha512": "e736ce9e43f1d1e82aaa613247288f8999a8b351d4837e98961d7fb4daee95eaa68bf5c1398f2510a07bba143236a8721fc04248c4adba9d708088bb84299f1c",
          "sha256": "f040ed85c9a6a71fb2f0603a763f6fd9ec1ea14bce1e7abed0893662140a00d6",
          "sha1": "84eea40a98872a3080f32a911b445f2e0a3e2ffa",
          "md5": "5666cdf008593857cb4da4c634c2e5b5"
        }
      ]
    }
  ]
}
