{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-velocity",
    "version": "1.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-velocity-1.13.1-mc1.21.jar",
          "url": "magicutils-velocity-1.13.1-mc1.21.jar",
          "size": 37735,
          "sha512": "2e025bc21422a6b4931e315a7fa52967e4f251168f1138b1d42039a6f0fd53077f3c4f144172f9e81903b9313126fede674f6fc35c11f38638c2d710a9029334",
          "sha256": "5191a45f59c7da226e2d687db08d3da13ae83a55532c398fdab89726fb5ec875",
          "sha1": "ed39ed3d489934da4f36cf362e92e113d475748c",
          "md5": "b8236b519bba19e8c8ffc4afa29594e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-velocity-1.13.1-mc1.21.jar",
          "url": "magicutils-velocity-1.13.1-mc1.21.jar",
          "size": 37735,
          "sha512": "2e025bc21422a6b4931e315a7fa52967e4f251168f1138b1d42039a6f0fd53077f3c4f144172f9e81903b9313126fede674f6fc35c11f38638c2d710a9029334",
          "sha256": "5191a45f59c7da226e2d687db08d3da13ae83a55532c398fdab89726fb5ec875",
          "sha1": "ed39ed3d489934da4f36cf362e92e113d475748c",
          "md5": "b8236b519bba19e8c8ffc4afa29594e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.13.1-sources.jar",
          "url": "magicutils-velocity-1.13.1-sources.jar",
          "size": 14462,
          "sha512": "21babaf90f154ea93600c91c5e5a50c4d96decd50d78d60b208a2736fb4cc5568d8413ef53dac19777210c91c273c42d233eb4c0904c4ddd948dfc5eee0959e1",
          "sha256": "42e96486f667fab3176ead16cb1cad3556c524992fa6c844de59237021b2ee11",
          "sha1": "359f9a182eaa0ce86569ba95aab224bce87c1cb2",
          "md5": "dc7ed239578ac344c8a692d68e6b965e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.13.1-javadoc.jar",
          "url": "magicutils-velocity-1.13.1-javadoc.jar",
          "size": 128589,
          "sha512": "024d0c7c3323cbddef04f0ef7ef91ef2aeedddac66ad3e7addf826b38f7cb4ce162cb29ce82e51546406a47e406338cc1a341a9bc479d54e8ef8583bc4a62e31",
          "sha256": "799754aff7908a525dbc2e112395f614181eea4c4a041aae5521e9b6c2b63658",
          "sha1": "b9606c352204d283efde6b4c8cf43dca87e589b5",
          "md5": "2463533f523ae3eecae743cc20432fdb"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.13.1-all.jar",
          "url": "magicutils-velocity-1.13.1-all.jar",
          "size": 3442656,
          "sha512": "18e0403aa74afef73d964e2063debc8f9237566c4a7463c0f6fcef834252fd09d61307040ffc6885df967c58c57803d681ac79f3d4291a1cbb1a12036b781a41",
          "sha256": "e9b6b2479d11e67e0afdd1b120f26458f69e3d9e7665fb2a5ce5cf31ea77a63d",
          "sha1": "c2bc7b6f827c671a59b9bd022eb74822ebbada65",
          "md5": "6187dfd5e65461459ed742b96dbaffe1"
        }
      ]
    }
  ]
}
