{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands-brigadier",
    "version": "1.21.1-mc1201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.1-mc1201-mc1.20.jar",
          "url": "magicutils-commands-brigadier-1.21.1-mc1201-mc1.20.jar",
          "size": 22466,
          "sha512": "14fc27c123ed8000d3368b304bfe8956070b5e72d00087d75138ffdafccd9c709a32ad05804a8798fc2b6d85a7a527892930528075b1d6c29ffa48e12f35af6b",
          "sha256": "45d13fc110e21059014e2f7b0e06e8b179bc08e9975d1c29466d381cbe8a33da",
          "sha1": "e99d0dda729aa11fcbd4286e67aeb7428cba9c5a",
          "md5": "31e8b4de5680e42d0ae24dd2d62c1f15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.1-mc1201-mc1.20.jar",
          "url": "magicutils-commands-brigadier-1.21.1-mc1201-mc1.20.jar",
          "size": 22466,
          "sha512": "14fc27c123ed8000d3368b304bfe8956070b5e72d00087d75138ffdafccd9c709a32ad05804a8798fc2b6d85a7a527892930528075b1d6c29ffa48e12f35af6b",
          "sha256": "45d13fc110e21059014e2f7b0e06e8b179bc08e9975d1c29466d381cbe8a33da",
          "sha1": "e99d0dda729aa11fcbd4286e67aeb7428cba9c5a",
          "md5": "31e8b4de5680e42d0ae24dd2d62c1f15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.1-mc1201-sources.jar",
          "url": "magicutils-commands-brigadier-1.21.1-mc1201-sources.jar",
          "size": 8154,
          "sha512": "25f9dd6bed138735d89c5c631f16d9706c5aeaef73fd2f6be4b6c34d10bfe7c7915b5099946b5ef3f97c4000678c1fc3f691fd5c14e40c3fa1bcfb5414eb0a92",
          "sha256": "88be7c5f9e2f69a9aebcab3f464f144eca700f8317649f6fbf8a8686ae449ee6",
          "sha1": "0c17dbc0cb33d0b3a7d067480b123cead0c45f03",
          "md5": "57137a65b952bdc8d20269aed9abf9a0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.1-mc1201-javadoc.jar",
          "url": "magicutils-commands-brigadier-1.21.1-mc1201-javadoc.jar",
          "size": 96661,
          "sha512": "10515ce24a34fe18d8ad8d25d1336bed1b5d075dbce62f0534e0388c23972126bfc670f0fd9dd4f048213da80d1c4ff43b9d8d248c32be34a3b2edd4d6ba3fcb",
          "sha256": "832b8d3a82d1be46b0797a7a3d03c435e07282386085e95e04d887f20d201433",
          "sha1": "b16b147fa5f986ad5b51993ab884b00c283d7a02",
          "md5": "4e7e240927fc788edcc9e08bbb3e149a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.1-mc1201-all.jar",
          "url": "magicutils-commands-brigadier-1.21.1-mc1201-all.jar",
          "size": 3442855,
          "sha512": "4aaadbe0f67bcf755742a230ea3bab6df8f0bedaebf7c5974b257935e2d609c585bf510e64022b09ab4dc91b1b11e969585dc255a0cceb17de10338f49fa11c4",
          "sha256": "9c553562e586a65925540b38765f8893b34915d0df6a7b479b810dd16931c292",
          "sha1": "81102290f0acb986a1fe8dbc553ac1230560df09",
          "md5": "13fb623c5d894d8a2d3e8164bdc43863"
        }
      ]
    }
  ]
}
