{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-1.13.0-mc1.21.jar",
          "url": "magicutils-commands-1.13.0-mc1.21.jar",
          "size": 149633,
          "sha512": "88f3b4bd031cea1a7860283271ef81184ddc7a611e09b8858a1b5e25773b53871262ebad9719ac136ba6791ff885096354a9e54fbf64ea17dcc69a928ad6f7de",
          "sha256": "943c7b97ea3101bf1146f38d3d06f15bfe9245717d3f0fb0f0f5954126a0b5e9",
          "sha1": "b40fbffadddce33889cb53028af1b8019f85e3a1",
          "md5": "4d843a636121828e75fb7aa8f03d98ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-1.13.0-mc1.21.jar",
          "url": "magicutils-commands-1.13.0-mc1.21.jar",
          "size": 149633,
          "sha512": "88f3b4bd031cea1a7860283271ef81184ddc7a611e09b8858a1b5e25773b53871262ebad9719ac136ba6791ff885096354a9e54fbf64ea17dcc69a928ad6f7de",
          "sha256": "943c7b97ea3101bf1146f38d3d06f15bfe9245717d3f0fb0f0f5954126a0b5e9",
          "sha1": "b40fbffadddce33889cb53028af1b8019f85e3a1",
          "md5": "4d843a636121828e75fb7aa8f03d98ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.13.0-sources.jar",
          "url": "magicutils-commands-1.13.0-sources.jar",
          "size": 67258,
          "sha512": "2ac26905b2ab8a0380ff1aff3488f0cc9c889ddf85fa45f41a66259dde06359a19e678dc573af3b217af1c5f70fa7c52ec9b5d9b7abe5f270c554e1c8f1894ef",
          "sha256": "bb7d733f19bbc2c832eee3cc66456fa3446916a39d601489b0369bd896e3c229",
          "sha1": "e7f83ea668101586fae9ba53ea513bfce53e6934",
          "md5": "967c7acdf2eaeed7c266066bfcabace7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.13.0-javadoc.jar",
          "url": "magicutils-commands-1.13.0-javadoc.jar",
          "size": 267369,
          "sha512": "07f83f7799bc0c25368b83f0af1af46e183c8511fde26db33c3f4ce9d41ab41db0a7ef664f58766f0389f9b34fb042e48cb801362ce63d2b941d1d5ce56248df",
          "sha256": "82b0af70328d5f9515ee1641d9644ba3b9687e631953aa5a59e5447707ceb7d8",
          "sha1": "6ee683d6350e973320b51cdc232e885881c82333",
          "md5": "93071e4a2ba6b2a0ff752a9799aa529d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.13.0-all.jar",
          "url": "magicutils-commands-1.13.0-all.jar",
          "size": 3359378,
          "sha512": "1c8df5e37f86fe3503ba23eed913a25d44e0710735e8e0e09a18ef21c7a0ede7b0684ac4078dbe62ac1b8355bf93a0d91911fba96d527da6bafc489660fb0b6e",
          "sha256": "7b7fc208a22d54b5a182c8f5a106e788b6028429a39080e089df426b26e4dd97",
          "sha1": "2267aac81d70237dacc97eebf2ecd68d315e3b8e",
          "md5": "d53a595808306151f4c09c494a59d66f"
        }
      ]
    }
  ]
}
