{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-neoforge",
    "version": "1.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.17.0-mc1.21.jar",
          "url": "magicutils-neoforge-1.17.0-mc1.21.jar",
          "size": 14913,
          "sha512": "08a6eb075099bee13b1141e6be355d96d18f77f60ade237a78fd6c5cc8bd61c995b05ed989a2229d842abcf4041be6cce0774d2140b25e2c1db21d88ce4c48da",
          "sha256": "9d737a1758b9003d3bd98bc2aef6a51506ef42f1727f1cfd686bd541c8228c84",
          "sha1": "bcad89feb61d3947ffb1c68ab03a69ce024355ea",
          "md5": "8be12cb734b8996590e50509869c5be8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.17.0-mc1.21.jar",
          "url": "magicutils-neoforge-1.17.0-mc1.21.jar",
          "size": 14913,
          "sha512": "08a6eb075099bee13b1141e6be355d96d18f77f60ade237a78fd6c5cc8bd61c995b05ed989a2229d842abcf4041be6cce0774d2140b25e2c1db21d88ce4c48da",
          "sha256": "9d737a1758b9003d3bd98bc2aef6a51506ef42f1727f1cfd686bd541c8228c84",
          "sha1": "bcad89feb61d3947ffb1c68ab03a69ce024355ea",
          "md5": "8be12cb734b8996590e50509869c5be8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.17.0-sources.jar",
          "url": "magicutils-neoforge-1.17.0-sources.jar",
          "size": 8372,
          "sha512": "f2373ab50691b7ac1e0353b5a9b7f689d797c2102412120359dddb63661ed0c86b61b9f8649cee22d1c8ded1e4007038929195ba1d7e13524c353ffeaf65bcfc",
          "sha256": "9e430214db30cf121ae00c2445f83ac4a849de2e15d3222e3faab89f616ebf67",
          "sha1": "ed1167f081ee1e685090da02d64089ad2152cc29",
          "md5": "8300dad78e7e71c590451f704f23ff13"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.17.0-javadoc.jar",
          "url": "magicutils-neoforge-1.17.0-javadoc.jar",
          "size": 114915,
          "sha512": "0448dcb10bcb4588021fdf8e9951e054a6d3e663e35212461e83aa7868766d7cb52e72d0fc5590482049f0f2bf3fc05e7667e65fdf66faadb8b64163b619cc10",
          "sha256": "a6277d797c02a14569999bf7bdbe85a079d7862f8afdc412701e7b25d72c95e3",
          "sha1": "4ad9dda97ff2f06c79d3e300ff2736e617618b32",
          "md5": "501fec35f2da6bc8be77ef20347f1546"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.17.0-all.jar",
          "url": "magicutils-neoforge-1.17.0-all.jar",
          "size": 40353141,
          "sha512": "2f1a993d830e4e8d78c7cda863b39aa8824e12e350d87f6f4e958ee714315d3ac5c1c468eaa7328d34633d639a41a5f66e23b2148bd5480f509759b383cabd97",
          "sha256": "55576cd2b581ee76f2bfc1f56fd224f8ea328c24e7a5f0a14e0d4db5d68db9e2",
          "sha1": "f0527da18a39f1f1c0ba026bd88b128d1aebf702",
          "md5": "4722c57c0887891c351202374e5cb6ce"
        }
      ]
    }
  ]
}
