{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-lang",
    "version": "1.21.5-mc2611",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.5-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.21.5-mc2611-mc26.1.jar",
          "url": "magicutils-lang-1.21.5-mc2611-mc26.1.jar",
          "size": 51897,
          "sha512": "2a5d4c15700a38f19a54737ebc77ec448f192960927065557a8ab67888349d45a9790e5614dddbee0deacf2bc13fc57c45b9e90171b65b540e98e16f6ca157fa",
          "sha256": "d6901dce2b5511a995fd208958848abaa4b406a36217c6407a56613283381f51",
          "sha1": "39e487526d621a6787c3464d8356782cf989f1aa",
          "md5": "7c307dc755e5a63c79d23a3fb3f0a564"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.5-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.21.5-mc2611-mc26.1.jar",
          "url": "magicutils-lang-1.21.5-mc2611-mc26.1.jar",
          "size": 51897,
          "sha512": "2a5d4c15700a38f19a54737ebc77ec448f192960927065557a8ab67888349d45a9790e5614dddbee0deacf2bc13fc57c45b9e90171b65b540e98e16f6ca157fa",
          "sha256": "d6901dce2b5511a995fd208958848abaa4b406a36217c6407a56613283381f51",
          "sha1": "39e487526d621a6787c3464d8356782cf989f1aa",
          "md5": "7c307dc755e5a63c79d23a3fb3f0a564"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.21.5-mc2611-sources.jar",
          "url": "magicutils-lang-1.21.5-mc2611-sources.jar",
          "size": 31450,
          "sha512": "a34c0b43bdd6a6f20f2cf9522a5565a280ca57866cca6337715f6ecd7bfb1e379f01f3739b3b2278a7635a1103357e0b0cfc3fc7cd352957ba5caf8a215aaf2d",
          "sha256": "64ed562273ae171839ee732e268f23e740f3df2be2ce55f5b9e904aadee233de",
          "sha1": "efdc4adc4a48166c249dd6bac8abd6d0f2a99088",
          "md5": "5d2385ce895fe432310a5e91b07fc26a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.21.5-mc2611-javadoc.jar",
          "url": "magicutils-lang-1.21.5-mc2611-javadoc.jar",
          "size": 4211678,
          "sha512": "eb93a0e3b4b7d1585e19e93878c18ccc44d654f9e54ff6c13340a87bc4d4708da125cefa6e174e5537a7d8e35a7ac328ea1a5e5c95d4080124e7819ff9a72bf0",
          "sha256": "fa1dd4bcb2db59ee24e820c5a196898b1ee1fd97f7f08d1ea40adcaed016764b",
          "sha1": "7140f54341ff5f44f08fe4cc11de904c8ca79ca7",
          "md5": "fe24449d745fe6273969b60519a6a047"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.21.5-mc2611-all.jar",
          "url": "magicutils-lang-1.21.5-mc2611-all.jar",
          "size": 3202006,
          "sha512": "bc0a0a113eb022556cb41e4d3dd177d579c4b0f92d4a29c3d82c5904aa8450f7e24cab836251618b23d232bea74a1b45139e992457c3b17b78a44f6c5971ef8e",
          "sha256": "d468379a217ae4b2c59835893b20ce7283be2a966a802ade6606e9c7696391fd",
          "sha1": "8829c38306270a79381d9fb353b4a09f9e1d167e",
          "md5": "b25609e95025a672cd807e92a85f3e2b"
        }
      ]
    }
  ]
}
