{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-logger",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.10.0.jar",
          "url": "magicutils-logger-1.10.0.jar",
          "size": 77452,
          "sha512": "785b4aa6232be2deb3a9c58da55c3fdfc58b678a7293eaf7d70f8d8b5ea7fe7635db125c57ca9d3f6532c4d00e877b929a77d6ea6d3a05c0b1a6a50ad35726f2",
          "sha256": "a2dfdbd2a6e4ebfd9e6dd783d255ecd92e05bb8e8c30ef93d7d2d039ed6c9f43",
          "sha1": "61aad5562c2fcdd07c295f0669cd8c5643b7c9ad",
          "md5": "dab8cc5e7c47793822a7d29c606ea826"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.10.0.jar",
          "url": "magicutils-logger-1.10.0.jar",
          "size": 77452,
          "sha512": "785b4aa6232be2deb3a9c58da55c3fdfc58b678a7293eaf7d70f8d8b5ea7fe7635db125c57ca9d3f6532c4d00e877b929a77d6ea6d3a05c0b1a6a50ad35726f2",
          "sha256": "a2dfdbd2a6e4ebfd9e6dd783d255ecd92e05bb8e8c30ef93d7d2d039ed6c9f43",
          "sha1": "61aad5562c2fcdd07c295f0669cd8c5643b7c9ad",
          "md5": "dab8cc5e7c47793822a7d29c606ea826"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.10.0-all.jar",
          "url": "magicutils-logger-1.10.0-all.jar",
          "size": 3179978,
          "sha512": "1b7652d4cf52a3a97eca586d0ebe3480e27a59c0128fda657209395878f541bf6f2cfcc16f9d2fffd22f370d75b3196893d4e6bc71ffc39d0c73258766ac0214",
          "sha256": "5e3a197f3b6e4aed702e679d43beb5e300bf5749510a119d45b8888a7d960220",
          "sha1": "b5652d47fba63bf5dcc4c83933e65ddddc218c7c",
          "md5": "721e4e7fa852163547f371d86e535fd8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.10.0-sources.jar",
          "url": "magicutils-logger-1.10.0-sources.jar",
          "size": 34680,
          "sha512": "6c0b58de4a637782f1368423ed5d36406d5c87829d6af1c61a8ac23dec3b115bf36c37c2ad7a62074d276c8c6c6d9b788ada025d06f72b8f7894dee0310df719",
          "sha256": "e54c6e18d6682f147a93d52d9acd963a19dde58a6928f0b179137f8df265b85d",
          "sha1": "c2042932ceaa4dea1792f444a7f2b2677353bfb4",
          "md5": "dda8c57b898aa57badf48161859a16fe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.10.0-javadoc.jar",
          "url": "magicutils-logger-1.10.0-javadoc.jar",
          "size": 206972,
          "sha512": "60188b5adb5058bcc340fa35bf3e60d9dd0d2d51905a49896386eb0c99922593040c561be8c8d53d2687802ed647fe9616d8ca366dc7eb644a4213db0ad54b5c",
          "sha256": "856c9718ad55c85506a08362a01d959d501380c80d074dd9777c330d5a6e3eb9",
          "sha1": "fdd3c89fb7660ffd76d39b7d35c50c75aa14f7ca",
          "md5": "430111b484d6d238062febfa9a55a42d"
        }
      ]
    }
  ]
}
