{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-logger",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.10.0.jar",
          "url": "magicutils-logger-1.10.0.jar",
          "size": 77454,
          "sha512": "cd9780aa3d69077a9ee737b81aae0cb06d5f91511149944d2a1f214d11c5435e39f3822c8541bc3681f22c1d8b9de2149bb32b1136c3439bfe763663d505355b",
          "sha256": "0160e84c9f2791930a3c3a3f6a4cd724128e5839b2586895f41c9b7cf1c6fe19",
          "sha1": "f4892b0a886dfaa2acb56ae3b7fd515a0c0a8e9a",
          "md5": "5f2ec57573f6b1c83117da75e418520b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.10.0.jar",
          "url": "magicutils-logger-1.10.0.jar",
          "size": 77454,
          "sha512": "cd9780aa3d69077a9ee737b81aae0cb06d5f91511149944d2a1f214d11c5435e39f3822c8541bc3681f22c1d8b9de2149bb32b1136c3439bfe763663d505355b",
          "sha256": "0160e84c9f2791930a3c3a3f6a4cd724128e5839b2586895f41c9b7cf1c6fe19",
          "sha1": "f4892b0a886dfaa2acb56ae3b7fd515a0c0a8e9a",
          "md5": "5f2ec57573f6b1c83117da75e418520b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.10.0-all.jar",
          "url": "magicutils-logger-1.10.0-all.jar",
          "size": 3179980,
          "sha512": "e8cfbea31e74133cda1909432300bce844116ad4a1fa1269877c28865d1ff14aba61072e88f27cca401e30d8ba0445a4c3514eae71c5e9247e265b664b8e5960",
          "sha256": "01d65018ed6d4320841237905461378445dcc42fea060663e483dc67c0c081a7",
          "sha1": "97a275aff29f218aad92ef1652ca68a9f1302007",
          "md5": "8a93fe6534a30ef1bb0d2153bb41bb05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.10.0-sources.jar",
          "url": "magicutils-logger-1.10.0-sources.jar",
          "size": 34680,
          "sha512": "78c585d9601252f8176fda4aa8082b371158a959554874efe85f9154587e9a8fb5b3675bb6f7e3b83f9b6598d168450ec9c11caf18e785f052c82fc02768c7f3",
          "sha256": "25d0923c05688501c5575440a4e8a2e3ef783a7afaca02aba4dec3688b3e9fcd",
          "sha1": "1b192ccbaef7acda12335d58a2f76b3b35cfc254",
          "md5": "2f0c13f0ee3c72dd35e8c9481b8d38e5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.10.0-javadoc.jar",
          "url": "magicutils-logger-1.10.0-javadoc.jar",
          "size": 206972,
          "sha512": "00d54bb2422a78dfe1848ee435abdf9e6e1c60dab395d0b0c1e11febfc4556851a7be25c010c450eef81c9f2aa82d183eca9ce442a90c3ae287e8123de804a63",
          "sha256": "28025b2f73558007150c70b4846ffd6e3f8d1d42f36bad72db7c494b8c430143",
          "sha1": "7f31a578e87e8e6a6d988d26b0a367a3c9a56c16",
          "md5": "10e28803a46338444d54ba2c7c5167cd"
        }
      ]
    }
  ]
}
