{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-logger",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.10.0.jar",
          "url": "magicutils-logger-1.10.0.jar",
          "size": 77454,
          "sha512": "d9be0615aa9b02064190e8ad493efe80c374c50e29f0786ec4b6b42a388b5757633ab2697fba8569b956f7b8c8ee5f486f9407d667cd7441418d6270b8cf6fe7",
          "sha256": "ec3d44b8126af43a7bac8c7154ebafe264f523004f94f4724cce5351d7d12aaf",
          "sha1": "77f99d5c98078f0020ccb34a696f6d73692b9830",
          "md5": "91b7a8404326bae45802df3334c385b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.10.0.jar",
          "url": "magicutils-logger-1.10.0.jar",
          "size": 77454,
          "sha512": "d9be0615aa9b02064190e8ad493efe80c374c50e29f0786ec4b6b42a388b5757633ab2697fba8569b956f7b8c8ee5f486f9407d667cd7441418d6270b8cf6fe7",
          "sha256": "ec3d44b8126af43a7bac8c7154ebafe264f523004f94f4724cce5351d7d12aaf",
          "sha1": "77f99d5c98078f0020ccb34a696f6d73692b9830",
          "md5": "91b7a8404326bae45802df3334c385b2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.10.0-all.jar",
          "url": "magicutils-logger-1.10.0-all.jar",
          "size": 3179980,
          "sha512": "e8cfbea31e74133cda1909432300bce844116ad4a1fa1269877c28865d1ff14aba61072e88f27cca401e30d8ba0445a4c3514eae71c5e9247e265b664b8e5960",
          "sha256": "01d65018ed6d4320841237905461378445dcc42fea060663e483dc67c0c081a7",
          "sha1": "97a275aff29f218aad92ef1652ca68a9f1302007",
          "md5": "8a93fe6534a30ef1bb0d2153bb41bb05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.10.0-sources.jar",
          "url": "magicutils-logger-1.10.0-sources.jar",
          "size": 34680,
          "sha512": "47fc54d261ab515a68197d9d70bad29e8910539528d32c076c7d016745d0f013be4e0aad9587d3c79a7b4d652ace15b4581bad66cdd2aff77596726e479ab5bb",
          "sha256": "e6c251f57da0839aa7a90bcd0f161d819d8533ccc2ff3b1268314b76e4e3b5d7",
          "sha1": "c8faf08ecc92618ecb0afa185196b4752cebbf7c",
          "md5": "cd11ab67e4a42b62912d33eb4397889f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.10.0-javadoc.jar",
          "url": "magicutils-logger-1.10.0-javadoc.jar",
          "size": 206972,
          "sha512": "3b1f9c6ad7d25afa8a50addd779f2f9f8bc31766a86b0de84fb3d366f6283b9137931811467d34213bd53468020bd3067a3fa63201758ba54e6ebe03ae47c0e4",
          "sha256": "fab68dd50ce31194b31f2160bd9ff19cb6c6eed8520087265d84e6aa0f5c69f9",
          "sha1": "f22eb77cbf1c0d32f56a572027c0706d47fc56b7",
          "md5": "5e253c4c13f92d09851660f1d301a7e9"
        }
      ]
    }
  ]
}
