{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-config-yaml",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-yaml-1.10.0-mc1.21.jar",
          "url": "magicutils-config-yaml-1.10.0-mc1.21.jar",
          "size": 1719,
          "sha512": "627e2e48f9eb437f787bd8c4c2d3da424a212523eca37de004ceff40fb284033c7e68d0f96dac8135b9ed6e9ae24273afdc4ce2580347cb00ef2ae1e5907d9c3",
          "sha256": "79073caf650baddb60d92fcb7e63a14541b25bc866651488ecca6da043ae396c",
          "sha1": "84360f0f4d57f92dc850d23a6fe6462a0b86c465",
          "md5": "2a28a40efa6855459c79503c57743cd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-yaml-1.10.0-mc1.21.jar",
          "url": "magicutils-config-yaml-1.10.0-mc1.21.jar",
          "size": 1719,
          "sha512": "627e2e48f9eb437f787bd8c4c2d3da424a212523eca37de004ceff40fb284033c7e68d0f96dac8135b9ed6e9ae24273afdc4ce2580347cb00ef2ae1e5907d9c3",
          "sha256": "79073caf650baddb60d92fcb7e63a14541b25bc866651488ecca6da043ae396c",
          "sha1": "84360f0f4d57f92dc850d23a6fe6462a0b86c465",
          "md5": "2a28a40efa6855459c79503c57743cd6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.10.0-sources.jar",
          "url": "magicutils-config-yaml-1.10.0-sources.jar",
          "size": 1615,
          "sha512": "7dd035aa467194e1f75f05e02b1afd2a2c881d14c30a7d577196ca3a326633df2cd9700da0936c91f30e1e9cb7cdedb5e3b373fab0a5b3ee0552940a8037fcbb",
          "sha256": "134bc160155c0948959d106b1fb7d7cb2b2e759d22e70303a8297ba77a13697e",
          "sha1": "3d4491714d06e6a1d91b497be8c6bfe0ef63c648",
          "md5": "f03bc030224c866efafb871d3584d804"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.10.0-javadoc.jar",
          "url": "magicutils-config-yaml-1.10.0-javadoc.jar",
          "size": 91108,
          "sha512": "1bdf4489467b24cd5325ed696d35bf7568c057a2b2cc5423fdcf52701d2e2de6d3aa46cec3ad47348db1ff798537be7bdea1bdefbbeed7bcfdb8e87f3c7d919b",
          "sha256": "c2268f6ac2ff523b722f0be728515f13fed440a93c81448186dd3cc359967f51",
          "sha1": "8f74a08d41b74eac15e6b4f4d2d76f77fd77556b",
          "md5": "919bbf2327add6c919570c7cd10a8daa"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.10.0-all.jar",
          "url": "magicutils-config-yaml-1.10.0-all.jar",
          "size": 3317671,
          "sha512": "a125fd84b001734dc607b62080b99f31c78130aea51f6677db8426731e86224df57d3f3d777ccadf93be8a9fa9e717e0b06b0291ec52d54c9a7f4049e4acf5fd",
          "sha256": "c50721825b3fcb9935a6e6cefb668bf65d8bb362d7a30cf53abb34a9f4789494",
          "sha1": "50315b626d94a1ae40a67c5056e4a6eaf5f9978d",
          "md5": "984c59ed30510ab5d69b460c2ea77516"
        }
      ]
    }
  ]
}
