{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-config-yaml",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-yaml-1.10.0.jar",
          "url": "magicutils-config-yaml-1.10.0.jar",
          "size": 1719,
          "sha512": "c543827254a2ff102d7ca648daac239ee73a2cef3df23a9143f88d89a7945005ca82b19644cafda5970cbbadfaa778746395f5ef3e1ddd9f842bbf47ab435862",
          "sha256": "b3772002aa2025850c6eafae46d8ba60fce839dcbfeac610cf710b3de31ba957",
          "sha1": "bf369e0d4345ce26af35ad60482f74ee9e86f925",
          "md5": "4b8a2a08f7c73cf2f75bc52d5c04f0fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-yaml-1.10.0.jar",
          "url": "magicutils-config-yaml-1.10.0.jar",
          "size": 1719,
          "sha512": "c543827254a2ff102d7ca648daac239ee73a2cef3df23a9143f88d89a7945005ca82b19644cafda5970cbbadfaa778746395f5ef3e1ddd9f842bbf47ab435862",
          "sha256": "b3772002aa2025850c6eafae46d8ba60fce839dcbfeac610cf710b3de31ba957",
          "sha1": "bf369e0d4345ce26af35ad60482f74ee9e86f925",
          "md5": "4b8a2a08f7c73cf2f75bc52d5c04f0fc"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.10.0-all.jar",
          "url": "magicutils-config-yaml-1.10.0-all.jar",
          "size": 3319233,
          "sha512": "f2900c658467a8c53526282ef127c077be021be279cfd99f24260fa6f4108a23063238effadbd31353088342667a67502743f8e7a0d01191067c0a0bd02c4ba9",
          "sha256": "9d3bad56843c0e0ab90df1e4909d81abe116d34cbbe7716e26367b0155c9ef63",
          "sha1": "7d0e10f6efe90353ed4b35aaf7d2800219a47c23",
          "md5": "29ad7eca72c7a493893b3f88da230219"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.10.0-sources.jar",
          "url": "magicutils-config-yaml-1.10.0-sources.jar",
          "size": 1615,
          "sha512": "379b854334b1fda7c7c902386fe33fff75edca53abae4c6ee4fbfc3f9c4a6610ef7a2a8f00c2b1d6efdef80fd28bd838ebffe1676ffd8ad48b3ae3726d5fe96d",
          "sha256": "80dbd2becce468c73289b81b658e40ec66ffaba86387df989c5263f95e62757a",
          "sha1": "d1d9272d23a0d554762ec7546bdc57a9f6ee6004",
          "md5": "cd858fbfc33ea1e1876362c285b3d6c5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.10.0-javadoc.jar",
          "url": "magicutils-config-yaml-1.10.0-javadoc.jar",
          "size": 91108,
          "sha512": "0a91f194d15e91e122bcd39e698e94d53125d810ce1eed56378deb5e08a851955c0231c1f0d0aa3fd17b1ddf313f7f67897b48ef4d0093ee6080e6c09b566fd1",
          "sha256": "210e85769f93e5d0596a696d43b75a86c7c59837a31ab55f672b9dfe94344ec5",
          "sha1": "6d2106a5eb87f9e3cface68cf92b7636fc1ff80a",
          "md5": "557652402cadafa445ab13785b4130e1"
        }
      ]
    }
  ]
}
