{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-neoforge",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.10.0.jar",
          "url": "magicutils-neoforge-1.10.0.jar",
          "size": 3676,
          "sha512": "4917ae215ffaa521b8f4551bdac77d6ddbecbb833c8a939c50a1986b1e87e86c3fe5b0547dfca2cc05d48bb71fd662c49eeb0ed431e2723e68d17415e631fe9e",
          "sha256": "6e81f4eabf0be2079828649f4e86cbf454d0aa53809a95ba722190714f1038a0",
          "sha1": "264c4c553d1ff63db1ade74a3465e4421000c800",
          "md5": "032b14f6b2246539f01a02b9db72976d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.10.0.jar",
          "url": "magicutils-neoforge-1.10.0.jar",
          "size": 3676,
          "sha512": "4917ae215ffaa521b8f4551bdac77d6ddbecbb833c8a939c50a1986b1e87e86c3fe5b0547dfca2cc05d48bb71fd662c49eeb0ed431e2723e68d17415e631fe9e",
          "sha256": "6e81f4eabf0be2079828649f4e86cbf454d0aa53809a95ba722190714f1038a0",
          "sha1": "264c4c553d1ff63db1ade74a3465e4421000c800",
          "md5": "032b14f6b2246539f01a02b9db72976d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.10.0-all.jar",
          "url": "magicutils-neoforge-1.10.0-all.jar",
          "size": 3329090,
          "sha512": "b35dd89122d42ec640963d265681292960ff8b1acf4b31a5aea021aa51e09d1008ab001620e3e731551a12a6670ab086ea10ae1104e21ecd5eb66ba4ae1409c5",
          "sha256": "99ce0df587cbd42d7fac10bd6ea02f9a6869705d0b9d27959c1cde7bb1d40c2c",
          "sha1": "985020d7e2c3b30c117f929e0e0096f9230a632d",
          "md5": "0efae75580143ce35275704b66a03cd8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.10.0-sources.jar",
          "url": "magicutils-neoforge-1.10.0-sources.jar",
          "size": 2875,
          "sha512": "ab432c7abb5dcbf62f28052da8fe300d55266b5fd3be12794c15b7dee1fe7cd8c0deb488be8fa71cfbe7da024b8834ad2ffd351c424d9f1d4f29c046c5375d46",
          "sha256": "05b0da08c60cb49a55ab33e79396804c22f21b18876e8bb1f911efa810f85a1d",
          "sha1": "36665d86978db427454cc1434a60d876766e16b1",
          "md5": "ecfedc8c3fe034946102ea78b0fc9660"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.10.0-javadoc.jar",
          "url": "magicutils-neoforge-1.10.0-javadoc.jar",
          "size": 99429,
          "sha512": "8023f687f5565357ec7cc818a903b4bc5d6d75e982f48a52eecbc0f14b226aa68b370f09db12de2aaed7ad1d9eb4465c00e8ac6e1da14b3c3179cade61e1093f",
          "sha256": "6a945bbac974cb22146f0b2d8c0b6de9a5fe775bfed38ce328e71b3c7d5e5211",
          "sha1": "b4991dfa6c167048dce6d25d1f3c1ffe2a17f4f1",
          "md5": "581de5e811bbb8c8b97cb5bfe8960745"
        }
      ]
    }
  ]
}
