{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-neoforge",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.10.0.jar",
          "url": "magicutils-neoforge-1.10.0.jar",
          "size": 3676,
          "sha512": "32a919931ab24d4831bbe75c537802e73ef8464912eedd8b9fc3183888c2f53f095f3a2af0247bce2cc66f3fac33ee558dfaad0ce7d0c1968f52b7664ee96f68",
          "sha256": "7ad2eb128aed8345540d9c223c82fbead9874e9fc39cc9139cd0f88559a1a299",
          "sha1": "6ecaaf68831ef08ae45beaf5945c50c24994a9f1",
          "md5": "5bc41ff8b3602af78a30c9352f2e7ff4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.10.0.jar",
          "url": "magicutils-neoforge-1.10.0.jar",
          "size": 3676,
          "sha512": "32a919931ab24d4831bbe75c537802e73ef8464912eedd8b9fc3183888c2f53f095f3a2af0247bce2cc66f3fac33ee558dfaad0ce7d0c1968f52b7664ee96f68",
          "sha256": "7ad2eb128aed8345540d9c223c82fbead9874e9fc39cc9139cd0f88559a1a299",
          "sha1": "6ecaaf68831ef08ae45beaf5945c50c24994a9f1",
          "md5": "5bc41ff8b3602af78a30c9352f2e7ff4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.10.0-all.jar",
          "url": "magicutils-neoforge-1.10.0-all.jar",
          "size": 3329090,
          "sha512": "b35dd89122d42ec640963d265681292960ff8b1acf4b31a5aea021aa51e09d1008ab001620e3e731551a12a6670ab086ea10ae1104e21ecd5eb66ba4ae1409c5",
          "sha256": "99ce0df587cbd42d7fac10bd6ea02f9a6869705d0b9d27959c1cde7bb1d40c2c",
          "sha1": "985020d7e2c3b30c117f929e0e0096f9230a632d",
          "md5": "0efae75580143ce35275704b66a03cd8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.10.0-sources.jar",
          "url": "magicutils-neoforge-1.10.0-sources.jar",
          "size": 2875,
          "sha512": "87951d9e6e5da4bdbe0a876cbe9ce40451c4867fbba663668273bb32cea26a8379c14678f896664abe6a33fe3b8eb2491ddd484b480c6a6a9786fc6083e9ad42",
          "sha256": "a74d38031a03b26c3018a22be84973e5da666da151aed9ae6ed4446da4ae0930",
          "sha1": "01b6b35195765eccd177f1f7e7db9b62c163b98b",
          "md5": "6764feb68cb0be4783508c655fd9e2d6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.10.0-javadoc.jar",
          "url": "magicutils-neoforge-1.10.0-javadoc.jar",
          "size": 99429,
          "sha512": "418503862d500f5867e358686ea2fa810f36a50da0a9b3ac253db5ccc1cfb195e3b064a86d81321adaf055265ced1d3b3b3e57b26ecd4f4a479976901cd27837",
          "sha256": "522b8814934bdd60fa88f245e31a53bc8567aa73d35d0e29fdb09b4c5401a3ad",
          "sha1": "112455a6c2909b63f9593590a5ff78d091c5459d",
          "md5": "b5b0ef05fb6e72b13d012ec4f258c5b4"
        }
      ]
    }
  ]
}
