{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands-brigadier",
    "version": "1.14.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.14.5"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.14.5-mc1.21.jar",
          "url": "magicutils-commands-brigadier-1.14.5-mc1.21.jar",
          "size": 22275,
          "sha512": "637779b72b225c8b850a2d1ad3f9d1417ca3bc79551b0248bb3328baee5796b4c864298d33c81fc213d639682c92122e74e92485ef1636c329b669c70b807b23",
          "sha256": "9482ae47a37d2fdf6c378f3435037483a07d24d7e13cd9ebea25aac57b841504",
          "sha1": "7fd0e7cf4349cefe3b3a82240916e0927c9f898a",
          "md5": "743056a9418e9c107beb96842acaaa46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.14.5"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.14.5-mc1.21.jar",
          "url": "magicutils-commands-brigadier-1.14.5-mc1.21.jar",
          "size": 22275,
          "sha512": "637779b72b225c8b850a2d1ad3f9d1417ca3bc79551b0248bb3328baee5796b4c864298d33c81fc213d639682c92122e74e92485ef1636c329b669c70b807b23",
          "sha256": "9482ae47a37d2fdf6c378f3435037483a07d24d7e13cd9ebea25aac57b841504",
          "sha1": "7fd0e7cf4349cefe3b3a82240916e0927c9f898a",
          "md5": "743056a9418e9c107beb96842acaaa46"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.14.5-sources.jar",
          "url": "magicutils-commands-brigadier-1.14.5-sources.jar",
          "size": 7877,
          "sha512": "917b949d668ac2cb4e335d0b61c61fd687420971fc2e457c08e64f497b199a23d9530fa501d5af0d2869f2ae6475b69314a1228010feb399de2b86e096a2f360",
          "sha256": "ecdb49e6dedcd89c7edebdf549658b53b5fa0b9375c5df23b70732d402606e9a",
          "sha1": "2e8d27ab8769d326169d31c1368d6793c92ed273",
          "md5": "191bbea570ded279de44b591055abcfb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.14.5-javadoc.jar",
          "url": "magicutils-commands-brigadier-1.14.5-javadoc.jar",
          "size": 107319,
          "sha512": "e2bde1d1cb6bbeb5a9ca705a3bd4a15dd930b467403450cbc67e75772c94bdc3ec443e492eebfbab020fc358acd0dccf05e87cc22875302f34d214d73cf9980b",
          "sha256": "f17b872b8d1c8d44ad91c3f2de48f27b8c5bfebf52e88f4fad1ae94d23b3118e",
          "sha1": "0015294746a2c7e274f55b84e4bd1ba281ef8722",
          "md5": "63f8f26e002241b1a24f54d9c5762f04"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.14.5-all.jar",
          "url": "magicutils-commands-brigadier-1.14.5-all.jar",
          "size": 3412366,
          "sha512": "76d5915ab775eb4567550a369f144c0220d51e108d287b762f472faac301fc27552f008806b5e7d3ee0c184b958e1a8ab2f95886cdaa29abd3105e05b6a5d200",
          "sha256": "3c595ed2372a91a03645dc817cf1c8303f3f24e3e828605e67a131cc10e8d298",
          "sha1": "b524ad008459fd2b4250f16e833b9c6f7d5d4c21",
          "md5": "69aa90aff058b774bda3f025b6cfbc06"
        }
      ]
    }
  ]
}
