{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-config-toml",
    "version": "1.21.1-mc2611",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.1-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-toml-1.21.1-mc2611-mc26.1.jar",
          "url": "magicutils-config-toml-1.21.1-mc2611-mc26.1.jar",
          "size": 1723,
          "sha512": "f5302a84952325cbc81375d2ad336457266004b9b0e10249b7a65800ff38df31b6f4057e20e1964f27554350290d56f94e49e31f89ecaaa9b485b9b7a49e1fd5",
          "sha256": "53bd71df4eceac6b30ec632405975d0fdd047906d706f3bad47dae83db362999",
          "sha1": "9c6867a8ce58ee306f279d97f1719753ddeeab3f",
          "md5": "e3ea8e08744007ba8381f72dce2c2901"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-toml",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.1-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-toml-1.21.1-mc2611-mc26.1.jar",
          "url": "magicutils-config-toml-1.21.1-mc2611-mc26.1.jar",
          "size": 1723,
          "sha512": "f5302a84952325cbc81375d2ad336457266004b9b0e10249b7a65800ff38df31b6f4057e20e1964f27554350290d56f94e49e31f89ecaaa9b485b9b7a49e1fd5",
          "sha256": "53bd71df4eceac6b30ec632405975d0fdd047906d706f3bad47dae83db362999",
          "sha1": "9c6867a8ce58ee306f279d97f1719753ddeeab3f",
          "md5": "e3ea8e08744007ba8381f72dce2c2901"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-toml-1.21.1-mc2611-sources.jar",
          "url": "magicutils-config-toml-1.21.1-mc2611-sources.jar",
          "size": 1611,
          "sha512": "093d30bd041edff4de4e720f24bfd2690e9d69fc33698c5899980c86e15cd24e410f1712fad09100b2338ea76b328ac23b3208d35a9a82158d7cea76b2b553aa",
          "sha256": "1660c82d5c18c9ebfc2e16469f3a4f3c411430786b1d80f9bcbd7b1ee9cd1d42",
          "sha1": "3c9b74690a899f902f0f5d37d8d00c667bd96184",
          "md5": "0c278a8894541f165eb9c5233ee66a4b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-toml-1.21.1-mc2611-javadoc.jar",
          "url": "magicutils-config-toml-1.21.1-mc2611-javadoc.jar",
          "size": 4145851,
          "sha512": "ff1363809a817813bdc278a42604b7d0c6a1c420d247fa4d1d740c56557463b234a847afdc7976486c8e49af39889e47938181649c4e150ca90e50a916cc1df6",
          "sha256": "6f3dd1b9f85fb2cf0d74d2a030546ea1359dae8c28320f05f8b0b4d5ae485cf9",
          "sha1": "4eb96c56695fb46362d9f5e2207d4f809b133271",
          "md5": "9c4d9346303ace2a85a73d3c2dfd0a9b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-toml-1.21.1-mc2611-all.jar",
          "url": "magicutils-config-toml-1.21.1-mc2611-all.jar",
          "size": 3018237,
          "sha512": "309cb72e38baa60da43d5d6773bab64e95d839718fa52d3c337a606132c5f397461436c36afb02efdbb4930b95e6fec1032c4d29feef8b3b4cfd36ab390be271",
          "sha256": "2b1f3660ba715cc94dc08f2d0226aea7f19fb1a630469c274a9786d090e61257",
          "sha1": "6a63654a078fc7a90925bce9ac2d0afb056a41c7",
          "md5": "a2ae3271a5d96372013d6df56d2eb6db"
        }
      ]
    }
  ]
}
