{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-api",
    "version": "1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-api-1.21.1-mc1.21.jar",
          "url": "magicutils-api-1.21.1-mc1.21.jar",
          "size": 29878,
          "sha512": "226c540c7e967dcb33582765bec7f2b2f25179cc09f2fcb9c8b83b4928d87493f07d0a53badf9aee3d9997163f1067be0cc8dc19378701b2d87aa9a65c675f41",
          "sha256": "4c1c6ab0ccce69dabd9c99bdb956bebf8ab229876f9fb31845a549e3e6597ac4",
          "sha1": "753b970c27b09b64abe063874410d10c4a24eb1f",
          "md5": "3df5b042b2cb437d26a13cd19ad27c90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-api-1.21.1-mc1.21.jar",
          "url": "magicutils-api-1.21.1-mc1.21.jar",
          "size": 29878,
          "sha512": "226c540c7e967dcb33582765bec7f2b2f25179cc09f2fcb9c8b83b4928d87493f07d0a53badf9aee3d9997163f1067be0cc8dc19378701b2d87aa9a65c675f41",
          "sha256": "4c1c6ab0ccce69dabd9c99bdb956bebf8ab229876f9fb31845a549e3e6597ac4",
          "sha1": "753b970c27b09b64abe063874410d10c4a24eb1f",
          "md5": "3df5b042b2cb437d26a13cd19ad27c90"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-api-1.21.1-sources.jar",
          "url": "magicutils-api-1.21.1-sources.jar",
          "size": 19867,
          "sha512": "552374f703879e5836355c79163af1b018e92cf1bd17e773f99f4cf543e486beda9ec1bea3cb592c8c86faa8122105a53a30fa2e2894c0e1bf4732d5d3e6af29",
          "sha256": "245c843a242969fb9ea81ed53c08383c0a9ad7a86e3a851cca6b881fa841114f",
          "sha1": "d096ea52f5d152716aabcc5fbfaa3493940458d1",
          "md5": "15f669e0d564377f4f7c7a46ee052df5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-api-1.21.1-javadoc.jar",
          "url": "magicutils-api-1.21.1-javadoc.jar",
          "size": 173142,
          "sha512": "9fc116913c225ecdcfc3d69d7150e745fe00b809556f7940829d976f38f0c38e87e8d0f9aa111d927959e59e45060148fb8f0d52c0e4e1a373b3da4f59262e27",
          "sha256": "2dc0caaeb7bfbe8e9f1aac709597f05ccf0cbdd440fc6668cc135edec182f8a3",
          "sha1": "af5d5eab11b47aa82c6426ae985678afa59ba65c",
          "md5": "5f543dfeeebcb8e902d244d7ce80f98b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-api-1.21.1-all.jar",
          "url": "magicutils-api-1.21.1-all.jar",
          "size": 517408,
          "sha512": "767a253f4b427470803342026d718ccd09bee9433b09bf15388f72c86aba96ebd141db0622b0ad7f722890a78e5e5ffda92c708e73bfac5b1313907019830c35",
          "sha256": "22fcfb1a2ee0ee93799cec8802d885facf64a961364ee415506efe8cfa1f7e0a",
          "sha1": "29f55f19e9d87bc467a723dd405aac6d4fb94c0e",
          "md5": "00f3b2bbd590b86aed13771be85665cd"
        }
      ]
    }
  ]
}
