{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands-neoforge",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands-brigadier",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-neoforge",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.12.0-mc1.21.jar",
          "url": "magicutils-commands-neoforge-1.12.0-mc1.21.jar",
          "size": 19500,
          "sha512": "8b1a1aafd7a143f7107e8c48655b2d10636ff440fee094ee868b8d0711542a8d082adb2193fa818af8a79c91e3440cbdd8381dce437d16a3477a74cb3ed36c31",
          "sha256": "80b37f593eb28bfaae4367332fd6b050d06a2be16346c0d1cea089eef185eed3",
          "sha1": "e0fb4e921651fb38c7b2617cea5ba4eda88874f3",
          "md5": "1de8fa54f9271ec4c35628de4cc75db8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands-brigadier",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-neoforge",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.12.0-mc1.21.jar",
          "url": "magicutils-commands-neoforge-1.12.0-mc1.21.jar",
          "size": 19500,
          "sha512": "8b1a1aafd7a143f7107e8c48655b2d10636ff440fee094ee868b8d0711542a8d082adb2193fa818af8a79c91e3440cbdd8381dce437d16a3477a74cb3ed36c31",
          "sha256": "80b37f593eb28bfaae4367332fd6b050d06a2be16346c0d1cea089eef185eed3",
          "sha1": "e0fb4e921651fb38c7b2617cea5ba4eda88874f3",
          "md5": "1de8fa54f9271ec4c35628de4cc75db8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.12.0-sources.jar",
          "url": "magicutils-commands-neoforge-1.12.0-sources.jar",
          "size": 8358,
          "sha512": "32c3bebab07c2b83c8076dc630be57752221eeec2e6874f9f36cc99e5439367ef7cd72c8b05d8a9d6e1cc681d8de97af26fbb3a08738bf69df35c5d56f8abe02",
          "sha256": "f3c4c0db0d85b53f5266a34c5b49b2066994dcce373728f01c48873e34134a9a",
          "sha1": "49bc6ceeb80bb7cbcecc85640176c7751bc96b4c",
          "md5": "9ee67c549726c966fd0f7c8ebc25c627"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.12.0-javadoc.jar",
          "url": "magicutils-commands-neoforge-1.12.0-javadoc.jar",
          "size": 110423,
          "sha512": "a3c220e896a32d4c4d13dc31e0656e6f1608f333fbbae4129acb2ff015e61233c84f23e9f458e9462aa3e2c1e023bffce14f506ba3a576c4bf3059dedc97a4af",
          "sha256": "da6256c1e7f58f9aa20b16da9cde87f61349ac8389b0d23dea500c87c51e74a8",
          "sha1": "aaab55987900e699231ac4efae185901ae537287",
          "md5": "8e7dc5c6968b1b1c1a0b9405b7239e04"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.12.0-all.jar",
          "url": "magicutils-commands-neoforge-1.12.0-all.jar",
          "size": 40327998,
          "sha512": "9fed8e064516230adece26cff2c9b91903668503c0b9b9b811aad22f3129734dbcd79ee4b2d78b8ee21ea442457657225d84772a81c4bd9abac5b4b987ef30a6",
          "sha256": "9800036aee8bdbef47810958df9b83f1628428ce072298d7747318351f508ae5",
          "sha1": "e8b1c3a318e80056a06fd3ccf994465497981003",
          "md5": "b8962898608c0a0568960c95e7a3e841"
        }
      ]
    }
  ]
}
