{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-http-client",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.10.0.jar",
          "url": "magicutils-http-client-1.10.0.jar",
          "size": 30051,
          "sha512": "cc6b83a02525af2fb31fe759de5ae41ecaea07ee2285ca7aac366a6904f5cfa8520427a324eb79f073bfa9039993904a00bd131ce4282233bf66ff65ea365223",
          "sha256": "921ee7eba9eab5ef1f09dc3ea3200579e1c3c786b13933bd445e405fd643b65c",
          "sha1": "b3d44c42863ae077044effc937f860f8ae39106a",
          "md5": "1ed8323dbcaed86e7beecbe7df1222ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.10.0.jar",
          "url": "magicutils-http-client-1.10.0.jar",
          "size": 30051,
          "sha512": "cc6b83a02525af2fb31fe759de5ae41ecaea07ee2285ca7aac366a6904f5cfa8520427a324eb79f073bfa9039993904a00bd131ce4282233bf66ff65ea365223",
          "sha256": "921ee7eba9eab5ef1f09dc3ea3200579e1c3c786b13933bd445e405fd643b65c",
          "sha1": "b3d44c42863ae077044effc937f860f8ae39106a",
          "md5": "1ed8323dbcaed86e7beecbe7df1222ae"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.10.0-all.jar",
          "url": "magicutils-http-client-1.10.0-all.jar",
          "size": 2896949,
          "sha512": "a46ae08954660f2bc9ad3db8aea3a48ed51b5f0ff6f80f9748be61ee799956bdac5534fce7ee67c39d2ab20693b11665fe474f74274e31bb7600974f061386db",
          "sha256": "5b7c5eb495be93200884eeafbaccacfbee3bbf3d89c4711da6b729833b937057",
          "sha1": "cb455862f6104ca42f8e4b7ca4089633a0248635",
          "md5": "795e85c9c953fdadcbc82421de0de5af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.10.0-sources.jar",
          "url": "magicutils-http-client-1.10.0-sources.jar",
          "size": 8892,
          "sha512": "06805d9a0cc8d6738c9e53d263b43e2733aebcbb80ab35d60fa94b035cd9f6ca5cc44ff42030cf3246c0767c2cf1f7526eb44560c3889aa2f32163b74f0aa7ae",
          "sha256": "cfc727fc9af0ea083d28ff89b885762fb1b4f9873841c99d21b42e560b5707b9",
          "sha1": "c0db10675dbde7a43465fd7e5f38ad5a564ee3d9",
          "md5": "aa2c0414ecfad2ee02249e493e44a395"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.10.0-javadoc.jar",
          "url": "magicutils-http-client-1.10.0-javadoc.jar",
          "size": 119379,
          "sha512": "8262178a0c5400d80736160ac441cc11f224a7d5c5515aedb5fe03578f5d4b75f2c930116a5f5dee50b518f201f323efb778741836beae9e2a1a6ba269e5d1ff",
          "sha256": "370506e00da84899f2848701fe026846c04ce0c8ceb4a09991b0fd0dc2d4a898",
          "sha1": "dd213586510da99f56f256d3cf2e51d7b7ee0916",
          "md5": "6ffb80880f055d8ec0c39641124c3e4a"
        }
      ]
    }
  ]
}
