{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-http-client",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.10.0-mc1.21.jar",
          "url": "magicutils-http-client-1.10.0-mc1.21.jar",
          "size": 32915,
          "sha512": "1ed9a462d789e12d84317093d3e78bb8a32e0fc984d5439e09124f8ed6075f82e625d1d8fbebf84d2a1653d52a9e4a1026b638d5bf2890050816abca9d890af6",
          "sha256": "c3a309866581337cd161a4752b75af3d50ab28c33f1bf92158b65fc598b91163",
          "sha1": "025fc3ee2bd9f252962859a25aa73b97ddfe9e14",
          "md5": "797109301367c10d3099702eac971399"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.10.0-mc1.21.jar",
          "url": "magicutils-http-client-1.10.0-mc1.21.jar",
          "size": 32915,
          "sha512": "1ed9a462d789e12d84317093d3e78bb8a32e0fc984d5439e09124f8ed6075f82e625d1d8fbebf84d2a1653d52a9e4a1026b638d5bf2890050816abca9d890af6",
          "sha256": "c3a309866581337cd161a4752b75af3d50ab28c33f1bf92158b65fc598b91163",
          "sha1": "025fc3ee2bd9f252962859a25aa73b97ddfe9e14",
          "md5": "797109301367c10d3099702eac971399"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.10.0-sources.jar",
          "url": "magicutils-http-client-1.10.0-sources.jar",
          "size": 11479,
          "sha512": "841e6cdf2dbf69af2ef37703c614a2cf9de8814a2fae47ebaa276750a299dd943f7fce9bb3cc2406c73e6f825b8c01476b325b71376235179db0a31156b985e2",
          "sha256": "add593fd41d6ab4d67218efac36cba6e973b303123825c34442f1355922ba8f2",
          "sha1": "c876e63b8c3ee28c8cc4301b0b9a4f9ab86a4260",
          "md5": "5da2ccc25dfbc8caab451f9466b3dbd8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.10.0-javadoc.jar",
          "url": "magicutils-http-client-1.10.0-javadoc.jar",
          "size": 123053,
          "sha512": "4c138b28c7425ec189f2ca5a4083386cca0d999a7bd9d127cd7cb5e411da321faea7bcd141c8be9ffa1e75b78c4fddf6888f789ee738182f57fbad3263348e43",
          "sha256": "393cddef7e6187d9e234b3a10a3a87361858c82be636bca6ed10687a3faa6cd8",
          "sha1": "e57ac65418880c8144ce5723c59d2552b8feba23",
          "md5": "b9ce8831bc106c04d769ef14f0ac1178"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.10.0-all.jar",
          "url": "magicutils-http-client-1.10.0-all.jar",
          "size": 2895852,
          "sha512": "ec81958527ac293d06bcd5c8dd9b4d5053f0a9f7b90edb78ec83566db3e0289701f1a5082e55180bd13012eba3728c2905494a55a2df461306f0d22aeeb5ffcf",
          "sha256": "9d7024f81ba249997d2ba7547109b9b31b70047222f3579c123f71deba1db458",
          "sha1": "61206e5052bc369403329761e91d63a35a7ba9a5",
          "md5": "9e2c8bcb0dfe99dbccfe27e77e30e99a"
        }
      ]
    }
  ]
}
