{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-diagnostics",
    "version": "1.21.1-mc1201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-diagnostics-1.21.1-mc1201-mc1.20.jar",
          "url": "magicutils-diagnostics-1.21.1-mc1201-mc1.20.jar",
          "size": 60878,
          "sha512": "b4463b19d85ab11305f5938c6308bbe8433f9370c990e5b9c1f367a6fc94ef8fd81b8584e7cc28a8be05f7385573152b9f373a0ecf0cc14d012daedc51bebb08",
          "sha256": "0dc6f2f058e12871698aac27b5c8980ecf7d5093a9074e953b3fafc64bcf97e0",
          "sha1": "42f5d9ccde7c1fe6f1a382aa935a845fc95c3591",
          "md5": "238371cecd97c31c671bc8c0eb138e86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-diagnostics-1.21.1-mc1201-mc1.20.jar",
          "url": "magicutils-diagnostics-1.21.1-mc1201-mc1.20.jar",
          "size": 60878,
          "sha512": "b4463b19d85ab11305f5938c6308bbe8433f9370c990e5b9c1f367a6fc94ef8fd81b8584e7cc28a8be05f7385573152b9f373a0ecf0cc14d012daedc51bebb08",
          "sha256": "0dc6f2f058e12871698aac27b5c8980ecf7d5093a9074e953b3fafc64bcf97e0",
          "sha1": "42f5d9ccde7c1fe6f1a382aa935a845fc95c3591",
          "md5": "238371cecd97c31c671bc8c0eb138e86"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-diagnostics-1.21.1-mc1201-sources.jar",
          "url": "magicutils-diagnostics-1.21.1-mc1201-sources.jar",
          "size": 25570,
          "sha512": "bf1bf971429d2dde57dfd3d93f1fb15a3a68fe5170ba37ebaf51de9cd9e82946f72525e34a4759030a9718ab12b6fefc598f2e2ff2acdd8d46ceb0ea455dd72a",
          "sha256": "7eb04daf0a6018fe354e44ad851e3a124106faf431fd17c5d6634e154676ab80",
          "sha1": "bd353cf97eb2f2a6e4ecdbd129cacacfac9944e0",
          "md5": "80d76ce16f395f6bc5ba377f237d9cb2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-diagnostics-1.21.1-mc1201-javadoc.jar",
          "url": "magicutils-diagnostics-1.21.1-mc1201-javadoc.jar",
          "size": 135845,
          "sha512": "5e6a1e6a33fb67fb827b32343ac6f494a00fb434dcbaf061bb1e7adb03d2858618f03b35683e84848b6f1a823d0f4a20e33f49292ed3045f84a8bd42d98a6f12",
          "sha256": "c9513afe33f51aa717cdffcf89991b4e00e8245b257d114cff084e457d2aac1d",
          "sha1": "efdffc18bde602c8807a85f3c4f0b4f6176b11b0",
          "md5": "c3dfb43a6f1d656ac91ea4ddb6771909"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-diagnostics-1.21.1-mc1201-all.jar",
          "url": "magicutils-diagnostics-1.21.1-mc1201-all.jar",
          "size": 3502807,
          "sha512": "17ff690f6589bc1adc03e32a7cc48678697792e2bf0a6414974202a2f0da56b3ab07e16e1e0abe766066df3ef5f4b89fbacbeefa6e3dc9abfeeb2b4bf4d8255b",
          "sha256": "be8d367084c59deed86ff70d235d1886d3769127e4d5ecfdfc7007234835477c",
          "sha1": "1381c70607c2be13a7eb7029addbcdee76a1254a",
          "md5": "7caca0bcbaa66847486dfe2d2a90c1a4"
        }
      ]
    }
  ]
}
