{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands-neoforge",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands-brigadier",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-neoforge",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.11.0-mc1.21.jar",
          "url": "magicutils-commands-neoforge-1.11.0-mc1.21.jar",
          "size": 19500,
          "sha512": "8b1a1aafd7a143f7107e8c48655b2d10636ff440fee094ee868b8d0711542a8d082adb2193fa818af8a79c91e3440cbdd8381dce437d16a3477a74cb3ed36c31",
          "sha256": "80b37f593eb28bfaae4367332fd6b050d06a2be16346c0d1cea089eef185eed3",
          "sha1": "e0fb4e921651fb38c7b2617cea5ba4eda88874f3",
          "md5": "1de8fa54f9271ec4c35628de4cc75db8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands-brigadier",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-neoforge",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.11.0-mc1.21.jar",
          "url": "magicutils-commands-neoforge-1.11.0-mc1.21.jar",
          "size": 19500,
          "sha512": "8b1a1aafd7a143f7107e8c48655b2d10636ff440fee094ee868b8d0711542a8d082adb2193fa818af8a79c91e3440cbdd8381dce437d16a3477a74cb3ed36c31",
          "sha256": "80b37f593eb28bfaae4367332fd6b050d06a2be16346c0d1cea089eef185eed3",
          "sha1": "e0fb4e921651fb38c7b2617cea5ba4eda88874f3",
          "md5": "1de8fa54f9271ec4c35628de4cc75db8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.11.0-sources.jar",
          "url": "magicutils-commands-neoforge-1.11.0-sources.jar",
          "size": 8358,
          "sha512": "32c3bebab07c2b83c8076dc630be57752221eeec2e6874f9f36cc99e5439367ef7cd72c8b05d8a9d6e1cc681d8de97af26fbb3a08738bf69df35c5d56f8abe02",
          "sha256": "f3c4c0db0d85b53f5266a34c5b49b2066994dcce373728f01c48873e34134a9a",
          "sha1": "49bc6ceeb80bb7cbcecc85640176c7751bc96b4c",
          "md5": "9ee67c549726c966fd0f7c8ebc25c627"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.11.0-javadoc.jar",
          "url": "magicutils-commands-neoforge-1.11.0-javadoc.jar",
          "size": 110422,
          "sha512": "8e774ba8e2299f50edd7bcef46975b347612f18c281a076e1047987bee8f43adb474e2fb354cf05dba84b78ba1041fa8def9d1cceee8aaf787817d9164c7bbfa",
          "sha256": "861ee4f9d1d84506bc3403a9a07c1efc6829c485887771b6859bc611eaa12786",
          "sha1": "e301775abb11871fa761eabb902d28798b78513f",
          "md5": "1135617a03fba5839d78ea670cde72f4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.11.0-all.jar",
          "url": "magicutils-commands-neoforge-1.11.0-all.jar",
          "size": 40324592,
          "sha512": "f6a7da28081d74aa90452b7b240b3b50305f758d70284d8e76fd21f4f12eb87fa552875a938d864b0b02148cbe11601f35fb4e8098adffc7c182972650faddfc",
          "sha256": "7ec499e33469b9357c105b06b0fea0d399c98b7aed78fa483cccb4dd7edd499c",
          "sha1": "82fe5bc27c0b68a5447f928395b68772c22ac8b8",
          "md5": "a12b13c1a454a358c12b4f028ac8f3b8"
        }
      ]
    }
  ]
}
