{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bungee",
    "version": "1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bungee-1.21.1-mc1.21.jar",
          "url": "magicutils-bungee-1.21.1-mc1.21.jar",
          "size": 42404,
          "sha512": "47e504e93b3f3ed208780b4bd2bcb2faed82f9038055b82c4a6784752891f2fafc5d98055fd77f9956163ae7d79408601014f43331803b75f17b584fa43e10f6",
          "sha256": "7fab1946479194d9d29474ea1264d7262501af67aaebda021fa1a4838bebf1d7",
          "sha1": "424f01e9d14782674674d446d27445a35f7f86c1",
          "md5": "45433efe4c580a8dbca648226552d078"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bungee-1.21.1-mc1.21.jar",
          "url": "magicutils-bungee-1.21.1-mc1.21.jar",
          "size": 42404,
          "sha512": "47e504e93b3f3ed208780b4bd2bcb2faed82f9038055b82c4a6784752891f2fafc5d98055fd77f9956163ae7d79408601014f43331803b75f17b584fa43e10f6",
          "sha256": "7fab1946479194d9d29474ea1264d7262501af67aaebda021fa1a4838bebf1d7",
          "sha1": "424f01e9d14782674674d446d27445a35f7f86c1",
          "md5": "45433efe4c580a8dbca648226552d078"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bungee-1.21.1-sources.jar",
          "url": "magicutils-bungee-1.21.1-sources.jar",
          "size": 16806,
          "sha512": "038a7f651f83adde1cb4403b846921051c45a0a2f51b376aa13f27c7deeaa77a2a1164c386df971dfe1341168e43adb4a0413d294907796e1b568079795c32ea",
          "sha256": "0e6323df58d45145207515cb68ffc024defa9712443293ce377eba5c3650036f",
          "sha1": "4a73eef78c16c6462f82fd710fc4f3687975db44",
          "md5": "838c7b3e13c8c3ba07deb471764ac3bb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bungee-1.21.1-javadoc.jar",
          "url": "magicutils-bungee-1.21.1-javadoc.jar",
          "size": 133644,
          "sha512": "88db83b8a867e21bbe2d64932f4dc66c00b44941b2d9dff01799b041f827659c9a98c45a9d35473a2119d6ee12c3dac0680a1547718f161cd7536d36c705b286",
          "sha256": "b5c601f60216e89174b80030e810f3e0b688512091879ecf486f98f280710971",
          "sha1": "2decb19322edc6a6a1fad5a9f246c357007cb5ec",
          "md5": "e86c4886d1b2e11cc40d6c948c7bc797"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bungee-1.21.1-all.jar",
          "url": "magicutils-bungee-1.21.1-all.jar",
          "size": 3573484,
          "sha512": "0f9d4a9bcbe74e4bab94cb30addb5a6aff30c6e8570a08f16763e2383c011ca8fe1d91dce39e18cb68ecd1871b64804f06dcf2cd64327fd6a0f4d5ac0daabcb6",
          "sha256": "c3feca0211b79c3016b176514b8c2a58903911a7d843c049dd3ef3f3743621c0",
          "sha1": "b65cc9e83ae17cbb4a6b6a8c135fefbda6d8c10a",
          "md5": "f42cd3f98122ebdd3a9e3e9048fc6a0a"
        }
      ]
    }
  ]
}
