{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-http-client",
    "version": "1.19.1-mc1201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.19.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.19.1-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.19.1-mc1201-mc1.20.jar",
          "url": "magicutils-http-client-1.19.1-mc1201-mc1.20.jar",
          "size": 58198,
          "sha512": "ae8b86c80d40484ad1224bf792d2e16c12330d4cb3e73ff4778ed0478b52589a3eb711189261d94980b1a56bbef2dc68e350046275b04065ff31191ea2926b46",
          "sha256": "6652253d30705ff3d686d45f1b82b915c4ae271bea80740d03951a929157e278",
          "sha1": "9f1d67ead1dbf8b3f435176fdc283db41299603e",
          "md5": "5a967544f3e25a44a6a8d5350f81152b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.19.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.19.1-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.19.1-mc1201-mc1.20.jar",
          "url": "magicutils-http-client-1.19.1-mc1201-mc1.20.jar",
          "size": 58198,
          "sha512": "ae8b86c80d40484ad1224bf792d2e16c12330d4cb3e73ff4778ed0478b52589a3eb711189261d94980b1a56bbef2dc68e350046275b04065ff31191ea2926b46",
          "sha256": "6652253d30705ff3d686d45f1b82b915c4ae271bea80740d03951a929157e278",
          "sha1": "9f1d67ead1dbf8b3f435176fdc283db41299603e",
          "md5": "5a967544f3e25a44a6a8d5350f81152b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.19.1-mc1201-sources.jar",
          "url": "magicutils-http-client-1.19.1-mc1201-sources.jar",
          "size": 21590,
          "sha512": "94fde141f0c6aa3a602f194001bb5d9ad3c924882c6f3e07209ba8b8cc11f72c6e9457102864565d6585a3ddad4ffecc68bd63ba15345c5e4fb7133cebc699c0",
          "sha256": "d56fd445eccd8f18d0dc1cbd0a4e52ef38ea3ae752784fd7b9775bf86f362081",
          "sha1": "c75bc9748d407dc223ef8b26d8a203437fa98cf9",
          "md5": "fbf841914dd9cb02b159c954a7176056"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.19.1-mc1201-javadoc.jar",
          "url": "magicutils-http-client-1.19.1-mc1201-javadoc.jar",
          "size": 137278,
          "sha512": "b68376cf8654fa080cbd81a25d936cee855b2764c1aba43a36d77a99be1c01c9e6bd2f4747fb38a60c01e7ae32965f1998046ddcd9df5031409a57e1bc862cc3",
          "sha256": "aeacf930998ab802df24c23de2c4da5c937cc633177232c1b32719d2271f7f80",
          "sha1": "0304d798892ba5f5d8594dbbf1e53b894077a083",
          "md5": "8056d9b4e47ff4dd741a6fdbfb94aad0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.19.1-mc1201-all.jar",
          "url": "magicutils-http-client-1.19.1-mc1201-all.jar",
          "size": 3479150,
          "sha512": "7f46345bc02d31bf321fc79a2a5f8ea7b06cd680ce10d64ee823965f9e1ef1db8455102fa5f02370e63ec20750a12103324efd34ad840591688576a064361639",
          "sha256": "da35e445e4e4830fdeee1cbe02445ff692a1f72c1f087b4e574f7aae1fcc8abc",
          "sha1": "9929bdc0d9a43f4570abc6a1e13ba48de285410b",
          "md5": "e310c36306a8a7fa58e1290a21b5570a"
        }
      ]
    }
  ]
}
