{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-neoforge",
    "version": "1.14.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.14.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.14.1-mc1.21.jar",
          "url": "magicutils-neoforge-1.14.1-mc1.21.jar",
          "size": 14657,
          "sha512": "90370a0e5f8c60342d8db38fab04e52a179d623b83f24d81284899c6b586ad76ccd28af7d997c530625fece6841ad52cee90b1172c51f439ac9f3d4fb238dbf2",
          "sha256": "adca55258d6aa90380984d0c429ebfecc5bf7bace7fc4444784e31c3d33363fa",
          "sha1": "df08fbadd3343b7f52bda5d4aa1fb0f85e4ec58b",
          "md5": "50b429d8a42021ff774bd9857a23c2bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.14.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.14.1-mc1.21.jar",
          "url": "magicutils-neoforge-1.14.1-mc1.21.jar",
          "size": 14657,
          "sha512": "90370a0e5f8c60342d8db38fab04e52a179d623b83f24d81284899c6b586ad76ccd28af7d997c530625fece6841ad52cee90b1172c51f439ac9f3d4fb238dbf2",
          "sha256": "adca55258d6aa90380984d0c429ebfecc5bf7bace7fc4444784e31c3d33363fa",
          "sha1": "df08fbadd3343b7f52bda5d4aa1fb0f85e4ec58b",
          "md5": "50b429d8a42021ff774bd9857a23c2bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.14.1-sources.jar",
          "url": "magicutils-neoforge-1.14.1-sources.jar",
          "size": 8247,
          "sha512": "184ba0fe6dfafafe701e5bc77b283e6fbd9f220c68bdf2c58637ded5c8804968cca371c0f1af366fbc6712c3c600d8e9710e42c35a3b290da170d959f4773304",
          "sha256": "23f283d33e0113687ef05e2fba9713115daaffd00fb6fb671a2d3cdf43aaa3d7",
          "sha1": "1003943f1510f59e5ca4acb08a60f7f796b4248b",
          "md5": "fcb2110501a1262d5d033f0ded246695"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.14.1-javadoc.jar",
          "url": "magicutils-neoforge-1.14.1-javadoc.jar",
          "size": 114908,
          "sha512": "b95783885eabe067b79a6f34ac32a9a1b9fae9b420fa137ba10467515ac96385f70d82162f68d05c5b69e81c48b4637c6aaba06050f28c420b69d30c8c1b24e3",
          "sha256": "a900d2ad534b6459c1a364405ef6baed3f54aefc75d1841bb977946f55b3643c",
          "sha1": "90bcc2c944c3cbf914090f5a3d5b1b99b6f0cff6",
          "md5": "54a2e8a6bc5554199f7b474129a67b06"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.14.1-all.jar",
          "url": "magicutils-neoforge-1.14.1-all.jar",
          "size": 40349847,
          "sha512": "7d9222177f0c9fa5a43e2c2cb37ebb8805d7e2958d4b93253d16a0c177df7e2f1a06a5107b021a0c7eede48ef0ab64eb8a7bd29e7ae4d17702e56e73fbc02b09",
          "sha256": "862f1dd9b4800c4ec853d30fa834216b0a9aaa866cd9764c3e134a556d367d76",
          "sha1": "f1e1466bfbe9a85288cef14333463caecccdd9a9",
          "md5": "0be92f458d2242265bb75b882def62ae"
        }
      ]
    }
  ]
}
