{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands-brigadier",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.12.1-mc1.21.jar",
          "url": "magicutils-commands-brigadier-1.12.1-mc1.21.jar",
          "size": 12073,
          "sha512": "aca1157f99d616fa91b6417e3b713b2b3334af55884e74cd35f4c89b6b7eb89c5dec8e04cbd8e05973a8a88270dcedabb6938dec996016088c73ebb4f3f548e5",
          "sha256": "3c1d9bb7b7bd29b0604b90f56b309224a283c632a43484b9c04248be60273d91",
          "sha1": "5d8e6955a7405d8496eb1bd09bb7f120bd71bf0f",
          "md5": "f80421fc6d9a9d6733e5ae29ca481179"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.12.1-mc1.21.jar",
          "url": "magicutils-commands-brigadier-1.12.1-mc1.21.jar",
          "size": 12073,
          "sha512": "aca1157f99d616fa91b6417e3b713b2b3334af55884e74cd35f4c89b6b7eb89c5dec8e04cbd8e05973a8a88270dcedabb6938dec996016088c73ebb4f3f548e5",
          "sha256": "3c1d9bb7b7bd29b0604b90f56b309224a283c632a43484b9c04248be60273d91",
          "sha1": "5d8e6955a7405d8496eb1bd09bb7f120bd71bf0f",
          "md5": "f80421fc6d9a9d6733e5ae29ca481179"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.12.1-sources.jar",
          "url": "magicutils-commands-brigadier-1.12.1-sources.jar",
          "size": 4690,
          "sha512": "4d4c30c4c6e3ac008c9343e474bbbfed946e5309de13983d9e72d63f9d121d4cc936a112aad9fb4b49abb766bec909577902dc76eb56fb5505e8f4abee4b1fc3",
          "sha256": "c87756ee8c698f658a1f1684699d9c546059455f3f7a38921c152074680a889c",
          "sha1": "7be903e55f9614d75471b42645d0ba8729a9aaf9",
          "md5": "a96a0bb34998cc655604ec84f84a5c36"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.12.1-javadoc.jar",
          "url": "magicutils-commands-brigadier-1.12.1-javadoc.jar",
          "size": 97407,
          "sha512": "8daccb001403dadcd33143e7e38d064c699708cb2d76545a170252c51f280bf5d84325b07680ca1779730dee77a95e40c4dc8080aa3d33db4ef441a91d6692c8",
          "sha256": "e81ffeb17351bf108e79980c59b7b2b93e115a06d3758b210f5e7d38129559c2",
          "sha1": "f278d39690e4e5a9cde19d51b723ca2f5e2d1767",
          "md5": "a6cd5cc74e8dbec10dbf227c2d143fde"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.12.1-all.jar",
          "url": "magicutils-commands-brigadier-1.12.1-all.jar",
          "size": 3367434,
          "sha512": "cdab4dafcd13aa33b10ff3133ff43cd7e737d77abd2dd5c2e1299befbbba19be4a6482dfeea3461bd681c17e585a103eb468e112e841fc7d4a32c9b13afee10e",
          "sha256": "b1aad4395d8eda2592b17504e4cf6e740b1f4982dcef5294ffb358f7bda3fba1",
          "sha1": "400619d4d5eced0d559c65ac84a6f38b25e89e3a",
          "md5": "a8b378d87a829b78147b69c7fa972a3f"
        }
      ]
    }
  ]
}
