package dev.ua.theroer.magicutils.logger;

import dev.ua.theroer.magicutils.Logger;
import java.util.Collection;
import net.minecraft.server.level.ServerPlayer;

/**
 * Logger instance with custom prefix.
 * All log methods are generated by annotation processor.
 */
@LogMethods(staticMethods = false, audienceType = "net.minecraft.server.level.ServerPlayer")
public class PrefixedLogger extends PrefixedLoggerMethods implements PrefixedLoggerAdapter<ServerPlayer, LogBuilder> {
    private final Logger logger;
    private final PrefixedLoggerCore core;

    /**
     * Creates a prefixed logger wrapper.
     *
     * @param logger parent logger
     * @param core prefixed core instance
     */
    public PrefixedLogger(Logger logger, PrefixedLoggerCore core) {
        this.logger = logger;
        this.core = core;
    }

    @Override
    public PrefixedLoggerCore getCore() {
        return core;
    }

    @Override
    public LoggerAdapter<ServerPlayer, ?> getLoggerAdapter() {
        return logger;
    }

    @Override
    public LogBuilder buildLogBuilder(LogLevel level) {
        return new PrefixedLogBuilder(level);
    }

    @Override
    public void send(LogLevel level, Object message) {
        PrefixedLoggerAdapter.super.send(level, message);
    }

    @Override
    public void send(LogLevel level, Object message, ServerPlayer player) {
        PrefixedLoggerAdapter.super.send(level, message, player);
    }

    @Override
    public void send(LogLevel level, Object message, ServerPlayer player, boolean all) {
        PrefixedLoggerAdapter.super.send(level, message, player, all);
    }

    @Override
    public void sendToConsole(LogLevel level, Object message) {
        PrefixedLoggerAdapter.super.sendToConsole(level, message);
    }

    @Override
    public void sendToPlayers(LogLevel level, Object message, Collection<? extends ServerPlayer> players) {
        PrefixedLoggerAdapter.super.sendToPlayers(level, message, players);
    }

    private class PrefixedLogBuilder extends LogBuilder {
        PrefixedLogBuilder(LogLevel level) {
            super(logger, level);
        }

        @Override
        protected void performSend(Object message, Object... placeholders) {
            if (!core.isEnabled()) {
                return;
            }
            LogTarget finalTarget = getTarget() != null ? getTarget() : logger.getCore().getDefaultTarget();
            Collection<? extends dev.ua.theroer.magicutils.platform.Audience> audienceRecipients = null;
            if (!getRecipients().isEmpty()) {
                audienceRecipients = getRecipients();
            }
            logger.getCore().send(
                    level,
                    message,
                    getAudience(),
                    audienceRecipients,
                    finalTarget,
                    isBroadcast(),
                    new ConsoleMessageMetadata(level, core.getName()),
                    core.getPrefix(),
                    getPrefixOverride(),
                    placeholders
            );
        }
    }
}
