{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands-neoforge",
    "version": "1.14.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands-brigadier",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-neoforge",
          "version": {
            "requires": "1.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.14.3-mc1.21.jar",
          "url": "magicutils-commands-neoforge-1.14.3-mc1.21.jar",
          "size": 48291,
          "sha512": "6875d4871d224c2016c436fe19875243f2647aa56d0daaddaa4ef5c824b3031bd54889b13e0080dc81d234227efbad289360e0f46cd2f64a2c8a49de2d03251d",
          "sha256": "febb35e6830f63810318ff9777e3fcec1e0483c84893e6b9334c5019f84012ae",
          "sha1": "3850a0949c0e88e2afa76de18d9fd72119c80def",
          "md5": "324330c2dad77a091b526ea58d1e402b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands-brigadier",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-neoforge",
          "version": {
            "requires": "1.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.14.3-mc1.21.jar",
          "url": "magicutils-commands-neoforge-1.14.3-mc1.21.jar",
          "size": 48291,
          "sha512": "6875d4871d224c2016c436fe19875243f2647aa56d0daaddaa4ef5c824b3031bd54889b13e0080dc81d234227efbad289360e0f46cd2f64a2c8a49de2d03251d",
          "sha256": "febb35e6830f63810318ff9777e3fcec1e0483c84893e6b9334c5019f84012ae",
          "sha1": "3850a0949c0e88e2afa76de18d9fd72119c80def",
          "md5": "324330c2dad77a091b526ea58d1e402b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.14.3-sources.jar",
          "url": "magicutils-commands-neoforge-1.14.3-sources.jar",
          "size": 15291,
          "sha512": "df689869aada78262b28f911d0f4bc1ee90c2a812d09e07f65a5c69c2ad3b4f57b47bcb58daeef66e6a6fefbb0eba8c59ee1e2d34c2216377a6c8472b58a64af",
          "sha256": "50999dd33fb7ae4318ef39546aaf5a5e92276f8b9ee6337a4ea90f49c2711b47",
          "sha1": "ff26f94d3d3bb0571e31823502432b1aa223d8f9",
          "md5": "547390671f3688749a23e2e44f97bb53"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.14.3-javadoc.jar",
          "url": "magicutils-commands-neoforge-1.14.3-javadoc.jar",
          "size": 150197,
          "sha512": "480aae6e436259294670c32c06187e05c90f28cf0f83a02666c0a5895ad05221e54129ce35639afee95da2bdda575c29ece7401c353f94aca9520ae14c2fdb4e",
          "sha256": "f17e6ae3ae19f79d7a11240476f2c6e7daa827e23ab0eece892766c6ac1c3767",
          "sha1": "b15c45ab1bc585f3f533f5e534e44ef4b51a6755",
          "md5": "cd57a09253c7bd02d17218a9a907e6b5"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.14.3-all.jar",
          "url": "magicutils-commands-neoforge-1.14.3-all.jar",
          "size": 40418895,
          "sha512": "f97d8e29103817942023d2a8ce1d664169c4253977ef2b75924114522e73ced3cc99e3f1fdc957585582002293ae33d48b97dcf2968d58dc225adf7f657c1dab",
          "sha256": "32c0cdcf5e59e12ac65d92e25dcce2819226a858707f59e174f7a768a53ca927",
          "sha1": "7b6a56efabf3a715b16c610ce41fc479e9f50edb",
          "md5": "601cb7993ff0723b23950e3859796da6"
        }
      ]
    }
  ]
}
