{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-lang",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.10.0.jar",
          "url": "magicutils-lang-1.10.0.jar",
          "size": 35621,
          "sha512": "d5c2eaa077508ad0b782991fb206260c62019bd88def2af39f50ea3ff3b07e482d08cf9f19a388f424ffbee3d5899426a8fe92d67c263ecac730a1c9844a61e1",
          "sha256": "ec6ac45a955c759f4859461a53d15e60cd0bba8e9ae5b418bce059f8533a11d1",
          "sha1": "ea97fcbe8f7f6a12a132939ec462e021c22299a2",
          "md5": "7eb37e6c424e535eae59daf6413cb51e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.10.0.jar",
          "url": "magicutils-lang-1.10.0.jar",
          "size": 35621,
          "sha512": "d5c2eaa077508ad0b782991fb206260c62019bd88def2af39f50ea3ff3b07e482d08cf9f19a388f424ffbee3d5899426a8fe92d67c263ecac730a1c9844a61e1",
          "sha256": "ec6ac45a955c759f4859461a53d15e60cd0bba8e9ae5b418bce059f8533a11d1",
          "sha1": "ea97fcbe8f7f6a12a132939ec462e021c22299a2",
          "md5": "7eb37e6c424e535eae59daf6413cb51e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.10.0-all.jar",
          "url": "magicutils-lang-1.10.0-all.jar",
          "size": 3152556,
          "sha512": "36df09ab332f861b8f7c7f1666910da2d0b119c0c8fbe7ed24a9c8d027203ecd5c2494588caacd477ff7cb403e99ec00061fa28ce72ad0d5cc549ce496b164d1",
          "sha256": "8c9417bdd1bcedb49d2894efd990f5845b1e72643e338ee275854f434a1d5de9",
          "sha1": "4ba6cac787e4a1c23984088a4d803839e58c76e5",
          "md5": "e535af59f960d25dc565914e49391881"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.10.0-sources.jar",
          "url": "magicutils-lang-1.10.0-sources.jar",
          "size": 20047,
          "sha512": "7bcd8eafdbcf100431d8e7fceb379967d249f9b2e22c04fd52ce16da5173d801c2bf8bdf15371b48d7a516b5d9619bc0b8034fa90ee0806366bf89910118780b",
          "sha256": "67b308ac8ca9b2b665b713507c1b1a387c924a60481c48e494e5596857f29fc4",
          "sha1": "debb643d8c4a2a45b0fe0e5305213e7e804e755c",
          "md5": "b06887d26ba9e1da46384aed9464fd32"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.10.0-javadoc.jar",
          "url": "magicutils-lang-1.10.0-javadoc.jar",
          "size": 133362,
          "sha512": "7450ef9b4fb4d9603a1c27ac0b469ee36eb602bc3db87ba246ca4119e4dcafa3aec01035cc2d6026c72be7cebae4f2c05ac382ede9907ded3fecfe319a75eb26",
          "sha256": "5151395b2035bafab50977365ae6b6c3eaf44545a0b8399e68fcdefb497c33ee",
          "sha1": "9cf2607aad17466693d56e5c5243e44a4d4d7bc6",
          "md5": "17747147056ae89bfe74d2af66a4d7e7"
        }
      ]
    }
  ]
}
