{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-lang",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.10.0.jar",
          "url": "magicutils-lang-1.10.0.jar",
          "size": 35621,
          "sha512": "4434a454668cd1e367eefc8472af0f78eea23523d1a5e6a9a7d92c4bb4a379ee62ed668344032868b761f025c4ef1ab2538cb1846b5ba8a1acc41edf02efcb13",
          "sha256": "b36ce1b5dfe4d7ace7c301d0d9e60707d2772cb5f02f0262bc64a6d9e8e909f2",
          "sha1": "39eede87fed981ecb9dfe3431124791c1d6e2380",
          "md5": "afe0bb778ecc6dfe8e43e9a84b9293a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.10.0.jar",
          "url": "magicutils-lang-1.10.0.jar",
          "size": 35621,
          "sha512": "4434a454668cd1e367eefc8472af0f78eea23523d1a5e6a9a7d92c4bb4a379ee62ed668344032868b761f025c4ef1ab2538cb1846b5ba8a1acc41edf02efcb13",
          "sha256": "b36ce1b5dfe4d7ace7c301d0d9e60707d2772cb5f02f0262bc64a6d9e8e909f2",
          "sha1": "39eede87fed981ecb9dfe3431124791c1d6e2380",
          "md5": "afe0bb778ecc6dfe8e43e9a84b9293a4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.10.0-all.jar",
          "url": "magicutils-lang-1.10.0-all.jar",
          "size": 3152556,
          "sha512": "36df09ab332f861b8f7c7f1666910da2d0b119c0c8fbe7ed24a9c8d027203ecd5c2494588caacd477ff7cb403e99ec00061fa28ce72ad0d5cc549ce496b164d1",
          "sha256": "8c9417bdd1bcedb49d2894efd990f5845b1e72643e338ee275854f434a1d5de9",
          "sha1": "4ba6cac787e4a1c23984088a4d803839e58c76e5",
          "md5": "e535af59f960d25dc565914e49391881"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.10.0-sources.jar",
          "url": "magicutils-lang-1.10.0-sources.jar",
          "size": 20047,
          "sha512": "4e4535301d48d9b20b267dd3ba23cc136496d2a7b24c9d6956016166a2b4b345e0aae3b2aecec2382463124bbb3f892d7dc98478436c92b31b215b47610048cf",
          "sha256": "74b14a0067da0d9588930b42e4d0918e90b9c490e8418fc67e9285a7f4d63971",
          "sha1": "5f5a97ffebde0686b20def855767a42d60b4d280",
          "md5": "272208764d0ee62cc1cb591e5656fd3f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.10.0-javadoc.jar",
          "url": "magicutils-lang-1.10.0-javadoc.jar",
          "size": 133362,
          "sha512": "44a1460e03d3defbe85d57d459b57bc0901cb7585c3294eba3bb1a78d490bbc61ee543f26f5aa0e9ad8254cfe49dc8da98578ca7b7d8d78a992599f2026a33a7",
          "sha256": "a441403092acc6d9cae18b253c371da39c7ca22e226f606eef6e497626f58d45",
          "sha1": "ff4eae8000369be8e4c558a7fbd0f089a0554d1a",
          "md5": "32cbd3a8c2454253133d574f7021f23c"
        }
      ]
    }
  ]
}
