{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-lang",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.10.0.jar",
          "url": "magicutils-lang-1.10.0.jar",
          "size": 35621,
          "sha512": "ac8eae06a904e51348bf8a593bf7b03a58d9a706c24a78701f148df2c1b681bdce9c837a3afffd55adbff826653993122e611158d5076a6e37bbc95a3153f205",
          "sha256": "87042a8eb41d1edd336c9bf75df69324e20a6858d358af949d6e1d815262754d",
          "sha1": "8137dba5424c0129a282e1037adaf6212d4709c2",
          "md5": "d16515b2b8e5bf19c97c45ca30f35ebc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.10.0.jar",
          "url": "magicutils-lang-1.10.0.jar",
          "size": 35621,
          "sha512": "ac8eae06a904e51348bf8a593bf7b03a58d9a706c24a78701f148df2c1b681bdce9c837a3afffd55adbff826653993122e611158d5076a6e37bbc95a3153f205",
          "sha256": "87042a8eb41d1edd336c9bf75df69324e20a6858d358af949d6e1d815262754d",
          "sha1": "8137dba5424c0129a282e1037adaf6212d4709c2",
          "md5": "d16515b2b8e5bf19c97c45ca30f35ebc"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.10.0-all.jar",
          "url": "magicutils-lang-1.10.0-all.jar",
          "size": 3152556,
          "sha512": "1a7edf13eb30c4f347ebdd116708c85408d414d4f4d62fcd9e798974e86d03e658798845aa08429431bab0ce80d1a8b82deee2109b358d107ee08259ad71baa0",
          "sha256": "387f2de352f35dfaff7cc23c7252b24e774dc485948cb70740db1d09548ac5e2",
          "sha1": "3492d1789d72b69f6337820b37b9b76a9d6667bd",
          "md5": "8c845e6a0361791aaf2262ed5b9105ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.10.0-sources.jar",
          "url": "magicutils-lang-1.10.0-sources.jar",
          "size": 20047,
          "sha512": "ec94a81538d6ace914df4c2a0ce31dcbf872a96ccbfa91eef118b0cb1850406cc9c413548a2a4d0e5dd32d684055ae5b2e8a8e44ad5531806d9253d5151165d1",
          "sha256": "61040bd82cf6c0103f16967ebeb963fa541ba1270852763bc3c3a958249148f9",
          "sha1": "c12b68c87e72624c1a679e86648555db335f2eb6",
          "md5": "bfaeef6afe93a2ac0baf9a4479e52996"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.10.0-javadoc.jar",
          "url": "magicutils-lang-1.10.0-javadoc.jar",
          "size": 133362,
          "sha512": "b4f72c2bb772ef51f33571da0931e9eb205d2dd6aa6a3ac2f324d2953e5c6cf9e583e960e0d86b2b55583557b0c22db6fd7573fa57caa05fef5b3f189e20a7f0",
          "sha256": "615394e0a9d57d5ed04925a322e7ea1d35722255d000984e6982ccf00ea8ea6a",
          "sha1": "424eebdd73903c091233d3cf10304c092c8858e6",
          "md5": "35ec713812c08f5a53cba495dac5c97d"
        }
      ]
    }
  ]
}
