{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-logger",
    "version": "1.14.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.14.3-mc1.21.jar",
          "url": "magicutils-logger-1.14.3-mc1.21.jar",
          "size": 81980,
          "sha512": "9122af85c69b36dcf4428bd8224fcfbc8f624ee8e80e33d129c353a796c13e0b166b382b46e71fc24fe9fb691f0179df8453f4c4505cb9f056b2d98df9ea9b67",
          "sha256": "d48a4032d573a5d8c6d39f40a734ee6b27d2665488b9b1a57bf9dc421596476d",
          "sha1": "b05cf037bcd0455ef8512b71ec0482d66015635b",
          "md5": "337fae7d65d783bc1fa75a612f73dbc6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.14.3-mc1.21.jar",
          "url": "magicutils-logger-1.14.3-mc1.21.jar",
          "size": 81980,
          "sha512": "9122af85c69b36dcf4428bd8224fcfbc8f624ee8e80e33d129c353a796c13e0b166b382b46e71fc24fe9fb691f0179df8453f4c4505cb9f056b2d98df9ea9b67",
          "sha256": "d48a4032d573a5d8c6d39f40a734ee6b27d2665488b9b1a57bf9dc421596476d",
          "sha1": "b05cf037bcd0455ef8512b71ec0482d66015635b",
          "md5": "337fae7d65d783bc1fa75a612f73dbc6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.14.3-sources.jar",
          "url": "magicutils-logger-1.14.3-sources.jar",
          "size": 37091,
          "sha512": "8fb4a19d76381a526d932c9496f1c2e11566f367e6e3e10f31e8bde1e3f29f03fcebc5991844f6316d69a68e2abc9e8f5b00fb38ad8e263623bc6111c0a9fea7",
          "sha256": "924c540b4f11a948cee8a3c6186710886480da705a214dcd0fc961a467a5a808",
          "sha1": "4d92c8aeb01ad38dc3f24fab076822459ab481be",
          "md5": "cacf8cfedd506cda721c6e33934f32a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.14.3-javadoc.jar",
          "url": "magicutils-logger-1.14.3-javadoc.jar",
          "size": 210304,
          "sha512": "ecefb0e913326412715b665ef50e97b0e330c085257ec4bfc56ef486b8e307ddfaf2aa49c939219b3457f17a01dabb399ea30a03b4fef3d80a4916d0bef25f10",
          "sha256": "1267ecc4f543c21f4bd8f18e8c397fd322639a728e765f93ab276d1395b2de69",
          "sha1": "bcc5c913c203d36b8ca9c25ff69039a417aacc94",
          "md5": "e284abcbda140fd23e0e000e8e35f07b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.14.3-all.jar",
          "url": "magicutils-logger-1.14.3-all.jar",
          "size": 3220096,
          "sha512": "479e3f2123a3ba81a8acbc64549a280896824bc688512272416958cfb7065d3364e69bb21916545f1d6c6d2c54c3cdf4978f17adb04a8fffc83081f6d18727e0",
          "sha256": "2a8da03a251a8eeb6b441d41411cbb2f62f63f29dfeb243cace142003a80a39c",
          "sha1": "740b9af1a4f5e568396e1cabb2f70d9ed8ff5b7c",
          "md5": "627e1a6325163032d7ec26d2204f538d"
        }
      ]
    }
  ]
}
