{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-logger",
    "version": "1.14.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.14.3-mc1.21.jar",
          "url": "magicutils-logger-1.14.3-mc1.21.jar",
          "size": 81982,
          "sha512": "43c9f1b32db25bf7b3ac3d3c3cabc675012b6af22acc41dbc069180c51aaa069ad208d00e16e48a71a7d50cf071758dd1efa8d8cb52f0d1b6e4aecd7e66dde72",
          "sha256": "ea481f8ea841e8642e82fe52f0a9cb53c7225db6531757ad5aa74649ec26db08",
          "sha1": "195dcf7617969106c56012051d00913f3707587d",
          "md5": "e97b45dff850f134da08a1ae4a5d38c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.14.3-mc1.21.jar",
          "url": "magicutils-logger-1.14.3-mc1.21.jar",
          "size": 81982,
          "sha512": "43c9f1b32db25bf7b3ac3d3c3cabc675012b6af22acc41dbc069180c51aaa069ad208d00e16e48a71a7d50cf071758dd1efa8d8cb52f0d1b6e4aecd7e66dde72",
          "sha256": "ea481f8ea841e8642e82fe52f0a9cb53c7225db6531757ad5aa74649ec26db08",
          "sha1": "195dcf7617969106c56012051d00913f3707587d",
          "md5": "e97b45dff850f134da08a1ae4a5d38c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.14.3-sources.jar",
          "url": "magicutils-logger-1.14.3-sources.jar",
          "size": 37091,
          "sha512": "8fb4a19d76381a526d932c9496f1c2e11566f367e6e3e10f31e8bde1e3f29f03fcebc5991844f6316d69a68e2abc9e8f5b00fb38ad8e263623bc6111c0a9fea7",
          "sha256": "924c540b4f11a948cee8a3c6186710886480da705a214dcd0fc961a467a5a808",
          "sha1": "4d92c8aeb01ad38dc3f24fab076822459ab481be",
          "md5": "cacf8cfedd506cda721c6e33934f32a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.14.3-javadoc.jar",
          "url": "magicutils-logger-1.14.3-javadoc.jar",
          "size": 210304,
          "sha512": "ecefb0e913326412715b665ef50e97b0e330c085257ec4bfc56ef486b8e307ddfaf2aa49c939219b3457f17a01dabb399ea30a03b4fef3d80a4916d0bef25f10",
          "sha256": "1267ecc4f543c21f4bd8f18e8c397fd322639a728e765f93ab276d1395b2de69",
          "sha1": "bcc5c913c203d36b8ca9c25ff69039a417aacc94",
          "md5": "e284abcbda140fd23e0e000e8e35f07b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.14.3-all.jar",
          "url": "magicutils-logger-1.14.3-all.jar",
          "size": 3220098,
          "sha512": "28b74c09a64bfcc047d246c526ddaf63503b387ed240b5e048cb49757637b49c7dc0aa5cf70c1b05ff42df803e0f5ccf2ceca258df08094ab5fae69bec000593",
          "sha256": "f9fa6d7db893db6513120843b88aa5fe68f89445c1f32408134c0435babdb938",
          "sha1": "f015778c2b48bea4a296087291955487b66ce4cb",
          "md5": "a828979ab8820a219cbe53d7cd89b9dd"
        }
      ]
    }
  ]
}
