package dev.ua.theroer.magicutils.logger;

import dev.ua.theroer.magicutils.Logger;
import dev.ua.theroer.magicutils.Logger.LogLevel;
import dev.ua.theroer.magicutils.Logger.Target;
import org.bukkit.entity.Player;

import java.util.Collection;

/**
 * Generated logger methods for convenient static access.
 * This class is normally generated by annotation processor, but provided here as example.
 * 
 * TODO: This is a temporary implementation. Remove when annotation processor is ready.
 */
public final class LoggerGen {
    private LoggerGen() {} // Private constructor to prevent instantiation
    
    // INFO level methods
    public static void info(Object msg) {
        Logger.send(LogLevel.INFO, msg, null, null, Logger.getDefaultTarget(), false);
    }
    
    public static void info(String fmt, Object... args) {
        Logger.send(LogLevel.INFO, String.format(fmt, args), null, null, Logger.getDefaultTarget(), false);
    }
    
    public static void infoConsole(Object msg) {
        Logger.send(LogLevel.INFO, msg, null, null, Target.CONSOLE, false);
    }
    
    public static void infoConsole(String fmt, Object... args) {
        Logger.send(LogLevel.INFO, String.format(fmt, args), null, null, Target.CONSOLE, false);
    }
    
    public static void infoAll(Object msg) {
        Logger.send(LogLevel.INFO, msg, null, null, Target.BOTH, true);
    }
    
    public static void infoAll(String fmt, Object... args) {
        Logger.send(LogLevel.INFO, String.format(fmt, args), null, null, Target.BOTH, true);
    }
    
    public static void info(Player p, Object msg) {
        Logger.send(LogLevel.INFO, msg, p, null, Target.CHAT, false);
    }
    
    public static void info(Player p, String fmt, Object... args) {
        Logger.send(LogLevel.INFO, String.format(fmt, args), p, null, Target.CHAT, false);
    }
    
    public static void info(Collection<? extends Player> players, Object msg) {
        Logger.send(LogLevel.INFO, msg, null, players, Target.CHAT, false);
    }
    
    public static void info(Collection<? extends Player> players, String fmt, Object... args) {
        Logger.send(LogLevel.INFO, String.format(fmt, args), null, players, Target.CHAT, false);
    }
    
    // WARN level methods
    public static void warn(Object msg) {
        Logger.send(LogLevel.WARN, msg, null, null, Logger.getDefaultTarget(), false);
    }
    
    public static void warn(String fmt, Object... args) {
        Logger.send(LogLevel.WARN, String.format(fmt, args), null, null, Logger.getDefaultTarget(), false);
    }
    
    public static void warnConsole(Object msg) {
        Logger.send(LogLevel.WARN, msg, null, null, Target.CONSOLE, false);
    }
    
    public static void warnConsole(String fmt, Object... args) {
        Logger.send(LogLevel.WARN, String.format(fmt, args), null, null, Target.CONSOLE, false);
    }
    
    public static void warnAll(Object msg) {
        Logger.send(LogLevel.WARN, msg, null, null, Target.BOTH, true);
    }
    
    public static void warnAll(String fmt, Object... args) {
        Logger.send(LogLevel.WARN, String.format(fmt, args), null, null, Target.BOTH, true);
    }
    
    public static void warn(Player p, Object msg) {
        Logger.send(LogLevel.WARN, msg, p, null, Target.CHAT, false);
    }
    
    public static void warn(Player p, String fmt, Object... args) {
        Logger.send(LogLevel.WARN, String.format(fmt, args), p, null, Target.CHAT, false);
    }
    
    public static void warn(Collection<? extends Player> players, Object msg) {
        Logger.send(LogLevel.WARN, msg, null, players, Target.CHAT, false);
    }
    
    public static void warn(Collection<? extends Player> players, String fmt, Object... args) {
        Logger.send(LogLevel.WARN, String.format(fmt, args), null, players, Target.CHAT, false);
    }
    
    // ERROR level methods
    public static void error(Object msg) {
        Logger.send(LogLevel.ERROR, msg, null, null, Logger.getDefaultTarget(), false);
    }
    
    public static void error(String fmt, Object... args) {
        Logger.send(LogLevel.ERROR, String.format(fmt, args), null, null, Logger.getDefaultTarget(), false);
    }
    
    public static void errorConsole(Object msg) {
        Logger.send(LogLevel.ERROR, msg, null, null, Target.CONSOLE, false);
    }
    
    public static void errorConsole(String fmt, Object... args) {
        Logger.send(LogLevel.ERROR, String.format(fmt, args), null, null, Target.CONSOLE, false);
    }
    
    public static void errorAll(Object msg) {
        Logger.send(LogLevel.ERROR, msg, null, null, Target.BOTH, true);
    }
    
    public static void errorAll(String fmt, Object... args) {
        Logger.send(LogLevel.ERROR, String.format(fmt, args), null, null, Target.BOTH, true);
    }
    
    public static void error(Player p, Object msg) {
        Logger.send(LogLevel.ERROR, msg, p, null, Target.CHAT, false);
    }
    
    public static void error(Player p, String fmt, Object... args) {
        Logger.send(LogLevel.ERROR, String.format(fmt, args), p, null, Target.CHAT, false);
    }
    
    public static void error(Collection<? extends Player> players, Object msg) {
        Logger.send(LogLevel.ERROR, msg, null, players, Target.CHAT, false);
    }
    
    public static void error(Collection<? extends Player> players, String fmt, Object... args) {
        Logger.send(LogLevel.ERROR, String.format(fmt, args), null, players, Target.CHAT, false);
    }
    
    // DEBUG level methods
    public static void debug(Object msg) {
        Logger.send(LogLevel.DEBUG, msg, null, null, Logger.getDefaultTarget(), false);
    }
    
    public static void debug(String fmt, Object... args) {
        Logger.send(LogLevel.DEBUG, String.format(fmt, args), null, null, Logger.getDefaultTarget(), false);
    }
    
    public static void debugConsole(Object msg) {
        Logger.send(LogLevel.DEBUG, msg, null, null, Target.CONSOLE, false);
    }
    
    public static void debugConsole(String fmt, Object... args) {
        Logger.send(LogLevel.DEBUG, String.format(fmt, args), null, null, Target.CONSOLE, false);
    }
    
    public static void debugAll(Object msg) {
        Logger.send(LogLevel.DEBUG, msg, null, null, Target.BOTH, true);
    }
    
    public static void debugAll(String fmt, Object... args) {
        Logger.send(LogLevel.DEBUG, String.format(fmt, args), null, null, Target.BOTH, true);
    }
    
    public static void debug(Player p, Object msg) {
        Logger.send(LogLevel.DEBUG, msg, p, null, Target.CHAT, false);
    }
    
    public static void debug(Player p, String fmt, Object... args) {
        Logger.send(LogLevel.DEBUG, String.format(fmt, args), p, null, Target.CHAT, false);
    }
    
    public static void debug(Collection<? extends Player> players, Object msg) {
        Logger.send(LogLevel.DEBUG, msg, null, players, Target.CHAT, false);
    }
    
    public static void debug(Collection<? extends Player> players, String fmt, Object... args) {
        Logger.send(LogLevel.DEBUG, String.format(fmt, args), null, players, Target.CHAT, false);
    }
    
    // SUCCESS level methods
    public static void success(Object msg) {
        Logger.send(LogLevel.SUCCESS, msg, null, null, Logger.getDefaultTarget(), false);
    }
    
    public static void success(String fmt, Object... args) {
        Logger.send(LogLevel.SUCCESS, String.format(fmt, args), null, null, Logger.getDefaultTarget(), false);
    }
    
    public static void successConsole(Object msg) {
        Logger.send(LogLevel.SUCCESS, msg, null, null, Target.CONSOLE, false);
    }
    
    public static void successConsole(String fmt, Object... args) {
        Logger.send(LogLevel.SUCCESS, String.format(fmt, args), null, null, Target.CONSOLE, false);
    }
    
    public static void successAll(Object msg) {
        Logger.send(LogLevel.SUCCESS, msg, null, null, Target.BOTH, true);
    }
    
    public static void successAll(String fmt, Object... args) {
        Logger.send(LogLevel.SUCCESS, String.format(fmt, args), null, null, Target.BOTH, true);
    }
    
    public static void success(Player p, Object msg) {
        Logger.send(LogLevel.SUCCESS, msg, p, null, Target.CHAT, false);
    }
    
    public static void success(Player p, String fmt, Object... args) {
        Logger.send(LogLevel.SUCCESS, String.format(fmt, args), p, null, Target.CHAT, false);
    }
    
    public static void success(Collection<? extends Player> players, Object msg) {
        Logger.send(LogLevel.SUCCESS, msg, null, players, Target.CHAT, false);
    }
    
    public static void success(Collection<? extends Player> players, String fmt, Object... args) {
        Logger.send(LogLevel.SUCCESS, String.format(fmt, args), null, players, Target.CHAT, false);
    }
    
    // Broadcast helper (was in Logger)
    public static void broadcast(Object message) {
        Logger.send(LogLevel.INFO, message, null, null, Target.BOTH, true);
    }
}