package dev.ua.theroer.magicutils.logger;

import dev.ua.theroer.magicutils.Logger.LogLevel;
import org.bukkit.entity.Player;

import java.util.Collection;

/**
 * Generated logger methods for PrefixedLogger instances.
 * This class is normally generated by annotation processor, but provided here
 * as example.
 */
public final class PrefixedLoggerGen {
    /**
     * Private constructor to prevent instantiation.
     */
    private PrefixedLoggerGen() {
    }

    /**
     * Sends an info message.
     * 
     * @param self the PrefixedLogger instance
     * @param msg  the message to send
     */
    public static void info(PrefixedLogger self, Object msg) {
        self.send(LogLevel.INFO, msg);
    }

    /**
     * Sends an info message with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void info(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.INFO, String.format(fmt, args));
    }

    /**
     * Sends an info message to the console.
     * 
     * @param self the PrefixedLogger instance
     * @param msg  the message to send
     */
    public static void infoConsole(PrefixedLogger self, Object msg) {
        self.sendToConsole(LogLevel.INFO, msg);
    }

    /**
     * Sends an info message to the console with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void infoConsole(PrefixedLogger self, String fmt, Object... args) {
        self.sendToConsole(LogLevel.INFO, String.format(fmt, args));
    }

    /**
     * Sends an info message to all players.
     * 
     * @param self the PrefixedLogger instance
     * @param msg  the message to send
     */
    public static void infoAll(PrefixedLogger self, Object msg) {
        self.send(LogLevel.INFO, msg, null, true);
    }

    /**
     * Sends an info message to all players with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void infoAll(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.INFO, String.format(fmt, args), null, true);
    }

    /**
     * Sends an info message to a specific player.
     * 
     * @param self the PrefixedLogger instance
     * @param p    the player to send the message to
     * @param msg  the message to send
     */
    public static void info(PrefixedLogger self, Player p, Object msg) {
        self.send(LogLevel.INFO, msg, p);
    }

    /**
     * Sends an info message to a specific player with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param p    the player to send the message to
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void info(PrefixedLogger self, Player p, String fmt, Object... args) {
        self.send(LogLevel.INFO, String.format(fmt, args), p);
    }

    /**
     * Sends an info message to a collection of players.
     * 
     * @param self    the PrefixedLogger instance
     * @param players the collection of players to send the message to
     * @param msg     the message to send
     */
    public static void info(PrefixedLogger self, Collection<? extends Player> players, Object msg) {
        self.sendToPlayers(LogLevel.INFO, msg, players);
    }

    /**
     * Sends an info message to a collection of players with a format string.
     * 
     * @param self    the PrefixedLogger instance
     * @param players the collection of players to send the message to
     * @param fmt     the format string
     * @param args    the arguments for the format string
     */
    public static void info(PrefixedLogger self, Collection<? extends Player> players, String fmt, Object... args) {
        self.sendToPlayers(LogLevel.INFO, String.format(fmt, args), players);
    }

    /**
     * Sends a warning message.
     * 
     * @param self the PrefixedLogger instance
     * @param msg  the message to send
     */
    public static void warn(PrefixedLogger self, Object msg) {
        self.send(LogLevel.WARN, msg);
    }

    /**
     * Sends a warning message with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void warn(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.WARN, String.format(fmt, args));
    }

    /**
     * Sends a warning message to the console.
     * 
     * @param self the PrefixedLogger instance
     * @param msg  the message to send
     */
    public static void warnConsole(PrefixedLogger self, Object msg) {
        self.sendToConsole(LogLevel.WARN, msg);
    }

    /**
     * Sends a warning message to the console with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void warnConsole(PrefixedLogger self, String fmt, Object... args) {
        self.sendToConsole(LogLevel.WARN, String.format(fmt, args));
    }

    /**
     * Sends a warning message to all players.
     * 
     * @param self the PrefixedLogger instance
     * @param msg  the message to send
     */
    public static void warnAll(PrefixedLogger self, Object msg) {
        self.send(LogLevel.WARN, msg, null, true);
    }

    /**
     * Sends a warning message to all players with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void warnAll(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.WARN, String.format(fmt, args), null, true);
    }

    /**
     * Sends a warning message to a specific player.
     * 
     * @param self the PrefixedLogger instance
     * @param p    the player to send the message to
     * @param msg  the message to send
     */
    public static void warn(PrefixedLogger self, Player p, Object msg) {
        self.send(LogLevel.WARN, msg, p);
    }

    /**
     * Sends a warning message to a specific player with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param p    the player to send the message to
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void warn(PrefixedLogger self, Player p, String fmt, Object... args) {
        self.send(LogLevel.WARN, String.format(fmt, args), p);
    }

    /**
     * Sends a warning message to a collection of players.
     * 
     * @param self    the PrefixedLogger instance
     * @param players the collection of players to send the message to
     * @param msg     the message to send
     */
    public static void warn(PrefixedLogger self, Collection<? extends Player> players, Object msg) {
        self.sendToPlayers(LogLevel.WARN, msg, players);
    }

    /**
     * Sends a warning message to a collection of players with a format string.
     * 
     * @param self    the PrefixedLogger instance
     * @param players the collection of players to send the message to
     * @param fmt     the format string
     * @param args    the arguments for the format string
     */
    public static void warn(PrefixedLogger self, Collection<? extends Player> players, String fmt, Object... args) {
        self.sendToPlayers(LogLevel.WARN, String.format(fmt, args), players);
    }

    // ERROR level methods
    /**
     * Sends an error message.
     * 
     * @param self the PrefixedLogger instance
     * @param msg  the message to send
     */
    public static void error(PrefixedLogger self, Object msg) {
        self.send(LogLevel.ERROR, msg);
    }

    /**
     * Sends an error message with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void error(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.ERROR, String.format(fmt, args));
    }

    /**
     * Sends an error message to the console.
     * 
     * @param self the PrefixedLogger instance
     * @param msg  the message to send
     */
    public static void errorConsole(PrefixedLogger self, Object msg) {
        self.sendToConsole(LogLevel.ERROR, msg);
    }

    /**
     * Sends an error message to the console with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void errorConsole(PrefixedLogger self, String fmt, Object... args) {
        self.sendToConsole(LogLevel.ERROR, String.format(fmt, args));
    }

    /**
     * Sends an error message to all players.
     * 
     * @param self the PrefixedLogger instance
     * @param msg  the message to send
     */
    public static void errorAll(PrefixedLogger self, Object msg) {
        self.send(LogLevel.ERROR, msg, null, true);
    }

    /**
     * Sends an error message to all players with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void errorAll(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.ERROR, String.format(fmt, args), null, true);
    }

    /**
     * Sends an error message to a specific player.
     * 
     * @param self the PrefixedLogger instance
     * @param p    the player to send the message to
     * @param msg  the message to send
     */
    public static void error(PrefixedLogger self, Player p, Object msg) {
        self.send(LogLevel.ERROR, msg, p);
    }

    /**
     * Sends an error message to a specific player with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param p    the player to send the message to
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void error(PrefixedLogger self, Player p, String fmt, Object... args) {
        self.send(LogLevel.ERROR, String.format(fmt, args), p);
    }

    /**
     * Sends an error message to a collection of players.
     * 
     * @param self    the PrefixedLogger instance
     * @param players the collection of players to send the message to
     * @param msg     the message to send
     */
    public static void error(PrefixedLogger self, Collection<? extends Player> players, Object msg) {
        self.sendToPlayers(LogLevel.ERROR, msg, players);
    }

    /**
     * Sends an error message to a collection of players with a format string.
     * 
     * @param self    the PrefixedLogger instance
     * @param players the collection of players to send the message to
     * @param fmt     the format string
     * @param args    the arguments for the format string
     */
    public static void error(PrefixedLogger self, Collection<? extends Player> players, String fmt, Object... args) {
        self.sendToPlayers(LogLevel.ERROR, String.format(fmt, args), players);
    }

    // DEBUG level methods
    /**
     * Sends a debug message.
     * 
     * @param self the PrefixedLogger instance
     * @param msg  the message to send
     */
    public static void debug(PrefixedLogger self, Object msg) {
        self.send(LogLevel.DEBUG, msg);
    }

    /**
     * Sends a debug message with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void debug(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.DEBUG, String.format(fmt, args));
    }

    /**
     * Sends a debug message to the console.
     * 
     * @param self the PrefixedLogger instance
     * @param msg  the message to send
     */
    public static void debugConsole(PrefixedLogger self, Object msg) {
        self.sendToConsole(LogLevel.DEBUG, msg);
    }

    /**
     * Sends a debug message to the console with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void debugConsole(PrefixedLogger self, String fmt, Object... args) {
        self.sendToConsole(LogLevel.DEBUG, String.format(fmt, args));
    }

    /**
     * Sends a debug message to all players.
     * 
     * @param self the PrefixedLogger instance
     * @param msg  the message to send
     */
    public static void debugAll(PrefixedLogger self, Object msg) {
        self.send(LogLevel.DEBUG, msg, null, true);
    }

    /**
     * Sends a debug message to all players with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void debugAll(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.DEBUG, String.format(fmt, args), null, true);
    }

    /**
     * Sends a debug message to a specific player.
     * 
     * @param self the PrefixedLogger instance
     * @param p    the player to send the message to
     * @param msg  the message to send
     */
    public static void debug(PrefixedLogger self, Player p, Object msg) {
        self.send(LogLevel.DEBUG, msg, p);
    }

    /**
     * Sends a debug message to a specific player with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param p    the player to send the message to
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void debug(PrefixedLogger self, Player p, String fmt, Object... args) {
        self.send(LogLevel.DEBUG, String.format(fmt, args), p);
    }

    /**
     * Sends a debug message to a collection of players.
     * 
     * @param self    the PrefixedLogger instance
     * @param players the collection of players to send the message to
     * @param msg     the message to send
     */
    public static void debug(PrefixedLogger self, Collection<? extends Player> players, Object msg) {
        self.sendToPlayers(LogLevel.DEBUG, msg, players);
    }

    /**
     * Sends a debug message to a collection of players with a format string.
     * 
     * @param self    the PrefixedLogger instance
     * @param players the collection of players to send the message to
     * @param fmt     the format string
     * @param args    the arguments for the format string
     */
    public static void debug(PrefixedLogger self, Collection<? extends Player> players, String fmt, Object... args) {
        self.sendToPlayers(LogLevel.DEBUG, String.format(fmt, args), players);
    }

    // SUCCESS level methods
    /**
     * Sends a success message.
     * 
     * @param self the PrefixedLogger instance
     * @param msg  the message to send
     */
    public static void success(PrefixedLogger self, Object msg) {
        self.send(LogLevel.SUCCESS, msg);
    }

    /**
     * Sends a success message with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void success(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.SUCCESS, String.format(fmt, args));
    }

    /**
     * Sends a success message to the console.
     * 
     * @param self the PrefixedLogger instance
     * @param msg  the message to send
     */
    public static void successConsole(PrefixedLogger self, Object msg) {
        self.sendToConsole(LogLevel.SUCCESS, msg);
    }

    /**
     * Sends a success message to the console with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void successConsole(PrefixedLogger self, String fmt, Object... args) {
        self.sendToConsole(LogLevel.SUCCESS, String.format(fmt, args));
    }

    /**
     * Sends a success message to all players.
     * 
     * @param self the PrefixedLogger instance
     * @param msg  the message to send
     */
    public static void successAll(PrefixedLogger self, Object msg) {
        self.send(LogLevel.SUCCESS, msg, null, true);
    }

    /**
     * Sends a success message to all players with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void successAll(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.SUCCESS, String.format(fmt, args), null, true);
    }

    /**
     * Sends a success message to a specific player.
     * 
     * @param self the PrefixedLogger instance
     * @param p    the player to send the message to
     * @param msg  the message to send
     */
    public static void success(PrefixedLogger self, Player p, Object msg) {
        self.send(LogLevel.SUCCESS, msg, p);
    }

    /**
     * Sends a success message to a specific player with a format string.
     * 
     * @param self the PrefixedLogger instance
     * @param p    the player to send the message to
     * @param fmt  the format string
     * @param args the arguments for the format string
     */
    public static void success(PrefixedLogger self, Player p, String fmt, Object... args) {
        self.send(LogLevel.SUCCESS, String.format(fmt, args), p);
    }

    /**
     * Sends a success message to a collection of players.
     * 
     * @param self    the PrefixedLogger instance
     * @param players the collection of players to send the message to
     * @param msg     the message to send
     */
    public static void success(PrefixedLogger self, Collection<? extends Player> players, Object msg) {
        self.sendToPlayers(LogLevel.SUCCESS, msg, players);
    }

    /**
     * Sends a success message to a collection of players with a format string.
     * 
     * @param self    the PrefixedLogger instance
     * @param players the collection of players to send the message to
     * @param fmt     the format string
     * @param args    the arguments for the format string
     */
    public static void success(PrefixedLogger self, Collection<? extends Player> players, String fmt, Object... args) {
        self.sendToPlayers(LogLevel.SUCCESS, String.format(fmt, args), players);
    }
}