package dev.ua.theroer.magicutils.logger;

import dev.ua.theroer.magicutils.Logger.LogLevel;
import org.bukkit.entity.Player;

import java.util.Collection;

/**
 * Generated logger methods for PrefixedLogger instances.
 * This class is normally generated by annotation processor, but provided here as example.
 * 
 * TODO: This is a temporary implementation. Remove when annotation processor is ready.
 */
public final class PrefixedLoggerGen {
    private PrefixedLoggerGen() {} // Private constructor to prevent instantiation
    
    // INFO level methods
    public static void info(PrefixedLogger self, Object msg) {
        self.send(LogLevel.INFO, msg);
    }
    
    public static void info(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.INFO, String.format(fmt, args));
    }
    
    public static void infoConsole(PrefixedLogger self, Object msg) {
        self.sendToConsole(LogLevel.INFO, msg);
    }
    
    public static void infoConsole(PrefixedLogger self, String fmt, Object... args) {
        self.sendToConsole(LogLevel.INFO, String.format(fmt, args));
    }
    
    public static void infoAll(PrefixedLogger self, Object msg) {
        self.send(LogLevel.INFO, msg, null, true);
    }
    
    public static void infoAll(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.INFO, String.format(fmt, args), null, true);
    }
    
    public static void info(PrefixedLogger self, Player p, Object msg) {
        self.send(LogLevel.INFO, msg, p);
    }
    
    public static void info(PrefixedLogger self, Player p, String fmt, Object... args) {
        self.send(LogLevel.INFO, String.format(fmt, args), p);
    }
    
    public static void info(PrefixedLogger self, Collection<? extends Player> players, Object msg) {
        self.sendToPlayers(LogLevel.INFO, msg, players);
    }
    
    public static void info(PrefixedLogger self, Collection<? extends Player> players, String fmt, Object... args) {
        self.sendToPlayers(LogLevel.INFO, String.format(fmt, args), players);
    }
    
    // WARN level methods
    public static void warn(PrefixedLogger self, Object msg) {
        self.send(LogLevel.WARN, msg);
    }
    
    public static void warn(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.WARN, String.format(fmt, args));
    }
    
    public static void warnConsole(PrefixedLogger self, Object msg) {
        self.sendToConsole(LogLevel.WARN, msg);
    }
    
    public static void warnConsole(PrefixedLogger self, String fmt, Object... args) {
        self.sendToConsole(LogLevel.WARN, String.format(fmt, args));
    }
    
    public static void warnAll(PrefixedLogger self, Object msg) {
        self.send(LogLevel.WARN, msg, null, true);
    }
    
    public static void warnAll(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.WARN, String.format(fmt, args), null, true);
    }
    
    public static void warn(PrefixedLogger self, Player p, Object msg) {
        self.send(LogLevel.WARN, msg, p);
    }
    
    public static void warn(PrefixedLogger self, Player p, String fmt, Object... args) {
        self.send(LogLevel.WARN, String.format(fmt, args), p);
    }
    
    public static void warn(PrefixedLogger self, Collection<? extends Player> players, Object msg) {
        self.sendToPlayers(LogLevel.WARN, msg, players);
    }
    
    public static void warn(PrefixedLogger self, Collection<? extends Player> players, String fmt, Object... args) {
        self.sendToPlayers(LogLevel.WARN, String.format(fmt, args), players);
    }
    
    // ERROR level methods
    public static void error(PrefixedLogger self, Object msg) {
        self.send(LogLevel.ERROR, msg);
    }
    
    public static void error(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.ERROR, String.format(fmt, args));
    }
    
    public static void errorConsole(PrefixedLogger self, Object msg) {
        self.sendToConsole(LogLevel.ERROR, msg);
    }
    
    public static void errorConsole(PrefixedLogger self, String fmt, Object... args) {
        self.sendToConsole(LogLevel.ERROR, String.format(fmt, args));
    }
    
    public static void errorAll(PrefixedLogger self, Object msg) {
        self.send(LogLevel.ERROR, msg, null, true);
    }
    
    public static void errorAll(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.ERROR, String.format(fmt, args), null, true);
    }
    
    public static void error(PrefixedLogger self, Player p, Object msg) {
        self.send(LogLevel.ERROR, msg, p);
    }
    
    public static void error(PrefixedLogger self, Player p, String fmt, Object... args) {
        self.send(LogLevel.ERROR, String.format(fmt, args), p);
    }
    
    public static void error(PrefixedLogger self, Collection<? extends Player> players, Object msg) {
        self.sendToPlayers(LogLevel.ERROR, msg, players);
    }
    
    public static void error(PrefixedLogger self, Collection<? extends Player> players, String fmt, Object... args) {
        self.sendToPlayers(LogLevel.ERROR, String.format(fmt, args), players);
    }
    
    // DEBUG level methods
    public static void debug(PrefixedLogger self, Object msg) {
        self.send(LogLevel.DEBUG, msg);
    }
    
    public static void debug(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.DEBUG, String.format(fmt, args));
    }
    
    public static void debugConsole(PrefixedLogger self, Object msg) {
        self.sendToConsole(LogLevel.DEBUG, msg);
    }
    
    public static void debugConsole(PrefixedLogger self, String fmt, Object... args) {
        self.sendToConsole(LogLevel.DEBUG, String.format(fmt, args));
    }
    
    public static void debugAll(PrefixedLogger self, Object msg) {
        self.send(LogLevel.DEBUG, msg, null, true);
    }
    
    public static void debugAll(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.DEBUG, String.format(fmt, args), null, true);
    }
    
    public static void debug(PrefixedLogger self, Player p, Object msg) {
        self.send(LogLevel.DEBUG, msg, p);
    }
    
    public static void debug(PrefixedLogger self, Player p, String fmt, Object... args) {
        self.send(LogLevel.DEBUG, String.format(fmt, args), p);
    }
    
    public static void debug(PrefixedLogger self, Collection<? extends Player> players, Object msg) {
        self.sendToPlayers(LogLevel.DEBUG, msg, players);
    }
    
    public static void debug(PrefixedLogger self, Collection<? extends Player> players, String fmt, Object... args) {
        self.sendToPlayers(LogLevel.DEBUG, String.format(fmt, args), players);
    }
    
    // SUCCESS level methods
    public static void success(PrefixedLogger self, Object msg) {
        self.send(LogLevel.SUCCESS, msg);
    }
    
    public static void success(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.SUCCESS, String.format(fmt, args));
    }
    
    public static void successConsole(PrefixedLogger self, Object msg) {
        self.sendToConsole(LogLevel.SUCCESS, msg);
    }
    
    public static void successConsole(PrefixedLogger self, String fmt, Object... args) {
        self.sendToConsole(LogLevel.SUCCESS, String.format(fmt, args));
    }
    
    public static void successAll(PrefixedLogger self, Object msg) {
        self.send(LogLevel.SUCCESS, msg, null, true);
    }
    
    public static void successAll(PrefixedLogger self, String fmt, Object... args) {
        self.send(LogLevel.SUCCESS, String.format(fmt, args), null, true);
    }
    
    public static void success(PrefixedLogger self, Player p, Object msg) {
        self.send(LogLevel.SUCCESS, msg, p);
    }
    
    public static void success(PrefixedLogger self, Player p, String fmt, Object... args) {
        self.send(LogLevel.SUCCESS, String.format(fmt, args), p);
    }
    
    public static void success(PrefixedLogger self, Collection<? extends Player> players, Object msg) {
        self.sendToPlayers(LogLevel.SUCCESS, msg, players);
    }
    
    public static void success(PrefixedLogger self, Collection<? extends Player> players, String fmt, Object... args) {
        self.sendToPlayers(LogLevel.SUCCESS, String.format(fmt, args), players);
    }
}