{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-config",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-1.10.0.jar",
          "url": "magicutils-config-1.10.0.jar",
          "size": 70468,
          "sha512": "d03dc2096879381e59f3c0fa6f55f1cb3da71a848fdab6d3367935306f18097ccbbfe0ff0eb0c58cb55ac4b2b128f50be2b5508fafa730107b70d8d08a23c466",
          "sha256": "48bc5ea058865a10bef84df5d51a45d56a5ff28fdb50da1edb7aec0e96ee4dde",
          "sha1": "57e1c6ef5478fd9dde88b030cb16595408585350",
          "md5": "5e756849bd6b78d70408e51a29034148"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-1.10.0.jar",
          "url": "magicutils-config-1.10.0.jar",
          "size": 70468,
          "sha512": "d03dc2096879381e59f3c0fa6f55f1cb3da71a848fdab6d3367935306f18097ccbbfe0ff0eb0c58cb55ac4b2b128f50be2b5508fafa730107b70d8d08a23c466",
          "sha256": "48bc5ea058865a10bef84df5d51a45d56a5ff28fdb50da1edb7aec0e96ee4dde",
          "sha1": "57e1c6ef5478fd9dde88b030cb16595408585350",
          "md5": "5e756849bd6b78d70408e51a29034148"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.10.0-all.jar",
          "url": "magicutils-config-1.10.0-all.jar",
          "size": 2930355,
          "sha512": "b79feaa563ff2af72cfb1e320c105ebf78ac866491c171ca82c5725734dae9a599f209008404302ceccaaa0461bf3bdbacbea6e0120f4a8f8dbbd04023e7421c",
          "sha256": "42ae55c2c6ad07a53c2099e5c2fcadcf0e378f639be0529254abc9fe773f976b",
          "sha1": "bc616b320681b147ceed0e44de4800b328f8b630",
          "md5": "3c1022f3ff820fe1b3f7cd46843fdb9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.10.0-sources.jar",
          "url": "magicutils-config-1.10.0-sources.jar",
          "size": 31617,
          "sha512": "d234d76380a79ef73289d4dcded66609c3b6a2b8fa430d51d51339b5edf10183a1a75107919d59f7bc121d735a2eebe6e0a43fc11ae10cd6c056d694f58845d8",
          "sha256": "491d537bad4289734f5e50966612723173f5307bce844e48c111a4b9cdc3a346",
          "sha1": "a074ce8fbb2535cf038a32f230d4b8f6e396fe0a",
          "md5": "f9377868c547ebcb1f5117b920a2978b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.10.0-javadoc.jar",
          "url": "magicutils-config-1.10.0-javadoc.jar",
          "size": 154977,
          "sha512": "3bba8e7c5a1f15297063c90cc8b69874fdfc5f782509b630188d798a8d850149969d0697f2db590793c75f9998e6287bc84be76197c1f8c6994748e09d674dda",
          "sha256": "511dee3a2bc3861db72959a84be214bdba1916891c8c918ac5703a7d91e11499",
          "sha1": "3673dcf7e6f677fc5f756a6fdec0418731274cc2",
          "md5": "9debcc45ad73b9620ff3f0469d4f7726"
        }
      ]
    }
  ]
}
