{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-config",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-1.10.0.jar",
          "url": "magicutils-config-1.10.0.jar",
          "size": 70468,
          "sha512": "1f70b7e4c706d065174fdf588e00bbf024c9cc3b5955b30922b4abba598fc295c8a8270967cc359ddb7632760f350acd2c38ec5927246e5eed6d703ff028eeca",
          "sha256": "055e22fb2e2071984d7075e6432a06131dca99f1a49f681236e513220ea6a2de",
          "sha1": "553e6f0e6284d79334acc77ad1b147760b2c842b",
          "md5": "d016479705420f8566992c41e5291641"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-1.10.0.jar",
          "url": "magicutils-config-1.10.0.jar",
          "size": 70468,
          "sha512": "1f70b7e4c706d065174fdf588e00bbf024c9cc3b5955b30922b4abba598fc295c8a8270967cc359ddb7632760f350acd2c38ec5927246e5eed6d703ff028eeca",
          "sha256": "055e22fb2e2071984d7075e6432a06131dca99f1a49f681236e513220ea6a2de",
          "sha1": "553e6f0e6284d79334acc77ad1b147760b2c842b",
          "md5": "d016479705420f8566992c41e5291641"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.10.0-all.jar",
          "url": "magicutils-config-1.10.0-all.jar",
          "size": 2930355,
          "sha512": "21452fcff4cfdaadb9a3e3a3799dbaa79310ff5eef54d2f7857c6f4d6f17b49fb44c3c0e187315abe988fb8671f341d88f93f5566743c16139f08330813fc94b",
          "sha256": "df1c58a1ebeaddacb7c716e94b8bdc6a1ad11cc3fcedb1ed86768653fc11aa52",
          "sha1": "d36110d9fe779e9f230daddecbbabff2ec041c50",
          "md5": "0171a2bdb3c91c10ff57935b0913e598"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.10.0-sources.jar",
          "url": "magicutils-config-1.10.0-sources.jar",
          "size": 31617,
          "sha512": "da62f0831e080c383e076298e3154e60f4e5528bf999a04ed9b80e2be44cdfb1ff6ffc2ae3fc974fa1395d9b181a251adc445811f712482527ba0840252969cd",
          "sha256": "d2b133294f92321bc79a56b44df9657a4da8524f0c87e907ebcaeebbb58d137f",
          "sha1": "4b483d21224ca747b9ca8015b0fe54875c8d23d0",
          "md5": "ad9261dcf261d05b6c4d9afb5bfb7fe6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.10.0-javadoc.jar",
          "url": "magicutils-config-1.10.0-javadoc.jar",
          "size": 154977,
          "sha512": "9b37e1b9077e6def8d6a6113d1860ba5ab365bea62a5f42b505b72b5485bb34e03e2c33a9430ddbb29bdb95ab7dd48fddd0c336809955b5712f15d310266a9cb",
          "sha256": "c159d4520648e32ff1532934a0d4de71cf256ddb07e022320b6edf4d0da66f1b",
          "sha1": "42524d333c63e20a498d388ed3c7f6d213f26eb2",
          "md5": "2f2261721bd71a5ecd5bf9d989799f22"
        }
      ]
    }
  ]
}
