{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-config",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-1.10.0.jar",
          "url": "magicutils-config-1.10.0.jar",
          "size": 70468,
          "sha512": "cc94476a04c214e2a287e8b77604cd533a6c1af14c84c07af7f81e4925e5ad06c95717be28609901906246e0cdf4578ad608a50199b790f204d40d0007c9b7ad",
          "sha256": "de5d4792572ea53687c2ce7e3e10c7816bfc3af240f7c034f732528004009e15",
          "sha1": "a96c67eaa08352ff6a7cecd6265f84e0702b6d84",
          "md5": "30ca46371740e569010f5ff9acb68118"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-1.10.0.jar",
          "url": "magicutils-config-1.10.0.jar",
          "size": 70468,
          "sha512": "cc94476a04c214e2a287e8b77604cd533a6c1af14c84c07af7f81e4925e5ad06c95717be28609901906246e0cdf4578ad608a50199b790f204d40d0007c9b7ad",
          "sha256": "de5d4792572ea53687c2ce7e3e10c7816bfc3af240f7c034f732528004009e15",
          "sha1": "a96c67eaa08352ff6a7cecd6265f84e0702b6d84",
          "md5": "30ca46371740e569010f5ff9acb68118"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.10.0-all.jar",
          "url": "magicutils-config-1.10.0-all.jar",
          "size": 2930355,
          "sha512": "21452fcff4cfdaadb9a3e3a3799dbaa79310ff5eef54d2f7857c6f4d6f17b49fb44c3c0e187315abe988fb8671f341d88f93f5566743c16139f08330813fc94b",
          "sha256": "df1c58a1ebeaddacb7c716e94b8bdc6a1ad11cc3fcedb1ed86768653fc11aa52",
          "sha1": "d36110d9fe779e9f230daddecbbabff2ec041c50",
          "md5": "0171a2bdb3c91c10ff57935b0913e598"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.10.0-sources.jar",
          "url": "magicutils-config-1.10.0-sources.jar",
          "size": 31617,
          "sha512": "879362aaaa1c8e83f8036b79a3ac54b11829585a00149d8a6bbc8956680135047e1a422bfc2f9a4ab800c106a5dc9ebf9e23470e4515a5abb1b36c421b1d42cc",
          "sha256": "102daea09482c2db524906adecfe8ee2056c7669f809327c52d32ffe534834cc",
          "sha1": "801b6b30dca3c2ff61d3916e388266fd230dbaa5",
          "md5": "324889786f1c3b5b8c972dbbecd0a09f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.10.0-javadoc.jar",
          "url": "magicutils-config-1.10.0-javadoc.jar",
          "size": 154977,
          "sha512": "96e9004185949ecc1fdf72ab22da5d65d7a69430209a8fa69bfb0cb8e742f5e4b7b6d53219fb59d1930992fa6e228167299e95cbea356a3fcb9781ac6dbd0e2c",
          "sha256": "47fdd7ab53f4e4be022785c1ec3a382818cca89d4ba50aba46a14ea74d66a97e",
          "sha1": "2a50bb1c4ec085234da34468bb613e9341587017",
          "md5": "9a4a5835e6b5a2d9e9fb1eada219b425"
        }
      ]
    }
  ]
}
