{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bukkit",
    "version": "1.21.1-mc2611",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.1-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.1-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.21.1-mc2611-mc26.1.jar",
          "url": "magicutils-bukkit-1.21.1-mc2611-mc26.1.jar",
          "size": 137711,
          "sha512": "a433e5dcf140d9ec8ba7289fa1a75bf904c1ad9d7fd3cded2d0216e84868cac878ea363b8cbb2aa3dc94cdfebba947751549a00887baf6e12d4639d3d83705c7",
          "sha256": "d4bfed6f5652341f940460dce956b136c3264572f7de902ef040909909ede0d0",
          "sha1": "511ba8afecd15b6a24f18a1c2a80b318dc2bc0e8",
          "md5": "f1f25d8d0b39f17077fe661362ebe2f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.1-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.1-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.21.1-mc2611-mc26.1.jar",
          "url": "magicutils-bukkit-1.21.1-mc2611-mc26.1.jar",
          "size": 137711,
          "sha512": "a433e5dcf140d9ec8ba7289fa1a75bf904c1ad9d7fd3cded2d0216e84868cac878ea363b8cbb2aa3dc94cdfebba947751549a00887baf6e12d4639d3d83705c7",
          "sha256": "d4bfed6f5652341f940460dce956b136c3264572f7de902ef040909909ede0d0",
          "sha1": "511ba8afecd15b6a24f18a1c2a80b318dc2bc0e8",
          "md5": "f1f25d8d0b39f17077fe661362ebe2f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.1-mc2611-sources.jar",
          "url": "magicutils-bukkit-1.21.1-mc2611-sources.jar",
          "size": 59830,
          "sha512": "53e94fae59db7a9ebf65137b8ab321bcb4fae0282d6e06f1e2715580cbf1c5cb80b6b845d63771353f9485b432e9d4b2358fb07a1a1957d0a985a436d983699b",
          "sha256": "31accedcce4e0028bd11fc4b8fe9cc11c181b83840e5bec49937a7324e04cfc3",
          "sha1": "4ff8c65cc052f02986d54ce44a2591b8e1d80845",
          "md5": "ae938ea6f30d022ce01b5d70d389df39"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.1-mc2611-javadoc.jar",
          "url": "magicutils-bukkit-1.21.1-mc2611-javadoc.jar",
          "size": 4353133,
          "sha512": "ccf068fe1f9edeafbdbfec09099baab2ca04ef0b71c23cc12986a3badb5c45db89bb3d47bd3fb864b5b129a8a1d23175512ce24314f8856dec2730505d67e24f",
          "sha256": "9f0f320c47cc1e7763cdd5e2bc4c302779c675e68bd35de54f74c836af1387da",
          "sha1": "b23a66896928d80fca3869521949998fb1d5a551",
          "md5": "6cfdded0dcbc0f1fd5114c9eab8340aa"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.1-mc2611-all.jar",
          "url": "magicutils-bukkit-1.21.1-mc2611-all.jar",
          "size": 3639813,
          "sha512": "8e8695d63b18d617994ea0b2f1e6f1c441532a450bec715be73d19e093551282e62ee9f40892357b0a6dae2b5ec05592afa8b22e3c0a949babaee29e8e173387",
          "sha256": "d54696641121c8b188ed8540a0abfb443a9390afeddcc912a82a387636ad4c09",
          "sha1": "2c7ae26a3bbb17acd0d7b2305f6a5d0723659f59",
          "md5": "6f7744ec046222b5efed2859d01897c9"
        }
      ]
    }
  ]
}
