{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-velocity",
    "version": "1.14.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-velocity-1.14.3-mc1.21.jar",
          "url": "magicutils-velocity-1.14.3-mc1.21.jar",
          "size": 38274,
          "sha512": "34037e452fbf71a93c5cc1729ffdcd72121ab9d46705fd21f0340f42eb721caa8fe5283fc311971be0883f6ff7aa740fbfa2db4ff7715503b9408ba73688e3e1",
          "sha256": "04e90c82f5acc508691abbe790a68af527d4086454d1d5eae0ffcf05c01c6ae6",
          "sha1": "e993f9e837bd4cf9441ebc40c00e7318fbc201bc",
          "md5": "49b59798789cffd7e00a541f53b5a3b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-velocity-1.14.3-mc1.21.jar",
          "url": "magicutils-velocity-1.14.3-mc1.21.jar",
          "size": 38274,
          "sha512": "34037e452fbf71a93c5cc1729ffdcd72121ab9d46705fd21f0340f42eb721caa8fe5283fc311971be0883f6ff7aa740fbfa2db4ff7715503b9408ba73688e3e1",
          "sha256": "04e90c82f5acc508691abbe790a68af527d4086454d1d5eae0ffcf05c01c6ae6",
          "sha1": "e993f9e837bd4cf9441ebc40c00e7318fbc201bc",
          "md5": "49b59798789cffd7e00a541f53b5a3b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.14.3-sources.jar",
          "url": "magicutils-velocity-1.14.3-sources.jar",
          "size": 14617,
          "sha512": "77f0d02b0244c5aec67695cd7df5cfb6fdd1182b5b3495c538df78053f6fd78a62cfac6a037ce8eb3161662ae1ca6857eb73cc05fafede15711e4a989e1b6ae0",
          "sha256": "9737347738110514ff593d07cd7ca7f83bf564f9fc32a4a1672dd5defd86d857",
          "sha1": "5edfd4b307937bbb69996e05b30fa30778248dbc",
          "md5": "19cab55fe5d558a730b8a947424a1285"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.14.3-javadoc.jar",
          "url": "magicutils-velocity-1.14.3-javadoc.jar",
          "size": 128596,
          "sha512": "05bdf66128337e047ee3539d1b6a791b573e7a113cfa9575fd0b042cb5188bbf936825f44657be9a8525cd331083540ea0231c725235321a779f5182ddeff756",
          "sha256": "b578661fb0397a46fb5ed4151a70b3eafb83edcb46dc82da234a603b7c1ffc15",
          "sha1": "7f9cf49d549dc486368b9650d9452882e1cea733",
          "md5": "7690b6ef313241c8b64110b8004da481"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.14.3-all.jar",
          "url": "magicutils-velocity-1.14.3-all.jar",
          "size": 3447305,
          "sha512": "dd69e396425155af3468877a7e3a8e415171697c4e388884665bcc1fd304d63e9f80e3726a778b5ec9f2a1bc0058dd22bd169153c1ce7461cddb76dc629d5e6d",
          "sha256": "3eebe248a02391c8e2eab6487c9a4199bbc76129a10c6902efeac6a17fff0811",
          "sha1": "8d8b1b32ab0b489c6f306b705d765fac30456062",
          "md5": "0d9aa2ecb7100a4e9d7527208e584150"
        }
      ]
    }
  ]
}
