{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-velocity",
    "version": "1.14.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-velocity-1.14.3-mc1.21.jar",
          "url": "magicutils-velocity-1.14.3-mc1.21.jar",
          "size": 38274,
          "sha512": "34037e452fbf71a93c5cc1729ffdcd72121ab9d46705fd21f0340f42eb721caa8fe5283fc311971be0883f6ff7aa740fbfa2db4ff7715503b9408ba73688e3e1",
          "sha256": "04e90c82f5acc508691abbe790a68af527d4086454d1d5eae0ffcf05c01c6ae6",
          "sha1": "e993f9e837bd4cf9441ebc40c00e7318fbc201bc",
          "md5": "49b59798789cffd7e00a541f53b5a3b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-velocity-1.14.3-mc1.21.jar",
          "url": "magicutils-velocity-1.14.3-mc1.21.jar",
          "size": 38274,
          "sha512": "34037e452fbf71a93c5cc1729ffdcd72121ab9d46705fd21f0340f42eb721caa8fe5283fc311971be0883f6ff7aa740fbfa2db4ff7715503b9408ba73688e3e1",
          "sha256": "04e90c82f5acc508691abbe790a68af527d4086454d1d5eae0ffcf05c01c6ae6",
          "sha1": "e993f9e837bd4cf9441ebc40c00e7318fbc201bc",
          "md5": "49b59798789cffd7e00a541f53b5a3b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.14.3-sources.jar",
          "url": "magicutils-velocity-1.14.3-sources.jar",
          "size": 14617,
          "sha512": "77f0d02b0244c5aec67695cd7df5cfb6fdd1182b5b3495c538df78053f6fd78a62cfac6a037ce8eb3161662ae1ca6857eb73cc05fafede15711e4a989e1b6ae0",
          "sha256": "9737347738110514ff593d07cd7ca7f83bf564f9fc32a4a1672dd5defd86d857",
          "sha1": "5edfd4b307937bbb69996e05b30fa30778248dbc",
          "md5": "19cab55fe5d558a730b8a947424a1285"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.14.3-javadoc.jar",
          "url": "magicutils-velocity-1.14.3-javadoc.jar",
          "size": 128596,
          "sha512": "05bdf66128337e047ee3539d1b6a791b573e7a113cfa9575fd0b042cb5188bbf936825f44657be9a8525cd331083540ea0231c725235321a779f5182ddeff756",
          "sha256": "b578661fb0397a46fb5ed4151a70b3eafb83edcb46dc82da234a603b7c1ffc15",
          "sha1": "7f9cf49d549dc486368b9650d9452882e1cea733",
          "md5": "7690b6ef313241c8b64110b8004da481"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.14.3-all.jar",
          "url": "magicutils-velocity-1.14.3-all.jar",
          "size": 3447303,
          "sha512": "d3d3511d793128b290d4ae6db3c87672c70da7f9c494a71ce3527de73954ae7bcd9d8db7f682aa0706d0318b3ba752978cbc9bbd47b1fb78ac0627c0a0983093",
          "sha256": "63c7086848e0bc1b3508956dbb299591a40899eb1cf5880902678b0f36372f1c",
          "sha1": "302cdb4e44c24ddd623eb2b3d1404475758c61eb",
          "md5": "d504e284495b64d534aa77cb96dc07a8"
        }
      ]
    }
  ]
}
