{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-neoforge",
    "version": "1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.21.4-mc1.21.jar",
          "url": "magicutils-neoforge-1.21.4-mc1.21.jar",
          "size": 23837,
          "sha512": "4899651e64dcda4e6f25fcf0525d8955468a77a462683730fab24836086365eec89feb0834df6acc04fd8bf151d4a9b046938482b36f1cd4200a1992aa1c6ca6",
          "sha256": "5adfc1dddae6dbb771471a5b96bc8cd36886eaa809f4042fffb0cf67cd48a6ef",
          "sha1": "0af80c228f6b60dc614ddf5b949bc81c1fde2820",
          "md5": "c28e623b6d8311fbbf23b120b501e855"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.21.4-mc1.21.jar",
          "url": "magicutils-neoforge-1.21.4-mc1.21.jar",
          "size": 23837,
          "sha512": "4899651e64dcda4e6f25fcf0525d8955468a77a462683730fab24836086365eec89feb0834df6acc04fd8bf151d4a9b046938482b36f1cd4200a1992aa1c6ca6",
          "sha256": "5adfc1dddae6dbb771471a5b96bc8cd36886eaa809f4042fffb0cf67cd48a6ef",
          "sha1": "0af80c228f6b60dc614ddf5b949bc81c1fde2820",
          "md5": "c28e623b6d8311fbbf23b120b501e855"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.21.4-sources.jar",
          "url": "magicutils-neoforge-1.21.4-sources.jar",
          "size": 11938,
          "sha512": "544ab1961a75b0f63cf82fc8cdd4f8a8305f2d659692563ffc3f7073fee749b0096b2cf81d1fec8f2fb07431c8a3ba2f1c1beda9ee61aa01203028eec1f73b38",
          "sha256": "a6596cb4f0cfbf218a254d9d022a81b8c7e0bcbd988fd8402ca29900c05418c3",
          "sha1": "ed588c451a1a3d8f9d733a9d047e1b1aa1a96af3",
          "md5": "8f8275ef04ff51a5d4d40acee2646404"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.21.4-javadoc.jar",
          "url": "magicutils-neoforge-1.21.4-javadoc.jar",
          "size": 119864,
          "sha512": "cace247fe279765eab97000c01cc068f0f8cda44c854a8b50acebb392c554c95fd521f3124473cc0f95d38489aef1783535eba81270b6debd3a24e5b9eb0babf",
          "sha256": "976e3f0c86e6d092c64e6cc3d88f8d9a5ff6c0fa9bc7d6d36b3a08a9a107c0d3",
          "sha1": "3f4fb61a133282c0662b6889fc1cd8676fa8b39e",
          "md5": "0b097ad4e6d5a370b413bbde188cd7f2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.21.4-all.jar",
          "url": "magicutils-neoforge-1.21.4-all.jar",
          "size": 40394821,
          "sha512": "29d37a5d02651c7f2cd4a67891c25b12e101455295a51db27075f522e6d1806e84a5a90c1e023feee687cb244b886093934bcc48e5c8025ac22da08cb6565b88",
          "sha256": "2c2e66e9add6c9f8a196d9d9ff9e7374d8f4a3c68a7c4fc249603076b1e6fb47",
          "sha1": "4f2d7d979faa1830f36ac27d135f6f838f6e337b",
          "md5": "5a1aa5e1bf0fd7c8c1e0cad909d2149e"
        }
      ]
    }
  ]
}
