{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-http-client",
    "version": "1.18.1-mc2611",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.18.1-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.18.1-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.18.1-mc2611-mc26.1.jar",
          "url": "magicutils-http-client-1.18.1-mc2611-mc26.1.jar",
          "size": 58197,
          "sha512": "b53cd29092b7c3fd0193199235d7c512639c4f69c4fca2334e97dac472467e83ad2285662b37bdc83836666a3f54804490d11135b4c37611de4e21275f608d26",
          "sha256": "57488e93d717c0f235e00d27d662e3a9986c837b62a0d6139f0e779e2366f1fa",
          "sha1": "fa4585052c47d410c3b3388b0f2d966225b785bf",
          "md5": "aee5207d0c40fecc09de68636f781f24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.18.1-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.18.1-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.18.1-mc2611-mc26.1.jar",
          "url": "magicutils-http-client-1.18.1-mc2611-mc26.1.jar",
          "size": 58197,
          "sha512": "b53cd29092b7c3fd0193199235d7c512639c4f69c4fca2334e97dac472467e83ad2285662b37bdc83836666a3f54804490d11135b4c37611de4e21275f608d26",
          "sha256": "57488e93d717c0f235e00d27d662e3a9986c837b62a0d6139f0e779e2366f1fa",
          "sha1": "fa4585052c47d410c3b3388b0f2d966225b785bf",
          "md5": "aee5207d0c40fecc09de68636f781f24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.18.1-mc2611-sources.jar",
          "url": "magicutils-http-client-1.18.1-mc2611-sources.jar",
          "size": 21590,
          "sha512": "94fde141f0c6aa3a602f194001bb5d9ad3c924882c6f3e07209ba8b8cc11f72c6e9457102864565d6585a3ddad4ffecc68bd63ba15345c5e4fb7133cebc699c0",
          "sha256": "d56fd445eccd8f18d0dc1cbd0a4e52ef38ea3ae752784fd7b9775bf86f362081",
          "sha1": "c75bc9748d407dc223ef8b26d8a203437fa98cf9",
          "md5": "fbf841914dd9cb02b159c954a7176056"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.18.1-mc2611-javadoc.jar",
          "url": "magicutils-http-client-1.18.1-mc2611-javadoc.jar",
          "size": 4207750,
          "sha512": "ec2113c091d9843b4ff12ad80fd8fce397b1c004e414ec82bc0da7187c4be5c63b0e67538e3656f128b91b7b861694c465f2fb3533d57ff721f05925ab95ec33",
          "sha256": "a726813a596843cf08bea4f8e2fcef8e082a1ecce6cf1e7e0d4a415e192ec971",
          "sha1": "cc3ecca7f0038f966529a5fc324e38c2b0ffc70b",
          "md5": "931dd094c686d87812c8b3f0f6c76c94"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.18.1-mc2611-all.jar",
          "url": "magicutils-http-client-1.18.1-mc2611-all.jar",
          "size": 3471966,
          "sha512": "e7077787914c79bf9cb9b64d9eef8bd340020c5bd2c7b71aa612d9ea91e8afde6352a51494cc2bf1045f17ff64d7b462144775009de2d1f259caa862f1845526",
          "sha256": "02f79cdb4e74ef7d20004fc6054be9d813ca19c582cb60e00b5b8ceaed612d04",
          "sha1": "acd28b916a8737aa3e5275a572d3d720d4825f1c",
          "md5": "cab42d24291639c64287213584ee81fb"
        }
      ]
    }
  ]
}
