{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands",
    "version": "1.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-1.13.1-mc1.21.jar",
          "url": "magicutils-commands-1.13.1-mc1.21.jar",
          "size": 165508,
          "sha512": "e710865abef6493ae0daf1894c541c164bb7681524fcb7ed268c47732bcb7ed723f7236e8858a04e74a96841a66cc64c01390fe1b404016f51f97864e0aa3508",
          "sha256": "0d7535f3c31c7b4f16283af00e279be9cd27aba3973811525bb37fe5b3ed9a5f",
          "sha1": "6f706052561a844377831fc0408306fbaf079c86",
          "md5": "1d78af17b8aa9a70645bd8afcd9a5fde"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-1.13.1-mc1.21.jar",
          "url": "magicutils-commands-1.13.1-mc1.21.jar",
          "size": 165508,
          "sha512": "e710865abef6493ae0daf1894c541c164bb7681524fcb7ed268c47732bcb7ed723f7236e8858a04e74a96841a66cc64c01390fe1b404016f51f97864e0aa3508",
          "sha256": "0d7535f3c31c7b4f16283af00e279be9cd27aba3973811525bb37fe5b3ed9a5f",
          "sha1": "6f706052561a844377831fc0408306fbaf079c86",
          "md5": "1d78af17b8aa9a70645bd8afcd9a5fde"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.13.1-sources.jar",
          "url": "magicutils-commands-1.13.1-sources.jar",
          "size": 73112,
          "sha512": "b8d6185de17b3062c09ccb5fbb9793655919b77e05d2c91ca08d9da38d1311f7811b252a73ace5843cc8829734fbbc398a6f6b617e888c895eb3195384fdef0a",
          "sha256": "12b090fe4de8518922fa749b478820e2b0bdfc3d088f3184a1705e11c9c4b64d",
          "sha1": "31bbb9b9c84f044855921be0d0ac3813468773b5",
          "md5": "9c37c367900591cc9ec654aabdf817b0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.13.1-javadoc.jar",
          "url": "magicutils-commands-1.13.1-javadoc.jar",
          "size": 283709,
          "sha512": "0698ad5e35e3d2e88a1a7d253df9ab1f07ef39ddbfe5f48cb0b9b609ebfe683f2376092eebea3a4ee698c86d5dc8927442bc5bc50b45f20b1b0f2ff5d47e6791",
          "sha256": "2f28f0b7f3313decf4f8bb8d19242b5c1ce4b0348f4ca7f41432c5cd71e746be",
          "sha1": "0aae21efd20d349274cb42c7416469f5d253fa92",
          "md5": "972d307f88ea28a003cc4a5038a2b5ce"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.13.1-all.jar",
          "url": "magicutils-commands-1.13.1-all.jar",
          "size": 3381704,
          "sha512": "1e95072c25215b54d36473e1ccd439e57792fde160ebd04be1e3d7a6c12740dc0483e9bec4e8c33e72b391ae2e74f009604fa3fbcba3e8277169865e97b45aca",
          "sha256": "997409909bb921f7a7dded11605a0193f8f1820bd2b00624bea254c58a74e72f",
          "sha1": "2799fa660c055ee36f89576840fa5fa098f677a6",
          "md5": "0f55b2f2b8a191dc8e77cd51dcbe3b7e"
        }
      ]
    }
  ]
}
