{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands",
    "version": "1.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-1.13.1-mc1.21.jar",
          "url": "magicutils-commands-1.13.1-mc1.21.jar",
          "size": 168941,
          "sha512": "c226cabb2421c3840618093866fc96355b76c1bdac70e71de610f70c2f69ded2bafb2bf5b1bf6bea0f78fe59407da9466ad3e1eda6044cdb0be54bfe64520f43",
          "sha256": "1b039d2bcbf3c54271a187f484ee3a91515ee659bf747c652f07d44b4c7251ac",
          "sha1": "0ff3fe9a5a7c6f3a21c529c57221eecf91bb0bc5",
          "md5": "2b512137a63e5aa62cb230817d7e34bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-1.13.1-mc1.21.jar",
          "url": "magicutils-commands-1.13.1-mc1.21.jar",
          "size": 168941,
          "sha512": "c226cabb2421c3840618093866fc96355b76c1bdac70e71de610f70c2f69ded2bafb2bf5b1bf6bea0f78fe59407da9466ad3e1eda6044cdb0be54bfe64520f43",
          "sha256": "1b039d2bcbf3c54271a187f484ee3a91515ee659bf747c652f07d44b4c7251ac",
          "sha1": "0ff3fe9a5a7c6f3a21c529c57221eecf91bb0bc5",
          "md5": "2b512137a63e5aa62cb230817d7e34bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.13.1-sources.jar",
          "url": "magicutils-commands-1.13.1-sources.jar",
          "size": 74452,
          "sha512": "80f2522e1bb29297a3ed30101456d2852bf4e45509f5f190beebb19d888c95e87eb2445b29f64d85bb2b3d98f306f78e2f91744eb67457fb95a1fb677dc10022",
          "sha256": "109adf1c75b42e3621819ee19c1206ae92c4712ded3378ee20593fb7edb564bd",
          "sha1": "769b1786b235563b8df563fae5ad8aebba66498a",
          "md5": "52db5ad6a2ee6fbe11a0ce5e62818ff7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.13.1-javadoc.jar",
          "url": "magicutils-commands-1.13.1-javadoc.jar",
          "size": 292459,
          "sha512": "c23a363349a51e5f57a9532bba19f5450d9b65665ea98010a96950e3a45010376224c2ff5544e095c18a98b6575a0519f1bd464f967b8972cb66d635dfe6cde0",
          "sha256": "a9351f7214c43d0341e86fbf527fb00e3297c3fb475ab262af8eb233eea3cf93",
          "sha1": "24d5fc225b4b224bd8a2f188f8993cf963c96269",
          "md5": "2db93f65061831741b75b122246bae28"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-1.13.1-all.jar",
          "url": "magicutils-commands-1.13.1-all.jar",
          "size": 3385168,
          "sha512": "b8e4fc40537147cb5e104ea5c3ead83d7fd1c29433b133f626c770209bab10e4743460729179c1b816682ad7ec07a4faa603f7c2348c2f096e694714b1e9eb56",
          "sha256": "ba6806cdda2595aea3b4d759991485ec5646359e4d158292154edadf6aeccec1",
          "sha1": "e66c2500705905c14801eb7fdea37c667e70fc22",
          "md5": "e8283aafdbd5f65dcbdbcab6f246a25d"
        }
      ]
    }
  ]
}
