{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bukkit",
    "version": "1.21.3-mc1201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.3-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.3-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.21.3-mc1201-mc1.20.jar",
          "url": "magicutils-bukkit-1.21.3-mc1201-mc1.20.jar",
          "size": 137384,
          "sha512": "9b2e0a8085963773a1052a2accc8b6bc82f5da5278d47c8040819ee6db066f9ab1882665f414631235423c8708524d9cac89e19eccb3ae08451a5f5513802af1",
          "sha256": "6ba116a1cf5d2b301a2a70fa7afa78623c14494e07655e32015bf09194153628",
          "sha1": "bf9a43da574ef13dbf2e4ed31b682843e0088b73",
          "md5": "49e959e80e818a051a2fd6cacc995fc5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.3-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.3-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.21.3-mc1201-mc1.20.jar",
          "url": "magicutils-bukkit-1.21.3-mc1201-mc1.20.jar",
          "size": 137384,
          "sha512": "9b2e0a8085963773a1052a2accc8b6bc82f5da5278d47c8040819ee6db066f9ab1882665f414631235423c8708524d9cac89e19eccb3ae08451a5f5513802af1",
          "sha256": "6ba116a1cf5d2b301a2a70fa7afa78623c14494e07655e32015bf09194153628",
          "sha1": "bf9a43da574ef13dbf2e4ed31b682843e0088b73",
          "md5": "49e959e80e818a051a2fd6cacc995fc5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.3-mc1201-sources.jar",
          "url": "magicutils-bukkit-1.21.3-mc1201-sources.jar",
          "size": 59830,
          "sha512": "53e94fae59db7a9ebf65137b8ab321bcb4fae0282d6e06f1e2715580cbf1c5cb80b6b845d63771353f9485b432e9d4b2358fb07a1a1957d0a985a436d983699b",
          "sha256": "31accedcce4e0028bd11fc4b8fe9cc11c181b83840e5bec49937a7324e04cfc3",
          "sha1": "4ff8c65cc052f02986d54ce44a2591b8e1d80845",
          "md5": "ae938ea6f30d022ce01b5d70d389df39"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.3-mc1201-javadoc.jar",
          "url": "magicutils-bukkit-1.21.3-mc1201-javadoc.jar",
          "size": 272481,
          "sha512": "05b775f2dea62680d4eb80c8839a9b8874be237f389deea2808da935f9b3e761d50e7f8705bc32e779d28f0c1a1005c5b2c6b9abf340ea4c8fc697c34345c957",
          "sha256": "ffda697a1b173456a773df204b5d9efd371f9e1333c5fd5a6b23f8d2edf3b7b1",
          "sha1": "0320cf047fa961576f8f28cbc47a4bfad349d112",
          "md5": "214c9177151aac95d80da515e10a801c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.3-mc1201-all.jar",
          "url": "magicutils-bukkit-1.21.3-mc1201-all.jar",
          "size": 3639606,
          "sha512": "a70c59d50d212a2bcca1dfccfe8dcfc7c0913d69a498626b9f8d944d9934e60c3eaa7054eae3b908432112653ee55dea2afbf08e525b21d0a6f1f210955ddc29",
          "sha256": "e5834157d18ec20f131504de4a122f70a6837a9355f70979c6da567ce93a3101",
          "sha1": "3b994f17c5cc1431a120f027488f1c006b4ff921",
          "md5": "988bdfbbb8301633cd4a5c0da21c7149"
        }
      ]
    }
  ]
}
