{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bukkit",
    "version": "1.21.3-mc2611",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.21.3-mc2611-mc26.1.jar",
          "url": "magicutils-bukkit-1.21.3-mc2611-mc26.1.jar",
          "size": 137712,
          "sha512": "8a04146f8f7dcb998d6bedd456799b61305611ada3d1a0017351c1a459c5c729b05f57f7dda4c9549317905f852b8aa3b51cbfa41f6f06e09543feeee96db75c",
          "sha256": "7c36f9c2980777cfc5a4db73d64ab13188ffac62433ffe83e1452cad4ac42775",
          "sha1": "45eb9e96d0870b37effada4a1a8ed5e4e17c57fd",
          "md5": "1cf7cb98e4ad24eeac24172b0b82e05a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.21.3-mc2611-mc26.1.jar",
          "url": "magicutils-bukkit-1.21.3-mc2611-mc26.1.jar",
          "size": 137712,
          "sha512": "8a04146f8f7dcb998d6bedd456799b61305611ada3d1a0017351c1a459c5c729b05f57f7dda4c9549317905f852b8aa3b51cbfa41f6f06e09543feeee96db75c",
          "sha256": "7c36f9c2980777cfc5a4db73d64ab13188ffac62433ffe83e1452cad4ac42775",
          "sha1": "45eb9e96d0870b37effada4a1a8ed5e4e17c57fd",
          "md5": "1cf7cb98e4ad24eeac24172b0b82e05a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.3-mc2611-sources.jar",
          "url": "magicutils-bukkit-1.21.3-mc2611-sources.jar",
          "size": 59830,
          "sha512": "53e94fae59db7a9ebf65137b8ab321bcb4fae0282d6e06f1e2715580cbf1c5cb80b6b845d63771353f9485b432e9d4b2358fb07a1a1957d0a985a436d983699b",
          "sha256": "31accedcce4e0028bd11fc4b8fe9cc11c181b83840e5bec49937a7324e04cfc3",
          "sha1": "4ff8c65cc052f02986d54ce44a2591b8e1d80845",
          "md5": "ae938ea6f30d022ce01b5d70d389df39"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.3-mc2611-javadoc.jar",
          "url": "magicutils-bukkit-1.21.3-mc2611-javadoc.jar",
          "size": 4353145,
          "sha512": "a0288b82914271ea519d040a88a9f44dc913c904fa0c78471f96f4b8894e62c4fb9e5d114612108e567ea3cb529d0cfc3eef6a6e35ed7cefe5ba1183d6bd138e",
          "sha256": "0683d6117333f716433afe308df70c00cafb6b2b159213db7a15ed99430f0b11",
          "sha1": "a7907b168f6ff72d556776da1ff348cd415303a4",
          "md5": "369e3af3ee768638f6021836de14beca"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.3-mc2611-all.jar",
          "url": "magicutils-bukkit-1.21.3-mc2611-all.jar",
          "size": 3640055,
          "sha512": "017b1a1af80b3bf9581861f82c5dc3106b47db191a6a1d42f764f8f4573199be1173a6ea49f69be4084004ef4795e08c358d5c37f8ae99c02f65f973a69e06b2",
          "sha256": "33ceb71a5eed2002fa30b9b7407e330cdde1aaaf47aaf43183455c017fc90d9f",
          "sha1": "78a306df34a234bbea83415d9e633089754db3fa",
          "md5": "1ecbfa9d2f7660c8307af53b11c95944"
        }
      ]
    }
  ]
}
