{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-http-client",
    "version": "1.21.3-mc2611",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.21.3-mc2611-mc26.1.jar",
          "url": "magicutils-http-client-1.21.3-mc2611-mc26.1.jar",
          "size": 58197,
          "sha512": "b53cd29092b7c3fd0193199235d7c512639c4f69c4fca2334e97dac472467e83ad2285662b37bdc83836666a3f54804490d11135b4c37611de4e21275f608d26",
          "sha256": "57488e93d717c0f235e00d27d662e3a9986c837b62a0d6139f0e779e2366f1fa",
          "sha1": "fa4585052c47d410c3b3388b0f2d966225b785bf",
          "md5": "aee5207d0c40fecc09de68636f781f24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.21.3-mc2611-mc26.1.jar",
          "url": "magicutils-http-client-1.21.3-mc2611-mc26.1.jar",
          "size": 58197,
          "sha512": "b53cd29092b7c3fd0193199235d7c512639c4f69c4fca2334e97dac472467e83ad2285662b37bdc83836666a3f54804490d11135b4c37611de4e21275f608d26",
          "sha256": "57488e93d717c0f235e00d27d662e3a9986c837b62a0d6139f0e779e2366f1fa",
          "sha1": "fa4585052c47d410c3b3388b0f2d966225b785bf",
          "md5": "aee5207d0c40fecc09de68636f781f24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.21.3-mc2611-sources.jar",
          "url": "magicutils-http-client-1.21.3-mc2611-sources.jar",
          "size": 21590,
          "sha512": "94fde141f0c6aa3a602f194001bb5d9ad3c924882c6f3e07209ba8b8cc11f72c6e9457102864565d6585a3ddad4ffecc68bd63ba15345c5e4fb7133cebc699c0",
          "sha256": "d56fd445eccd8f18d0dc1cbd0a4e52ef38ea3ae752784fd7b9775bf86f362081",
          "sha1": "c75bc9748d407dc223ef8b26d8a203437fa98cf9",
          "md5": "fbf841914dd9cb02b159c954a7176056"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.21.3-mc2611-javadoc.jar",
          "url": "magicutils-http-client-1.21.3-mc2611-javadoc.jar",
          "size": 4207751,
          "sha512": "0e63535e805937f7f5e00e1cb8235919e6d31a31e118c4276c22010e90cce716e775ac68d0badc019e7662eee0b7ebf4daf39a59e9dcd1cc4a9ca8228f63f528",
          "sha256": "6b587d7ed6eb7147104b72f7b1ec389a7e12245929e8d3ec0bb8f7ca0a1dd9fd",
          "sha1": "e58800544c5cced6d860b9fcde69c8ce0b91212f",
          "md5": "268cec4f3fec33ce505b87ede81b5188"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.21.3-mc2611-all.jar",
          "url": "magicutils-http-client-1.21.3-mc2611-all.jar",
          "size": 3500334,
          "sha512": "299658f3e2318e866a618eb814db2e708f639e0b6f27d7f4df34075d604c443e25f0a3468dc365cbde1a4e4654db20a9897d50ea35887f6fc47b1728ca51a03e",
          "sha256": "2e4c0fa4e4ec2623566030bee6aaaf9b72ecf049e6e8b098b87827c10b684b56",
          "sha1": "5c934af9a7f5c6ac2e4e5c3f64877a91f361e222",
          "md5": "e2f95e54212d7f23dc7191d5fb183573"
        }
      ]
    }
  ]
}
