{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-placeholders",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-placeholders-1.10.0.jar",
          "url": "magicutils-placeholders-1.10.0.jar",
          "size": 8537,
          "sha512": "8cd969c4c317008dd982889d58c461282f44b2b37f400f5d2796f680aaf062876fc80173bb5a4c4718603ae3d1a89c11e514ad9222a8e4322bab601c4e35df90",
          "sha256": "7d8b1bd42eb4a70f80c574461841d52c868b4a3069e908b03cd34786e4f74cda",
          "sha1": "59dc2a6693284ce2b60d0409ab4593cf3f265aea",
          "md5": "55ff5d790efb1df689f2c0a758ef51fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-placeholders-1.10.0.jar",
          "url": "magicutils-placeholders-1.10.0.jar",
          "size": 8537,
          "sha512": "8cd969c4c317008dd982889d58c461282f44b2b37f400f5d2796f680aaf062876fc80173bb5a4c4718603ae3d1a89c11e514ad9222a8e4322bab601c4e35df90",
          "sha256": "7d8b1bd42eb4a70f80c574461841d52c868b4a3069e908b03cd34786e4f74cda",
          "sha1": "59dc2a6693284ce2b60d0409ab4593cf3f265aea",
          "md5": "55ff5d790efb1df689f2c0a758ef51fd"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-placeholders-1.10.0-all.jar",
          "url": "magicutils-placeholders-1.10.0-all.jar",
          "size": 500740,
          "sha512": "32a108e5a4ca012a598921e9bb4e1b26824892b864ac4f7878f82a69b27a73f5542de36a1ea71b66a9476349cefadd9e801608b6641c08349047d5d117b77c6a",
          "sha256": "08a18e4fc04ee739dd76f657a487d422de27f663f898a531790f788c763be115",
          "sha1": "1366301b4e2033894fb28ebf44fa50586db42116",
          "md5": "ecc42701f601b73975b2d07bec5ca562"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-placeholders-1.10.0-sources.jar",
          "url": "magicutils-placeholders-1.10.0-sources.jar",
          "size": 3448,
          "sha512": "4afbd6ab2c5d45936ee3fddf13d5edbc8668589d00fa9f6c45dfede2bd9848334e677dc4a06b81d3e2e1cb867f29b1bc9caaafc037310a16e3dbaa8c6d02e8c0",
          "sha256": "955fcb75ed7f5294b46421ebdce7cae8b292b20f15bc228ad25a9f673602da92",
          "sha1": "1b4a69d9dc0de27b80642b846a0f6d313bcea0f0",
          "md5": "6cb240af19158f6117d23a4ded00dab1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-placeholders-1.10.0-javadoc.jar",
          "url": "magicutils-placeholders-1.10.0-javadoc.jar",
          "size": 106655,
          "sha512": "a371997e5d8a4059e9e2c73fa94591f8a98995c9272ae55ed5bf4d139cdd9bb9c68820c48b893603e1b6227049fdab9857682b779358ef5566dd510c12fddb6a",
          "sha256": "b2fc644ddf01cc6bf7844fc389b0c114878128e2645c532100b1bdcba3e6730d",
          "sha1": "af3263fb75a010d94824801ae9e14afac1c4b1d8",
          "md5": "f19231b003197c04c2cbd81bcf50cb23"
        }
      ]
    }
  ]
}
