{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-placeholders",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-placeholders-1.10.0.jar",
          "url": "magicutils-placeholders-1.10.0.jar",
          "size": 8537,
          "sha512": "b71386e8ca09741b6eff71741e8228ec1fdd470754bcffdc05a45893e28616bb6eaa1cc5142f8a55a79cd84e5c7d7b6bbe1007241dd66d4d62339b3f6cfb3e6b",
          "sha256": "89ea134bc7a3e62c68450ec09831212646617087e99f1c535642a259311ae08e",
          "sha1": "17327cabd904443e485cb1de05b913745a7b6d6e",
          "md5": "82cb39f062963ce10db2f91377647eb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-placeholders-1.10.0.jar",
          "url": "magicutils-placeholders-1.10.0.jar",
          "size": 8537,
          "sha512": "b71386e8ca09741b6eff71741e8228ec1fdd470754bcffdc05a45893e28616bb6eaa1cc5142f8a55a79cd84e5c7d7b6bbe1007241dd66d4d62339b3f6cfb3e6b",
          "sha256": "89ea134bc7a3e62c68450ec09831212646617087e99f1c535642a259311ae08e",
          "sha1": "17327cabd904443e485cb1de05b913745a7b6d6e",
          "md5": "82cb39f062963ce10db2f91377647eb8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-placeholders-1.10.0-all.jar",
          "url": "magicutils-placeholders-1.10.0-all.jar",
          "size": 500740,
          "sha512": "a4041a7c4c745856ab0ce1eeae52fa3cdc1dc8622a6fe5858bfc6deb864192e5f21f40fcfd648ff521682d793b93109e0b0a947ee62f51fe5ec80f38976ca769",
          "sha256": "9ef3938bbd505d4b3dc8fc1735abeffbafb70ea5da16ab63d1c646c39b7017aa",
          "sha1": "7974ca8d88618fdc0d5bacb0ccd91d38b548486f",
          "md5": "875484a4f4bf080015030c5ffa7814a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-placeholders-1.10.0-sources.jar",
          "url": "magicutils-placeholders-1.10.0-sources.jar",
          "size": 3448,
          "sha512": "ff3b657739928d3db9fcd5d07e8590003b9e35ade7825e9dd3e9a024f98832d3e9760d807246bd7a9430ee4fefc601715fb5200a3c7323e526b1536652a0f0df",
          "sha256": "aef48a832d31fb4456c283122136a20c98758a65c3fb8c0cd9a5bc848ff55176",
          "sha1": "09322dbcd4a7e4bb9267c76471cf274170160340",
          "md5": "18c90df674a6a0dc97a6a3d7b8903c85"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-placeholders-1.10.0-javadoc.jar",
          "url": "magicutils-placeholders-1.10.0-javadoc.jar",
          "size": 106655,
          "sha512": "6a6decbfe088ba4d5a84083d5ac5b17e320ef3948a680a670e2c0042382e4dfe45de3a538107b69694c39003512cfe55d2825f8e792636bd8dbc0bf295d05eec",
          "sha256": "693a00482dd2071b31831a75b37a34f6a04df39473dfedda4a9e13458bb1f39f",
          "sha1": "0310a9536eaae3934bd647b1da8c194cf071bfe3",
          "md5": "71be122399bcd54d1819bf1a06526d69"
        }
      ]
    }
  ]
}
