{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-core",
    "version": "1.14.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.14.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.14.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.14.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.14.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.14.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.14.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.14.1-mc1.21.jar",
          "url": "magicutils-core-1.14.1-mc1.21.jar",
          "size": 21073,
          "sha512": "808e2aa8a2d8826203345e9a292f7d06d57f3087e22ceed2e15768dedde1f488385ebbc25139d8f7eb4612dcd31cf8d2bc7455b714dc7ea706326873330c9966",
          "sha256": "e172b0e6c223cecfb55f43ae1931c8dfe1e68cb9a177da3b53ad7509ec32503b",
          "sha1": "b39f222759a1ad18cf4541e8c8f9d1b43b1b679a",
          "md5": "8a72fe7e233fffa8cbbc832ab2689c54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.14.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.14.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.14.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.14.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.14.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.14.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.14.1-mc1.21.jar",
          "url": "magicutils-core-1.14.1-mc1.21.jar",
          "size": 21073,
          "sha512": "808e2aa8a2d8826203345e9a292f7d06d57f3087e22ceed2e15768dedde1f488385ebbc25139d8f7eb4612dcd31cf8d2bc7455b714dc7ea706326873330c9966",
          "sha256": "e172b0e6c223cecfb55f43ae1931c8dfe1e68cb9a177da3b53ad7509ec32503b",
          "sha1": "b39f222759a1ad18cf4541e8c8f9d1b43b1b679a",
          "md5": "8a72fe7e233fffa8cbbc832ab2689c54"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.14.1-sources.jar",
          "url": "magicutils-core-1.14.1-sources.jar",
          "size": 9454,
          "sha512": "2bfdc337b18f931a1ef6d82bf08df4c1cf27d2b6b6703a7d7c12c8d9d2b15387876b73d06876b6460c8addb495580d5eebc910099013c6f24fa02caab29fa3ec",
          "sha256": "c9b2e6842dce04bf0391e2af4264d7d57e5ea985870093fd24d3be3710e75bad",
          "sha1": "8b17c7a2c6b430bc25a04638fb36894c3f45e873",
          "md5": "fb8036fbcc4202637eabec9101e6e7c1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.14.1-javadoc.jar",
          "url": "magicutils-core-1.14.1-javadoc.jar",
          "size": 120820,
          "sha512": "ebd69bf770ca56a9c8bcb3dbbe12f1b1fc34a0e13ace38db09f16c8ed1908a798ca31f1ee9fe3cd5b531f68b0e4a752192d259ca672e403d1192f69b3a469bcf",
          "sha256": "bd45d2b98a7d5bb2a7f1e249d495b8dd698b0e4f6467a84a06ac79f6bcdd6d8e",
          "sha1": "574bfc8cec3c326aa61046aeea9f9863766cafd1",
          "md5": "22ae9265aefa5303c4f99140fd14cd3b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.14.1-all.jar",
          "url": "magicutils-core-1.14.1-all.jar",
          "size": 3409738,
          "sha512": "93486f43ddb9c8e605c7585f385a5a631f618e850ad7d4fc4989b926cfcd4a1c1d66f791dfd4c754d313694418b3d94c7d38e5b66b8a419471d6ddc8f0173c05",
          "sha256": "ac3881db05a27cf57caa90c13242058b0047ef6dfa388e1318576c83aedfc77d",
          "sha1": "6948beca6e2c98e0c91677db71c007e813b8658a",
          "md5": "3cfafb3aa7f783e311b2ea3c28b327c8"
        }
      ]
    }
  ]
}
