{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-placeholders",
    "version": "1.21.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-placeholders-1.21.3-mc1.21.jar",
          "url": "magicutils-placeholders-1.21.3-mc1.21.jar",
          "size": 17883,
          "sha512": "48fa3253647d52855d4887d34b9e2161a6f2ecda563bc48895bf349f6e593dfc2718f76996b71bc8e779bec41c1ac7d3c4a789653aa82a9a435180c9d79d0bbd",
          "sha256": "89c2fb4b44ecba19e34ff71703139a14d88cf28a6aceafb9476ec64ca5f14bc3",
          "sha1": "df409b3b1b4225d1744d76c2daa885919a92c4bb",
          "md5": "a848dfbd78eb27f95a09de0a4dbf97b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-placeholders-1.21.3-mc1.21.jar",
          "url": "magicutils-placeholders-1.21.3-mc1.21.jar",
          "size": 17883,
          "sha512": "48fa3253647d52855d4887d34b9e2161a6f2ecda563bc48895bf349f6e593dfc2718f76996b71bc8e779bec41c1ac7d3c4a789653aa82a9a435180c9d79d0bbd",
          "sha256": "89c2fb4b44ecba19e34ff71703139a14d88cf28a6aceafb9476ec64ca5f14bc3",
          "sha1": "df409b3b1b4225d1744d76c2daa885919a92c4bb",
          "md5": "a848dfbd78eb27f95a09de0a4dbf97b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-placeholders-1.21.3-sources.jar",
          "url": "magicutils-placeholders-1.21.3-sources.jar",
          "size": 7370,
          "sha512": "6ca047e63ff109127ca4d04c8cb3eb30fae2e48ff422ba9b8346479427ffe29d2c1514b4a3227ec09b2978acf81bf72a72305580fb9ee22c02ad9bace12b183a",
          "sha256": "3b8210282b46b06732a9febb7c21c84a6c2da06bc48218455d25a24eb20cd272",
          "sha1": "f94ae8c1bf477eb39ee3f978c683b420249545dc",
          "md5": "c24c7817acb07ecc60c3bbd58f314cc1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-placeholders-1.21.3-javadoc.jar",
          "url": "magicutils-placeholders-1.21.3-javadoc.jar",
          "size": 122280,
          "sha512": "31d4a0244e4b78c9102c6ace2cf9a7316863248897424193f0a70e5fc1d8a006ad347b70ced24f3bf7348c4755286a32c9ea5823cfbb308e21eb0d61d181d7d7",
          "sha256": "519d23be9af3bde65504b1d01557632583ad5fa3ad5d4b753ac59f9b13854a5e",
          "sha1": "f1df51ce0b8c04215f9a60f5130bd23a915fde00",
          "md5": "98561ef709b4075a264d1304df08ed08"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-placeholders-1.21.3-all.jar",
          "url": "magicutils-placeholders-1.21.3-all.jar",
          "size": 534806,
          "sha512": "51fd22af137a6c415049e2cd44fe9c8e428589f28693650f003277b505986f81ecf88039a5e6c33f00962e57d11f807fc387d4c4add8935e05f60e7469ccfdf6",
          "sha256": "c72120218f75263d4ad674d22004a73245611427b745cca9ed353757edd373d4",
          "sha1": "6cdd47c01b60c6fae92008724a6e56800c6f1310",
          "md5": "e6fd5625fa6944ac72ef62f3f8e38792"
        }
      ]
    }
  ]
}
