{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-http-client",
    "version": "1.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.20.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.20.0-mc1.21.jar",
          "url": "magicutils-http-client-1.20.0-mc1.21.jar",
          "size": 58185,
          "sha512": "2683cc0ebc7cbd762ce286dca30b997963189adb9d3571e665e9ad3d8659a0871950a86e2cab10f8ab4843361498b77811bf8ec8db5f5c10cd1159e04eeb8986",
          "sha256": "8aa57567cb0f11a06d41d7ad546d93acbfe607c31a3093c108607db0ef80f316",
          "sha1": "0d64821e851a9bb6c8c53f740ba82606d3dcd002",
          "md5": "ce14bcaf9e04320ade05e8d8cfdcb409"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.20.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.20.0-mc1.21.jar",
          "url": "magicutils-http-client-1.20.0-mc1.21.jar",
          "size": 58185,
          "sha512": "2683cc0ebc7cbd762ce286dca30b997963189adb9d3571e665e9ad3d8659a0871950a86e2cab10f8ab4843361498b77811bf8ec8db5f5c10cd1159e04eeb8986",
          "sha256": "8aa57567cb0f11a06d41d7ad546d93acbfe607c31a3093c108607db0ef80f316",
          "sha1": "0d64821e851a9bb6c8c53f740ba82606d3dcd002",
          "md5": "ce14bcaf9e04320ade05e8d8cfdcb409"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.20.0-sources.jar",
          "url": "magicutils-http-client-1.20.0-sources.jar",
          "size": 21590,
          "sha512": "94fde141f0c6aa3a602f194001bb5d9ad3c924882c6f3e07209ba8b8cc11f72c6e9457102864565d6585a3ddad4ffecc68bd63ba15345c5e4fb7133cebc699c0",
          "sha256": "d56fd445eccd8f18d0dc1cbd0a4e52ef38ea3ae752784fd7b9775bf86f362081",
          "sha1": "c75bc9748d407dc223ef8b26d8a203437fa98cf9",
          "md5": "fbf841914dd9cb02b159c954a7176056"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.20.0-javadoc.jar",
          "url": "magicutils-http-client-1.20.0-javadoc.jar",
          "size": 149266,
          "sha512": "40ebb4835dccc6cb11db91253fdaed44792946ff4157098c1cdd88944fb06298ddbfe6414a8ded0b6ff2d05bab403083226f4ad351bcce2818cc52cb78f35c29",
          "sha256": "3c5e755073413aaea7ab445ddd76e6d2e08afe5e8738d7c6f0ed5d395539a4e9",
          "sha1": "94a4d904818d200a4cadb3053f71cbe14f3c993d",
          "md5": "840dee2a1c41086046376a329b23509c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.20.0-all.jar",
          "url": "magicutils-http-client-1.20.0-all.jar",
          "size": 3490727,
          "sha512": "74d63091e78a25945550bcadc251481a4e3a37f74c00fa8b930db17413e27af11b01509d49b4f0f5585d3ef3b70a7a1fabe60025d1969326cf5dabb4d810c5f6",
          "sha256": "7e3bd8518fa9abc2b183f81fc06631cf195d87508c8bd09048dcb498a5267923",
          "sha1": "205496cbb61da7d0914f27d99cd3df23f6f62f4f",
          "md5": "02574e4cdf0e91b64191cd219dda6273"
        }
      ]
    }
  ]
}
