{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-http-client",
    "version": "1.14.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.14.2-mc1.21.jar",
          "url": "magicutils-http-client-1.14.2-mc1.21.jar",
          "size": 56617,
          "sha512": "09bc1bde919e4fda8f6c168ef98c1f0e02ca522d9b5bf33c9bce4a68ca3b9ecb1b874efcf2c62822d46b28acb286b35c4873a19cf391ee835f214b622f5fc659",
          "sha256": "1dc5d645190a791d7b790b906de0154280b2412e35ff2a867e533969d7d8762a",
          "sha1": "0fd45cf9fc8496713e2f80562a9b0f4aec7a88b0",
          "md5": "33a5198d9d28ce0ddf5e3d5fe51f7893"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.14.2-mc1.21.jar",
          "url": "magicutils-http-client-1.14.2-mc1.21.jar",
          "size": 56617,
          "sha512": "09bc1bde919e4fda8f6c168ef98c1f0e02ca522d9b5bf33c9bce4a68ca3b9ecb1b874efcf2c62822d46b28acb286b35c4873a19cf391ee835f214b622f5fc659",
          "sha256": "1dc5d645190a791d7b790b906de0154280b2412e35ff2a867e533969d7d8762a",
          "sha1": "0fd45cf9fc8496713e2f80562a9b0f4aec7a88b0",
          "md5": "33a5198d9d28ce0ddf5e3d5fe51f7893"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.14.2-sources.jar",
          "url": "magicutils-http-client-1.14.2-sources.jar",
          "size": 20828,
          "sha512": "0592c15958ee8060d8cc40f8a3fb91cfb7e7225c37fd4df5dce4bebf8b298175987529bb353d73c8e0e395a5a78b7ac8134d9a700317c68a1c8f1ac4fa6fdd9e",
          "sha256": "a047a1bfc5aacbbfb4742069ff1b8609623a6c1e3a63fe03e431a6ecd6661f82",
          "sha1": "c02180acd21e930582c4e58ef05048e4bcaccbdb",
          "md5": "08a71f85e7ea867926357543a8860bc2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.14.2-javadoc.jar",
          "url": "magicutils-http-client-1.14.2-javadoc.jar",
          "size": 149259,
          "sha512": "84d9f412818c929f6c2e4386d0e3a077740e717d1f78d2c76e9df23c0f95e14b6baddd209989eeb3a6d36ab5a8131d3266e9fcb1aaaef55c0f0fb0d19007f8f7",
          "sha256": "2afbe2d9089cfe29c6fe7926274b104f33f6c515afd8d7b15ed35de0cd35ac4d",
          "sha1": "4daece87bf86b5b2909404893de39e40f65f356a",
          "md5": "1bdd74bcae731f11c4801d24daf4ece0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.14.2-all.jar",
          "url": "magicutils-http-client-1.14.2-all.jar",
          "size": 3466054,
          "sha512": "53fa626bdfa09122e5f8d6be9b7d8f3001fed4006a61c68981d98e23a455912521ba93b5d68d4c8385deba38ec5d74dc2fe91b2fa9bb6b29d9f5ee179ddde2d0",
          "sha256": "fe96be5e20ad4629215d3b68017c613aeedd12ec60559a6abecb6cf2a468aea9",
          "sha1": "8da99af29a950e9b5ddfa63c1c7cf772ec9d2937",
          "md5": "4b66cc2f547d5c66863efdc62326df7b"
        }
      ]
    }
  ]
}
