{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-neoforge",
    "version": "1.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.15.0-mc1.21.jar",
          "url": "magicutils-neoforge-1.15.0-mc1.21.jar",
          "size": 14657,
          "sha512": "90370a0e5f8c60342d8db38fab04e52a179d623b83f24d81284899c6b586ad76ccd28af7d997c530625fece6841ad52cee90b1172c51f439ac9f3d4fb238dbf2",
          "sha256": "adca55258d6aa90380984d0c429ebfecc5bf7bace7fc4444784e31c3d33363fa",
          "sha1": "df08fbadd3343b7f52bda5d4aa1fb0f85e4ec58b",
          "md5": "50b429d8a42021ff774bd9857a23c2bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.15.0-mc1.21.jar",
          "url": "magicutils-neoforge-1.15.0-mc1.21.jar",
          "size": 14657,
          "sha512": "90370a0e5f8c60342d8db38fab04e52a179d623b83f24d81284899c6b586ad76ccd28af7d997c530625fece6841ad52cee90b1172c51f439ac9f3d4fb238dbf2",
          "sha256": "adca55258d6aa90380984d0c429ebfecc5bf7bace7fc4444784e31c3d33363fa",
          "sha1": "df08fbadd3343b7f52bda5d4aa1fb0f85e4ec58b",
          "md5": "50b429d8a42021ff774bd9857a23c2bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.15.0-sources.jar",
          "url": "magicutils-neoforge-1.15.0-sources.jar",
          "size": 8247,
          "sha512": "184ba0fe6dfafafe701e5bc77b283e6fbd9f220c68bdf2c58637ded5c8804968cca371c0f1af366fbc6712c3c600d8e9710e42c35a3b290da170d959f4773304",
          "sha256": "23f283d33e0113687ef05e2fba9713115daaffd00fb6fb671a2d3cdf43aaa3d7",
          "sha1": "1003943f1510f59e5ca4acb08a60f7f796b4248b",
          "md5": "fcb2110501a1262d5d033f0ded246695"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.15.0-javadoc.jar",
          "url": "magicutils-neoforge-1.15.0-javadoc.jar",
          "size": 114920,
          "sha512": "514d03a61409e9f48ecb4abae57118fa887eb1e35a39d30320aeefb2f59937196432cae81dd59d1b3691a4653459c6375480691ed135863e691966370387f0d7",
          "sha256": "961c6023867ca03d3557f0ab13a8020ff4193c0e3b5fc9d0d68f6b17078dabc9",
          "sha1": "d073c17b199b687ba70c5543c6a653bb7e55d2e7",
          "md5": "49a9ecb099c1de2cde8dd9d135eb2847"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.15.0-all.jar",
          "url": "magicutils-neoforge-1.15.0-all.jar",
          "size": 40351467,
          "sha512": "3e89ef7bfbfa7b2eec5704791f0c2a9fefb1148ef5463e37f734dc85bc24e76fd5c239dbd2888eb792986d14753c0a2c8075acaf83a1c35947a2405a9a08caf6",
          "sha256": "a2228bd0369473f6a7c70a5edace9fdf1451a9eec7a51b18b57a17aab021ab5e",
          "sha1": "84dbf0c9de9c4760938c0fe24cffa548ebc188d0",
          "md5": "81294b07b7d5d926776e7cd98d537ecc"
        }
      ]
    }
  ]
}
