{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-logger",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.11.0-mc1.21.jar",
          "url": "magicutils-logger-1.11.0-mc1.21.jar",
          "size": 77624,
          "sha512": "3b623601a2ddcec7b519c6a3cdbcc874fc41eeb0d16c6ca7ad32bc520ca67e01c7c00b353e3a3ac0488a2b0a04cb70ae7420329420c632169a852b7ba26d5725",
          "sha256": "ea9be38929fb241cc6e94e1d02ba8752335f1d5eb79150ee33cfe24ac17c180d",
          "sha1": "bacc04f1c8f0557e424a7b74c386572389fb5536",
          "md5": "dc08d6805879446413c07ea39fe8ff7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.11.0-mc1.21.jar",
          "url": "magicutils-logger-1.11.0-mc1.21.jar",
          "size": 77624,
          "sha512": "3b623601a2ddcec7b519c6a3cdbcc874fc41eeb0d16c6ca7ad32bc520ca67e01c7c00b353e3a3ac0488a2b0a04cb70ae7420329420c632169a852b7ba26d5725",
          "sha256": "ea9be38929fb241cc6e94e1d02ba8752335f1d5eb79150ee33cfe24ac17c180d",
          "sha1": "bacc04f1c8f0557e424a7b74c386572389fb5536",
          "md5": "dc08d6805879446413c07ea39fe8ff7f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.11.0-sources.jar",
          "url": "magicutils-logger-1.11.0-sources.jar",
          "size": 35476,
          "sha512": "e1278ad8aa538ee283d71dba7b2fdc6906ff6fec309eeb5771cfeb53ad33739c59cca5a0d9974997f9672b9321d43664aaaa14ce3268e3bb3edf3502dab7ffea",
          "sha256": "be5680d78bccc936dab4b6a2276878154c3996ab18f0195e80bb26971240d62a",
          "sha1": "789d506bf48cc5bc9319e9606fc169a6833e7d72",
          "md5": "0297e41bd2871b88c268a8faeaf17f9f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.11.0-javadoc.jar",
          "url": "magicutils-logger-1.11.0-javadoc.jar",
          "size": 203088,
          "sha512": "856c7fc6c2c7e775d0fbec16ff8026aacbce8df6d58d2ccbcdc5bf67ae0e9b5bda980d3c131a60029bd3cefb8b116001aefc43a0af7e629acb2e3169348a02c1",
          "sha256": "82c715cfb01de404141cd1a8aa1f84895d62c3dccfe6906870b200f78ddb3d9f",
          "sha1": "4090fd1a10dd6226fc1a34868eb9e77f048d0621",
          "md5": "1d86fdc5662acb7116277f8a09971423"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.11.0-all.jar",
          "url": "magicutils-logger-1.11.0-all.jar",
          "size": 3204316,
          "sha512": "e3824207de0e266328beb2b23f628bc014cf50e2dabab8601bb9d30e254ff2049273c4ba9b188153eb5b4ed749a1acf52ee9aca2aa3d31cc31b12c050f3ebeaf",
          "sha256": "ebf14fc30f0366c09507b46fcbb049a222d6829844588462881df01d1b954b4b",
          "sha1": "be1fad8545ffdf1f29ff8dec04cf840ead622866",
          "md5": "d3a920bbff7b015579a8734e81e870fc"
        }
      ]
    }
  ]
}
