{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-logger",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.11.0-mc1.21.jar",
          "url": "magicutils-logger-1.11.0-mc1.21.jar",
          "size": 77625,
          "sha512": "f166c1b57ef4a3fa6d57b7b992ac31e0a4bc927cb60cc50cc3a51bd2396710fd63081448f73aa62878d2591a59d3c471595dfd987238fb5c300675d8255206bf",
          "sha256": "f8b953b2c152312d6a9f8010da57e98d6562e8167986079a8135dea4f253def7",
          "sha1": "ea3733101992a5a2710fc465308552b61fce26fe",
          "md5": "385ffb361e4fc83564403a695d9b8936"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.11.0-mc1.21.jar",
          "url": "magicutils-logger-1.11.0-mc1.21.jar",
          "size": 77625,
          "sha512": "f166c1b57ef4a3fa6d57b7b992ac31e0a4bc927cb60cc50cc3a51bd2396710fd63081448f73aa62878d2591a59d3c471595dfd987238fb5c300675d8255206bf",
          "sha256": "f8b953b2c152312d6a9f8010da57e98d6562e8167986079a8135dea4f253def7",
          "sha1": "ea3733101992a5a2710fc465308552b61fce26fe",
          "md5": "385ffb361e4fc83564403a695d9b8936"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.11.0-sources.jar",
          "url": "magicutils-logger-1.11.0-sources.jar",
          "size": 35476,
          "sha512": "e1278ad8aa538ee283d71dba7b2fdc6906ff6fec309eeb5771cfeb53ad33739c59cca5a0d9974997f9672b9321d43664aaaa14ce3268e3bb3edf3502dab7ffea",
          "sha256": "be5680d78bccc936dab4b6a2276878154c3996ab18f0195e80bb26971240d62a",
          "sha1": "789d506bf48cc5bc9319e9606fc169a6833e7d72",
          "md5": "0297e41bd2871b88c268a8faeaf17f9f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.11.0-javadoc.jar",
          "url": "magicutils-logger-1.11.0-javadoc.jar",
          "size": 203088,
          "sha512": "856c7fc6c2c7e775d0fbec16ff8026aacbce8df6d58d2ccbcdc5bf67ae0e9b5bda980d3c131a60029bd3cefb8b116001aefc43a0af7e629acb2e3169348a02c1",
          "sha256": "82c715cfb01de404141cd1a8aa1f84895d62c3dccfe6906870b200f78ddb3d9f",
          "sha1": "4090fd1a10dd6226fc1a34868eb9e77f048d0621",
          "md5": "1d86fdc5662acb7116277f8a09971423"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.11.0-all.jar",
          "url": "magicutils-logger-1.11.0-all.jar",
          "size": 3204317,
          "sha512": "1eba50a2842a6ea7803521e82daa3f49499c85c5b5ce8f384b868e543cbeafaad9b87cab7b58458fecf6757fb4cd0ce381ab7974c3167f4d6cb26d57ef62db36",
          "sha256": "2adcb05a16820b48c3ce5dd9334974a7d54f0827ab546e1114313a298a72246a",
          "sha1": "4debf5cfab92f75e74a66de504d8a1bab00d9f24",
          "md5": "dbee12bb3f6778918fd7a7ae5a6f3f37"
        }
      ]
    }
  ]
}
