{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-core",
    "version": "1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.21.5-mc1.21.jar",
          "url": "magicutils-core-1.21.5-mc1.21.jar",
          "size": 24710,
          "sha512": "fc676cf22c7a431ca86641069f1dcc7dd2cc260816f111646e827135c704edfb8d842ca3017300366ab46e7f74e4ea78ec461a14188bf51103e55edbf43996c8",
          "sha256": "57d14bf4fdb2eebfe1f50b8b9eded297f2b733d312c34e81681b97db4b1c0565",
          "sha1": "cb01fe7e1071d6d0a61f09a0e0951a2f6c775ea5",
          "md5": "532e06df9a188296c9a7d7964e27a6ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.21.5-mc1.21.jar",
          "url": "magicutils-core-1.21.5-mc1.21.jar",
          "size": 24710,
          "sha512": "fc676cf22c7a431ca86641069f1dcc7dd2cc260816f111646e827135c704edfb8d842ca3017300366ab46e7f74e4ea78ec461a14188bf51103e55edbf43996c8",
          "sha256": "57d14bf4fdb2eebfe1f50b8b9eded297f2b733d312c34e81681b97db4b1c0565",
          "sha1": "cb01fe7e1071d6d0a61f09a0e0951a2f6c775ea5",
          "md5": "532e06df9a188296c9a7d7964e27a6ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.21.5-sources.jar",
          "url": "magicutils-core-1.21.5-sources.jar",
          "size": 11429,
          "sha512": "366046a1b2881491de583381d25c0eb5f51bc2bd4eca91778eeb13dfaf9ed3dfc9d1ea03c05e3e46223131e457dd49bf119804fb9ccb32afbbe604f333e79f7c",
          "sha256": "d6849c514b7b77e80352b4837c7a57a651e3208481273c93cde5d997b23f5f7c",
          "sha1": "f8c5d42098260a75f847664f0e026f4ba705769d",
          "md5": "5d73e26508225e840f7e7cadbec0d0c4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.21.5-javadoc.jar",
          "url": "magicutils-core-1.21.5-javadoc.jar",
          "size": 126827,
          "sha512": "be98b3da4d77a8c60a3c52e269a7599b2c6a53fd8a4bf53ef8f3bee5234ccff253dd7eeb19f63ae59db1a96208634b2cc4dbfc6b20837d992e06c4d60a396c3a",
          "sha256": "d287d979cb199f3c0e665526104fd8a640221ce854b03f3df0b425fabfc1375a",
          "sha1": "251927a003ba01895a41666e29288d815c282bed",
          "md5": "4301474858dfd7bf93df90433fc79725"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.21.5-all.jar",
          "url": "magicutils-core-1.21.5-all.jar",
          "size": 3445504,
          "sha512": "42615132a7c087daaf1e0c29e16786683d290abcafbd59624370a208c0bbc6355e47d2e0aa15063402c6c35e2bc3e2537dbf7d6b0791de2003590e5b930e82b6",
          "sha256": "e69054d9481a5f8f813327159c99fcff6547e6dc3338cad9134fe3ee46d184e9",
          "sha1": "624df02accf342dcc8a3ba93cbbfa20e8fbddb9c",
          "md5": "735bc93308d268a6619121562a0bbbab"
        }
      ]
    }
  ]
}
