{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-core",
    "version": "1.21.1-mc1201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.21.1-mc1201-mc1.20.jar",
          "url": "magicutils-core-1.21.1-mc1201-mc1.20.jar",
          "size": 21573,
          "sha512": "def566566bd755fbee04224cf18df4ae5c2d7b0fd2d74b0de1075d8ddd3f33ab195e54ac139455206e58efd118bf28c4604ce90ce4e05a0187bc0ed9ea377233",
          "sha256": "55a3e234f6ab98dbd65a5f82cc40383b0ef690a2899b0889551b97444e5a9f47",
          "sha1": "67250d113deec133f16fa3eedf7868ab3078fcd8",
          "md5": "85ee42a5828a4840cd99776db2310336"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-logger",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-core-1.21.1-mc1201-mc1.20.jar",
          "url": "magicutils-core-1.21.1-mc1201-mc1.20.jar",
          "size": 21573,
          "sha512": "def566566bd755fbee04224cf18df4ae5c2d7b0fd2d74b0de1075d8ddd3f33ab195e54ac139455206e58efd118bf28c4604ce90ce4e05a0187bc0ed9ea377233",
          "sha256": "55a3e234f6ab98dbd65a5f82cc40383b0ef690a2899b0889551b97444e5a9f47",
          "sha1": "67250d113deec133f16fa3eedf7868ab3078fcd8",
          "md5": "85ee42a5828a4840cd99776db2310336"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.21.1-mc1201-sources.jar",
          "url": "magicutils-core-1.21.1-mc1201-sources.jar",
          "size": 10338,
          "sha512": "5ec9b1b570253a5b2ab33e165a55df137e8e241db74cff79a6d82b683d1d6c9fd3a550a850709a74f229fd4192f45a8afd31db1552bb4c340bf7e142040dcbef",
          "sha256": "388e8ac0008cf994d9bc1518078ff142c4494378213bfa5034624c1128f43779",
          "sha1": "891c0b82ab64d34839fa6ab30f90722c58cbc74b",
          "md5": "e12dfdce1a918c4f37af991308b785c9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.21.1-mc1201-javadoc.jar",
          "url": "magicutils-core-1.21.1-mc1201-javadoc.jar",
          "size": 110599,
          "sha512": "c9ae69ea89d007d7ee78b1ae8e9f7e65de59be4b612a6430ac59260663a8a255d99498c732c504077970a6f5676dc649d5906f9919a7fab0db6e3fefcc2bde2d",
          "sha256": "2ee2ba5002abbb42fbd03d5cc3ad0a2d3f0126475b3c079407555552e53e0a5f",
          "sha1": "5aecdc572927eca07287f703f3e4f21a7506113d",
          "md5": "30db6c13f130e2ea94b4a3689ab8c73b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-core-1.21.1-mc1201-all.jar",
          "url": "magicutils-core-1.21.1-mc1201-all.jar",
          "size": 3442162,
          "sha512": "235a4f857c6244e99414a10cb5ac1cfe06d2c19a26226da88dfa37b487e4c514a475506598a0c353f89d9d93907da83946e72ad422144273bac6a4cd378fb188",
          "sha256": "cbdd37e5d1c7921360cd742a3e1b4f65710f35f49dc37ff789fc68e67fdce7c8",
          "sha1": "81b2f952ce7d27de405133d88183e756eb2b3d41",
          "md5": "9b8de17bcc948555b227746694382714"
        }
      ]
    }
  ]
}
