{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-neoforge",
    "version": "1.14.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.14.2-mc1.21.jar",
          "url": "magicutils-neoforge-1.14.2-mc1.21.jar",
          "size": 14657,
          "sha512": "90370a0e5f8c60342d8db38fab04e52a179d623b83f24d81284899c6b586ad76ccd28af7d997c530625fece6841ad52cee90b1172c51f439ac9f3d4fb238dbf2",
          "sha256": "adca55258d6aa90380984d0c429ebfecc5bf7bace7fc4444784e31c3d33363fa",
          "sha1": "df08fbadd3343b7f52bda5d4aa1fb0f85e4ec58b",
          "md5": "50b429d8a42021ff774bd9857a23c2bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.14.2-mc1.21.jar",
          "url": "magicutils-neoforge-1.14.2-mc1.21.jar",
          "size": 14657,
          "sha512": "90370a0e5f8c60342d8db38fab04e52a179d623b83f24d81284899c6b586ad76ccd28af7d997c530625fece6841ad52cee90b1172c51f439ac9f3d4fb238dbf2",
          "sha256": "adca55258d6aa90380984d0c429ebfecc5bf7bace7fc4444784e31c3d33363fa",
          "sha1": "df08fbadd3343b7f52bda5d4aa1fb0f85e4ec58b",
          "md5": "50b429d8a42021ff774bd9857a23c2bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.14.2-sources.jar",
          "url": "magicutils-neoforge-1.14.2-sources.jar",
          "size": 8247,
          "sha512": "184ba0fe6dfafafe701e5bc77b283e6fbd9f220c68bdf2c58637ded5c8804968cca371c0f1af366fbc6712c3c600d8e9710e42c35a3b290da170d959f4773304",
          "sha256": "23f283d33e0113687ef05e2fba9713115daaffd00fb6fb671a2d3cdf43aaa3d7",
          "sha1": "1003943f1510f59e5ca4acb08a60f7f796b4248b",
          "md5": "fcb2110501a1262d5d033f0ded246695"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.14.2-javadoc.jar",
          "url": "magicutils-neoforge-1.14.2-javadoc.jar",
          "size": 114911,
          "sha512": "3eafaf89ccb0cc95f6511f23b70240162391b20109a44ccd120a2da13f2d1b4a4867b61ce294932abbb78437d12cb3033d13ed7e70a230ac414bb6d47f0874c0",
          "sha256": "38cd07a8de4d4fac50f997a36066636eb3b9e78818ace762fb866ea8aa604e6f",
          "sha1": "1775359cd41c2c9714dbb88ebcb7cdba7ebc0f1d",
          "md5": "cd07ca4cdbb7ab3115234cc2ee090b31"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.14.2-all.jar",
          "url": "magicutils-neoforge-1.14.2-all.jar",
          "size": 40349919,
          "sha512": "48741bf4fc5a4e5c21c7357da334ddb4dff59466e01bb9d54a3a471505700acf9b0ee7f558123623f50ed7398daf35e3fe9917b6d8fd28d47fabd8d568deab1c",
          "sha256": "9f7da0e39f9757b34f8ab72dffbc1a7832ae2b0c477ca050e74e70d3cbe77018",
          "sha1": "79a1e0bb098a03d7cce25e81492edc6229f99d22",
          "md5": "95ee1864d08a1acd6184a8b0238e0433"
        }
      ]
    }
  ]
}
