{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-neoforge",
    "version": "1.21.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.21.3-mc1.21.jar",
          "url": "magicutils-neoforge-1.21.3-mc1.21.jar",
          "size": 23698,
          "sha512": "3805f4c7747a717cc130dcc0a4343cd9080ff709c91b255f9a9a19c513d7eebcb6d566d3c881583939905914a64e519e284bfbc8b0a9a86ab987215be69e4259",
          "sha256": "4d7ef58cee399e16747c11118fa86c7deaa4d9189b150800203d20bf9faec1f4",
          "sha1": "7d32d0e66b60972bc53d8818c653884349cc60a6",
          "md5": "e4d3fe6ef93f24af54332341c9f4be3c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-neoforge-1.21.3-mc1.21.jar",
          "url": "magicutils-neoforge-1.21.3-mc1.21.jar",
          "size": 23698,
          "sha512": "3805f4c7747a717cc130dcc0a4343cd9080ff709c91b255f9a9a19c513d7eebcb6d566d3c881583939905914a64e519e284bfbc8b0a9a86ab987215be69e4259",
          "sha256": "4d7ef58cee399e16747c11118fa86c7deaa4d9189b150800203d20bf9faec1f4",
          "sha1": "7d32d0e66b60972bc53d8818c653884349cc60a6",
          "md5": "e4d3fe6ef93f24af54332341c9f4be3c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.21.3-sources.jar",
          "url": "magicutils-neoforge-1.21.3-sources.jar",
          "size": 11808,
          "sha512": "7a27b891caa07493502d668280f250c5fdb47481736e3821599b3c72ede215d1d54c99bb2595d625334bf11ac48d3ac2bbc47367c88921d912ed7ee201d708b1",
          "sha256": "2e80da3d74da9eb41af9ac8bb0989b3d9a89131ffaa833907428e45401d43bad",
          "sha1": "9c68e828fbc815a71fc85936c368f27d4366b871",
          "md5": "5a6602070970fc9f80522a7b51fe6bf9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.21.3-javadoc.jar",
          "url": "magicutils-neoforge-1.21.3-javadoc.jar",
          "size": 119484,
          "sha512": "08533671114be38c3def775825ec35fcde5fb875fbc0eae413bed56c3a444c0c5184735c6fbe55e17e39cbe3d10043c347733bc8a34980bd6627807585275d21",
          "sha256": "930a58090692bfefbe63eca8c32d221425059ea122a68d8756b1d161d79632b7",
          "sha1": "c5ff2edf8b5651dbd809028a8d9eed13bb4bdb24",
          "md5": "0ae0256407db1b3ec6e9c2404e031848"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-1.21.3-all.jar",
          "url": "magicutils-neoforge-1.21.3-all.jar",
          "size": 40391544,
          "sha512": "c8dfe9f505b4421a75437e15acf89e8f95a1c2eaf7cf104dbe2f873a9854e58aaf1ab9b06bf26a0ff815029c1a5760b9e2c1ee6e444a1022b72cf7aa69b7caf5",
          "sha256": "8ab4086257ae47843fce8cab8c0f4645b3503e18cb46123924633a12057524d2",
          "sha1": "b551deafccb3dd9aab409b4ec20fca43942253fe",
          "md5": "4e0025ece3ac657c8ebcf35e2df6f2c7"
        }
      ]
    }
  ]
}
