{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bukkit",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.10.0.jar",
          "url": "magicutils-bukkit-1.10.0.jar",
          "size": 105823,
          "sha512": "2dcfcc94dbf39ce62215d489496771b674a750c4f30fdcf63d49feae057baab53f8d8c1ae8dabfe36b587053c6e09acf39b64b9cba0715faaa7e64373030e3e8",
          "sha256": "b7a6779b60115fd43bbc85c7c205eb2c015cd32e1c8a6911b65b47d32d539d0b",
          "sha1": "0244afad72a58f581adfe76bf973b449beadc481",
          "md5": "079554be8b7455fe585f881086a1d0a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.10.0.jar",
          "url": "magicutils-bukkit-1.10.0.jar",
          "size": 105823,
          "sha512": "2dcfcc94dbf39ce62215d489496771b674a750c4f30fdcf63d49feae057baab53f8d8c1ae8dabfe36b587053c6e09acf39b64b9cba0715faaa7e64373030e3e8",
          "sha256": "b7a6779b60115fd43bbc85c7c205eb2c015cd32e1c8a6911b65b47d32d539d0b",
          "sha1": "0244afad72a58f581adfe76bf973b449beadc481",
          "md5": "079554be8b7455fe585f881086a1d0a3"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.10.0-all.jar",
          "url": "magicutils-bukkit-1.10.0-all.jar",
          "size": 3431333,
          "sha512": "9796319070a995f5158bb53c2d2eaa6b5a9ffa723c9c7c957ece18121d959d51661577bf15f0da82366f8bd61cde6c86e004ecf0166f1ca4f4163cb7f3f03df3",
          "sha256": "0789be9a4187dc539c91d3c5cfac1f3502bfa467d9e25f999c43cb2825af403e",
          "sha1": "20fec3ef053f641a272c450ef2c1cdb8cb2d458c",
          "md5": "c37d8df03d5f783004295ee0476d2ed3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.10.0-sources.jar",
          "url": "magicutils-bukkit-1.10.0-sources.jar",
          "size": 48576,
          "sha512": "11a3f1bcb9a4b425af76498da08111bca6706e7eb239774029e403e809d96fd7f003af86356ac8b061bb3e24a586e48471a3b3c17df3eb8534db2836e4ed0c2b",
          "sha256": "c6663bb37a50af774eec1cc92b335bcb0a2fd6e2325e2ff71199e41337976e20",
          "sha1": "2715c1698c4ee1a534d5b124178ff77628c9f555",
          "md5": "023069953e5fe1409b4fee43aeb8effb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.10.0-javadoc.jar",
          "url": "magicutils-bukkit-1.10.0-javadoc.jar",
          "size": 242210,
          "sha512": "64885819403db5a2fdafd91e13fc0b52a41b7610313fa2ae8b03d8f7081211affa7d6ea2bbc5d0827ff4a500239f3799facdc691c8b272857a73d24991c1a571",
          "sha256": "5e2e78fda27e4c88a28a4cbb9b69bbc7b1faf391723b15146bab2da0d09e3c79",
          "sha1": "5da095f00d417d6c052fa3da6ba93085d3a80fe6",
          "md5": "d155d01b5f630101e0fe31b83c5976b9"
        }
      ]
    }
  ]
}
