{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bukkit",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.10.0.jar",
          "url": "magicutils-bukkit-1.10.0.jar",
          "size": 105823,
          "sha512": "ee10dde18153f116aa82fd1b1357e60205849c71405abc8dc872fc2f62ef19740261fb309248f69eaa0c1a3b586acd0d0bb7386f398f2712c4719d815e0d6984",
          "sha256": "b83e43cd7d89cb4c44aa3fe9a28e3705b5d5cbe53b54cb87323d6ba4b76a533b",
          "sha1": "ad1194637894a3740d547f54d74fd0cf9d991490",
          "md5": "e93ffd1cfb1bd9501b8222ee25fe7ae8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.10.0.jar",
          "url": "magicutils-bukkit-1.10.0.jar",
          "size": 105823,
          "sha512": "ee10dde18153f116aa82fd1b1357e60205849c71405abc8dc872fc2f62ef19740261fb309248f69eaa0c1a3b586acd0d0bb7386f398f2712c4719d815e0d6984",
          "sha256": "b83e43cd7d89cb4c44aa3fe9a28e3705b5d5cbe53b54cb87323d6ba4b76a533b",
          "sha1": "ad1194637894a3740d547f54d74fd0cf9d991490",
          "md5": "e93ffd1cfb1bd9501b8222ee25fe7ae8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.10.0-all.jar",
          "url": "magicutils-bukkit-1.10.0-all.jar",
          "size": 3431333,
          "sha512": "9796319070a995f5158bb53c2d2eaa6b5a9ffa723c9c7c957ece18121d959d51661577bf15f0da82366f8bd61cde6c86e004ecf0166f1ca4f4163cb7f3f03df3",
          "sha256": "0789be9a4187dc539c91d3c5cfac1f3502bfa467d9e25f999c43cb2825af403e",
          "sha1": "20fec3ef053f641a272c450ef2c1cdb8cb2d458c",
          "md5": "c37d8df03d5f783004295ee0476d2ed3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.10.0-sources.jar",
          "url": "magicutils-bukkit-1.10.0-sources.jar",
          "size": 48576,
          "sha512": "13628083f056d9210ee86695daa9baf5a2204e6404a5d3ec9e92fa89a5dda26679407d46d67c81b4c87347ee2db19a57c8c50abb412af9c265de705153342ec3",
          "sha256": "d2a654610ca218e6a23d1b5724e6a213e99ce315b669d706eb2caefb65f827e0",
          "sha1": "302b04a9d2e8894c71dd7e2a1c409d2ee2721f05",
          "md5": "6a918fe8164ad66862a3ba2000220411"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.10.0-javadoc.jar",
          "url": "magicutils-bukkit-1.10.0-javadoc.jar",
          "size": 242210,
          "sha512": "ce646f6ddf93b019a2964462fa42944c286896b48ab61aa56514b2d22461c990b901ea6ce64e96093b7fd0def4d342a079a693c3175ed5c771ea5e2dcb3494bf",
          "sha256": "5f7dfd5626706d95bf5d9765a9efa817d98afb912768288f4eb160e34c5bc4de",
          "sha1": "d3fa5846740d6f3c7132a621e387a650993bc1f2",
          "md5": "36e10ec6e121ed09679eef2c0f1739ae"
        }
      ]
    }
  ]
}
