{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bukkit",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.10.0.jar",
          "url": "magicutils-bukkit-1.10.0.jar",
          "size": 105823,
          "sha512": "683da9698ab774f3aabd42fabcba5faf7895692261ef6856055375553f682fc7adf38f0137d6745bc3c99b9549a8f587e8beca43cebf6cc64580f083ef8e5eb7",
          "sha256": "3adcbb3e524d7230f102f15333d44fa2d9bf612605a4e302639d92fe080d9f22",
          "sha1": "15ed8aaab203c47f9c3fd149fafad85822c06d18",
          "md5": "b31a998f095f595b0ca05508cae1a0ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.10.0.jar",
          "url": "magicutils-bukkit-1.10.0.jar",
          "size": 105823,
          "sha512": "683da9698ab774f3aabd42fabcba5faf7895692261ef6856055375553f682fc7adf38f0137d6745bc3c99b9549a8f587e8beca43cebf6cc64580f083ef8e5eb7",
          "sha256": "3adcbb3e524d7230f102f15333d44fa2d9bf612605a4e302639d92fe080d9f22",
          "sha1": "15ed8aaab203c47f9c3fd149fafad85822c06d18",
          "md5": "b31a998f095f595b0ca05508cae1a0ef"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.10.0-all.jar",
          "url": "magicutils-bukkit-1.10.0-all.jar",
          "size": 3431333,
          "sha512": "9796319070a995f5158bb53c2d2eaa6b5a9ffa723c9c7c957ece18121d959d51661577bf15f0da82366f8bd61cde6c86e004ecf0166f1ca4f4163cb7f3f03df3",
          "sha256": "0789be9a4187dc539c91d3c5cfac1f3502bfa467d9e25f999c43cb2825af403e",
          "sha1": "20fec3ef053f641a272c450ef2c1cdb8cb2d458c",
          "md5": "c37d8df03d5f783004295ee0476d2ed3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.10.0-sources.jar",
          "url": "magicutils-bukkit-1.10.0-sources.jar",
          "size": 48576,
          "sha512": "690a07d8bad39f32b58c9c62544adfda24d68ea0265157f76993bcd730ae464c427f70709663bac587ad80f13948be9daa19d5f841fe26aacc9107994c03eae5",
          "sha256": "35130d76750308e1b1ad8fd23ca2f4b2d0f121d220d51e9c8f78f6941e8c7f8d",
          "sha1": "8428b38f1f227b4be1e62932575f9fcba74131e4",
          "md5": "454050f5f8b4871a7f92925fe8c71dbe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.10.0-javadoc.jar",
          "url": "magicutils-bukkit-1.10.0-javadoc.jar",
          "size": 242210,
          "sha512": "1c848b82c63ac3bcaf300c1d6269fad051d477f5b1747e55f13ebdfdab5d6392f7230abb54d9f81cd010315b9ec4ffdfea99fcb120559668120b143668c553b1",
          "sha256": "988fe19278aa6344d3042b15c048347806e3b37db6a63854a0b21d6c936249e9",
          "sha1": "fc76e00df5af585302bc96cf0b1f8fad0d9d9f3a",
          "md5": "e433a553070b2f6430405cdf20e620f7"
        }
      ]
    }
  ]
}
