{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-lang",
    "version": "1.19.1-mc1201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.19.1-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.19.1-mc1201-mc1.20.jar",
          "url": "magicutils-lang-1.19.1-mc1201-mc1.20.jar",
          "size": 41804,
          "sha512": "c9bf5bd8591edf58869a08209656965ef3c8bca48e52811b7cbc2ba9c883a6b9b993b1e012d6399d711edc973a3b06e5b4fb4bdb9def0d972443670e25e07253",
          "sha256": "adfbc6a269573b80ab00112853abaf05fd08a63da6533e80c0b5010ba5d72464",
          "sha1": "256a69d8d07737424fbd0ce50c95439a211e38cb",
          "md5": "76447b698a87bbea1609252cb069506a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.19.1-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.19.1-mc1201-mc1.20.jar",
          "url": "magicutils-lang-1.19.1-mc1201-mc1.20.jar",
          "size": 41804,
          "sha512": "c9bf5bd8591edf58869a08209656965ef3c8bca48e52811b7cbc2ba9c883a6b9b993b1e012d6399d711edc973a3b06e5b4fb4bdb9def0d972443670e25e07253",
          "sha256": "adfbc6a269573b80ab00112853abaf05fd08a63da6533e80c0b5010ba5d72464",
          "sha1": "256a69d8d07737424fbd0ce50c95439a211e38cb",
          "md5": "76447b698a87bbea1609252cb069506a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.19.1-mc1201-sources.jar",
          "url": "magicutils-lang-1.19.1-mc1201-sources.jar",
          "size": 23172,
          "sha512": "ebca78beaf397a96538de30923753638ff183f3eb1b4594f6fcbab18c048f91cdeec5b47c415c40bf9c5773414d960550f163e1b33553e28a55edc89bc2bd95c",
          "sha256": "a06e77f724d3f28841860d3efac581680fca66271bd70474e7834c4f665bfc47",
          "sha1": "0aaf39446117747542056e2d6fb815f97d835c4a",
          "md5": "b7da6363835125509bb651acebde3e75"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.19.1-mc1201-javadoc.jar",
          "url": "magicutils-lang-1.19.1-mc1201-javadoc.jar",
          "size": 129878,
          "sha512": "65ea9c21d6acd2b5232698b654beeadfb2f16d98337bcdb157b9ccd9bd284c04aab35d34b267aa55ea3bf21811a6a8b3c0887b1129e526c14a1beccfb14375e5",
          "sha256": "aa4fa48006f455243005ff53a3c971a0485b928021e370e4e945a18477b63d17",
          "sha1": "4000d5d10cca95880bd97d1b2cb90a923a5070e8",
          "md5": "a31756cf956a504d2a26fd77cca40c01"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.19.1-mc1201-all.jar",
          "url": "magicutils-lang-1.19.1-mc1201-all.jar",
          "size": 3183027,
          "sha512": "06191edab831dc747fe2a81bf1dac001a5f8cb611899fd8d4488b13ccbcf345182efe28368a80523318628746240465e5176228f942757520edb0960af6ad7e9",
          "sha256": "e084f38229b4ff30a0e671683fc3c86d64d8d3daaca0e80ff18b6da2d0853281",
          "sha1": "6a5d1e551fc11954c638f9ecf4f9052c083b0fbd",
          "md5": "d312ec38dff0c53ad3c495ded20e7eb0"
        }
      ]
    }
  ]
}
