{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-http-client",
    "version": "1.21.2-mc2611",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.2-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.2-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.21.2-mc2611-mc26.1.jar",
          "url": "magicutils-http-client-1.21.2-mc2611-mc26.1.jar",
          "size": 58197,
          "sha512": "b53cd29092b7c3fd0193199235d7c512639c4f69c4fca2334e97dac472467e83ad2285662b37bdc83836666a3f54804490d11135b4c37611de4e21275f608d26",
          "sha256": "57488e93d717c0f235e00d27d662e3a9986c837b62a0d6139f0e779e2366f1fa",
          "sha1": "fa4585052c47d410c3b3388b0f2d966225b785bf",
          "md5": "aee5207d0c40fecc09de68636f781f24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.2-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.2-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.21.2-mc2611-mc26.1.jar",
          "url": "magicutils-http-client-1.21.2-mc2611-mc26.1.jar",
          "size": 58197,
          "sha512": "b53cd29092b7c3fd0193199235d7c512639c4f69c4fca2334e97dac472467e83ad2285662b37bdc83836666a3f54804490d11135b4c37611de4e21275f608d26",
          "sha256": "57488e93d717c0f235e00d27d662e3a9986c837b62a0d6139f0e779e2366f1fa",
          "sha1": "fa4585052c47d410c3b3388b0f2d966225b785bf",
          "md5": "aee5207d0c40fecc09de68636f781f24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.21.2-mc2611-sources.jar",
          "url": "magicutils-http-client-1.21.2-mc2611-sources.jar",
          "size": 21590,
          "sha512": "94fde141f0c6aa3a602f194001bb5d9ad3c924882c6f3e07209ba8b8cc11f72c6e9457102864565d6585a3ddad4ffecc68bd63ba15345c5e4fb7133cebc699c0",
          "sha256": "d56fd445eccd8f18d0dc1cbd0a4e52ef38ea3ae752784fd7b9775bf86f362081",
          "sha1": "c75bc9748d407dc223ef8b26d8a203437fa98cf9",
          "md5": "fbf841914dd9cb02b159c954a7176056"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.21.2-mc2611-javadoc.jar",
          "url": "magicutils-http-client-1.21.2-mc2611-javadoc.jar",
          "size": 4207720,
          "sha512": "e3f5509051372770729a5dff8c7806d7bd5b403c6d2164ad46e1aa0f7fc35bf71176fc281cfdae2f5b1cc4389e86ccca4cd59954942d5c2fdf915a0edc2439a6",
          "sha256": "681853d1140d51e1f918ed250f182333bb289da9549fd5ce5c7c8f47505726e0",
          "sha1": "9c36abb635f584716feee4b6ca3a4ac44057322c",
          "md5": "7fbb5f49f3eaac0b9c6d880025f6ddfe"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.21.2-mc2611-all.jar",
          "url": "magicutils-http-client-1.21.2-mc2611-all.jar",
          "size": 3500093,
          "sha512": "c24a4dee6ef1a24e665d6c107ec1da1a5adf6bc28dbc07c53782a06bb869ed7210222af5d25ce306a166d29c4b1a6a65387ae64b67e6ababc4dc8224286242e7",
          "sha256": "90fa0e84a6cbc7e5864518f3dc807ed1c3771a5fa17f4bcb7875e0cdc9e87fea",
          "sha1": "8535537952d5c54dfa63777a91c97ac6077cb09b",
          "md5": "ff5a2d9d8e9ce2983292ec54afbe44df"
        }
      ]
    }
  ]
}
