{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-velocity",
    "version": "1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-velocity-1.21.5-mc1.21.jar",
          "url": "magicutils-velocity-1.21.5-mc1.21.jar",
          "size": 39861,
          "sha512": "dae4ff957ca52fc27beaeebf30e76319fb3294e05088ddf99aaa8a006af376c5748ebbf801e28626b7ed77e7ddd0cbbc6a3179fa55ae71ddcb013d34966ad57f",
          "sha256": "4ca54a7df10dd99cdca27a526d50ad131fc37915d0ceff1d1a507fb747165d09",
          "sha1": "d372169902dc8673637d13f9f6209695241429de",
          "md5": "65fa8fe4cdebdd61a20c5af64467a2a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-velocity-1.21.5-mc1.21.jar",
          "url": "magicutils-velocity-1.21.5-mc1.21.jar",
          "size": 39861,
          "sha512": "dae4ff957ca52fc27beaeebf30e76319fb3294e05088ddf99aaa8a006af376c5748ebbf801e28626b7ed77e7ddd0cbbc6a3179fa55ae71ddcb013d34966ad57f",
          "sha256": "4ca54a7df10dd99cdca27a526d50ad131fc37915d0ceff1d1a507fb747165d09",
          "sha1": "d372169902dc8673637d13f9f6209695241429de",
          "md5": "65fa8fe4cdebdd61a20c5af64467a2a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.21.5-sources.jar",
          "url": "magicutils-velocity-1.21.5-sources.jar",
          "size": 15878,
          "sha512": "e57b54f29527c7dd9f100413c9f844d4d648ac7cdbb8ca1a5d566badab7fb4fbeab5f2305cc18f49a2de4508320b0caa35d0ab94cbb5b24c82bd6649bfdd0efd",
          "sha256": "023cfb740e6202708650414ab3b870528ce765ceedddbbda9f73ecb1dc5b0906",
          "sha1": "fe75d033e8d132b8163ebb2ec6c7c0ef499339a7",
          "md5": "5d75e87442d112a2315b4bf5ea071b93"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.21.5-javadoc.jar",
          "url": "magicutils-velocity-1.21.5-javadoc.jar",
          "size": 130995,
          "sha512": "d6860e16abe63de20ca361c58dad32cc60c035b206582613e5c1550c719982ec93258940d56de628515ef5db9203cbdfc11c8d6a13f66e2ede8f8e880d695d5d",
          "sha256": "b63cb27f0956ae2ac59c4b56f08f0ad9ddcbfdf086316b78040e5a02f0864e55",
          "sha1": "c895ae47c752a979a4eb03f47bab827ae1b2e604",
          "md5": "c47b1303c2ca10e9f1cea10e474e844a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-velocity-1.21.5-all.jar",
          "url": "magicutils-velocity-1.21.5-all.jar",
          "size": 3545246,
          "sha512": "d83f16e904a7581b0fcff58756ffac73434d0008e6dbe863821abe7f40e2214a46a7c973a7a4a454c3d7c7f1bf9f2355ec7e2c5154ff2360bc46a2d87e7ebd76",
          "sha256": "cd0bc973302a0acbfd08090bfdf96fa227a37acafdc4d07a1ee7b2327e57b52d",
          "sha1": "c6e815a15fbf6078a2bd87dc81b15f53b07216a6",
          "md5": "89baf77bb5b2280c1567fa741fe412e2"
        }
      ]
    }
  ]
}
