{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-neoforge-bundle",
    "version": "1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magicutils-neoforge-bundle-1.21.4-mc1.21.jar",
          "url": "magicutils-neoforge-bundle-1.21.4-mc1.21.jar",
          "size": 3450358,
          "sha512": "9eb11c07ac63acae71cacc77538e0f87bf4a255200b3b2cb55c37ddd6500e6f55ac247b4d5a0bb0a36e951e5561261f8785f9b6719b565ee1932369cca033c5b",
          "sha256": "8cb56894722a03a4f2cae2eccf1ad2eec246569d38d6e4a4cc079e1323bef908",
          "sha1": "48ff6f3018ee11cee1aed21881718fe9cd61ce51",
          "md5": "64336e0ab6e9298ff79dfe2e55cd011e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-bundle-1.21.4-mc1.21.jar",
          "url": "magicutils-neoforge-bundle-1.21.4-mc1.21.jar",
          "size": 3450358,
          "sha512": "9eb11c07ac63acae71cacc77538e0f87bf4a255200b3b2cb55c37ddd6500e6f55ac247b4d5a0bb0a36e951e5561261f8785f9b6719b565ee1932369cca033c5b",
          "sha256": "8cb56894722a03a4f2cae2eccf1ad2eec246569d38d6e4a4cc079e1323bef908",
          "sha1": "48ff6f3018ee11cee1aed21881718fe9cd61ce51",
          "md5": "64336e0ab6e9298ff79dfe2e55cd011e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-bundle-1.21.4-sources.jar",
          "url": "magicutils-neoforge-bundle-1.21.4-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-bundle-1.21.4-javadoc.jar",
          "url": "magicutils-neoforge-bundle-1.21.4-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-neoforge-bundle-1.21.4-all.jar",
          "url": "magicutils-neoforge-bundle-1.21.4-all.jar",
          "size": 293,
          "sha512": "adf753a6141e26a37bb8579dcd330b83ffb01b2a3f5e79dbdce4a52a28eb1bb14dbcb6283a0300b280c79ebdbfcfcad134467c26feb5ceaa1297c10f4e44eef0",
          "sha256": "8c73aca879e0eaa2bef8dce824c4ccf6eab117bf18b7cfbc4133a730206adca8",
          "sha1": "22d6c7e81b12482a22cd5129b5567e655b03d323",
          "md5": "2a72a546127e0f030f06c858df0109a5"
        }
      ]
    }
  ]
}
