{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-logger",
    "version": "1.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.13.1-mc1.21.jar",
          "url": "magicutils-logger-1.13.1-mc1.21.jar",
          "size": 77986,
          "sha512": "9c360ffaf516f279a1459029dd13a9dc47c20369b95402e8dabf61e17667339e31683f3b02b9acf915a049c3144ac45448797d51083cb546481e89082e5b364e",
          "sha256": "e124148898a56992c1ae56cce4b03987c71b658739db887532bb4efc7e914c7d",
          "sha1": "255f03c1a009633c85bcdd8b21a283aabb61218b",
          "md5": "fbd950bcac0be1fd5a6b05234c240ff1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.13.1-mc1.21.jar",
          "url": "magicutils-logger-1.13.1-mc1.21.jar",
          "size": 77986,
          "sha512": "9c360ffaf516f279a1459029dd13a9dc47c20369b95402e8dabf61e17667339e31683f3b02b9acf915a049c3144ac45448797d51083cb546481e89082e5b364e",
          "sha256": "e124148898a56992c1ae56cce4b03987c71b658739db887532bb4efc7e914c7d",
          "sha1": "255f03c1a009633c85bcdd8b21a283aabb61218b",
          "md5": "fbd950bcac0be1fd5a6b05234c240ff1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.13.1-sources.jar",
          "url": "magicutils-logger-1.13.1-sources.jar",
          "size": 35572,
          "sha512": "901c72117fa8aba68a8c1e1b95f43d2a6eedb043cb550f84c95db896dd13f2a76aa8a06650ccde7feba7a4c1c49ad924a2796d8d54610f19b64c234881150bb4",
          "sha256": "7de625e7ac169af18d79da99d270c16ea592a0fd43d57c47e1e62b0367a7bb80",
          "sha1": "cead366e19c120406cc4751779efa341bc63e865",
          "md5": "0e38178b5f6f0060752892e1b677aa30"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.13.1-javadoc.jar",
          "url": "magicutils-logger-1.13.1-javadoc.jar",
          "size": 203070,
          "sha512": "c032b042953f97e588e01071fee56d38d4fe81f204b43bb3d48c3d5cae01948f78caa54562b0064b10fa8a50eea945a380b70551e4b4b688e2b21526982b2a0f",
          "sha256": "da6140384bd5f43b28e7a3d52952dfa3de55dfb414e6b937fdcf8ce5f9c92846",
          "sha1": "018d39272bd83b76f0cd212ee70e9fd0b96c85ed",
          "md5": "b5f1b6dab0fe00d28944debbd61cc939"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.13.1-all.jar",
          "url": "magicutils-logger-1.13.1-all.jar",
          "size": 3215976,
          "sha512": "36c19dc29abdac7e11dd53677febb55278ae085aa8fa2521f587c139c5f131090faaa3e36d25b667b9754fa5a73c9bf4d08e06b23b10849c2dd4833d3a96137e",
          "sha256": "ead28cd036be4ece812774d2e40b90bae1adcc8c26dc1f9b557b1f783964fdf5",
          "sha1": "b0f2d4d33b00fd7c15b8679a03438c2cb8185ed0",
          "md5": "9f0e4ddf21705e67456230cf81020a44"
        }
      ]
    }
  ]
}
