{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-logger",
    "version": "1.21.3-mc2611",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.21.3-mc2611-mc26.1.jar",
          "url": "magicutils-logger-1.21.3-mc2611-mc26.1.jar",
          "size": 77320,
          "sha512": "4412093c4bc596da6a5a24994a7e1c777b7dc7eec1237b4cbe672d3fca99fbaf5098ae9d695d9251e4918e786ad801451c5d0a7bcef62a0399c5694c8bbd0283",
          "sha256": "e12b70292686d16bd06fefbb1e1a9363b185dde1903f2eb739e87861e9c62e47",
          "sha1": "c1b8de3b797241d11e6f466027c044b36b40281e",
          "md5": "8eb78154eff5e269dadd28a025da2fa8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.21.3-mc2611"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.21.3-mc2611-mc26.1.jar",
          "url": "magicutils-logger-1.21.3-mc2611-mc26.1.jar",
          "size": 77320,
          "sha512": "4412093c4bc596da6a5a24994a7e1c777b7dc7eec1237b4cbe672d3fca99fbaf5098ae9d695d9251e4918e786ad801451c5d0a7bcef62a0399c5694c8bbd0283",
          "sha256": "e12b70292686d16bd06fefbb1e1a9363b185dde1903f2eb739e87861e9c62e47",
          "sha1": "c1b8de3b797241d11e6f466027c044b36b40281e",
          "md5": "8eb78154eff5e269dadd28a025da2fa8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.21.3-mc2611-sources.jar",
          "url": "magicutils-logger-1.21.3-mc2611-sources.jar",
          "size": 35251,
          "sha512": "fb897db17baadb42f711f76483f1384132753ea660dc056b714d16313bebdc466a4554ece221851150d28112b5963057af6982cdf57b7269518e842a5110dea2",
          "sha256": "5b3032ca147e41cebb07b060147495acf50d7865e8dc6de2791aaa15a9ec9bbc",
          "sha1": "3e3c73b102e2b0892885c3ede99623beeff994db",
          "md5": "7a802ef6011516fc85e3dd9b3543c493"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.21.3-mc2611-javadoc.jar",
          "url": "magicutils-logger-1.21.3-mc2611-javadoc.jar",
          "size": 4265023,
          "sha512": "3f06335b7ea125ef43873b261d3cae4b2325654883bbfa41fa00252ff0c56da82f0b322366b3660dc70a06ed7d446041ffb9e23c0539da53a67021909936d9b8",
          "sha256": "f41f6def78872fefb0cb93d0f6d9c4c42894ff20d25ce1126b972c4e38bbab4a",
          "sha1": "aed950a2c8b7600c26c0ee154deb313efaead5bb",
          "md5": "6e3fe1353b533c9bcedc037cd489bdc3"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.21.3-mc2611-all.jar",
          "url": "magicutils-logger-1.21.3-mc2611-all.jar",
          "size": 3240327,
          "sha512": "d0ed25b1fb45adf44f2b58999b26c22fcbb8330208b747e8e94429b82384cd146ffc73d026cad2d31e4d8a95d584f91902126515699160892df1aa0933510fcb",
          "sha256": "80d1a5f747cd0677f44461d35365bb4ce0881ad7ecf39d9e81f90e468b2b9298",
          "sha1": "43d4ded72003f6265642eed79b96190c0a0f7c4d",
          "md5": "fe6f7f00ddb80bcc1d361a80c92aadeb"
        }
      ]
    }
  ]
}
