{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-config",
    "version": "1.21.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-1.21.3-mc1.21.jar",
          "url": "magicutils-config-1.21.3-mc1.21.jar",
          "size": 78081,
          "sha512": "0ba5907208e65b12f99a178e3a7c1b59631c9338abbb8a1ba8ce8f625b4b81773e57a2f01c4f01536583a236dc8158d4a93c3e6e073b4523e048d38dc483b90c",
          "sha256": "f441ab916ee19307f281446476608c23fb2d271b6da31716c2791ddc6eaad655",
          "sha1": "7cf3929292a066de9725efa372988fe9ebc88886",
          "md5": "ae77a91d87ad798dd52de27882eb2779"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-1.21.3-mc1.21.jar",
          "url": "magicutils-config-1.21.3-mc1.21.jar",
          "size": 78081,
          "sha512": "0ba5907208e65b12f99a178e3a7c1b59631c9338abbb8a1ba8ce8f625b4b81773e57a2f01c4f01536583a236dc8158d4a93c3e6e073b4523e048d38dc483b90c",
          "sha256": "f441ab916ee19307f281446476608c23fb2d271b6da31716c2791ddc6eaad655",
          "sha1": "7cf3929292a066de9725efa372988fe9ebc88886",
          "md5": "ae77a91d87ad798dd52de27882eb2779"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.21.3-sources.jar",
          "url": "magicutils-config-1.21.3-sources.jar",
          "size": 36597,
          "sha512": "921e6f0523cdfe0a84a1e0feec2797e773c11df0f2242c25cf578243113cafdc2fc126b50130ba4a271f1b775ebefa83734b9c4335ce1a9ed4e69a86e2c352c0",
          "sha256": "9d06955f260b52eb66f342abefa84ac0186f309d8d54d6f3c7af8a7fa4796880",
          "sha1": "eda17a2dd1c6959cf559127d40e25a643590e4d5",
          "md5": "84e122178ab8c4cff174eafea74385bb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.21.3-javadoc.jar",
          "url": "magicutils-config-1.21.3-javadoc.jar",
          "size": 161111,
          "sha512": "5a048bc66498b86a35ed439a31e931546ea058f73104ef53369cf5d93425727a86b17d82159af507a0d117fb74f084e214cd9a6fcb3bba309455a8d701041d18",
          "sha256": "8cbfdf9bd864d047ce7fe3d595c5a45e6920c6e6d7e5e74bd7fbdeea9b5909f7",
          "sha1": "968c3433bfc9c7c583e443be325a39b0f2c83ab6",
          "md5": "1f86abab3c4aae14cc7425033ad211ad"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.21.3-all.jar",
          "url": "magicutils-config-1.21.3-all.jar",
          "size": 2962708,
          "sha512": "ba9844973a881b641a5800cd9553af544ac6402e52946e511d15e2a2ed7dee82ba7a54f049ea326b8846fe085ca7367e672a8549e6c5a1650abf5d5fdefca305",
          "sha256": "fdf1c2ad03e09e099e5c51a50cf7ac048ac13e7a93252efe9f94fab6dd520afd",
          "sha1": "b9b31ef40e9856460e6e1ea414c46c2ae833f37c",
          "md5": "468b9149bfa3a239f692619a695081b2"
        }
      ]
    }
  ]
}
