{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-config",
    "version": "1.21.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-1.21.3-mc1.21.jar",
          "url": "magicutils-config-1.21.3-mc1.21.jar",
          "size": 78318,
          "sha512": "5bf8106de30192067abe97f7feedcd7f4a6bb6044d41a7c0b9d3bda5c018c11080f30a00a6c9afc5d531b4e1eb563fb7eaf0664f5028b1a748f9e7720b381323",
          "sha256": "7e8a56c08747fedecf73201cfb3404cec2990cc8685e012a8509dedba18f77fd",
          "sha1": "9c2eb06db3d9784422581cf12c0c4d5f3f8f194c",
          "md5": "f8a59dc3e9e319796e16dd8c291f7f87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.21.3"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-1.21.3-mc1.21.jar",
          "url": "magicutils-config-1.21.3-mc1.21.jar",
          "size": 78318,
          "sha512": "5bf8106de30192067abe97f7feedcd7f4a6bb6044d41a7c0b9d3bda5c018c11080f30a00a6c9afc5d531b4e1eb563fb7eaf0664f5028b1a748f9e7720b381323",
          "sha256": "7e8a56c08747fedecf73201cfb3404cec2990cc8685e012a8509dedba18f77fd",
          "sha1": "9c2eb06db3d9784422581cf12c0c4d5f3f8f194c",
          "md5": "f8a59dc3e9e319796e16dd8c291f7f87"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.21.3-sources.jar",
          "url": "magicutils-config-1.21.3-sources.jar",
          "size": 37256,
          "sha512": "63dc0ef787b091790945cf85f94b22f955b01911bfb32a287d6425be58571b609b403207559b04982e46f07c52bf92dd865465419b09e5f47877d414bf226b4e",
          "sha256": "65049a214719af417f1e2b25839f9c8b07aa682b31a60436f08a58770ef0b6df",
          "sha1": "6b5544ab5393238ff5c49bdcf4b100e9be7262b0",
          "md5": "225e154a78687284fd724e8ddc37c9e4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.21.3-javadoc.jar",
          "url": "magicutils-config-1.21.3-javadoc.jar",
          "size": 161111,
          "sha512": "5a048bc66498b86a35ed439a31e931546ea058f73104ef53369cf5d93425727a86b17d82159af507a0d117fb74f084e214cd9a6fcb3bba309455a8d701041d18",
          "sha256": "8cbfdf9bd864d047ce7fe3d595c5a45e6920c6e6d7e5e74bd7fbdeea9b5909f7",
          "sha1": "968c3433bfc9c7c583e443be325a39b0f2c83ab6",
          "md5": "1f86abab3c4aae14cc7425033ad211ad"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.21.3-all.jar",
          "url": "magicutils-config-1.21.3-all.jar",
          "size": 2962942,
          "sha512": "d541023bb90a9c20315a6aa6390bdf123351e93e04d721834810fee9faf0ef647380f2c853f50fe5b1f26b59e110e6458de0b863446b718ffaeb6101dfb9ef0f",
          "sha256": "43cbaaceab2a19da4203c9ef340ace15f71ec0dbd0d82062f753f91d570ac975",
          "sha1": "d19498752dfbfac50bcad6378d68aee067727417",
          "md5": "2f3f6110a294c41e2e296cf8583c9e1b"
        }
      ]
    }
  ]
}
