{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands-neoforge",
    "version": "1.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands-brigadier",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-neoforge",
          "version": {
            "requires": "1.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.15.0-mc1.21.jar",
          "url": "magicutils-commands-neoforge-1.15.0-mc1.21.jar",
          "size": 48296,
          "sha512": "e7960a636484c22c5db31d251ea3cbe79147e6a037ed0eab1f0b614e1466dab2008d0226b1549654420bc458c455edc2a715d2708b479920be7c3d7992ffa3e8",
          "sha256": "9a03e527956aba88d94b10276a2648e722cb75b5cb5bd2f08ed245fac5525d9f",
          "sha1": "6a02ffa7ad086fcb3de1459c1f09e23d4221fea3",
          "md5": "9352741a401f11dd99a90fa88212e1c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands-brigadier",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-neoforge",
          "version": {
            "requires": "1.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.15.0-mc1.21.jar",
          "url": "magicutils-commands-neoforge-1.15.0-mc1.21.jar",
          "size": 48296,
          "sha512": "e7960a636484c22c5db31d251ea3cbe79147e6a037ed0eab1f0b614e1466dab2008d0226b1549654420bc458c455edc2a715d2708b479920be7c3d7992ffa3e8",
          "sha256": "9a03e527956aba88d94b10276a2648e722cb75b5cb5bd2f08ed245fac5525d9f",
          "sha1": "6a02ffa7ad086fcb3de1459c1f09e23d4221fea3",
          "md5": "9352741a401f11dd99a90fa88212e1c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.15.0-sources.jar",
          "url": "magicutils-commands-neoforge-1.15.0-sources.jar",
          "size": 15291,
          "sha512": "df689869aada78262b28f911d0f4bc1ee90c2a812d09e07f65a5c69c2ad3b4f57b47bcb58daeef66e6a6fefbb0eba8c59ee1e2d34c2216377a6c8472b58a64af",
          "sha256": "50999dd33fb7ae4318ef39546aaf5a5e92276f8b9ee6337a4ea90f49c2711b47",
          "sha1": "ff26f94d3d3bb0571e31823502432b1aa223d8f9",
          "md5": "547390671f3688749a23e2e44f97bb53"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.15.0-javadoc.jar",
          "url": "magicutils-commands-neoforge-1.15.0-javadoc.jar",
          "size": 150212,
          "sha512": "f461493b1a7cb78f34eb216f23ad412ff158b97d8dce3864dc6bb4abf790381ef8f1a1cc19d799a14eddd0f83470fd5d0e4619eddee453d4c1d3496910b40c43",
          "sha256": "616e5d2adee27454a30d4938e2ace73bb27de214c0136fc2ff192fafdd2fd552",
          "sha1": "ddd4336303218acd17ac6749e0a275d42f37d1e5",
          "md5": "de6a3c368cdb5009f5dfd6a32667f2b0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.15.0-all.jar",
          "url": "magicutils-commands-neoforge-1.15.0-all.jar",
          "size": 40420410,
          "sha512": "247874a115eac23ee92524e35618fa5a884165af8533fcc3e8704528eadb9c552ed52655ecc91c9062ebf8576e826bcbc8f88f56c1d016fc6ac00831e0389278",
          "sha256": "055a8706357385303dca368ef0a849c8b870ba3032d7c80ad369bc09e5349e32",
          "sha1": "a92540924b08b01472a5eccf22f1349e1e8630ac",
          "md5": "fe250e7ba4b49a3ef3d3204d6dda7dfa"
        }
      ]
    }
  ]
}
