{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-lang",
    "version": "1.21.2-mc2611",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.2-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.21.2-mc2611-mc26.1.jar",
          "url": "magicutils-lang-1.21.2-mc2611-mc26.1.jar",
          "size": 51896,
          "sha512": "4bca0d9469ce8ed8fe9c33d743edcd3653d6db8f10300170f78e180c97db0fa3275a1b3ef8b497d2b90855756decdf7192e88592112b400f250f1c6ecbdd9c1e",
          "sha256": "7d28beadc8361b5ab0a636c99296b08e3946983d8194eedde50b5e7dc126ee79",
          "sha1": "83461e2d7f0d8ffd086e186edf3d62c5cde9d369",
          "md5": "1b848bcf5cee77d5ea4178987dcfb54a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.2-mc2611"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.21.2-mc2611-mc26.1.jar",
          "url": "magicutils-lang-1.21.2-mc2611-mc26.1.jar",
          "size": 51896,
          "sha512": "4bca0d9469ce8ed8fe9c33d743edcd3653d6db8f10300170f78e180c97db0fa3275a1b3ef8b497d2b90855756decdf7192e88592112b400f250f1c6ecbdd9c1e",
          "sha256": "7d28beadc8361b5ab0a636c99296b08e3946983d8194eedde50b5e7dc126ee79",
          "sha1": "83461e2d7f0d8ffd086e186edf3d62c5cde9d369",
          "md5": "1b848bcf5cee77d5ea4178987dcfb54a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.21.2-mc2611-sources.jar",
          "url": "magicutils-lang-1.21.2-mc2611-sources.jar",
          "size": 31450,
          "sha512": "a34c0b43bdd6a6f20f2cf9522a5565a280ca57866cca6337715f6ecd7bfb1e379f01f3739b3b2278a7635a1103357e0b0cfc3fc7cd352957ba5caf8a215aaf2d",
          "sha256": "64ed562273ae171839ee732e268f23e740f3df2be2ce55f5b9e904aadee233de",
          "sha1": "efdc4adc4a48166c249dd6bac8abd6d0f2a99088",
          "md5": "5d2385ce895fe432310a5e91b07fc26a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.21.2-mc2611-javadoc.jar",
          "url": "magicutils-lang-1.21.2-mc2611-javadoc.jar",
          "size": 4211649,
          "sha512": "23397fc1509278a3bbcd92b79fc66c4a177488b0935637100b5a1b0f3733d084b6fa7e33ae1f5faa7884b7ac6f5c718523d1f1c33abc465e1843bca947dad817",
          "sha256": "62db1d0336882e3bfe7350e11433cab40a51dffdeb50136cb0621ddef1eac56e",
          "sha1": "3066aef556e93102d502ac4a280d2804f61e9ba3",
          "md5": "59c412012b0718915131a6f745e0d20d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.21.2-mc2611-all.jar",
          "url": "magicutils-lang-1.21.2-mc2611-all.jar",
          "size": 3201767,
          "sha512": "7c39774d43f158a9de7c41c9132f62737d842790c2b8f7a566d7acd717022e38924c4c22824e8862045cf12a0d92eb2a4fc399e8d860fc7bec2a0ea0e8d46b33",
          "sha256": "7fe1ffe710fd89f67d49dfffe2f8c443ae72e3d6de9aeb570866cf1a2a67a144",
          "sha1": "7677cf90b93ebfff6e7aaae8d551b9a1b666854c",
          "md5": "eb7ee85dc84be1eba16d19030974ffc9"
        }
      ]
    }
  ]
}
