{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-config-yaml",
    "version": "1.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-yaml-1.19.0-mc1.21.jar",
          "url": "magicutils-config-yaml-1.19.0-mc1.21.jar",
          "size": 1719,
          "sha512": "f35021979f1e2e42964b366ac396592f4c040ac6a364bde18228f6ad2091bfd009999ccfdfd622f04069e1f31eac1c7f5a409f5398a435f0bf24a01e7bc2986c",
          "sha256": "c64a3e10699c8cd14a09bc0366908c8e8ffd1816406cbbadff133558acd45952",
          "sha1": "c81742f0556862bf1c55b127762caf4b4b2df91d",
          "md5": "d893a717e192510bbf367c38d511c8ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-yaml-1.19.0-mc1.21.jar",
          "url": "magicutils-config-yaml-1.19.0-mc1.21.jar",
          "size": 1719,
          "sha512": "f35021979f1e2e42964b366ac396592f4c040ac6a364bde18228f6ad2091bfd009999ccfdfd622f04069e1f31eac1c7f5a409f5398a435f0bf24a01e7bc2986c",
          "sha256": "c64a3e10699c8cd14a09bc0366908c8e8ffd1816406cbbadff133558acd45952",
          "sha1": "c81742f0556862bf1c55b127762caf4b4b2df91d",
          "md5": "d893a717e192510bbf367c38d511c8ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.19.0-sources.jar",
          "url": "magicutils-config-yaml-1.19.0-sources.jar",
          "size": 1615,
          "sha512": "7dd035aa467194e1f75f05e02b1afd2a2c881d14c30a7d577196ca3a326633df2cd9700da0936c91f30e1e9cb7cdedb5e3b373fab0a5b3ee0552940a8037fcbb",
          "sha256": "134bc160155c0948959d106b1fb7d7cb2b2e759d22e70303a8297ba77a13697e",
          "sha1": "3d4491714d06e6a1d91b497be8c6bfe0ef63c648",
          "md5": "f03bc030224c866efafb871d3584d804"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.19.0-javadoc.jar",
          "url": "magicutils-config-yaml-1.19.0-javadoc.jar",
          "size": 91108,
          "sha512": "5236a1e032c28029e9a503ed88497d75bebfc49b902902973b556f5795a5cb435107162c3b4075e46a11ceb6eccd80694cea78d1f78d04152454eb5f44521d34",
          "sha256": "bf15fbd1bb25b9ce5f95de1911af792b8b4f30f5973867425fef48ec421c9b78",
          "sha1": "419a1d86958f98efee6b15a400816bbe231a9577",
          "md5": "67552465f67e9fc8721f1d3ba69b30b0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.19.0-all.jar",
          "url": "magicutils-config-yaml-1.19.0-all.jar",
          "size": 3340698,
          "sha512": "04ad4b0dabe65a7c84c0e87ebcf1844eec1f175886055f674bdb979aaf6b69679a82645ded676475a0dd29c4bdd266cc4f51ee3c0a2f9bed84bdbde6dd734597",
          "sha256": "5c678ec832de5356fef56ae25fe888d6265b1008ce730872be81869de5d64840",
          "sha1": "53d29d1411be62802c614dbf8ea7e09e3204a1fd",
          "md5": "5453b413b6760cc61716495e0dcdc562"
        }
      ]
    }
  ]
}
