{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands-neoforge",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands-brigadier",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-neoforge",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.13.0-mc1.21.jar",
          "url": "magicutils-commands-neoforge-1.13.0-mc1.21.jar",
          "size": 19500,
          "sha512": "8b1a1aafd7a143f7107e8c48655b2d10636ff440fee094ee868b8d0711542a8d082adb2193fa818af8a79c91e3440cbdd8381dce437d16a3477a74cb3ed36c31",
          "sha256": "80b37f593eb28bfaae4367332fd6b050d06a2be16346c0d1cea089eef185eed3",
          "sha1": "e0fb4e921651fb38c7b2617cea5ba4eda88874f3",
          "md5": "1de8fa54f9271ec4c35628de4cc75db8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands-brigadier",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-neoforge",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.13.0-mc1.21.jar",
          "url": "magicutils-commands-neoforge-1.13.0-mc1.21.jar",
          "size": 19500,
          "sha512": "8b1a1aafd7a143f7107e8c48655b2d10636ff440fee094ee868b8d0711542a8d082adb2193fa818af8a79c91e3440cbdd8381dce437d16a3477a74cb3ed36c31",
          "sha256": "80b37f593eb28bfaae4367332fd6b050d06a2be16346c0d1cea089eef185eed3",
          "sha1": "e0fb4e921651fb38c7b2617cea5ba4eda88874f3",
          "md5": "1de8fa54f9271ec4c35628de4cc75db8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.13.0-sources.jar",
          "url": "magicutils-commands-neoforge-1.13.0-sources.jar",
          "size": 8358,
          "sha512": "32c3bebab07c2b83c8076dc630be57752221eeec2e6874f9f36cc99e5439367ef7cd72c8b05d8a9d6e1cc681d8de97af26fbb3a08738bf69df35c5d56f8abe02",
          "sha256": "f3c4c0db0d85b53f5266a34c5b49b2066994dcce373728f01c48873e34134a9a",
          "sha1": "49bc6ceeb80bb7cbcecc85640176c7751bc96b4c",
          "md5": "9ee67c549726c966fd0f7c8ebc25c627"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.13.0-javadoc.jar",
          "url": "magicutils-commands-neoforge-1.13.0-javadoc.jar",
          "size": 110424,
          "sha512": "928182a44825125b8723a0fd5e5e1bf0c87565c728df3e60c928b8a27d01b720125ee312753ab5d8d5c5e33e3fef987b69419681e273dc343c8a8b28b0e1c8ae",
          "sha256": "c3ba54399acd72b56f4fd703a7a52e1b930625189c259fedb02413880cfb438a",
          "sha1": "d2de83438be22a19e2211054781b785b75b59c49",
          "md5": "02a2be13eb36267c20a9478031808d44"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.13.0-all.jar",
          "url": "magicutils-commands-neoforge-1.13.0-all.jar",
          "size": 40333186,
          "sha512": "3410be7bfc30dc63ef343e60f3bd07506e06abe4452dd9b92f52e97e08c554b949c01eda2559a1a6f6ff9206ff6a4d1cecad13463f0670e5d3028c0781914278",
          "sha256": "0ec33d1e57e1229a2c30f13317d0d5ac628e79436f300647af39352ffb4ce699",
          "sha1": "f6e9eb639cdc0ab9eb83d3e3b34f7d655a326134",
          "md5": "e4b0fc408e636fa54de5a37e25a2f0ce"
        }
      ]
    }
  ]
}
