{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-logger",
    "version": "1.21.1-mc2611",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.1-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.21.1-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.21.1-mc2611"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.21.1-mc2611-mc26.1.jar",
          "url": "magicutils-logger-1.21.1-mc2611-mc26.1.jar",
          "size": 77320,
          "sha512": "1220190424ca30d9dcd6ba4e6065a43320b08e8a63ea9ef8a87b3abd39f4ad225a046127388c8cc4b622d287c90214ddedc5206a73299cb0fcf1c790bb69f134",
          "sha256": "4ad6126f2027ff6964d93a7cb18c3883570ede93ee3926c3c5b0b7651b55dca2",
          "sha1": "732d7194b270b4a6c89fad21bcccfbef116dc44f",
          "md5": "b35885de0a5b55eded991593e3889f9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.1-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.21.1-mc2611"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.21.1-mc2611"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.21.1-mc2611-mc26.1.jar",
          "url": "magicutils-logger-1.21.1-mc2611-mc26.1.jar",
          "size": 77320,
          "sha512": "1220190424ca30d9dcd6ba4e6065a43320b08e8a63ea9ef8a87b3abd39f4ad225a046127388c8cc4b622d287c90214ddedc5206a73299cb0fcf1c790bb69f134",
          "sha256": "4ad6126f2027ff6964d93a7cb18c3883570ede93ee3926c3c5b0b7651b55dca2",
          "sha1": "732d7194b270b4a6c89fad21bcccfbef116dc44f",
          "md5": "b35885de0a5b55eded991593e3889f9f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.21.1-mc2611-sources.jar",
          "url": "magicutils-logger-1.21.1-mc2611-sources.jar",
          "size": 35251,
          "sha512": "fb897db17baadb42f711f76483f1384132753ea660dc056b714d16313bebdc466a4554ece221851150d28112b5963057af6982cdf57b7269518e842a5110dea2",
          "sha256": "5b3032ca147e41cebb07b060147495acf50d7865e8dc6de2791aaa15a9ec9bbc",
          "sha1": "3e3c73b102e2b0892885c3ede99623beeff994db",
          "md5": "7a802ef6011516fc85e3dd9b3543c493"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.21.1-mc2611-javadoc.jar",
          "url": "magicutils-logger-1.21.1-mc2611-javadoc.jar",
          "size": 4265019,
          "sha512": "0f3bae0878a09e6428edb29db1c21ffe8f6da97413803285eab5f6bc3747e7c209f31c4d2b67866282c3ee399303089aab84b9e6c335efdea00b28c3b45382b3",
          "sha256": "4ec04c280cee48eec1cd315058df48d26a573cddd385cb990b41da781f0cb24c",
          "sha1": "b40b1fde4fb92beb5b13c67d2150e5a9e27acf0a",
          "md5": "8499c9c56c86d04a39232dc27567a49f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.21.1-mc2611-all.jar",
          "url": "magicutils-logger-1.21.1-mc2611-all.jar",
          "size": 3240085,
          "sha512": "b28d5a20676ebbf06cbc99bbd5040b597a6184d37e68c4ae4450458302354b82c45faefa2c49d27252a1274a7e2caf8bf3d009fd76ab106a4b1cf72a852e7666",
          "sha256": "2c36543dd48189764d7a0471a5f404337e18c82bec66a20f3a00a9cac1af8799",
          "sha1": "1ae93610743b524949a044544a941061ef9f1dda",
          "md5": "60d9a4a45acc4e08b6af0984e40e0282"
        }
      ]
    }
  ]
}
