{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bukkit",
    "version": "1.21.1-mc1201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.21.1-mc1201-mc1.20.jar",
          "url": "magicutils-bukkit-1.21.1-mc1201-mc1.20.jar",
          "size": 137377,
          "sha512": "b6a2d1ea1d6252bee257cc7465efc7064fb98bffb540a40220f06ef17c0f30d06774732ab4811fef788065dad9838cfa506ce16ccabf976bbafb822cca20ebdb",
          "sha256": "fc016ced11f0081570ee13cb4229717d31bf240beab6e6544722523053c309d2",
          "sha1": "d1120722bb86a4821087039ca68a5434f1682516",
          "md5": "3a85f8dfd60fe600a5077c653267ff55"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.21.1-mc1201-mc1.20.jar",
          "url": "magicutils-bukkit-1.21.1-mc1201-mc1.20.jar",
          "size": 137377,
          "sha512": "b6a2d1ea1d6252bee257cc7465efc7064fb98bffb540a40220f06ef17c0f30d06774732ab4811fef788065dad9838cfa506ce16ccabf976bbafb822cca20ebdb",
          "sha256": "fc016ced11f0081570ee13cb4229717d31bf240beab6e6544722523053c309d2",
          "sha1": "d1120722bb86a4821087039ca68a5434f1682516",
          "md5": "3a85f8dfd60fe600a5077c653267ff55"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.1-mc1201-sources.jar",
          "url": "magicutils-bukkit-1.21.1-mc1201-sources.jar",
          "size": 59830,
          "sha512": "53e94fae59db7a9ebf65137b8ab321bcb4fae0282d6e06f1e2715580cbf1c5cb80b6b845d63771353f9485b432e9d4b2358fb07a1a1957d0a985a436d983699b",
          "sha256": "31accedcce4e0028bd11fc4b8fe9cc11c181b83840e5bec49937a7324e04cfc3",
          "sha1": "4ff8c65cc052f02986d54ce44a2591b8e1d80845",
          "md5": "ae938ea6f30d022ce01b5d70d389df39"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.1-mc1201-javadoc.jar",
          "url": "magicutils-bukkit-1.21.1-mc1201-javadoc.jar",
          "size": 272467,
          "sha512": "76649dd8426d2efb02ee91219d5fa9374fc4420ec788515185f3934830fb57f1cbe5c77820c2e6af9a57ccbd24292f56c2c3fe55e3c1068d253cbe0616710603",
          "sha256": "40f10e070b72eeb0769e06cddaaa49645e046527b463ccc2f5cba9c992a73600",
          "sha1": "d79400ea65877ba54055630507f75a1021ee271b",
          "md5": "5681cf7e4b98edae724356df38311c54"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.21.1-mc1201-all.jar",
          "url": "magicutils-bukkit-1.21.1-mc1201-all.jar",
          "size": 3639345,
          "sha512": "b14532359e4550109c68ffb6dfad7b9ea183a1a2f66df37c09829a7293466f902cb7aba3edf7cb1b08adc621c4597dd8689228f5c1d7d2d65238b25a002fa892",
          "sha256": "efc98666e8a7a19a4d88288ebaeb21498d3296716254aa4d255975d43e2191ad",
          "sha1": "f471c6278633d770e7fb5cb362543069dbf70f37",
          "md5": "3070b8b2154c994d1e9a7ecbdb3eacd4"
        }
      ]
    }
  ]
}
