{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands-brigadier",
    "version": "1.19.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.19.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.19.1-mc1.21.jar",
          "url": "magicutils-commands-brigadier-1.19.1-mc1.21.jar",
          "size": 22463,
          "sha512": "12bfc6ff3838d9a4a464a9588d81540235fd545070411192d7cd23b73d9066e643b1a4acf3edc015b7b6d728fbb1c4cd4fe062f2163006dde54a9181dd78487f",
          "sha256": "0c4814a02c6bbe07b3129d36948deb3fa3151b7b72bf1e4b25f79c80a0a1f94b",
          "sha1": "7ddd8658fdfe7c9ab1dc9ec60cc08e27a535a156",
          "md5": "dc259a2601d6ec1627b3309de8cbbe84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.19.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.19.1-mc1.21.jar",
          "url": "magicutils-commands-brigadier-1.19.1-mc1.21.jar",
          "size": 22463,
          "sha512": "12bfc6ff3838d9a4a464a9588d81540235fd545070411192d7cd23b73d9066e643b1a4acf3edc015b7b6d728fbb1c4cd4fe062f2163006dde54a9181dd78487f",
          "sha256": "0c4814a02c6bbe07b3129d36948deb3fa3151b7b72bf1e4b25f79c80a0a1f94b",
          "sha1": "7ddd8658fdfe7c9ab1dc9ec60cc08e27a535a156",
          "md5": "dc259a2601d6ec1627b3309de8cbbe84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.19.1-sources.jar",
          "url": "magicutils-commands-brigadier-1.19.1-sources.jar",
          "size": 8154,
          "sha512": "25f9dd6bed138735d89c5c631f16d9706c5aeaef73fd2f6be4b6c34d10bfe7c7915b5099946b5ef3f97c4000678c1fc3f691fd5c14e40c3fa1bcfb5414eb0a92",
          "sha256": "88be7c5f9e2f69a9aebcab3f464f144eca700f8317649f6fbf8a8686ae449ee6",
          "sha1": "0c17dbc0cb33d0b3a7d067480b123cead0c45f03",
          "md5": "57137a65b952bdc8d20269aed9abf9a0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.19.1-javadoc.jar",
          "url": "magicutils-commands-brigadier-1.19.1-javadoc.jar",
          "size": 107840,
          "sha512": "3e4902ed7a5f9a0cbb1dbe916794620317bae1d27e2dc9a8620900119fbd77c31945f2a44cb76698593ec49542747924254cbbb6d5d76a306a909fde5b598dea",
          "sha256": "5f97408811815d0f157c4ea2fb693f9f73bd244b7f964046242c4856777dc0fc",
          "sha1": "226d6b86606f8e8702eb832c522ff863a24a062c",
          "md5": "2f6d339c2d9f1e5e07ff2288fb05a24e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.19.1-all.jar",
          "url": "magicutils-commands-brigadier-1.19.1-all.jar",
          "size": 3421973,
          "sha512": "81322190ce54d553d8dee2f523945ccb05cf4c4c3409275387e95f9c00b035c636f89ef5b90a172af75b59ff1e527fce8dabec4959e15e309624a7108a641ab7",
          "sha256": "a510aee980f67ba575b8cc1e9651d6ea77bb65e16bfde7b89db5cb99d6e5e735",
          "sha1": "02070fd5094617623dc8530529c9fea856f6a6e0",
          "md5": "c9ec36c2754280aaa193b4ab68332db8"
        }
      ]
    }
  ]
}
