{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bukkit",
    "version": "1.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.15.0-mc1.21.jar",
          "url": "magicutils-bukkit-1.15.0-mc1.21.jar",
          "size": 121717,
          "sha512": "5ef44859cc6a61661c20feca85e9ca5a8d1f6870f58c82b5fb86bb0df0605d4da1ce853f25dca1d6222f0cf95d9ac568fd697e65beecdc33999918fb19c97014",
          "sha256": "e5ca0ae5bfe9c5be22b6eaac33a14129257613750abb9d616f69854427abf183",
          "sha1": "fcaa1ac689b45e6195d88763750fee3193f39ed8",
          "md5": "c002466036a34473885e706ed1ceda0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bukkit-1.15.0-mc1.21.jar",
          "url": "magicutils-bukkit-1.15.0-mc1.21.jar",
          "size": 121717,
          "sha512": "5ef44859cc6a61661c20feca85e9ca5a8d1f6870f58c82b5fb86bb0df0605d4da1ce853f25dca1d6222f0cf95d9ac568fd697e65beecdc33999918fb19c97014",
          "sha256": "e5ca0ae5bfe9c5be22b6eaac33a14129257613750abb9d616f69854427abf183",
          "sha1": "fcaa1ac689b45e6195d88763750fee3193f39ed8",
          "md5": "c002466036a34473885e706ed1ceda0e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.15.0-sources.jar",
          "url": "magicutils-bukkit-1.15.0-sources.jar",
          "size": 52639,
          "sha512": "2c2e2add96b2837638814a99e4301223a8b426bbc85c5b716106c787331bc59f90c5f5b4102e780ffbe5860d247ef3026a152bbeb4dfd4a42dbcaba5f5e75d11",
          "sha256": "114fde0153b8a21d0b82b4c27134b3c770a2044f06c85bcd88936ee58cf17cf2",
          "sha1": "cf83851c01ba49e4c777dd38839f4019a5539bd4",
          "md5": "460977a3272ae67c86e9694151fbc35b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.15.0-javadoc.jar",
          "url": "magicutils-bukkit-1.15.0-javadoc.jar",
          "size": 266349,
          "sha512": "2e33133b45ffcabbe297c0bcc096b67a9758ac92419d781eb05569af4ee732e631184a1f4a33eba86301cc4a2fdff6dbf776cdd2af92ccc2567e164f21077f5c",
          "sha256": "5c32102a5ae3d91775ae9d289ae6cf0a5f0d35bd463cc7d4c5c97dfd2f8da462",
          "sha1": "6064b393bb9ae9d1fb54f0241b7703dad284b19e",
          "md5": "2a5eff0b505b63b3c31dafac8a976e37"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bukkit-1.15.0-all.jar",
          "url": "magicutils-bukkit-1.15.0-all.jar",
          "size": 3532172,
          "sha512": "27c7032be3645bbae86b8dd4a5ced136107243d50cc62b5011997a4ccb3cbf5c6ded211d627e418a15a7905b437a6bfaeebf333556df018ebf4d5def7867281d",
          "sha256": "92ee018c23d122b081169e9811a0aea366b29e120400100cfd744362efd9a22f",
          "sha1": "fcc070fc1758246fd7e36e79d3a3af8349697b4c",
          "md5": "a8093bdd35a2bed1551ce7ef53fd01ee"
        }
      ]
    }
  ]
}
