{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands-brigadier",
    "version": "1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.5-mc1.21.jar",
          "url": "magicutils-commands-brigadier-1.21.5-mc1.21.jar",
          "size": 22463,
          "sha512": "12bfc6ff3838d9a4a464a9588d81540235fd545070411192d7cd23b73d9066e643b1a4acf3edc015b7b6d728fbb1c4cd4fe062f2163006dde54a9181dd78487f",
          "sha256": "0c4814a02c6bbe07b3129d36948deb3fa3151b7b72bf1e4b25f79c80a0a1f94b",
          "sha1": "7ddd8658fdfe7c9ab1dc9ec60cc08e27a535a156",
          "md5": "dc259a2601d6ec1627b3309de8cbbe84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands",
          "version": {
            "requires": "1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.5-mc1.21.jar",
          "url": "magicutils-commands-brigadier-1.21.5-mc1.21.jar",
          "size": 22463,
          "sha512": "12bfc6ff3838d9a4a464a9588d81540235fd545070411192d7cd23b73d9066e643b1a4acf3edc015b7b6d728fbb1c4cd4fe062f2163006dde54a9181dd78487f",
          "sha256": "0c4814a02c6bbe07b3129d36948deb3fa3151b7b72bf1e4b25f79c80a0a1f94b",
          "sha1": "7ddd8658fdfe7c9ab1dc9ec60cc08e27a535a156",
          "md5": "dc259a2601d6ec1627b3309de8cbbe84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.5-sources.jar",
          "url": "magicutils-commands-brigadier-1.21.5-sources.jar",
          "size": 8154,
          "sha512": "25f9dd6bed138735d89c5c631f16d9706c5aeaef73fd2f6be4b6c34d10bfe7c7915b5099946b5ef3f97c4000678c1fc3f691fd5c14e40c3fa1bcfb5414eb0a92",
          "sha256": "88be7c5f9e2f69a9aebcab3f464f144eca700f8317649f6fbf8a8686ae449ee6",
          "sha1": "0c17dbc0cb33d0b3a7d067480b123cead0c45f03",
          "md5": "57137a65b952bdc8d20269aed9abf9a0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.5-javadoc.jar",
          "url": "magicutils-commands-brigadier-1.21.5-javadoc.jar",
          "size": 107845,
          "sha512": "98fa93b43c12e0ffd84a92bac6861755cf01f4032fee47e934240ca38a3b13e94047b0cb08c139a3342891df3eeb2abb8adad95190a292dff26841ac114940ff",
          "sha256": "f377cebae9c1e734728b91a9b6353e5e5253c49f59072982ac3a20ee0bf34b46",
          "sha1": "f89a9304e2565ed6ce2144f3dd456ba5df95be6c",
          "md5": "eed6ea8fc082e6296c229f70b9b07949"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-brigadier-1.21.5-all.jar",
          "url": "magicutils-commands-brigadier-1.21.5-all.jar",
          "size": 3443045,
          "sha512": "833dbec0112cedf094cd9ad52862709d6c0c3eabc5f343353c1e3978d13101b61a396682390e602616e5139051db66de0e089df8162ed329fb3574b35369e26d",
          "sha256": "c2c524fd9f98af4bfab68df0c75439642d703ab2d7b26a8df64437f838d9aea0",
          "sha1": "31a748edd959e60a8a1d6f1abd7dface0b81df94",
          "md5": "bd3a073fdc4209cf7655a0ef7dd828d0"
        }
      ]
    }
  ]
}
