{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-lang",
    "version": "1.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.16.1-mc1.21.jar",
          "url": "magicutils-lang-1.16.1-mc1.21.jar",
          "size": 41392,
          "sha512": "0076b7627ae69b421a59e9a8721733fc8e611ff570a26c26c1b56a57612e9b64e8bd0e96d9d559b6934402479f4a165b3b269a2a3f380afa73879955ebf30935",
          "sha256": "8b359c35a1c4ddd7c196a818d2d70731da63270af0de5ed632364af1cbe42eaa",
          "sha1": "d61e1bdde4bea4e731df784f2086434a64591931",
          "md5": "81f0f77df41d97bbe001dbeb789d4ed9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-lang-1.16.1-mc1.21.jar",
          "url": "magicutils-lang-1.16.1-mc1.21.jar",
          "size": 41392,
          "sha512": "0076b7627ae69b421a59e9a8721733fc8e611ff570a26c26c1b56a57612e9b64e8bd0e96d9d559b6934402479f4a165b3b269a2a3f380afa73879955ebf30935",
          "sha256": "8b359c35a1c4ddd7c196a818d2d70731da63270af0de5ed632364af1cbe42eaa",
          "sha1": "d61e1bdde4bea4e731df784f2086434a64591931",
          "md5": "81f0f77df41d97bbe001dbeb789d4ed9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.16.1-sources.jar",
          "url": "magicutils-lang-1.16.1-sources.jar",
          "size": 23151,
          "sha512": "5b7fe3885850962867ba1b25b13a856d5831bbc4367d97971a99ea7254ffef9c2e6cec14fd54fc174b7604a8935cdbe5fcca61774966a39b17abaae4d18fd498",
          "sha256": "038cd0d76c55663c6ac5fb5ee0b32997e6e9a088a1173c86567ffb6bf8439fb6",
          "sha1": "7c56cd8901d8fe87389072b2b6b88149622b8db0",
          "md5": "35c27066e68e728f701346f77a592062"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.16.1-javadoc.jar",
          "url": "magicutils-lang-1.16.1-javadoc.jar",
          "size": 141901,
          "sha512": "fb0e3f6049695ef062adb4de8ae24f594713273fbc517df2669cfeb5fd13a5a782cb833e822ef5b3e38e03d090c27626c690e1012656d9e65665e815bcbf6a0f",
          "sha256": "3ae6b1b661ce5640c96835042be395fc1133e1dbebdbb2010289d6ed9add09eb",
          "sha1": "6b0a4d016dda6e1e2fcccfd8f579acce2259776e",
          "md5": "4b83d6b120ee7a74116a569e50ffe111"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-lang-1.16.1-all.jar",
          "url": "magicutils-lang-1.16.1-all.jar",
          "size": 3179014,
          "sha512": "552606936a8742a6b3209a1b84f4b01e86ab7c921bd5587b349dec5c2ea46ceed040cbbecfda92e1fa6d333d48c187cc0b6bdf536cb24df282f6067db507f3c5",
          "sha256": "9e9480197817010140be82a02f4724793fce5d3750166f27a10e99ef2f58acdb",
          "sha1": "bfcff315562260fa21518c82859e2c9e23b05335",
          "md5": "76bac7381dcc3d447551a9611c962253"
        }
      ]
    }
  ]
}
