{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-config",
    "version": "1.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-1.17.0-mc1.21.jar",
          "url": "magicutils-config-1.17.0-mc1.21.jar",
          "size": 77983,
          "sha512": "a3bfdfb932196d9ba0adba3c50114b63f8195cf7dcb27f91658c2b78b8b0dc36066d225197f8ae24ca25fc1008d3f5b4d70c45b1df9f88b9c57e5cfd395011be",
          "sha256": "f3b3dc2b0b597551594fa17ed1126470ad758d0b3f2ead22358075c0aa03fe09",
          "sha1": "2f535deda13f7b0eb479d47ae72001544a7f9474",
          "md5": "ed881e65a6e8cc80cb8a587a2bc9b865"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-1.17.0-mc1.21.jar",
          "url": "magicutils-config-1.17.0-mc1.21.jar",
          "size": 77983,
          "sha512": "a3bfdfb932196d9ba0adba3c50114b63f8195cf7dcb27f91658c2b78b8b0dc36066d225197f8ae24ca25fc1008d3f5b4d70c45b1df9f88b9c57e5cfd395011be",
          "sha256": "f3b3dc2b0b597551594fa17ed1126470ad758d0b3f2ead22358075c0aa03fe09",
          "sha1": "2f535deda13f7b0eb479d47ae72001544a7f9474",
          "md5": "ed881e65a6e8cc80cb8a587a2bc9b865"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.17.0-sources.jar",
          "url": "magicutils-config-1.17.0-sources.jar",
          "size": 36589,
          "sha512": "7117b6d90f42b9e2571da48efb81efb6455cccc754f291bf55d890a6fe64735b7fd829d12b1409894bb743aa090eda7f5c6a32e1399d7623430e3c4258e72ee8",
          "sha256": "2e8588fefee7d5dbf4f222f897384c59ac420d4597757e6a76447f031bc647b1",
          "sha1": "cd95d0584a5f5f957f8f2ea98070ab507182b94a",
          "md5": "e691d942f19d0cacbe54bf386027ccf4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.17.0-javadoc.jar",
          "url": "magicutils-config-1.17.0-javadoc.jar",
          "size": 161120,
          "sha512": "3352c366c54ccf72d64acda88063b58cb57ae3cbefc1c5a73f604e98056544506b8adc3433434ef2c003229aa0de20860a8e6f7b8b4512cd7f3100da1db86c25",
          "sha256": "cf79ddca238c3f67b3c07532165d162f24005d59ab174bfcc817bb7295ebda74",
          "sha1": "103df2eb19319f1062b9aa007ba976dde25d8c86",
          "md5": "38b6f716c2eb619b02454af7b941001f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-1.17.0-all.jar",
          "url": "magicutils-config-1.17.0-all.jar",
          "size": 2950625,
          "sha512": "4a9f1067b3fb2d288b7dd7d4a6843d9e30c12a17bd4082abc1fd05523e627e9986958de31615a460171c67bcbc6b3fbeced90393f5b8df733b31a8051b66f473",
          "sha256": "59a9463691314b3ea125d692d6e88103ee8071ddc6c84b3f7b81290482869a02",
          "sha1": "c2085f7677244831427c3e49eec88fc9299ea2b9",
          "md5": "67f5360215aedb44ee3968bf4c225af4"
        }
      ]
    }
  ]
}
