{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-logger",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.12.0-mc1.21.jar",
          "url": "magicutils-logger-1.12.0-mc1.21.jar",
          "size": 77625,
          "sha512": "42f224d11830d615b5fc4bc586511c76e7d7cdf2bcc7ab4a41dc455bedac8fdbc0a6c0d3065ea00f82566d198023fed551832b818292b24238646241a1f59688",
          "sha256": "396bb120d12f899d96218149ad7a81e3761737b5ed5bfb68ddc1b686b231cb32",
          "sha1": "47c8ba2e558a050ebaa5e16ea92c7338f367f82f",
          "md5": "29673458109e54acfe1896d8b7a24c1d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.12.0-mc1.21.jar",
          "url": "magicutils-logger-1.12.0-mc1.21.jar",
          "size": 77625,
          "sha512": "42f224d11830d615b5fc4bc586511c76e7d7cdf2bcc7ab4a41dc455bedac8fdbc0a6c0d3065ea00f82566d198023fed551832b818292b24238646241a1f59688",
          "sha256": "396bb120d12f899d96218149ad7a81e3761737b5ed5bfb68ddc1b686b231cb32",
          "sha1": "47c8ba2e558a050ebaa5e16ea92c7338f367f82f",
          "md5": "29673458109e54acfe1896d8b7a24c1d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.12.0-sources.jar",
          "url": "magicutils-logger-1.12.0-sources.jar",
          "size": 35476,
          "sha512": "e1278ad8aa538ee283d71dba7b2fdc6906ff6fec309eeb5771cfeb53ad33739c59cca5a0d9974997f9672b9321d43664aaaa14ce3268e3bb3edf3502dab7ffea",
          "sha256": "be5680d78bccc936dab4b6a2276878154c3996ab18f0195e80bb26971240d62a",
          "sha1": "789d506bf48cc5bc9319e9606fc169a6833e7d72",
          "md5": "0297e41bd2871b88c268a8faeaf17f9f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.12.0-javadoc.jar",
          "url": "magicutils-logger-1.12.0-javadoc.jar",
          "size": 203093,
          "sha512": "598351764a6330caf61faefb842a69652c07e676ec83161cd7b3d380e612a59c71228e2472840b812a5a654518b4c9d6efdd549a8b88e50579b6a9a2040d6f91",
          "sha256": "9658f4cdb5e0eda20bb60578f48552492d25b67cc0ce9295ac0df6992831ba57",
          "sha1": "43a79bea4b505a3d91cb18019232cff2adcd2a13",
          "md5": "fada176810050e142b246b6e8fe22e9b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.12.0-all.jar",
          "url": "magicutils-logger-1.12.0-all.jar",
          "size": 3204451,
          "sha512": "ee699e73a6ede3920d26ff74260048675206f82a99ee095d32edcd90968d217cf385f85db8b9bd8ff6dd69e52171f44db9deb5e479b1289799dc2b6b4dc8c562",
          "sha256": "f6985ee2f01a9232ca91d6d64a69968ee4d732ca85fcc771336d84aeae52d96a",
          "sha1": "475e12d06eebf04c777d6f4ae746491ab17ef055",
          "md5": "639439938f7885dee7dfa3489d8a502a"
        }
      ]
    }
  ]
}
