{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-bungee",
    "version": "1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bungee-1.21.5-mc1.21.jar",
          "url": "magicutils-bungee-1.21.5-mc1.21.jar",
          "size": 42404,
          "sha512": "47e504e93b3f3ed208780b4bd2bcb2faed82f9038055b82c4a6784752891f2fafc5d98055fd77f9956163ae7d79408601014f43331803b75f17b584fa43e10f6",
          "sha256": "7fab1946479194d9d29474ea1264d7262501af67aaebda021fa1a4838bebf1d7",
          "sha1": "424f01e9d14782674674d446d27445a35f7f86c1",
          "md5": "45433efe4c580a8dbca648226552d078"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-diagnostics",
          "version": {
            "requires": "1.21.5"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-bungee-1.21.5-mc1.21.jar",
          "url": "magicutils-bungee-1.21.5-mc1.21.jar",
          "size": 42404,
          "sha512": "47e504e93b3f3ed208780b4bd2bcb2faed82f9038055b82c4a6784752891f2fafc5d98055fd77f9956163ae7d79408601014f43331803b75f17b584fa43e10f6",
          "sha256": "7fab1946479194d9d29474ea1264d7262501af67aaebda021fa1a4838bebf1d7",
          "sha1": "424f01e9d14782674674d446d27445a35f7f86c1",
          "md5": "45433efe4c580a8dbca648226552d078"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bungee-1.21.5-sources.jar",
          "url": "magicutils-bungee-1.21.5-sources.jar",
          "size": 16806,
          "sha512": "038a7f651f83adde1cb4403b846921051c45a0a2f51b376aa13f27c7deeaa77a2a1164c386df971dfe1341168e43adb4a0413d294907796e1b568079795c32ea",
          "sha256": "0e6323df58d45145207515cb68ffc024defa9712443293ce377eba5c3650036f",
          "sha1": "4a73eef78c16c6462f82fd710fc4f3687975db44",
          "md5": "838c7b3e13c8c3ba07deb471764ac3bb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bungee-1.21.5-javadoc.jar",
          "url": "magicutils-bungee-1.21.5-javadoc.jar",
          "size": 133656,
          "sha512": "96d64cafdf6f3e4b7344a83fc5523efb9d93aba45ac002cce45dce19488400bcaa76d5f01e31b87a66f3eabc8e889db591121af153d94ffe0d828607a54afa7f",
          "sha256": "e4e4ea2c668cf93b02ac3db9140a25a213550c2f9a8a77a6f6adb7225357c6ae",
          "sha1": "752533daa24cd95fffb4325b04af04864f1a7436",
          "md5": "ad0f1456a5e59d0cc23b195e1b4af86a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-bungee-1.21.5-all.jar",
          "url": "magicutils-bungee-1.21.5-all.jar",
          "size": 3576867,
          "sha512": "ced442b1d4b7e1f1c69a5e11b37c80bbc663e17ac789968f581ac4b8fd5b33ef3ff7c81cfadf2e5f1c96936fdbfcdf00a2ed7eec535d9acfb75ce60eb1231765",
          "sha256": "412e7d2bd71b12942a0a241b15491b8feb1be207ee92807dc8e82a37b04276b6",
          "sha1": "282c8f5c2911226b2a464256ce2c347c1fb09593",
          "md5": "5bffaa27c6755660aa2edd63730b0aa6"
        }
      ]
    }
  ]
}
