{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-http-client",
    "version": "1.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.13.1-mc1.21.jar",
          "url": "magicutils-http-client-1.13.1-mc1.21.jar",
          "size": 56617,
          "sha512": "09bc1bde919e4fda8f6c168ef98c1f0e02ca522d9b5bf33c9bce4a68ca3b9ecb1b874efcf2c62822d46b28acb286b35c4873a19cf391ee835f214b622f5fc659",
          "sha256": "1dc5d645190a791d7b790b906de0154280b2412e35ff2a867e533969d7d8762a",
          "sha1": "0fd45cf9fc8496713e2f80562a9b0f4aec7a88b0",
          "md5": "33a5198d9d28ce0ddf5e3d5fe51f7893"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-http-client-1.13.1-mc1.21.jar",
          "url": "magicutils-http-client-1.13.1-mc1.21.jar",
          "size": 56617,
          "sha512": "09bc1bde919e4fda8f6c168ef98c1f0e02ca522d9b5bf33c9bce4a68ca3b9ecb1b874efcf2c62822d46b28acb286b35c4873a19cf391ee835f214b622f5fc659",
          "sha256": "1dc5d645190a791d7b790b906de0154280b2412e35ff2a867e533969d7d8762a",
          "sha1": "0fd45cf9fc8496713e2f80562a9b0f4aec7a88b0",
          "md5": "33a5198d9d28ce0ddf5e3d5fe51f7893"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.13.1-sources.jar",
          "url": "magicutils-http-client-1.13.1-sources.jar",
          "size": 20828,
          "sha512": "0592c15958ee8060d8cc40f8a3fb91cfb7e7225c37fd4df5dce4bebf8b298175987529bb353d73c8e0e395a5a78b7ac8134d9a700317c68a1c8f1ac4fa6fdd9e",
          "sha256": "a047a1bfc5aacbbfb4742069ff1b8609623a6c1e3a63fe03e431a6ecd6661f82",
          "sha1": "c02180acd21e930582c4e58ef05048e4bcaccbdb",
          "md5": "08a71f85e7ea867926357543a8860bc2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.13.1-javadoc.jar",
          "url": "magicutils-http-client-1.13.1-javadoc.jar",
          "size": 149252,
          "sha512": "902ce03cdf2cda1bc0d0cd61328859972223720f5fcd5978aa1e2c57fa190d7aa18b6c4b54527dd34cf1fb64d36dc945c314b589744270e2cfedb8da19304cea",
          "sha256": "bb464c7e11c58530ca6c322c89542177bff25eaeae3a1665bd0391723676836f",
          "sha1": "89bb142762edcb083ea0faa4c9195cd96fcbd61e",
          "md5": "424bc068ec9243df436a746515dae9ae"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-http-client-1.13.1-all.jar",
          "url": "magicutils-http-client-1.13.1-all.jar",
          "size": 3458520,
          "sha512": "37d0d1d3e4e6451a08144f73d61d733d7f68fb5edff47d47066a717abf6a19e6eba34c6ed5a00d55c83f50141f50f52bcb817b4299aaa165c3befd1a9993f89b",
          "sha256": "b19a41761068dff1109c6009183ac6a92763d482be8324e6a6e719a7e13a324b",
          "sha1": "178750cf31d6e38d6cc15e7884c55444da7f3022",
          "md5": "9a1cca5ab66d171e3d4f8b030097a42b"
        }
      ]
    }
  ]
}
