{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-config-yaml",
    "version": "1.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-yaml-1.21.0-mc1.21.jar",
          "url": "magicutils-config-yaml-1.21.0-mc1.21.jar",
          "size": 1740,
          "sha512": "611ca6a7146970315f265f42e4796993ce6c1a100f854d15485fae54c25b4719d4bd194e6373032a3c30c03edfe9b4caa4eba4106d9a53c8156aa4c42ce4759b",
          "sha256": "56b3f57f32c78b156ca7ac80f31405a096647e7238bb10508343245863c82925",
          "sha1": "06271bcffb3ad8f87fb6ef759a3197443de0a744",
          "md5": "b2b78c085eaf9857d51dab1e1ca75d7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-yaml-1.21.0-mc1.21.jar",
          "url": "magicutils-config-yaml-1.21.0-mc1.21.jar",
          "size": 1740,
          "sha512": "611ca6a7146970315f265f42e4796993ce6c1a100f854d15485fae54c25b4719d4bd194e6373032a3c30c03edfe9b4caa4eba4106d9a53c8156aa4c42ce4759b",
          "sha256": "56b3f57f32c78b156ca7ac80f31405a096647e7238bb10508343245863c82925",
          "sha1": "06271bcffb3ad8f87fb6ef759a3197443de0a744",
          "md5": "b2b78c085eaf9857d51dab1e1ca75d7f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.21.0-sources.jar",
          "url": "magicutils-config-yaml-1.21.0-sources.jar",
          "size": 1615,
          "sha512": "7dd035aa467194e1f75f05e02b1afd2a2c881d14c30a7d577196ca3a326633df2cd9700da0936c91f30e1e9cb7cdedb5e3b373fab0a5b3ee0552940a8037fcbb",
          "sha256": "134bc160155c0948959d106b1fb7d7cb2b2e759d22e70303a8297ba77a13697e",
          "sha1": "3d4491714d06e6a1d91b497be8c6bfe0ef63c648",
          "md5": "f03bc030224c866efafb871d3584d804"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.21.0-javadoc.jar",
          "url": "magicutils-config-yaml-1.21.0-javadoc.jar",
          "size": 91107,
          "sha512": "f1d8dec0324c50cf011de7fd0f01ac7c63258c5e2b868828d9cf4ae36abbf6a35e822dab8482149e9bca65a24b394d8097ea0918a448def962eb32fec8a18610",
          "sha256": "fdfcfb2901744e7bcc361beecdeaa5172042cd2a7fdbe097ca2e21e87711263f",
          "sha1": "9a2c6b42d072c7faee7e4c7c9e83fa30cc301165",
          "md5": "b74c8ff6cd9710ae36d45c9f1f5efaca"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-yaml-1.21.0-all.jar",
          "url": "magicutils-config-yaml-1.21.0-all.jar",
          "size": 3349316,
          "sha512": "9789e49ea60531631ba910c741df7029c3ed91f00218a9124d49ea4c804acd97a4263464818520efd58bb3feb6c17b71d711b6655627be7c82b86ab4949b8619",
          "sha256": "e08bbdce9a1c735a399881f6227dbb80cd49f5d3ef92aa95c67c400f9c53cb28",
          "sha1": "9a89c331736d3bce4f8dbf278b422e89597b1089",
          "md5": "5d677406ec4e7a0efaf5615ffa80284b"
        }
      ]
    }
  ]
}
