{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands-neoforge",
    "version": "1.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands-brigadier",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-neoforge",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.13.1-mc1.21.jar",
          "url": "magicutils-commands-neoforge-1.13.1-mc1.21.jar",
          "size": 47919,
          "sha512": "3e278c34d9126dc9ca90cb7e3a9a288f9d92949e6ca7646db201a65d666667303c6511e4ae1895ae63e2292d817216d4fd0045fff8046b06d06234542bd297ae",
          "sha256": "bd7298979112d342fbcd3e84a8024d113ad10dac1aa089c9eed5192a9eaedc72",
          "sha1": "d923bd2ee8ead1812ea905387bb454053ef5b871",
          "md5": "555b655072a5b9906a3c46f79d99bbe1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands-brigadier",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-neoforge",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.13.1-mc1.21.jar",
          "url": "magicutils-commands-neoforge-1.13.1-mc1.21.jar",
          "size": 47919,
          "sha512": "3e278c34d9126dc9ca90cb7e3a9a288f9d92949e6ca7646db201a65d666667303c6511e4ae1895ae63e2292d817216d4fd0045fff8046b06d06234542bd297ae",
          "sha256": "bd7298979112d342fbcd3e84a8024d113ad10dac1aa089c9eed5192a9eaedc72",
          "sha1": "d923bd2ee8ead1812ea905387bb454053ef5b871",
          "md5": "555b655072a5b9906a3c46f79d99bbe1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.13.1-sources.jar",
          "url": "magicutils-commands-neoforge-1.13.1-sources.jar",
          "size": 15197,
          "sha512": "cd378d51d75c55b1352c9cdc1d2e8a6a73eda504a7392908acb8a26ef79355737534c757167002c51172b98887a278e8aa7b0adff711eb8d76ef26569c2d466e",
          "sha256": "d99d06b490fdeabd2929e985e787576a5dbddea285523706a45d0395a642e61c",
          "sha1": "576ae8f52f3472eedcb005895b9fed78d8cb7e08",
          "md5": "01278bd134f51112339c77d8a88f1005"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.13.1-javadoc.jar",
          "url": "magicutils-commands-neoforge-1.13.1-javadoc.jar",
          "size": 150183,
          "sha512": "c441b6f742f7cd73e87efc9dbe8b9a0e6f3545e5b8a0d4819a4de93147abdbb75309543641c5fe082ebe29da691ed764a4fb2dc6f393cb15ad9d5d84d810220e",
          "sha256": "4dd2e846882ef50ffe910c9ec326f6428d369dfde7dce13e0ce42de4ce32b69f",
          "sha1": "eeda825866380447f32fb6463f65a9cec24fe0e4",
          "md5": "6e68713b17afd281bc6f2629fe7626d9"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.13.1-all.jar",
          "url": "magicutils-commands-neoforge-1.13.1-all.jar",
          "size": 40414415,
          "sha512": "81489713145da6f98d86f2bd3eaf5aa866287bcebdac760ba7aa1e14e34008ce7cdf5a50cd6a09100b6323140029a3b1836e86bc707c4d8a157d927300721d39",
          "sha256": "0be3ed986bf4ee127e85eadc57e20a14a7634ea565fddb979e86e05eb22f6b5e",
          "sha1": "e8601e44da3308b261b82795a6806956a902a02d",
          "md5": "f448968aa54763feca1d1a5893110758"
        }
      ]
    }
  ]
}
