{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-commands-neoforge",
    "version": "1.11.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands-brigadier",
          "version": {
            "requires": "1.11.6"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-neoforge",
          "version": {
            "requires": "1.11.6"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.11.6-mc1.21.jar",
          "url": "magicutils-commands-neoforge-1.11.6-mc1.21.jar",
          "size": 19500,
          "sha512": "8b1a1aafd7a143f7107e8c48655b2d10636ff440fee094ee868b8d0711542a8d082adb2193fa818af8a79c91e3440cbdd8381dce437d16a3477a74cb3ed36c31",
          "sha256": "80b37f593eb28bfaae4367332fd6b050d06a2be16346c0d1cea089eef185eed3",
          "sha1": "e0fb4e921651fb38c7b2617cea5ba4eda88874f3",
          "md5": "1de8fa54f9271ec4c35628de4cc75db8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-commands-brigadier",
          "version": {
            "requires": "1.11.6"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-neoforge",
          "version": {
            "requires": "1.11.6"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.11.6-mc1.21.jar",
          "url": "magicutils-commands-neoforge-1.11.6-mc1.21.jar",
          "size": 19500,
          "sha512": "8b1a1aafd7a143f7107e8c48655b2d10636ff440fee094ee868b8d0711542a8d082adb2193fa818af8a79c91e3440cbdd8381dce437d16a3477a74cb3ed36c31",
          "sha256": "80b37f593eb28bfaae4367332fd6b050d06a2be16346c0d1cea089eef185eed3",
          "sha1": "e0fb4e921651fb38c7b2617cea5ba4eda88874f3",
          "md5": "1de8fa54f9271ec4c35628de4cc75db8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.11.6-sources.jar",
          "url": "magicutils-commands-neoforge-1.11.6-sources.jar",
          "size": 8358,
          "sha512": "32c3bebab07c2b83c8076dc630be57752221eeec2e6874f9f36cc99e5439367ef7cd72c8b05d8a9d6e1cc681d8de97af26fbb3a08738bf69df35c5d56f8abe02",
          "sha256": "f3c4c0db0d85b53f5266a34c5b49b2066994dcce373728f01c48873e34134a9a",
          "sha1": "49bc6ceeb80bb7cbcecc85640176c7751bc96b4c",
          "md5": "9ee67c549726c966fd0f7c8ebc25c627"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.11.6-javadoc.jar",
          "url": "magicutils-commands-neoforge-1.11.6-javadoc.jar",
          "size": 110422,
          "sha512": "b448661166e7ea13be63d9882fce4e015302343f9f06136dd955fafdd6b1e8dd7896ba054b10ce1b6864703d66c64f1bfeaa6604f942a69b31d0157468326502",
          "sha256": "f2accd61210b1ae5345bad640c5c18b2983e375b1355f0bb252b9496e0604ae0",
          "sha1": "24f0aca155ca3a1b5cb80a721b966b2654a66622",
          "md5": "67cf74d7c768020c2e243928aed13be9"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-commands-neoforge-1.11.6-all.jar",
          "url": "magicutils-commands-neoforge-1.11.6-all.jar",
          "size": 40324816,
          "sha512": "4f2f5c40c08c4a4905ccee12ed405f8332f68c54fb4dd0d8068683f0622d28ffe3678522706e79126a6dd29ce967a2c451436cdd5c5c02a814a303f0d8f4413a",
          "sha256": "1ecd48b584b2edba6a8545d91e6bb1a33348c65f6794df6bcafc038923aac2ef",
          "sha1": "053c168c25286c7ca87e3f63167ccaee0595184d",
          "md5": "cb457f8d6ea8ad1e66abdb1fb865d8e9"
        }
      ]
    }
  ]
}
