{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-logger",
    "version": "1.21.1-mc1201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.21.1-mc1201-mc1.20.jar",
          "url": "magicutils-logger-1.21.1-mc1201-mc1.20.jar",
          "size": 77282,
          "sha512": "672f36fd09b60877f12d2a910ddef94cd6b3b7ca00d43b3c3da2d62ee025370e8f743cd31818b9f77fb425d042f3d7022333d23647930b6fb2fe0ccd1d03f1dc",
          "sha256": "3ba842a1b1bc8b5a789a4d49a734abffe5977e618d6c9b9cd090131fe667a2b8",
          "sha1": "04daa94327352263c0839429e58867c8fae69144",
          "md5": "4d660edc11c439b607b2a52619803cb3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-lang",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-placeholders",
          "version": {
            "requires": "1.21.1-mc1201"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-logger-1.21.1-mc1201-mc1.20.jar",
          "url": "magicutils-logger-1.21.1-mc1201-mc1.20.jar",
          "size": 77282,
          "sha512": "672f36fd09b60877f12d2a910ddef94cd6b3b7ca00d43b3c3da2d62ee025370e8f743cd31818b9f77fb425d042f3d7022333d23647930b6fb2fe0ccd1d03f1dc",
          "sha256": "3ba842a1b1bc8b5a789a4d49a734abffe5977e618d6c9b9cd090131fe667a2b8",
          "sha1": "04daa94327352263c0839429e58867c8fae69144",
          "md5": "4d660edc11c439b607b2a52619803cb3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.21.1-mc1201-sources.jar",
          "url": "magicutils-logger-1.21.1-mc1201-sources.jar",
          "size": 35251,
          "sha512": "fb897db17baadb42f711f76483f1384132753ea660dc056b714d16313bebdc466a4554ece221851150d28112b5963057af6982cdf57b7269518e842a5110dea2",
          "sha256": "5b3032ca147e41cebb07b060147495acf50d7865e8dc6de2791aaa15a9ec9bbc",
          "sha1": "3e3c73b102e2b0892885c3ede99623beeff994db",
          "md5": "7a802ef6011516fc85e3dd9b3543c493"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.21.1-mc1201-javadoc.jar",
          "url": "magicutils-logger-1.21.1-mc1201-javadoc.jar",
          "size": 190741,
          "sha512": "12f50ad895ec92ad97fad757112bb13097d7883eed914fdefae6691692913596df9c81ed4cb3beb27998ce4fc95cf0a0b26321f7492dc2c58dabfbf35fce1042",
          "sha256": "0c1e237de62011e9c1883d060a95025393429fd9da1542f94229b5546223da28",
          "sha1": "3dd1839c59fd4d3bc176f95de19e1fd798ce8888",
          "md5": "b9431cc782308418ff317dfa32175dc6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-logger-1.21.1-mc1201-all.jar",
          "url": "magicutils-logger-1.21.1-mc1201-all.jar",
          "size": 3240120,
          "sha512": "3eaf2c5974af2058b10cfa12ead48c64aaf7bb254cb44a78e063f23a33c0385e1f12309fd5bce4778832290f205d701acf09c143542463319164ed8aca701189",
          "sha256": "4f962d760298d4075f6a5ebf670309c6cf2d7b621ec110df89292d70372b7f63",
          "sha1": "ca5f3f6fc1dbf4f94f18a0c6302bc91a4a82153f",
          "md5": "60e2e6c0ed25ccd43a3553cde9d6ebde"
        }
      ]
    }
  ]
}
