{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-config-toml",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-toml-1.10.0.jar",
          "url": "magicutils-config-toml-1.10.0.jar",
          "size": 1715,
          "sha512": "81241e7055883ea64119da1119be07b6dd95d2bdcc2915e4796a6681374707e0b0461888eb95c500bdd3b6fab7df80c674a0fae3316ea970cd7517dc067619e0",
          "sha256": "17083d24b575e9b6d739a11c153cdcf8af4aa83bd7be561a179ac83f796e1471",
          "sha1": "597e480f444c7fb7640ff10cf01a85764ddfaf66",
          "md5": "7128d33beb4ef846d7e1bcd9b06f3ea6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-toml",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-toml-1.10.0.jar",
          "url": "magicutils-config-toml-1.10.0.jar",
          "size": 1715,
          "sha512": "81241e7055883ea64119da1119be07b6dd95d2bdcc2915e4796a6681374707e0b0461888eb95c500bdd3b6fab7df80c674a0fae3316ea970cd7517dc067619e0",
          "sha256": "17083d24b575e9b6d739a11c153cdcf8af4aa83bd7be561a179ac83f796e1471",
          "sha1": "597e480f444c7fb7640ff10cf01a85764ddfaf66",
          "md5": "7128d33beb4ef846d7e1bcd9b06f3ea6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-toml-1.10.0-all.jar",
          "url": "magicutils-config-toml-1.10.0-all.jar",
          "size": 2986203,
          "sha512": "3d919e0f23f90685ee32fa2c5ae161292b8316039c3dd450413ce8f54e3490b3a5d0a3064bd3a3c1f7be92f021d6aaf43851334eef25ae6a942d3f4c45f526fc",
          "sha256": "73d9e09409509449b34e5823fd14b535fef7aa866a73585454bc61a4bf325fe2",
          "sha1": "41444807d428f6dd02705ff0096814ee2ddbc5ef",
          "md5": "8e0db95048155685732e4de7c94b5deb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-toml-1.10.0-sources.jar",
          "url": "magicutils-config-toml-1.10.0-sources.jar",
          "size": 1611,
          "sha512": "e99f20f55b2444370b7a34a9c09298f5b3c9dee27c76592074d7102ca475efa3edb5f828c1119e397f341dce439a46b9647ebd365d02dc8066252f7074d827b7",
          "sha256": "c4f28319566355ab040596adcfab43e62c4a33cd344c7869f90fcf0ce99fe681",
          "sha1": "17b2eddd73d6e32599d31e4936943188cdb9d4f3",
          "md5": "2c091f978f898bf6b94c77eae1a28ce7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-toml-1.10.0-javadoc.jar",
          "url": "magicutils-config-toml-1.10.0-javadoc.jar",
          "size": 91110,
          "sha512": "f0846376b10c971cbd6eb2dc9d828dde9ee827974291d75ba4f32fc4c4f80a65c7ad2357d4cce2c9d9fe39e0c7a56e3023647cb3b00b348c29933a8001abbaf0",
          "sha256": "e28bd65ab93bdb81bbaa23419dcb9b158c14979c2e24ebf662d08cb64b44bd01",
          "sha1": "728d4f56b1f31a4f2e46f0ae99f729cbac9fc5d7",
          "md5": "7059010337c3af39a7c46adbb2388414"
        }
      ]
    }
  ]
}
