{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-config-toml",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-toml-1.10.0.jar",
          "url": "magicutils-config-toml-1.10.0.jar",
          "size": 1715,
          "sha512": "393df1febb649d5b0df27a368e5a8109c2c1909c210d70821062b1d537db2197287b14d8abffb86d1b52bb7cee658001e77055f05f834bd02e37e324f06546a4",
          "sha256": "e0f7e1c0564ef0680074198b0a7e57e7ca1dce164dff190df8f8211e1e3bcde0",
          "sha1": "302fd7a2b864f53972188948659700a2f3c448ec",
          "md5": "2ca00eb6134680a41d02b4d79e979b8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-toml",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-config",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-config-toml-1.10.0.jar",
          "url": "magicutils-config-toml-1.10.0.jar",
          "size": 1715,
          "sha512": "393df1febb649d5b0df27a368e5a8109c2c1909c210d70821062b1d537db2197287b14d8abffb86d1b52bb7cee658001e77055f05f834bd02e37e324f06546a4",
          "sha256": "e0f7e1c0564ef0680074198b0a7e57e7ca1dce164dff190df8f8211e1e3bcde0",
          "sha1": "302fd7a2b864f53972188948659700a2f3c448ec",
          "md5": "2ca00eb6134680a41d02b4d79e979b8d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-toml-1.10.0-all.jar",
          "url": "magicutils-config-toml-1.10.0-all.jar",
          "size": 2986203,
          "sha512": "3d919e0f23f90685ee32fa2c5ae161292b8316039c3dd450413ce8f54e3490b3a5d0a3064bd3a3c1f7be92f021d6aaf43851334eef25ae6a942d3f4c45f526fc",
          "sha256": "73d9e09409509449b34e5823fd14b535fef7aa866a73585454bc61a4bf325fe2",
          "sha1": "41444807d428f6dd02705ff0096814ee2ddbc5ef",
          "md5": "8e0db95048155685732e4de7c94b5deb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-toml-1.10.0-sources.jar",
          "url": "magicutils-config-toml-1.10.0-sources.jar",
          "size": 1611,
          "sha512": "326873806e9c53bf1aa3e2fd089286d2ac51efadf8f8ec8c0a18bb09758e80cbce87b3bb72eaef441e5974bf6f63721ae96e162b73c23e863e6eda82d539efde",
          "sha256": "9ee1ed15098fecded59f5f54c355f8e2ba215e7637d049e04a8dedca7f6e51b4",
          "sha1": "a3de0fd89b2f3325bbfb315a9bff56afe29dd044",
          "md5": "67c0bedfefb322eadbbe9bdef44fddcc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-config-toml-1.10.0-javadoc.jar",
          "url": "magicutils-config-toml-1.10.0-javadoc.jar",
          "size": 91110,
          "sha512": "95b2291b434609a7e9d345a220f1d780d24d209c5033d9ef3d11108a561a4243f1d71a2e38d6156ef67da8b5b5160cc86e3fd27807f4dbbbbda216a46429e5a8",
          "sha256": "8172748737d274588530e3969005926047ad0a36f63333de60a3a39c6af7972f",
          "sha1": "668f91fb9ab9781c2ed3ec17160ce7775ccaac43",
          "md5": "faca4572cad84d7ecc674946ce72a0df"
        }
      ]
    }
  ]
}
