{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ua.theroer",
    "module": "magicutils-placeholders",
    "version": "1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-placeholders-1.21.1-mc1.21.jar",
          "url": "magicutils-placeholders-1.21.1-mc1.21.jar",
          "size": 17881,
          "sha512": "89daaf1ecac905c3cd0704227dd96b932301a7c7d9a3c525df05fc8395dcfed042038bbbebb35e20c112143ef56b577bbf89b404366a7d92fd0af95c73823664",
          "sha256": "beb3595da9f3fd1da88d803ec61d12ce0cd2e2b582b0430277eb3f3e171de2c4",
          "sha1": "434dac0de1e96b9e1582d6d7504493ad8c47aee7",
          "md5": "28601fb10d3b4c277f8bcd53d96e6709"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.ua.theroer",
          "module": "magicutils-api",
          "version": {
            "requires": "1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicutils-placeholders-1.21.1-mc1.21.jar",
          "url": "magicutils-placeholders-1.21.1-mc1.21.jar",
          "size": 17881,
          "sha512": "89daaf1ecac905c3cd0704227dd96b932301a7c7d9a3c525df05fc8395dcfed042038bbbebb35e20c112143ef56b577bbf89b404366a7d92fd0af95c73823664",
          "sha256": "beb3595da9f3fd1da88d803ec61d12ce0cd2e2b582b0430277eb3f3e171de2c4",
          "sha1": "434dac0de1e96b9e1582d6d7504493ad8c47aee7",
          "md5": "28601fb10d3b4c277f8bcd53d96e6709"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-placeholders-1.21.1-sources.jar",
          "url": "magicutils-placeholders-1.21.1-sources.jar",
          "size": 7370,
          "sha512": "6ca047e63ff109127ca4d04c8cb3eb30fae2e48ff422ba9b8346479427ffe29d2c1514b4a3227ec09b2978acf81bf72a72305580fb9ee22c02ad9bace12b183a",
          "sha256": "3b8210282b46b06732a9febb7c21c84a6c2da06bc48218455d25a24eb20cd272",
          "sha1": "f94ae8c1bf477eb39ee3f978c683b420249545dc",
          "md5": "c24c7817acb07ecc60c3bbd58f314cc1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-placeholders-1.21.1-javadoc.jar",
          "url": "magicutils-placeholders-1.21.1-javadoc.jar",
          "size": 122277,
          "sha512": "37d18e47622dd177b3029365eb5b5560fa09115bbb15a38ffcf40d11239fef1fcf6ea96c068f2041f2e1468281864aa3583e9e9b700451908d012c9fe5eaa6e4",
          "sha256": "748291efd70e3344aa4ef5e16aed1a5f4bae74acdc2c4936fe8a2d66d87fc386",
          "sha1": "a353366c3ce71067d9418bf0ecefa920ea28fceb",
          "md5": "3f11d427db57aaab81dee6b1faed0763"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magicutils-placeholders-1.21.1-all.jar",
          "url": "magicutils-placeholders-1.21.1-all.jar",
          "size": 534804,
          "sha512": "4509b5e78fb0948a73978a48c1a654d6c3a7f6b7210e36a8c94febb01bc08951f7b8979fcc15f4aa090c9b3c2922b9be6d8d0dc57c600393b87e9762be76c13d",
          "sha256": "8684d1241277893324f9a04d79bef70d056683462be3347e3bf6be2919ff3ae4",
          "sha1": "04d93a361a7a7d61b43e74a4d808b328657168a1",
          "md5": "98512750c96813dd8cbfb1447cd4a567"
        }
      ]
    }
  ]
}
